### DISCUSSION TITLE
question: environments values to release values

### DISCUSSION THREAD

**Discussion by jjangga0214** [helmfile/helmfile#1037] [Questions] [answered]
Let's say I have *`helmfile.yaml `* and *`values.local.yaml`* like these.

**helmfile.yaml**:

```yaml
environments:
  local:
    values:
      - ./values.local.yaml

releases:
  - name: foo
    chart: ./foo
    values:
      {{ .Values.foo.values | indent 6 }}
```

**./values.local.yaml**:

```yaml
foo:
  values:
    - bar: 2
    - qux:
         baz: true
         kex: "abc"
```

I want the final result rendered as if I write helmfile like the below snippet.

```bash 
helmfile apply -e local
```

```yaml
releases:
  - name: foo
    chart: ./foo
    values:
      - bar: 2
      - qux:
           baz: true
           kex: "abc"
```

I there a way to achieve this?

Thanks.

**Comment by yxxhero** [comment]
```
environments:
  local:
    values:
      - ./values.local.yaml
---
releases:
  - name: foo
    chart: ./foo
    values:
      {{ .Values.foo.values | indent 6 }}
```

**Comment by jjangga0214** [comment, marked as answer]
I found the answer. 

```
environments:
  local:
    values:
      - ./values.local.yaml
---
releases:
  - name: foo
    chart: ./foo
    values:
{{ .Values.foo.values | indent 6 }}
```

`indent` is applied to the starting line as well, so `{{ .Values.foo.values | indent 6 }}` should be written like this.
