### DISCUSSION TITLE
question: error when using `if` for `needs` item

### DISCUSSION THREAD

**Discussion by jjangga0214** [helmfile/helmfile#1038] [Questions] [answered]
Let's say I have these files.

*`values.local.yaml`*

```yaml
cert-manager:
  enabled: false # or true
```

*`helmfile.yaml`*

```yaml
environments:
  local:
    values:
      - ./values.local.yaml
---
releases:
  - name: foo
    chart: ./foo
    namespace: default
    needs:
      - default/traefik
      {{ if .Values.cert-manager.enabled }}
      - cert-manager/cert-manager
      {{ end }}
```

```bash
helmfile apply -e local

in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:8: bad character U+002D '-'
```

`{{ if` ... `{{end }}` causes the error. Is there a proper way to do? 

Thanks!

**Comment by yxxhero** [comment]
--debug for more logs.

**Comment by jjangga0214** [comment]
@yxxhero 

Here it is!

```bash
$ helmfile apply -e local --debug

processing file "helmfile.yaml" in directory "."
changing working directory to "/Users/ocean/main/kakao-inviter/helm"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{local  map[] map[]}, overrode=<nil>
first-pass uses: &{local  map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: # REF: https://helmfile.readthedocs.io/en/latest/
 1:
 2: repositories:
 3:   - name: bitnami
 4:     url: https://charts.bitnami.com/bitnami
 5:   - name: hashicorp
 6:     url: https://helm.releases.hashicorp.com
 7:   - name: traefik
 8:     url: https://traefik.github.io/charts
 9:   - name: jetstack
10:     url: https://charts.jetstack.io
11:
12: environments:
13:   local:
14:     values:
15:       - ./values.local.yaml
16:   prod:
17:     values:
18:       - ./values.prod.yaml
19:   stg:
20:     values:
21:       - ./values.stg.yaml

envvals_loader: loaded ./values.local.yaml:map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]]
first-pass produced: &{local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
vals:
map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: # REF: https://helmfile.readthedocs.io/en/latest/
 1:
 2: repositories:
 3:   - name: bitnami
 4:     url: https://charts.bitnami.com/bitnami
 5:   - name: hashicorp
 6:     url: https://helm.releases.hashicorp.com
 7:   - name: traefik
 8:     url: https://traefik.github.io/charts
 9:   - name: jetstack
10:     url: https://charts.jetstack.io
11:
12: environments:
13:   local:
14:     values:
15:       - ./values.local.yaml
16:   prod:
17:     values:
18:       - ./values.prod.yaml
19:   stg:
20:     values:
21:       - ./values.stg.yaml

envvals_loader: loaded ./values.local.yaml:map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]]
merged environment: &{local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
first-pass rendering starting for "helmfile.yaml.part.1": inherited=&{local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}, overrode=<nil>
first-pass uses: &{local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
first-pass rendering input of "helmfile.yaml.part.1":
 0: releases:
 1:   - name: kakao-inviter-api
 2:     chart: ./kakao-inviter-api
 3:     namespace: default
 4:     condition: kakao-inviter-api.enabled
 5:     needs:
 6:       - default/traefik
 7:       {{ if .Values.cert-manager.enabled }}
 8:       - cert-manager/cert-manager
 9:       {{ end }}
10:     values:
11:       - ./values/kakao-inviter-api/{{ .Environment.Name }}.yaml
12:
13:   - name: traefik
14:     chart: ./traefik
15:     namespace: default
16:     condition: traefik.enabled
17:     # REF: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
18:     values:
19:       - ./values/traefik/{{ .Environment.Name }}.yaml
20:
21:   - name: cert-manager
22:     chart: ./cert-manager
23:     namespace: cert-manager
24:     condition: cert-manager.enabled
25:     # REF: https://artifacthub.io/packages/helm/cert-manager/cert-manager
26:     values:
27:       - ./values/cert-manager/{{ .Environment.Name }}.yaml
28:

template syntax error: template: stringTemplate:8: bad character U+002D '-'
first-pass produced: &{local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
first-pass rendering result of "helmfile.yaml.part.1": {local  map[cert-manager:map[enabled:false] kakao-inviter-api:map[enabled:false] traefik:map[enabled:true]] map[]}
second-pass rendering failed, input of "helmfile.yaml.part.1":
 0: releases:
 1:   - name: kakao-inviter-api
 2:     chart: ./kakao-inviter-api
 3:     namespace: default
 4:     condition: kakao-inviter-api.enabled
 5:     needs:
 6:       - default/traefik
 7:       {{ if .Values.cert-manager.enabled }}
 8:       - cert-manager/cert-manager
 9:       {{ end }}
10:     values:
11:       - ./values/kakao-inviter-api/{{ .Environment.Name }}.yaml
12:
13:   - name: traefik
14:     chart: ./traefik
15:     namespace: default
16:     condition: traefik.enabled
17:     # REF: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
18:     values:
19:       - ./values/traefik/{{ .Environment.Name }}.yaml
20:
21:   - name: cert-manager
22:     chart: ./cert-manager
23:     namespace: cert-manager
24:     condition: cert-manager.enabled
25:     # REF: https://artifacthub.io/packages/helm/cert-manager/cert-manager
26:     values:
27:       - ./values/cert-manager/{{ .Environment.Name }}.yaml
28:

err: error during helmfile.yaml.part.1 parsing: template: stringTemplate:8: bad character U+002D '-'
changing working directory back to "/Users/ocean/main/kakao-inviter/helm"
in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:8: bad character U+002D '-'
```


*`helmfile.yaml`*

```yaml
# REF: https://helmfile.readthedocs.io/en/latest/

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  local:
    values:
      - ./values.local.yaml
  prod:
    values:
      - ./values.prod.yaml
  stg:
    values:
      - ./values.stg.yaml
---
releases:
  - name: kakao-inviter-api
    chart: ./kakao-inviter-api
    namespace: default
    condition: kakao-inviter-api.enabled
    needs:
      - default/traefik
      {{ if .Values.cert-manager.enabled }}
      - cert-manager/cert-manager
      {{ end }}
    values:
      - ./values/kakao-inviter-api/{{ .Environment.Name }}.yaml

  - name: traefik
    chart: ./traefik
    namespace: default
    condition: traefik.enabled
    # REF: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
    values:
      - ./values/traefik/{{ .Environment.Name }}.yaml

  - name: cert-manager
    chart: ./cert-manager
    namespace: cert-manager
    condition: cert-manager.enabled
    # REF: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    values:
      - ./values/cert-manager/{{ .Environment.Name }}.yaml

```

## Info 

- helmfile: v0.157.0
- helm: `version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}`
- OS: macOS Ventura 13.5.2(22G91)
