### DISCUSSION TITLE
`KRM` functions to make `helmfile` as simple as any plugin in `kustomize`

### DISCUSSION THREAD

**Discussion by davinkevin** [helmfile/helmfile#1069] [Ideas]
Hello 👋 , 

> [!IMPORTANT]
> I would like to say, even if I'm a huge fan of `kustomize`, `helmfile` is one of the tool which makes me happier to use `helm`, and that is because the `declarative` way of doing things in `helmfile` is really good, for that… congratulation 👏!

I would like to propose, as a feature request, the introduction of a KRM (Kubernetes Resource Model) function supporting `helmfile`, as a `generator`. Specification for KRM Functions is available in the `kustomize` repository [here](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md).

The idea (and you have a working POC in the end of this comment), is to use `helmfile` as an official module to `inflate` a chart, available to everyone using `kustomize` using a `Container KRM Functions` [like described in the doc](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/containerized_krm_functions/)

> [!NOTE]
> Kustomize already has an `helmChartInflator`, but [this version](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) is VERY simple and doesn't provide all features `helmfile` provides. 

# POC

> [!NOTE]
> The project is fully available on [GitLab](https://gitlab.com/davinkevin.fr/experimentations/kustomize/helmfile-inflator)

The requirement for a generator using `Container KRM function` is to have an `apiVersion`, a `kind`, `metadata.name` and an `metadata.annotation["config.kubernetes.io/function"]` with a `yaml` value including parameters to run the `KRM function`. To cover the feature, I've added those parameters to the `helmfile` spec, resulting into the following file:

```yaml
apiVersion: helmfile.davinkevin.fr/v1alpha1
kind: HelmfileInflator

metadata:
  name: prometheus
  annotations:
    helmfile.davinkevin.fr/cli-parameters: ""
    config.kubernetes.io/function: |
      container:
        image: davinkevin.fr/helmfile-inflator
        network: true
        mounts: 
          - type: bind
            src: .
            dst: /opt/mount/

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 48.4.0
    values:
      - ./values.yaml
```

Then, I've developed a *VERY* simple image using `bash` (it should be done with something else, but it's enough for a POC) and with the following script as `entrypoint`: 

```shell
#!/bin/bash
set -euo pipefail

WORKING_DIR=$(mktemp -d)
cd $WORKING_DIR

# save the input provided by `kustomize`
KFN_INPUT="$WORKING_DIR/input.yaml"
cat > $KFN_INPUT

# extract the helmfile from the input
HELMFILE="$WORKING_DIR/extracted-helmfile.yaml"
cat $KFN_INPUT | \
    yq e '.functionConfig' - | \
    yq 'del(.apiVersion)' - | \
    yq 'del(.kind)' - | \
    yq 'del(.metadata)' - > $HELMFILE

# Copy files, especially to load the `./values.yaml` file
cp /opt/mount/* .

# Generate yaml using `helmfile`
HELMFILE_OUTPUT="$WORKING_DIR/helmfile-output"
helmfile template -f $HELMFILE --quiet > $HELMFILE_OUTPUT

# Generate the expected format, based on ResourceList, expected from any `Container KRM functions`
RESULT="$WORKING_DIR/output.yaml"
echo "kind: ResourceList" >> $RESULT
echo "items:" >> $RESULT
cat $HELMFILE_OUTPUT | yq ea '[.]' - >> $RESULT

cat $RESULT
```

# Conclusion

Currently, the provided code is a very bleeding POC, nothing else and is not meant to be used in prod, but it's a very good and simple way to incorporate `helmfile` into any `kustomize` pipeline, based on standard and specified `Container KRM Functions`. 

A lot of feature can be added, like supporting cli parameters for calling `helmfile` or others… but the simplest solution is available and can do the job 😉. 

Let me know what you think about it 😇
