### DISCUSSION TITLE
Why are my secrets decrypted but not rolled out

### DISCUSSION THREAD

**Discussion by totoroot** [helmfile/helmfile#1081] [Questions]
I suspect this is more of a user error, than an actual issue, so I think it fits better in discussion.

I want `helmfile` to roll out some secrets. Secrets were encrypted using the helm secrets plugin.

For the following release, I add the path of the encryted secret to the secrets list:

```yaml
  - name: datadog-operator
    namespace: datadog
    chart: datadog-repo/datadog-operator
    version: 1.2.1
    values:
      - datadog-operator/{{ .Environment.Name }}/values.yaml
    secrets:
      - datadog-operator/Secret.yaml.enc
```

When I roll it out using `helmfile`, it sucessfully decrypts the secret. The logs show:
`Decrypting secret .../datadog-operator/Secret.yaml.enc`

However, the secret is not rolled out to the cluster.

Why is that and what am I doing wrong?

I looked at issues and docs and cannot figure out why it would not just roll out the decrypted manifest.

**Comment by yxxhero** [comment]
@totoroot please show the logs by adding the --debug.

**Comment by totoroot** [comment]
Sure, here are the relevant parts of the logs:

```
...

Preparing to decrypt secret <redacted>/datadog-operator/Secret.yaml.enc
Decrypting secret <redacted>/datadog-operator/Secret.yaml.enc
exec: helm secrets decrypt <redacted>/datadog-operator/Secret.yaml.enc
helm:naOIc> apiVersion: v1
helm:naOIc> kind: Secret
helm:naOIc> type: Opaque
helm:naOIc> metadata:
helm:naOIc> name: datadog-secret
helm:naOIc> data:
helm:naOIc> api-key: <redacted>
helm:naOIc> app-key: <redacted>
Decrypted <redacted>/datadog-operator/Secret.yaml.enc into datadog-operator/secret3493607307.enc
Successfully generated the value file at datadog-operator/secret3493607307.enc. produced:
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: datadog-secret
data:
    api-key: <redacted>
    app-key: <redacted>
...

exec: helm diff upgrade --allow-unreleased datadog-operator datadog-repo/datadog-operator --version 1.2.1 --kube-version v1.27.3 --kube-context <redacted> datadog --values /tmp/helmfile2958993662/datadog-datadog-operator-values-5744d6cdd6 --values /tmp/helmfile3813299947/datadog-datadog-operator-values-57499f7bc6 --detailed-exitcode --color --reset-values

...
```

**Comment by yxxhero** [comment]
@totoroot what's meaning of `rolloed out`, could you show your command?

**Reply by totoroot** [reply]
`helmfile -e radar apply --interactive --log-level debug`

I had expected the decrypted `Secret.yaml` to get deployed to the cluster, just like a regular manifest. Perhaps that was the wrong approach.

But even if I put together a `secrets.yaml` with just the fields that I want to overwrite in the values.yaml, it does not seem to get applied to the cluster.

`secrets.yaml`
```yaml
datadog:
    apiKey: <redacted>
    appKey: <redacted>
```

`helmfile.yaml`
```yaml
  - name: datadog-operator
    namespace: datadog
    chart: datadog-repo/datadog-operator
    version: 1.2.1
    values:
      - datadog-operator/{{ .Environment.Name }}/values.yaml
    secrets:
      - datadog-operator/{{ .Environment.Name }}/secrets.yaml.enc
  ```
  
  Should that work?
