### DISCUSSION TITLE
helmfile environments structure for easy upgrade management with renovatebot

### DISCUSSION THREAD

**Discussion by DavidJacob** [helmfile/helmfile#1096] [Questions]
Hi all. We currently have one big `helmfile.yaml` in the root of our repo, and they way we handle upgrading our dependencies per environment is to define the versions of the charts in the `environment` block. Here's an simplified version of what we have:
```
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  default:
    values:
        env: NONE
  prod:
    values:
      - env: prod
        versions:
          ingress-nginx: 4.3.0
  staging:
    values:
      - env: staging
        versions:
          ingress-nginx: 4.4.2

releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress
    version: {{ index .Environment.Values.versions "ingress-nginx"}}
    values: config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: kube-system
    version: v1.12.1
    values: config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
```
The issue with this is that we use `renovatebot` to automatically pick up outdated dependencies and open PRs for us to review. `renovatebot` will pick up the `cert-manager` version because it is statically defined in `.releases.[].version`, but it doesn't pick up the one for `ingress-nginx`.

The reason we do it like this is so we can verify changes in our `staging` environment before we upgrade in `prod`.

Is there some way we can structure our environments to do this in a `helmfile` friendly manner? I was thinking of splitting the environments into separate files but the `helmfile` docs seem to only suggest this for teams/apps.

Thanks!

**Comment by yxxhero** [comment]
you can use files as env values. like below:
```
environments:
  prod:
    values:
      - prod.yaml.gotmpl
  staging:
    values:
      - staging.yaml.gotmpl
```
