### DISCUSSION TITLE
Allow overriding base releases definitions

### DISCUSSION THREAD

**Discussion by mgalliou** [helmfile/helmfile#1112] [Ideas]
When importing releases using the `bases` field, it would be useful to allow overriding releases definitions.

## Problem

Given the file `base.yaml` :

```yaml
releases:
  - name: app
    chart: repo/app
    version: 1.0.0
```

And the file `helmfile.yaml`

```yaml
bases:
  - base.yaml
  
 releases:
 - name: app
   version: 2.0.0
```

Currently, running `helmfile build` gives the error `encountered empty chart while reading release "app"`.

And after editing `helmfile.yaml` release definition to also contain the field `chart: repo/chart` the error `there were 2 releases named "app" matching specified selector` is given.

## Expected Behavior

Given the files above, running `helmfile build` should generate releases like so:

```yaml
releases:
  - name: app
    chart: repo/app
    version: 2.0.0
```
