### DISCUSSION TITLE
Nested variables in Templates

### DISCUSSION THREAD

**Discussion by ReddaHawk** [helmfile/helmfile#113] [Questions]
Hi, i'm trying to use templates to reduce the amount of redundancy in the helmfile.

In particular the template is:
```
templates:
  default: &default
    chart:  ../devops/charts/{{`{{ .Release.Name }}`}}
    version: {{` {{ .Environment.Values | get printf "%s.version" {{.Release.Name }} `}}
    missingFileHandler: Error
    values:
    - ./charts/{{`{{ .Release.Name }}`}}/values-{{ .Environment.Name }}.yaml
    - ingress:
        routeHost: "{{ .Environment.Name }}.test.tp"
```

The version variable throws an exception that is the following one:
```
in ./helmfile2.yaml: error during helmfile2.yaml.part.0 parsing: template: stringTemplate:20:38: executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type state.EnvironmentTemplateData
```

How i can fix this?
