### DISCUSSION TITLE
Helm --post-renderer-args support: cannot use Powershell script as post renderer

### DISCUSSION THREAD

**Discussion by boekhold** [helmfile/helmfile#1132] [Ideas]
Please add support for the Helm `--post-renderer-args` option:

```yaml
releases:
- name: myRelease
  postRenderer: PowerShell
  postRendererArgs:
  - "-Command"
  - "C:/path/to/powershell/script.ps1"
```
Currently it is not possible to use a PowerShell script as post renderer. If you specify just the path/name of the PS1 script, you get:

```
  Error: Failed to render chart: exit status 1: Error: error while running post render on files: error while running command patch-release.ps1. error output:
  : fork/exec patch-release.ps1: %1 is not a valid Win32 application.
```

If you specify "PowerShell -Command patch-release.ps1" as postRenderer, you get:
```
Error: Failed to render chart: exit status 1: Error: invalid argument "PowerShell -Command patch-release.ps1" for "--post-renderer" flag: unable to find binary at PowerShell -Command patch-release.ps1: exec: "PowerShell -Command C:/Maarten/Finastra/treasury/patch-thirdparties.ps1": file does not exist
```
since the entire string is passed as the name of the executable...
