### DISCUSSION TITLE
How to use `.Release.Name` as key in release templates to select a value from environment values file?

### DISCUSSION THREAD

**Discussion by amit-tewari** [helmfile/helmfile#1145] [Questions]
Can we use `.Release.Name` as a key to select a value from environment values file?

Following are minimal helmfile.yaml and environment values files for example:

==> helmfile.yaml <==
```
environments:
  default:
    values:
    - env-default-values.yaml
---

templates:
  default:
    chart: {{ .Values | get "release.`{{ .Release.Name }}`.name" "ChartName" }}

---
releases:
  - name: {{ .Environment.Values | get "release.hello.name" "hello" }}
    inherit:
    - template: default
```

==> env-default-values.yaml <==
```
release:
  hello:
    name: hello

```

I need, when I run `helmfile diff` or `helmfile apply`, that chart `hello` is used, however `ChartName` is the chart name used for the above configuration.

All other questions or issues refer to using `.Release.Name` as it is, instead of `.Release.Name` being used as key to select a value, and I could not make any progress using `--debug` runs.

This functionality helps make templates quite flexible for multiple environments and services, where chart name, versions etc can be specified per environment. 

Following are helmfile and helm version numbers.

`helm` : v3.12.3+g3a31588
`helmfile`: 0.158.1

Help is greatly appreciated.
