### DISCUSSION TITLE
Nested Bases

### DISCUSSION THREAD

**Discussion by mgalliou** [helmfile/helmfile#1148] [Ideas]
Currently, in multiple repositories, I import multiple base files from another repo like so:

```yaml
bases:
  - git::https://github.com/mgalliou/repo@base01.yaml.gotmpl
---
 bases:
  - git::https://github.com/mgalliou/repo@base02.yaml.gotmpl
---
 bases:
  - git::https://github.com/mgalliou/repo@base03.yaml.gotmpl
---
# ...
```

---

To eliminate redundancy, nested bases could be introduced, enabling the importation of base files that define other base files. This would allow for a more modular and reusable structure:

```yaml
 bases:
  - git::https://github.com/mgalliou/repo@bases.yaml.gotmpl
---
# ...
```

`bases.yaml.gotmpl` would look like this:

```yaml
bases:
  - base01.yaml.gotmpl
 ---
 bases:
  - base02.yaml.gotmpl
---
 bases:
  - base03.yaml.gotmpl
```
