### DISCUSSION TITLE
How is Value state passed to sub helmfiles

### DISCUSSION THREAD

**Discussion by kaldvelski** [helmfile/helmfile#1161] [Questions]
Hello,

I have a parent helmfile where I setup some initial state values using a remote load process, which I then want to have available to a set of sub helmfiles, e.g.

```
bases:
  - repository.yaml
---
helmfiles:
  - path: ./*-helmfile.yaml
    values:      
      - {{ tpl (readFile "templates/secrets/loadSecrets.gotmpl") . | nindent 6 }}
```
This works in that the sub helmfiles get the loaded values. However, what I'm finding is that remote load process happens once for this parent helmfile and then once per sub helmfile. Ideally I just want to load it once at the parent helmfile level and for it to just be available to the sub helmfiles in the 'inherited' state values. 

I've tried loading the values in a separate layer within the parent, i.e.

```
bases:
  - repository.yaml

values:      
  - {{ tpl (readFile "templates/secrets/loadSecrets.gotmpl") . | nindent 2 }}
---
helmfiles:
  - path: ./*-helmfile.yaml
```    
But that doesn't seem to make any difference. 
I've also tried setting a flag in the state to try to avoid loading again e.g.

```
helmfiles:
  - path: ./*-helmfile.yaml
    values:      
      {{- if not (.Values | get "loadedSecrets" false) -}}
      - {{ tpl (readFile "templates/secrets/loadSecrets.gotmpl") . | nindent 6 }}
      - loadedSecrets: true
      {{- end }}
 ```      

Clearly I'm not really understanding how the `values` in a parent helmfile are used by sub helmfiles or how the sub helmfiles are rendered relative to the parent. 
So is there anyway to share state better or make it persist between renders?

Thanks in advance
Craig
