### DISCUSSION TITLE
if else condition is not working in helmfile

### DISCUSSION THREAD

**Discussion by leon0306** [helmfile/helmfile#1163] [Questions] [answered]
this is my helmfile release file:
```
releases:
- name: ingress-nginx
  namespace: kube-system
  installed: {{ .Values | get "ingress-nginx.enable" true }}
  chart: {{ .Values.modulePath }}/ingress-nginx
  wait: true
  values:
  - platformConfig:
      imageRegistry: {{ .Values.registryDomain }}
      imageRepositoryRelease: {{ .Values.registryRepository }}
      imageRepositoryLibrary: {{ .Values.registryRepository }}
      imagePullPolicy: Always
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
    {{- if .Values.registrySecret }}
    imagePullSecrets:
      - name: {{ .Values.registrySecret }}
    {{- end }}
```

**how can i make this work?**

```
    {{- if .Values.registrySecret }}
    imagePullSecrets:
      - name: {{ .Values.registrySecret }}
    {{- end }}
```

**Comment by yxxhero** [comment]
@leon0306 any logs?

**Reply by leon0306** [reply]
This error will be reported when rendering
```
parsing: template: stringTemplate:29:18: executing "stringTemplate" at <.Values.registrySecret>: map has no entry for key "registrySecret"
```
It seems to be caused by the if else condition not taking effect, because I did not define Values.registrySecret

**Reply by yxxhero** [reply]
@leon0306 yeah. you are right. you can try to use the `get` func. then all will be ok.

**Reply by yxxhero** [reply]
https://helmfile.readthedocs.io/en/latest/templating_funcs/#get

**Reply by leon0306** [reply]
Can you give me an example based on my code? I don't know how to use this func ... :)

**Reply by yxxhero** [reply]
```
releases:
- name: ingress-nginx
  namespace: kube-system
  installed: {{ .Values | get "ingress-nginx.enable" true }}
  chart: {{ .Values.modulePath }}/ingress-nginx
  wait: true
  values:
  - platformConfig:
      imageRegistry: {{ .Values.registryDomain }}
      imageRepositoryRelease: {{ .Values.registryRepository }}
      imageRepositoryLibrary: {{ .Values.registryRepository }}
      imagePullPolicy: Always
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
    {{- if .Values | get "registrySecret" }}
    imagePullSecrets:
      - name: {{ .Values.registrySecret }}
    {{- end }}
```
