### DISCUSSION TITLE
Simple values insertion into `helmfile.yaml` from command line

### DISCUSSION THREAD

**Discussion by RagingTonberry** [helmfile/helmfile#120] [Questions]
So I've read, and probably misunderstood, the docs for some time now. I'm clearly not quite understanding something.
My goal is to simply insert a value into an entry in `releases` which is supplied via the command line. I want to do this in a few places, but here's one for the example:

```
releases:
# INGRESS-NGINX https://kubernetes.github.io/ingress-nginx/
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    cleanupOnFail: true
    createNamespace: true
    namespace: kube-system
    version: 4.0.17
    values:
    - controller:
        addHeaders:
          someHeader: {{ .Values.someHeaderValue }}
```

and I'm syncing this `helmfile.yaml` with:

`helmfile --file <pathtoabovehelmfile.yaml> sync --values <specificvalues.yaml>`

where `specificvalues.yaml` contains

```
someHeaderValue: some-header-value
```

I don't need to do anything fancy here, the use case is quite simple. I just want helmfile to sub in the value during the execution.

What have I missed?

**Edit**

I tried

`helmfile --state-values-file <specificvalues.yaml> --file <pathtoabovehelmfile.yaml> sync`

and that seemed to work. Is that the intended use?
