### DISCUSSION TITLE
CRD management

### DISCUSSION THREAD

**Discussion by nijave** [helmfile/helmfile#1203] [Questions]
Is anyone managing CRDs with `helmfile` and how are you doing it?

We have `helmfile apply` running in CI/CD to deploy our stack which has been working fairly well.

CRDs as `template` files seems to work o.k. but we have some older CRDs installed via Helm's CRD installation hook (where it installs them on first install but doesn't update them) and adopting those into dedicated chart/releases is proving very failure prone. We have some `preapply` hooks to update labels/annotations so the dedicated CRD charts can take ownership of the existing resources but this adds time to each apply run-through since it's running `kubectl` commands first.

We have a handful of charts/environments so it'd be ideal to not have to manually update labels/annotations for the older stuff.

**Comment by bersalazar** [comment]
An option is to disable the app chart's own CRD installation and manage it yourself with helmfile.
This means, install the CRDs as a helm chart first, then install the app's chart with CRD installation disabled.
This means using helmfile's `needs:` to create a dependency to the CRD chart.

e.g.

```
  - name: trust-manager-crds
    namespace: trust-manager
    chart: crds/trust-manager-crds

  - name: trust-manager
    namespace: trust-manager
    chart: charts/trust-manager
    needs:
      - trust-manager/trust-manager-crds
    values:
      - crds:
          enabled: false
```

This approach requires creating a CRD helm chart for each app, and some way of keeping it in-line with the chart's version. 
A bit of overhead, but works nicely for helmfile to manage the CRDs in a consistent way across apps.
