### DISCUSSION TITLE
Define Default Release Template

### DISCUSSION THREAD

**Discussion by ksappington275** [helmfile/helmfile#1205] [Questions]
I have a helmfile, which defines a handful of releases. These releases are defined in a fairly standard way. In particular
```yaml
  - name: mychart
    version: 0.1.7
    chart: oci://{{ .Values.registry }}/{{`{{ .Release.Name }}`}}
    namespace: {{ env "USER" }}
    missingFileHandler: Debug
    values:
      - values/global.yaml.gotmpl
      - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl
      - values/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml.gotmpl
```

Between my releases, the only thing I need to change is the name and version. Is there a good method to define some default release definition that all releases inherit?

One solution I found was using [YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/), however helmfile appears to have a strict schema on the `helmfile.yaml`, so I couldn't easily define some arbitrary
```yaml
defaultRelease: &defaultRelease
  ...
```

Instead I had to hack this a bit by jamming this into a dummy release's values section, which gives me a helmfile that looks like...
```
releases:
  - name: default-release-hack
    chart: default-release-hack
    installed: false
    values:
      - &defaultRelease
        chart: oci://{{ .Values.registry }}/{{`{{ .Release.Name }}`}}
        namespace: {{ env "USER" }}
        missingFileHandler: Debug
        values:
          - values/global.yaml.gotmpl
          - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl
          - values/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml.gotmpl

  - <<: *defaultRelease
    name: foo
    version: 1.2.3

  - <<: *defaultRelease
    name: bar
    version: 4.5.6

  - <<: *defaultRelease
    name: baz
    version: 7.8.9
```
This successfully deploys 3 charts (foo, bar, baz) with the proper values files.

I'd like to avoid this dummy release method though, is there a better way?
(Bonus points if the method also allows for overwriting, so for example, if `foo` could change its namespace after inheriting the default)

**Comment by yxxhero** [comment]
```
templates:
  default:
    chart: stable/{{`{{ .Release.Name }}`}}
    namespace: kube-system
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - config/{{`{{ .Release.Name }}`}}/secrets.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}-secrets.yaml
releases:
- name: heapster
  version: 0.3.2
  inherit:
  - template: default
- name: kubernetes-dashboard
  version: 0.10.0
  inherit:
  - template: default
```
