### DISCUSSION TITLE
Passing Kubernetes context down to layered helmfiles

### DISCUSSION THREAD

**Discussion by bersalazar** [helmfile/helmfile#1212] [Questions] [answered]
Hi,

I'm looking into dynamically passing the Kubernetes context down to helmfiles referenced at the `hemlfiles` block.
I've been unable to do so, so far.
The goal is to consume the incoming Kubernetes secrets `vals` provider, in which the kubeContext can be specified.

e.g. Given 2 files: environments.yaml and helmfile.yaml

environments.yaml
``` 
environments:
  orbstack:
    kubeContext: orbstack
  minikube:
    kubeContext: minikube
---
helmfiles:
  - path: helmfile.yaml
    values:
      - atlantis:
          service:
            type: LoadBalancer
```

helmfile.yaml
```
environments:
  {{ .Environment.Name }}:
    values:
      - mySecret: "ref+k8s://namespace/secret/key?kubeContext={{ .Environment.KubeContext }}"
---
releases:
  - name: any-helm-chart
    namespace: namespace
    chart: ../charts/any-helm-chart
    values:
      - some_secret_required_by_chart: '{{ .Values.mySecret }}'
```

Command would be something like:
`helmfile template -e minikube -f environments.yaml`

Unfortunately, `{{ .Environment.KubeContext }}` renders empty.
Is there a way to do this?

Alternatively, the Kubernetes context is inherited by `vals`, from the context used by helmfile in its execution (set at the top `environments` block). This is not the case at the moment.

**Comment by bersalazar** [comment]
@yxxhero :point_up: 
I you can shed some light here please. It's a use case for https://github.com/helmfile/vals/pull/186.

**Reply by bersalazar** [reply, marked as answer]
I've worked around defining a `kubeContext` value with the KubeContext from environments, and then using that value in the helmfile.yaml:

environments.yaml
```
environments:
  orbstack:
    kubeContext: orbstack
  minikube:
    kubeContext: minikube
---
helmfiles:
  - path: helmfile.yaml
    values:
      - atlantis:
          service:
            type: LoadBalancer
      - kubeContext: {{ .Environment.KubeContext }}
```
helmfile.yaml
```
environments:
  {{ .Environment.Name }}:
    values:
      - mySecret: "ref+k8s://namespace/secret/key?kubeContext={{ .Values.kubeContext }}"
---
releases:
  - name: any-helm-chart
    namespace: namespace
    chart: ../charts/any-helm-chart
    values:
      - some_secret_required_by_chart: '{{ .Values.mySecret }}'
```
However, this is not great as ideally the {{ .Environment.KubeContext }} can be directly referenced, or somehow it's implicitly inferred by vals when fetches the secret.
