### DISCUSSION TITLE
feat: allowing variables in values of `set`

### DISCUSSION THREAD

**Discussion by jjangga0214** [helmfile/helmfile#1219] [Ideas]
Let's say I have 3 environments, named `prod`, `stg`  and `local`.
Then I can write a release like this.

```yaml
  - name: foo
    chart: ./foo
    set:
      - name: bar
        {{ if eq .Environment.Name "prod" }}
        file: prod/bar
        {{ else if eq .Environment.Name "stg" }}
        file: stg/bar
        {{ else }}
        file: local/bar
        {{ end }}
```

However, I actually think it can become better by this.

```yaml
  - name: foo
    chart: ./foo
    set:
      - name: bar
        file: {{ .Environment.Name }}/bar
```

But this syntax is currently not allowed.

How do you think?

Thank you :)
