### DISCUSSION TITLE
helmfile needs to support Repositories that only support plain http

### DISCUSSION THREAD

**Discussion by hoangelos** [helmfile/helmfile#1224] [Ideas]
Helm has a flag for push and pull --plain-http for those that aren't in situations where they can use https.  Without this helmfile appears to be unusable in these situations.  Repositories should have a flag plainHttp, which can trigger that for fetch, pull, and push

```yaml
repositories:
- name: slave-to-the-charts
  url: super.ecret.registry.com:8082
  plainHttp: true
```
