### DISCUSSION TITLE
Does helmfile support kubeconfig directly ?

### DISCUSSION THREAD

**Discussion by joelee2012** [helmfile/helmfile#1253] [Questions]
Refer https://helmfile.readthedocs.io/en/latest/#configuration , only `kubeContext` is available for environments, can i set kubeconfig file directly in `helmfile.yaml` ?

**Comment by yxxhero** [comment]
@joelee2012 you can use KUBECONFIG env.

**Comment by joelee2012** [comment]
Yes, currently i set env for different cluster. but it's not convenient, and have to make sure cluster is correct before applying any change. so can helmfile support this feature like `kubeContext` ?

**Reply by tibeer** [reply]
@joelee2012 @yxxhero also interested in this. I have a script which creates a cluster and downloads the new kubeconfig file, right before helmfile is executed. This works well with the command line parameters of helmfile itself, but as soon as I run hooks in helmfile, things break:

```yaml
---
bases:
  - ../_environments/environments.yaml

helmDefaults:
  createNamespace: true
  wait: true
---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    installed: {{ .Values.cert_manager._enabled }}
    chart: jetstack/cert-manager
    version: v1.14.5
    labels:
      app: cert-manager
      infra: required
    hooks:
      # This hook adds the CRDs
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
```

The new context can be used from the release environment variables, but kubeconfig is not present here. Using something like:

```yaml
        (...)
        command: "KUBECONFIG=/foo/bar kubectl"
        (...)
```

Would also not work, because the name of that file changes based on the wrapping script that creates the clusters.
Is there a chance we can also get something like 

```yaml
        (...)
        args:
          - "apply"
          - "-f"
          - "https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
          - "--kubeconfig"
          - "{{`{{.Environment.Kubeconfig}}`}}"
        (...)
```

That would be awesome!
