### DISCUSSION TITLE
Support glob patterns for values files list

### DISCUSSION THREAD

**Discussion by achetronic** [helmfile/helmfile#1256] [Ideas]
Hello there. I would like Helmfile to support glob patterns on values files paths. Something like this would help with those companies that use helmfile in production and the amount of the values are huge

```yaml
  - name: tekton
    namespace: tekton
    chart: ../../charts/meta-tekton
    version: 0.1.0
    values:
      - ../../common/tekton.yaml
      - ./values/tekton/*.yaml
      - ./values/tekton/namespaces/*.yaml
    installed: {{ .Values.tekton_installed }}
```

WDYT about it?
