### DISCUSSION TITLE
Allow the helm-secrets backend to be configured using helmfile

### DISCUSSION THREAD

**Discussion by jeliebig** [helmfile/helmfile#1311] [Ideas]
I'd like to configure the secret backend used by helm-secrets in the `helmfile.yaml` instead of setting the environment variable `HELM_SECRETS_BACKEND` on the command line every time.

Maybe it would also be nice to use different backends for different environments.

How about an option called `secretsBackend`? It could be used like `missingFileHandler` currently:

```yaml
# Configure a default helm-secrets backend. The value can be one of `vals`, `sops` or a (absolute/relative) path to a custom backend.
secretsBackend: ""

environments:
  default:
    values:
      - environments/default/values.yaml
  production:
    values:
      - environments/production/values.yaml
    # Use a different helm-secrets backend for the production environment.
    secretsBackend: environments/production/custom.sh
```
