### DISCUSSION TITLE
helmfile environmental variables not being processed

### DISCUSSION THREAD

**Discussion by danilo-patrucco** [helmfile/helmfile#1351] [Questions] [answered]
Hi, 

I have three files, a helmfile.yaml, a values.yaml.gotmpl and a values.dev.yaml that is used as a a variable file for the environment.
In the values.yaml.gotmpl i have a field that require an env variable because it's a secret.

This is the field in the gotmpl file

```
configs:
  secret:
    createSecret: true
    extra: {{ .Values.config.secrets.extra }}
    argocdServerAdminPassword: ""
  styles: ""
```

this is how i'm trying to pass the env variable: 
repositories:
```
  - name: repo
    url: https://my-repo.com
    oci: true

environments:
  dev:
    values:
      - values.dev.yaml
  preprod:
    values:
      - values.preprod.yaml
  prod:
    values:
      - values.prod.yaml

---

releases:
  - name: argo-cd
    namespace: argo-cd
    chart: oci://my-repo.com/argo-cd
    version: 5.55.0
    values:
      - values.yaml.gotmpl
      - configs:
          secrets:
            extra: {{ requiredEnv $KEYCLOAKTOKEN }}
``` 
But when i run the helmfile - command it fails wiht the following error: 

helmfile -f ${HELMFILE_BASE_DIR}/helmfile.yaml deps
in helm/helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:11: undefined variable "$KEYCLOAKTOKEN"

I was wondering what am i doing wrong
