### DISCUSSION TITLE
How / where to define values, that are not in the environment, but also not in the release?

### DISCUSSION THREAD

**Discussion by tibeer** [helmfile/helmfile#1394] [Questions]
Imagine a multi-helmfile structure like this:

```sh
.
├── .age.key
├── .gitignore
├── .sops.yaml
├── gitea
│   ├── gitea.yaml.gotmpl
│   ├── helmfile.yaml
│   └── secrets.gitea.yaml
├── hedgedoc
│   ├── hedgedoc.yaml.gotmpl
│   ├── helmfile.yaml
│   └── secrets.hedgedoc.yaml
└── helmfile.yaml
```

The uppler layer helmfile just looks like this:

```yaml
---
helmDefaults:
  wait: true
  createNamespace: true

environments:
  prod:
    kubeContext: prod
    values:
      - _base_url: "prod.foobar.com"
      - _cluster_issuer: "production"
  dev:
    kubeContext: dev
    values:
      - _base_url: "dev.foobar.com"
      - _cluster_issuer: "staging"

helmfiles:
  - ./*/helmfile.yaml
```

While the sub-helmfiles look like this:

```yaml
---
environments:
  prod:
    values:
      - _sub_domain: "hedgedoc"
  dev:
    values:
      - _sub_domain: "hedgedoc"
---
repositories:
  - name: foo
    url: ghcr.io/foo
    oci: true

releases:
  - name: hedgedoc
    namespace: hedgedoc
    installed: true
    chart: foo/hedgedoc
    version: ~0.1.0
    values:
      - hedgedoc.yaml.gotmpl
    secrets:
      - secrets.hedgedoc.yaml
```

and the inside of the gotmpl files often have a setions that looks like this:

```yaml
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values._cluster_issuer }}"
  hosts:
    - host: "{{ .Values._sub_domain }}.{{ .Values._base_url }}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: hedgedoc-tls
      hosts:
        - "{{ .Values._sub_domain }}.{{ .Values._base_url }}"
```

What is the best way to store the value for "_sub_domain", as it is (in my scenario) every time the same value independent ot the environment used. It would be awesome to have it stored somewhere inside the folder of the respective app itself, but I would like to avoid repeating the environment again. Sure, I could hard code it inside the gotmpl file, but is there another solution?

**Comment by yxxhero** [comment]
@tibeer could give me some example on github?

**Comment by tibeer** [comment]
@yxxhero sure! I created a dummy repo that should represent partly my structure, except that in reality, there are a lot more helm charts and more environments ^^

**Comment by tibeer** [comment]
@yxxhero Did you already had the time to check on this? :)

**Reply by yxxhero** [reply]
maybe readfile && yaml Anchors

**Reply by tibeer** [reply]
Perfect! don't even need yaml Anchors :) I will post a long answer for others that might run into this problem.

**Comment by tibeer** [comment]
Answer that worked for me:

New file structure:

```sh
.
├── .age.key
├── .gitignore
├── .sops.yaml
├── gitea
│   ├── gitea.yaml.gotmpl
│   ├── helmfile.yaml
│   ├── secrets.gitea.yaml
│   └── values.yaml
├── hedgedoc
│   ├── hedgedoc.yaml.gotmpl
│   ├── helmfile.yaml
│   ├── secrets.hedgedoc.yaml
│   └── values.yaml
└── helmfile.yaml
```

The uppler layer helmfile still looks like this:

```yaml
---
helmDefaults:
  wait: true
  createNamespace: true

environments:
  prod:
    kubeContext: prod
    values:
      - _base_url: "prod.foobar.com"
      - _cluster_issuer: "production"
  dev:
    kubeContext: dev
    values:
      - _base_url: "dev.foobar.com"
      - _cluster_issuer: "staging"

helmfiles:
  - ./*/helmfile.yaml
```

While the sub-helmfiles now look like this:

```yaml
---
repositories:
  - name: foo
    url: ghcr.io/foo
    oci: true

releases:
  - name: hedgedoc
    namespace: hedgedoc
    installed: true
    chart: foo/hedgedoc
    version: ~0.1.0
    values:
      - hedgedoc.yaml.gotmpl
    secrets:
      - secrets.hedgedoc.yaml
```

and the inside of the gotmpl files now looks like this:

```yaml
---
{{- $common := ( readFile "values.yaml" | fromYaml ) }}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values._cluster_issuer }}"
  hosts:
    - host: "{{ $common.sub_domain }}.{{ .Values._base_url }}"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: hedgedoc-tls
      hosts:
        - "{{ $common.sub_domain }}.{{ .Values._base_url }}"
```

And the values.yaml file contains this:

```yaml
---
sub_domain: ntfy
```

Absolutely awesome @yxxhero! Thank you so much :)
