### DISCUSSION TITLE
How to escape brackets and dollar signs?

### DISCUSSION THREAD

**Discussion by soloradish** [helmfile/helmfile#142] [Questions] [answered]
There are `$` and `{{ }}` in our value strings. For example:

```
    values:
      - prometheusRule:
          enabled: true
          rules: 
            - alert: Some alert
              annotations:
                # message: 'Some metrics gone wrong'
                message: 'Instance {{ $labels.instance }} some metircs is  {{ $value }}'
              expr: 'some_metrics != 0'
              labels:
                severity: none
```

`Instance {{ $labels.instance }} some metircs is  {{ $value }}` follow the promtheus alert rule's syntax.

If I apply this helmfile I will get 
```
undefined variable "$labels"
```

How do I escape these characters? Please help me.
