### DISCUSSION TITLE
Extract collection from SOPS with vals?

### DISCUSSION THREAD

**Discussion by philomory** [helmfile/helmfile#143] [Questions] [answered]
Is there a way to write a `vals` reference, with or without the use of go template functions, such that it will extract a whole tree/collection from a subkey of a SOPS file?

For example, assume I have a SOPS file that looks like this when decrypted:
```yaml
foo:
  hello: world
  another: value
bar:
  some: secret
```

If you write a `vals` reference such as `ref+sops://path/to/secrets.yaml#/foo/hello`, you get `world` out as expected, but if you write `ref+sops://path/to/secrets.yaml#/foo` you get the error, "no value found for key foo` (which, aside from anything else, is a pretty misleading error message). You get more-or-less the same results if you pass the reference to the `fetchSecretValue` function.

I realize of course I could duplicate the tree structure on the "calling" side, e.g.
```yaml
values:
  - stuff:
      foo:
        hello: ref+sops://path/to/secrets.yaml#/foo/hello
        another: ref+sops://path/to/secrets.yaml#/foo/another
```
... however, this gets pretty cumbersome when you have a lot of different secrets. I could, of course, also just use the `helm secrets` functionality of `helmfile` instead, but this comes with the twin disadvantages that, a) you cannot select only a subset of the file, and b) you cannot load the values into a particular place in your values tree. And of course, even if you wanted to get your hands dirty doing things via e.g. `readFile`, you're stuck since you can't decrypt the file if you load it that way.
