### DISCUSSION TITLE
Deploy chart from private GitLab helm repo

### DISCUSSION THREAD

**Discussion by mananpreetsingh** [helmfile/helmfile#1431] [Questions]
Hi,
I have private helm package registry hosted on GitLab and would like to deploy chart using helmfile. I have the following in my helmfile., Any idea how can I deploy from private gitlab repo/package registry?

```
repositories:
  - name: app
    url: https://gitlab.com/api/v4/projects/xxxxxx/packages/helm/stable
    
releases:
  - name:app
    namespace: default
    chart: app/example
```

thanks,
