### DISCUSSION TITLE
needs resolution failure when using template

### DISCUSSION THREAD

**Discussion by gakesson** [helmfile/helmfile#145] [Questions] [answered]
Including @yxxhero @mjhuber but anyone else, feel free to chip in.

This is regarding https://github.com/helmfile/helmfile/issues/49 which I want to bring to life again. This issue is currently blocking us from upgrading to a more recent helmfile version (from 0.142), because templating etc. now suddenly requires needs to be fullfilled and there is no (working) flags allowing e.g. templating to skip needs.

Is there something that can be done regarding this?
If it is not feasible to address this, perhaps the change introducing this regression should be reverted?

**Comment by gakesson** [comment]
@yxxhero I'm unable to contribute to the #147 discussion because it is limited to collaborators, but attaching helmfile here. Issue can be reproduced using below command (v0.144.0):
_helmfile -l name=service-b template_

Error raised:
_in ./helmfile.yaml: release(s) "service-b" depend(s) on an undefined release "service-a". Perhaps you made a typo in "needs" or forgot defining a release named "service-a" with appropriate "namespace" and "kubeContext"?_

Running without selector works, as well as running with selector -l name=service-b -l name=service-a


```
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
releases:
- name: service-a
  chart: incubator/raw

- name: service-b
  needs:
    - service-a
  chart: incubator/raw

```
