### DISCUSSION TITLE
New Inherit Template not working with Layering State?

### DISCUSSION THREAD

**Discussion by ducnm0711** [helmfile/helmfile#1479] [Questions]
Following the guide here: 
https://helmfile.readthedocs.io/en/latest/writing-helmfile/#release-template-conventional-directory-structure
It's working fine if follow the document and write templates block in same helmfile.yaml
My folder structure is somewhat like this:
```
├── environments.yaml
├── helmfile.yaml
├── applications
│   ├── app_1
│   │   ├── helmfile.yaml
│   ├── app_2
│   │   ├── helmfile.yaml
```
Top level `helmfile.yaml`
```
bases:
  - environments.yaml
---
templates:
  default:
    missingFileHandler: Warn
    values:
    - ../../../vars/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - ../../../vars/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}/secrets.yaml
---
helmfiles:
  - applications/*/*/helmfile.yaml
```
App level `helmfile.yaml`
```
releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.10.0
    inherit:
    - template: default
```
failed executing release templates in "helmfile.yaml": release "ingress-nginx" tried to inherit inexistent release template "default
