### DISCUSSION TITLE
Combining Helmfile, Kustomize, and Raw manifests together

### DISCUSSION THREAD

**Discussion by mlkmhd** [helmfile/helmfile#1558] [Ideas]
Excuse me, I recently encountered a problem regarding the customization of generated manifests by a Helmfile. As you may know, it’s not possible to edit a Helm chart that I don’t maintain. Opening a pull request for the desired Helm chart can be time-consuming, and there’s a chance it might not be accepted. Therefore, in many cases, I customize the Helm chart using a Kustomize patch file and apply them to the manifests generated by Helmfile as follows:
```
helmfile template > resources.yaml
kustomize build . > resources-patched.yaml
kubectl apply -f resources-patched.yaml
```
Is it possible to add a new section inside the `helmfile.yaml` file in this manner? This would allow me to add a Kustomize patch file and build the final manifests with just a single command:
```
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  # Add other repositories as needed

releases:
  - name: my-helm-chart
    namespace: my-namespace
    chart: stable/my-chart
    version: 1.2.3
    values:
      key1: value1
      key2: value2

  - name: my-kustomize-resources
    namespace: my-namespace
    labels:
      app: my-app
    kustomize:
      path: ./kustomize/overlay   # <======== this is the patch file which I want to apply it to the helm chart after building the manifests
```

I recently wrote an article on Medium to elaborate on my idea. In the article, I used a Bash script to integrate different approaches, such as `Helmfile`, `Kustomize`, and `Raw manifests`:
https://medium.com/itnext/helm-kustomize-raw-manifests-combination-570f81acf996
