### DISCUSSION TITLE
helmfile --set append values for all releases

### DISCUSSION THREAD

**Discussion by sarathsprakash** [helmfile/helmfile#1567] [Questions]
Whats is the way to append values for a specific releases using --set?

I have the following helmfile

```
releases:
    - name: mysql
      chart :./mysql
      namespace: mysql
   - name: myservice
     chart:./myservice
     namespace: myservice
     needs:
         - mysql/mysql
```

 Now if I intend to override any values dynamically in inline using the the `--set` this will not work specific for particular release even though I pass the releasename, it gets applied to all the releases in the helmfile. How can I get past this?
 
 `helmfile sync --set myservice.imageName=myservice:1.2.0`

I don't want to use the `--state-values-set` as I don't want to get restricted on what I can override
`
