### DISCUSSION TITLE
when applying a helmfile vals reference is not rendered

### DISCUSSION THREAD

**Discussion by Pela2silveira** [helmfile/helmfile#1577] [Questions]
Hi community, I am glad to see this product is evolving nicely,

I wonder if I am doing something wrong or this is not supported, I am trying to reference a state dynamically in a helmfile but it fails:

ref+tfstate://../../../../terraform-live/environments/{{ .Environment.Name }}/eksv2/.terraform/terraform.tfstate/output.oidc_provider_arn

```
in helmfile.d/helmfile.yaml: in .helmfiles[0]: in /home/user/src/helmfile/centralized/kube-system/helmfile.d/helmfile.yaml: failed processing release metric-server: expand tfstate://../../../../terraform-live/environments/{{: reading tfstate for {{: invalid json: read ../../../../terraform-live/environments: is a directory
```

**Comment by yxxhero** [comment]
@Pela2silveira could  you show an demo?

**Reply by Pela2silveira** [reply]
Hi @yxxhero ! Glad to read you :) 

I realized that it works on a value.yaml.gotmpl without problems.

My problem was trying to render here:

```
releases:
- name: metric-server
  namespace: kube-system
  version: 3.12.1
  chart: metrics-server/metrics-server
  values: 
    - key: refs....{{ .Environment.Name }}....
```

I realized that no render at all is made in this way. I am trying more use cases..

thanks

**Reply by Pela2silveira** [reply]
Hi @yxxhero I found out that the above snippet works if I change the type of the file to helmfile.yaml.gotmpl

I am trying to use vals inside this block:

```
repositories:
 - name: metrics-server
   url: https://kubernetes-sigs.github.io/metrics-server/ 
  
 - name: aws-karpenter
   url:  public.ecr.aws/karpenter
   oci: true
   username: ref+tfstate://......
   .....
```
 The fields are processed as strings, do you want I make a demo of this?
