### DISCUSSION TITLE
Getting syntax error while looping a list, Please suggest.

### DISCUSSION THREAD

**Discussion by udayrt** [helmfile/helmfile#1584] [Questions]
```
helmfile --file helmfile.yaml apply --kube-context kind-monitoring
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:29:31: executing "stringTemplate" at <.Values.clusterNames>: map has no entry for key "clusterNames"
```

Below is the helmfile.yaml
```

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: monitoring
    values:
      - server:
          service:
            type: NodePort

  - name: grafana
    chart: grafana/grafana
    namespace: monitoring
    values:
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
              {{- range .Values.clusterNames }}
              - name: {{ . }}
                type: prometheus
                url: http://{{ index $.Values.externalIPs . }}:{{ index $.Values.nodePorts . }}
                access: proxy
                isDefault: false
              {{- end }}

      - clusterNames:
        - cluster1
        - cluster2
      - externalIPs:
          cluster1: 10.11.53.16
          cluster2: 10.11.53.16
      - nodePorts:
          cluster1: 30081
          cluster2: 30082
```
