### DISCUSSION TITLE
No matches for path will appear, confirm the use of bases and helmfiles

### DISCUSSION THREAD

**Discussion by 880831ian** [helmfile/helmfile#1613] [Questions]
Hello, I currently get no matches for path when using helmfile, but it will not affect my use. I just want to confirm why it appears.

This is the architecture diagram of my current projects

```
├── helmfile.yaml
├── dept-1
│   ├── api
│   │   ├── apps
│   │   ├── chart
│   │   └── helmfile.yaml
│   ├── helmfile.yaml
│   └── soketi
│       ├── apps
│       ├── chart
│       └── helmfile.yaml
```

We will have multiple departments use it. In the root directory, there will be department folders. There will be a helmfile.yaml file shared by all departments (hereinafter referred to as a.yaml). Within the department, there will also be the department's own helmfile.yaml (Subsequently referred to as b.yaml), and each service will have its own helmfile.yaml (Subsequently referred to as c.yaml)

<br>

There is such an architecture because we hope to achieve DRY. The following is a.yaml

- helmfile.yaml (a.yaml)
```
helmDefaults:
  createNamespace: true
  diffArgs:
    - "--context 5"
```
The default settings of helmDefaults are placed here so that all departments can use them to achieve DRT

<br>

The following is b.yaml

- dept-1/helmfile.yaml (b.yaml)
```
environments:
  test_dev:
    values:
    - platform: test
      env: dev
    kubeContext: {{ if env "CI_COMMIT_BRANCH" }}XXX/gitlab-agent:test-dev{{ else }}gke_XXXX_test-dev{{ end }}
  test_qa:
    values:
    - platform: test
      env: qa
    kubeContext: {{ if env "CI_COMMIT_BRANCH" }}XXX/gitlab-agent:test-qa{{ else }}gke_XXXX_test-qa{{ end }}

helmfiles:
- path: api/helmfile.yaml
```
b.yaml will contain the environments used by the department, because it will correspond to different gke or gitlab CICD's gitlab-agent. I use helmfiles ,so that he can operate under dept-1 command

<br>

The following is c.yaml

- dept-1/api/helmfile.yaml (c.yaml)

```
bases:
  - ../../helmfile.yaml
  - ../helmfile.yaml

templates:
  api: &api
    namespace: test
    chart: "./chart/"
    values:
      - apps/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml

releases:
  - <<: *api
    name: api-1
    labels:
      service: api-1

  - <<: *api
    name: api-2
    labels:
      service: api-2
```
Here I will add bases so that he can use the helmfile.yaml of the first two layers to get helmDefaults and environments, and there will be corresponding templates and releases depending on the service.

<br>

This mode allows me to issue this command under dept-1 or dept-1/api to operate helmfile

```
helmfile --color -e test_qa -l name=api-2 diff
```

After this, no matches for path: api/helmfile.yaml will appear, but the correct helmDefaults and environments settings are still used. I am wondering if there is something wrong with my helmfiles writing method?

Please help me to reply again, thank you all
