### DISCUSSION TITLE
Allow use of VALS references in repository credentials

### DISCUSSION THREAD

**Discussion by philomory** [helmfile/helmfile#165] [Ideas]
Right now, if you declare a repository like this:
```
repositories:
  - name: private
    url: https://helm.something.com/whatever/
    username: helm
    password: ref+vault://some/password
```
... then when Helmfile goes to set up the repository, it actually executes the command `helm repo add private https://helm.something.com/whatever/ --force-update --username helm --password ref+vault://some/password`. This is... not ideal. It'd be really nice to be able to use Vals refs here like you can nearly everywhere else.
