### DISCUSSION TITLE
When namespace creation occured?

### DISCUSSION THREAD

**Discussion by rpo-fr** [helmfile/helmfile#1716] [General]
I try to add secrets in a namespace  during prepare hook execution, but i have an error because namespace doesn't exist.
If I remove hook, namespace is created by helmfile execution.
Do you have an idea how i can do this?

**Comment by yxxhero** [comment]
you can use raw chart to manage your secret.

**Comment by yxxhero** [comment]
https://medium.com/@ectobit/control-kubernetes-resources-using-helmfile-and-raw-helm-chart-5cb6b046f11d

**Reply by rpo-fr** [reply]
raw helm chart is made for helm v2, it's too old to use it

**Reply by yxxhero** [reply]
@rpo-fr No. you can use it any time. not for helm v2.

**Comment by zhaque44** [comment]
@rpo-fr you can also use **createNamespace: true** <= to create the namespace (example below):

  ```
- name: example-chart
    namespace: mynamespace
    createNamespace: true
    chart: prometheus-community/example-chart-name
    version: 1.1.1 #example version
    labels:
      app: my-label
    values:
      - values/valuesfile.yaml
```
