### DISCUSSION TITLE
helm pod readiness

### DISCUSSION THREAD

**Discussion by uk1988** [helmfile/helmfile#1727] [Questions]
Hello Everyone,

I've found Helmfile to be an invaluable tool for orchestrating our deployments efficiently. However, we're encountering a challenge with deploying our charts sequentially, where the deployment of one chart depends on the successful and complete readiness of pods deployed by a preceding chart. Although Helmfile utilizes the wait parameter from Helm to ensure that a chart is fully deployed before moving on, this does not guarantee that all the pods are in a ready state. This can cause issues when a pod from chart B depends on the readiness of a pod from chart A, but Helmfile progresses to deploying chart B before chart A's pods are fully ready.

As a workaround, we're considering implementing a special helm chart that triggers a cron job. This job would perform curl requests against the Kubernetes API to verify the readiness of all relevant pods before proceeding. Before we proceed with this workaround, I wanted to ask the community:

Does Helmfile offer an out-of-the-box solution or feature to ensure that deployments of interdependent charts are sequenced based on the readiness state of pods, rather than just the completion of the helm deployment?

I appreciate any advice or insights you can offer on this topic

Best Uros

**Comment by zhaque44** [comment]
@uk1988 Hi, hope everything is good: 

Helmfile does offer a feature that might help with your use case without needing the cron job workaround. You can use `needs` field to control the sequencing of chart deployments based on dependencies:

```
releases:
  - name: myapp1
    chart: charts/myapp
    needs:
      - servicemesh
      - logging
  - name: myapp2
    chart: charts/myapp
    needs:
      - servicemesh
      - logging
  - name: servicemesh
    chart: charts/istio
    needs:
      - logging
  - name: logging
    chart: charts/fluentd
```

`myapp1` and `myapp2` depend on both `servicemesh` and `logging`, ensuring that these chart releases are fully deployed before Helmfile proceeds with `myapp1` and `myapp2`. Also notice that, `servicemesh` depends on `logging`, so `logging` will be installed first.

With this approach, you can ensure that charts are installed or deleted in the correct order. You need to specify the kubecontext and namespace if they are configured for specific env based releases.

**Reply by uk1988** [reply]
@zhaque44 this is only about order, not about forcing helm to only move forward when deployment is fully done

**Comment by xiaomudk** [comment]
@uk1988 The --wait-for-jobs parameter in Helm (represented as waitForJobs: true in Helmfile) can indeed help solve your issue. This parameter ensures that Helm waits for all Jobs in the release to complete before marking the release as successful. Here's an example of how to use it in Helmfile:
```
releases:
  - name: config-setup
    namespace: helmtest
    wait: true
    waitForJobs: true
    timeout: 1200
    labels:
      name: config-setup-label
```
- `wait`: true tells Helmfile to wait for the release to be ready.
- `waitForJobs`: true ensures all Jobs complete before considering the release successful.
- `timeout`: 1200 sets a 20-minute timeout for the operation.
