### DISCUSSION TITLE
Nested templates

### DISCUSSION THREAD

**Discussion by rlex** [helmfile/helmfile#174] [Questions]
Hello! Have issues with vector chart.

Full sample:
```yaml
---
repositories:
  - name: vector
    url: https://helm.vector.dev
releases:
  - name: vector
    namespace: monitoring
    createNamespace: true
    chart: vector/vector
    values:
      - customConfig:
          api:
            enabled: false
          data_dir: "/vector-data-dir"
          sinks:
            prometheus:
              address: "0.0.0.0:9090"
              inputs: ["internal_metrics", "host_metrics"]
              type: "prometheus"
            loki:
              inputs: ["kubernetes_logs"]
              type: "loki"
              endpoint: "https://loki"
              auth:
                strategy: basic
                user: loki
                password: loki
              remove_timestamp: true
              tenant_id: loki
              encoding: json
              labels:
                forwarder: "vector"
                file: "{{` {{ file }} `}}"
```

Problem comes with final line, that's supposed to look like this:
```
file: "{{ file }}"
```

And i can't get it to print like this.
tried wrapping in 
```{{` `}}```, no luck

Guess toYaml breaks it? https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/configmap.yaml#L10
