### DISCUSSION TITLE
Add .Release to templating for "installed"

### DISCUSSION THREAD

**Discussion by DanyHenriquez** [helmfile/helmfile#1741] [Ideas]
It would be very convenient to have access to `.Release` in the `installed` templating variables for use cases where, depending on environment, some apps need to be install and some not.

environment.yaml:
````
installed:
  - app-a
  - app-b
````
helmfile.yaml
```yaml
templates:
  default:
    installed: "{{ .Values.installed | has .Release.Name }}"
```
