### DISCUSSION TITLE
Set environment variables via Helmfile environments

### DISCUSSION THREAD

**Discussion by WillDaSilva** [helmfile/helmfile#1743] [Ideas]
It would be nice if we could set environment variables via Helmfile environments. These would be useful for [vals](https://github.com/helmfile/vals) references (i.e. ref+protocol://), or by templates using {{ env ... }} / {{ requireEnv ... }}?

In my case I have many vals refs to the Pulumi API, and I can either repeat the same 3 query parameters for each ref, or set env vars for them. I'd like to keep this self-contained by not requiring env vars be set when running `helmfile` commands, but I also don't want to repeat the query parameters for each ref. Ideally I could do something like this:

```yaml
environments:
  default:
    env:
      PULUMI_ORGANIZATION: my-pulumi-org
      PULUMI_PROJECT: my-pulumi-project
      PULUMI_STACK: my-pulumi-stack
```
