### DISCUSSION TITLE
Sub-helmfile concurrency

### DISCUSSION THREAD

**Discussion by philomory** [helmfile/helmfile#178] [Ideas]
In https://github.com/roboll/helmfile/issues/591, there was discussion of allowing sub-helmfile releases to be installed concurrently. @mumoshu [proposed the following design](https://github.com/roboll/helmfile/issues/591#issuecomment-653219220):
>Given all that, I guess our best bet would be to give up controlling order of files under the directory, and only allow controlling the order and the parallelism of `helmfiles:` entries, extending the DAG feature(`releases[].needs`) to sub-helmfiles.
>
>```yaml
>helmfiles:
>- name: infra
>  path: helmfile.infra.yam
>- name: apps1
>  path: helmfile.apps1.yaml 
>  needs: infra
>- name: apps2
>  path: helmfile.apps2.yaml 
>  needs: infra
>```
>This results in Helmfile computing a DAG of helmfiles [ infra ] <-- depends on [app1, app2]. As app1 and app2 being independent to each other after infra is given, helmfile will automatically install infra first, and then concurrently install app1 and app2.

This seems like an excellent idea that could be very helpful if you have a setup involving sub-helmfiles because it allows cleaner organization and separation of concerns, but, once all the releases and values are calculated, you still want the actual installation to be done in parallel for performance.

Obviously, I have no idea how much work this would  be to implement, but, the fact that @mumoshu is the one who proposed it leads me to believe it'd be at least _vaguely_ plausible to implement. I figured I'd re-post it here so it didn't get lost in the repository transition.

**Comment by roulettedares** [comment]
our gitops repo is organized in a 1 helmfile per namespace pattern with a top level helmfile:
```yaml
helmfiles:
- path: helmfiles/cert-manager/helmfile.yaml
- path: helmfiles/integration/helmfile.yaml
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/kafka/helmfile.yaml
- path: helmfiles/knative-operator/helmfile.yaml
- path: helmfiles/kuberhealthy/helmfile.yaml
- path: helmfiles/nginx/helmfile.yaml
- path: helmfiles/secret-infra/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
- path: helmfiles/monitor/helmfile.yaml
- path: helmfiles/vault-infra/helmfile.yaml
- path: helmfiles/sonarqube/helmfile.yaml
- path: helmfiles/goldilocks/helmfile.yaml
- path: helmfiles/knative/helmfile.yaml
- path: helmfiles/istio-system/helmfile.yaml
```
lack of parallelism when using subhelmfiles is starting to add up and hurt

**Reply by gakesson** [reply]
@joshuasimon-taulia have you tried to use _bases_ instead?
```
bases:
- helmfiles/cert-manager/helmfile.yaml
- helmfiles/integration/helmfile.yaml
...
```

We use that to achieve concurrency in multiple sub-helmfiles.

**Reply by roulettedares** [reply]
```shell
in ./helmfile.yaml: failed to read helmfiles/cert-manager/helmfile.yaml: environment values file matching "jx-values.yaml" does not exist in "."
```
i'm guessing `bases` doesn't work with values defined in the base helmfile `releases[*].values`
ex:
```yaml
releases:
- chart: bitnami/external-dns
  version: 6.4.5
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
  - external-dns-values.yaml.gotmpl
```

[this](https://github.com/jx3-gitops-repositories/jx3-gke-gsm/tree/main/helmfiles) is an example of the convention we have to follow

**Comment by mumoshu** [comment]
Hey! Thanks for bringing this up.

> at least vaguely plausible to implement.

Not at all... sorry 😅 
The hardest part is that we now need to abstract out our `needs` feature so that it can also support sub-helmfiles, which might result in many regressions to the existing `needs` feature if not done correctly.
I'm even unsure if the `sub-helmfiles` abstraction was right- for example we don't currently have the ability to diff all the releases from all the helmfiles before applying the releases defined in the root helmfile.yaml. The behavior might be a bit surprising to users who are familiar with e.g. terraform.
Can we instead introduce another abstraction over releases? Something like...

```
releaseSets:
- name: apps
  needs:
  - dbs
  releases:
  - name: frontend
    chart: charts/frontend
  - name: backend
    chart: charts/backend  
- name: dbs
  needs:
  - logging
  releases:
  - name: mysql
    charts: charts/mysql
  - name: redis
    charts: charts/redis
- name: logging
  path: helmfiles/logging/helmfile.yaml
```

**Reply by philomory** [reply]
Hm, this seems like it'd work in some cases, but in cases where people have other reasons to want to use sub-helmfiles (for example, separation of state values), they're still going to be kinda stuck.

**Reply by mumoshu** [reply]
> want to use sub-helmfiles (for example, separation of state values), they're still going to be kinda stuck.

Thanks for the feedback. Just curious, but how are you handling your use-case then? What if we were able to pass environment values to the sub-helmfile in `releaseSets` via a `values` field like this..?

```
releaseSets:
- name: logging
  path: helmfiles/logging/helmfile.yaml
  values:
  - yourdefaultenvvalues.yaml
```

**Reply by philomory** [reply]
Oh, sorry, I was assuming that these `releaseSets` wouldn't *be* actual helmfiles, but instead just lists of releases. If those are full helmfiles of their own with their own values already, then the `releaseSets` idea should work fine, although, I'm not sure what makes it different to `helmfiles` conceptually, at that point? It seems like `releaseSets` just becomes `helmfiles` with fewer bugs?

**Reply by philomory** [reply]
The core motivation here, by the way, is to have separate _state_ values, not _chart_ values, because unlike chart values, state values can have multiple environments in the same file, like this:

```yaml
# some-app.yaml
values:
  - key: default_value
    key2: another default

environments:
  test:
    values:
      - key3: test-specific
  prod:
    values:
      - key3: prod-specific
```

That's a truncated example (it's missing any releases, for one thing), but the main point is that when you have one (or a few) apps per helmfile, you can have per-environment values inline. The closest you could get if you had to do it on a release-by-release basis would be:

```yaml
releases:
  - name: some-app
    values:
      - key: default-value
        key2: another default
      {{- if eq .Environment.Name "test" }}
      - key3: test-specific
      {{- else if eq .Environment.Name "prod" }}
      - key3: prod-specific
      {{- end }}
```
... which is clunky and hard to read, or you could do:
```yaml
releases:
  - name: some-app
    values:
      - key: default-value
        key2: another default
      - values/some-app/{{ .Environment.Name }}.yaml
```
... which is less clunky but requires that the value for a given app be split across N+1 files (where N is the number of environments). Having an `environments` block is much nicer, and for most of my Helmfiles, it's fine (desirable, even) that the `environments` block is global, but sometimes you want per-app State-values, and putting each app into its own Helmfile and then calling them as sub-helmfiles from a parent is best way to accomplish that at the moment.

**Reply by mumoshu** [reply]
> It seems like releaseSets just becomes helmfiles with fewer bugs?

Yeah, that was my idea. We've initially introduced sub-helmfiles, maybe four or more years ago, to let a specific set of releases be a reusable "module", so that you can apply/sync/uninstall/etc either independently or along with other relevant modules.  If we're going to replace sub-helmfiles with it, it should probably support the same or a similar use-case to sub-helmfiles. 🤔 

Apparently your use-case doesn't require sub-helmfiles, right?

**Reply by philomory** [reply]
> > It seems like releaseSets just becomes helmfiles with fewer bugs?
> 
> Yeah, that was my idea. We've initially introduced sub-helmfiles, maybe four or more years ago, to let a specific set of releases be a reusable "module", so that you can apply/sync/uninstall/etc either independently or along with other relevant modules. If we're going to replace sub-helmfiles with it, it should probably support the same or a similar use-case to sub-helmfiles. 🤔
> 
> Apparently your use-case doesn't require sub-helmfiles, right?

I mean, I think it does? Conceptually, if not in implementation? I want multiple files that:
1. ... have their own `values` sections.
2. ... have their own `environments` sections
3. ... have their own `releases` sections
4. ... can be called all together at once from a top-level helmfile

Wouldn't you call each of those files a Helmfile? And if they're called all together from a top-level helmfile, then aren't they sub-helmfiles? I mean, you can reimplement the functionality under a different name (`releaseSets`), but at that point why not just take out the current code that handles the `helmfiles` section, and make `helmfiles` a synonym of `releaseSets`? It seems like they do the exact same thing, only `helmfiles` has limitations/bugs that `releaseSets` doesn't have. Are you just worried that there are users who depend on the bugs in the `helmfiles` section?

**Reply by philomory** [reply]
> Apparently your use-case doesn't require sub-helmfiles, right?

Alternatively, if you're just referring to the fact that I don't necessarily need to render them individually, and that my problem could (in principal) also be solved by adding support for `releases[*].environments[*].values`, sections, then, you're probably correct that I don't _require_ sub-helmfiles. After all, if/when I did need to install one in isolation, I could always just do `helmfile -e whatever -l name=something apply` rather than `helmfile -e whatever -f helmfiles/something.yaml apply`.

**Comment by jouve** [comment]
as I suggested in  https://github.com/helmfile/helmfile/issues/528#issuecomment-1345251687,

maybe helmfile could support parallelism in a way similar to [argo workflow](https://argoproj.github.io/argo-workflows/walk-through/steps/)

```yaml
helmfiles:
- path: helmfile1.yaml       # apply helmfile1
- - path: helmfile2a.yaml  # then helmfile2a & helmfile2b in parallel 
  - path: helmfile2b.yaml
```

that way, it does not need to have knowledge of each sub-helmfile releases.
