### DISCUSSION TITLE
Unexpected Precedence of Chart's values.yaml in Helmfile with Dependencies

### DISCUSSION THREAD

**Discussion by dariel-mizrachi** [helmfile/helmfile#1783] [Questions]
### Current Behavior
When using Helmfile with a release that includes dependencies, the values.yaml file located in the chart's directory (`apps/ingress-nginx/values.yaml`) is taking precedence over the environment-specific value files specified in the Helmfile (`environments/default-values.yaml` and `environments/nala/dev-values.yaml`).

### Expected Behavior
The values.yaml file in the chart's directory should be ignored, and only the values specified in the Helmfile should be applied.

### Configuration

helmfile.yaml
```
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  nala-dev:
    values:
      - environments/default-values.yaml
      - environments/nala/dev-values.yaml
  # Add other environments as needed, e.g.:
  # nala-prod:
  #   values:
  #     - environments/default-values.yaml
  #     - environments/nala/prod-values.yaml

---

- name: ingress-nginx
    namespace: ingress-nginx
    chart: ./apps/ingress-nginx
    version: 0.0.1 
    dependencies:
      - chart: ingress-nginx/ingress-nginx
        version: 4.11.1
    # condition: ingress-nginx.enabled
    values:
      - values-template.gotmpl

```
values-template.gotmpl
```
{{/* values-template.gotmpl */}}
{{ merge (.Values | get .Release.Name dict) (.Values | get "global" dict) | toYaml }}
```
Directory tree

```
.
├── apps
│   └──ingress-nginx
│        ├── charts
│        │   └── ingress-nginx-4.11.0.tgz
│        ├── Chart.yaml
│        ├── templates
│        │   ├── delete-ip-lua-cm.yaml
│        │   ├── fanout-loglevel-lua-cm.yaml
│        │   ├── find-instance-lua-cm.yaml
│        │   ├── find-store-lua-cm.yaml
│        │   ├── nginx-external-secrets.yaml
│        │   └── nginx-nodepool.yaml
│        └── values.yaml
├── environments
│   ├── apac
│   ├── default-values.yaml
│   └── nala
│       └── dev-values.yaml
├── helmfile.yaml
└── values-template.gotmpl
```
### Request for Assistance

If anyone has encountered a similar issue or has insights into Helmfile's behavior with dependencies and value precedence, please share your experience or potential solutions.
