### DISCUSSION TITLE
Layering State Template files

### DISCUSSION THREAD

**Discussion by cyrus-mc** [helmfile/helmfile#1797] [Questions]
I am following the guide to layering state template files - https://helmfile.readthedocs.io/en/latest/writing-helmfile/#layering-state-template-files

I have the following:

* myenv.yaml

```
environments:
  default:
    missingFileHandler: Warn
    values:
      - config.yaml
```

* config.yaml

```
foo: bar
```

* helmfile.yaml.gotmpl

```
bases:
  - myenv.yaml

---

helmfiles:
  - path: /somepath/helmfile.yaml
    values:
      - values.yaml.gotmpl
      - config:
          foo: {{ .StateValues.foo }}

---

releases:
  - name: testing
    namespace: "testing"
    chart: ./
    values:
      - fullnameOverride: testing
```

* values.yaml.gotmpl

```
config:
  foo-file: {{ .StateValues.foo }}
```

When applying/templating 

```
 because of template: stringTemplate:2:27: executing "stringTemplate" at <.StateValues.foo>: map has no entry for key "foo"
```

Inside `values.yaml.gotmpl` the `.StateValues` is an empty map. Is there a way to template within value files passed to external helmfiles?
