### DISCUSSION TITLE
Local chart need an absolute path

### DISCUSSION THREAD

**Discussion by jehutyy** [helmfile/helmfile#182] [Questions]
it seems that the example in the README.md can't work because of the following error : 
`in ./helmfile.yaml: [assertion failed: unexpected dir entry : it mnust be a abs path]`

Said example : 
```
  # Local chart example
  - name: grafana                            # name of this release
    namespace: another                       # target namespace
    chart: ../my-charts/grafana              # the chart being installed to create this release, referenced by relative path to local helmfile
    values:
    - "../../my-values/grafana/values.yaml"             # Values file (relative path to manifest)
    - ./values/{{ requiredEnv "PLATFORM_ENV" }}/config.yaml # Values file taken from path with environment variable. $PLATFORM_ENV must be set in the calling environment.
    wait: true
```
