### DISCUSSION TITLE
--output-dir-template to support environment values

### DISCUSSION THREAD

**Discussion by sigurdblueface** [helmfile/helmfile#1827] [Ideas]
```yaml
environments:
  test:
    values:
    - cluster: my-test-cluster
      namespace: test-env
---
releases:
  - name: my-release
```

would be extremely useful if it was possible to do smth like:

```bash
helmfile -e test template --output-dir-template='{{ .Environment.Values.cluster }}/{{ .Environment.Values.namespace }}/{{ .Release.Name }}
```
