### DISCUSSION TITLE
Deploying resources that contain gotemplate (ArgoCD)

### DISCUSSION THREAD

**Discussion by jess-belliveau** [helmfile/helmfile#1842] [Questions] [answered]
I'm deploying ArgoCD using helmfile along with the argo notifications feature.

As per their upstream helm chart, I'm including some notification templates that are deployed as configMaps: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L3488

My problem is, it seems helmfile is trying to render the argocd defined gotemplate variables as part of its pipeline. But I actually need these ignored and deployed "as is".

How can achieve this? I tried escape chars but that then feeds directly to the deployed CM and ArgoCD barfs when it attempts to render.

```
releases:
{{- if .Values.deployArgocd }}
  - name: argocd
    chart: argo/argo-cd
    namespace: argocd
    createNamespace: true
    wait: true
    version: 7.7.10
    labels:
      component: argocd
      app: argocd
    values:
      - credentialTemplates:
          githubApp:
            url: "https://github.com/test"
            githubAppID: "1"
            githubAppInstallationID: "2"
            type: git
            githubAppPrivateKey: {{- .Values.argocd.githubApp.key | toYaml | indent 12 }}
        notifications:
          notifiers:
            service.github: |
              appID: 1
              installationID: 2
              privateKey: $github-privateKey
          templates:
            template.app-deployed: |
              message: |
                Application {{.app.metadata.name}} is now running new preview instance.
              github:
                repoURLPath: "{{.app.spec.source.repoURL}}"
                revisionPath: "{{.app.status.operationState.syncResult.revision}}"
```

yields:

```
in helm/helmfile.d/07-argocd.yaml: error during 07-argocd.yaml.part.2 parsing: template: stringTemplate:35:34: executing "stringTemplate" at <.app.metadata.name>: can't evaluate field app in type *state.EnvironmentTemplateData
```

**Comment by jess-belliveau** [comment, marked as answer]
OK, looks like the solution is to use backticks.

```

          templates:
            template.app-deployed: |
              message: |
                Application {{ `{{.app.metadata.name}} is now running new preview instance.
              github:
                repoURLPath: "{{.app.spec.source.repoURL}}"
                revisionPath: "{{.app.status.operationState.syncResult.revision}}"` }}

```

note the opening and closing template with backticks. ClaudeAI actually told me this:

> This approach using backticks is generally cleaner and more maintainable. The helmfile/helm templating engine will treat everything within the backticks as a literal string, allowing ArgoCD to process the template syntax later.
