### DISCUSSION TITLE
Using cli passed state-values in environments values files

### DISCUSSION THREAD

**Discussion by Vince-Chenal** [helmfile/helmfile#1855] [Ideas]
It would be nice to be able to use cli passed state values (`--state-values-set`) within environment values files like that:

defaults.yaml.gotmpl:
```
some_values: {{ .Values.env }}
```

helmfile.yaml:
```
environments:
  default:
    values:
      - defaults.yaml.gotmpl
---
repositories:
  - name: examples
    url: https://helm.github.io/examples

releases:
  - name: hello
    chart: examples/hello-world
```

Today I'm getting this error:
```
> helmfile template . --state-values-set environment=dev
in ./helmfile.yaml: failed to read helmfile.yaml: failed to load environment values file "defaults.yaml.gotmpl": failed to render [defaults.yaml.gotmpl], because of template: stringTemplate:1:23: executing "stringTemplate" at <.Values.env>: map has no entry for key "env"

> helmfile version

▓▓▓ helmfile

  Version            0.169.2
  Git Commit         370b004
  Build Date         05 Dec 24 13:58 CET (1 month ago)
  Commit Date        05 Dec 24 01:23 CET (1 month ago)
  Dirty Build        no
  Go version         1.23.1
  Compiler           gc
  Platform           linux/amd64
```

I was able to make it work by using this expression instead:

```
some_values: {{ index .Environment.Values "env" }}
```

But according to [this note](https://helmfile.readthedocs.io/en/latest/#note-on-environmentvalues-vs-values), `.Environment.Values` is supposed to be deprecated.
