### DISCUSSION TITLE
Conditions on release dependencies

### DISCUSSION THREAD

**Discussion by Vince-Chenal** [helmfile/helmfile#1856] [Ideas]
Helm supports having a condition on Chart dependencies: https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags
We could have the same possibility on helmfile releases dependencies

**Comment by yxxhero** [comment]
@Vince-Chenal PR is welcome. good idea.

**Reply by Vince-Chenal** [reply]
As it's stated in [the doc](https://helmfile.readthedocs.io/en/latest/advanced-features/#adding-dependencies-without-forking-the-chart):

> When Helmfile encounters releases[].dependencies, it creates another temporary chart from ./path/to/foo and adds the following dependencies to the Chart.yaml, so that you don’t need to fork the chart.

```
dependencies:
- name: envoy
  repo: https://charts.helm.sh/stable
  condition: envoy.enabled
```

So there is already an implicit condition that is injected by Helmfile :+1:
