### DISCUSSION TITLE
Helmfile apply not rendering values.yaml.gotmpl, but helmfile write-values works fine?

### DISCUSSION THREAD

**Discussion by thenayr** [helmfile/helmfile#1860] [Questions]
Per the title,  when I run `helmfile apply` I get a message similar to this:

```
failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:15: unexpected "," in range
```

but when I tested generating the values with `helmfile write-values --output-file-template=file.yaml` it outputs perfectly.

Here is a segment of my `values.yaml.gotmpl`:

```
  env:
      {{ range $key,$value := .Values.datadog.env }}
      - name: {{ $key }}
        value: {{ toYaml $value }}
      {{ end }}
```

and a segment from `helmfile.yaml`

```
---
environments:
  dev:
    values:
      - datadog:
          env:
            DD_ENABLE_PAYLOADS_EVENTS: "false"
            DD_ENABLE_PAYLOADS_SERIES: "false"
            DD_ENABLE_PAYLOADS_SERVICE_CHECKS: "false"
            DD_ENABLE_PAYLOADS_SKETCHES: "false"

---
repositories:
  - name: datadog
    url: https://helm.datadoghq.com

---
releases:
  - name: datadog
    namespace: datadog
    chart: datadog/datadog
    version: 3.80.0
    createNamespace: true
    wait: true
    timeout: 1200
    values:
    - values.yaml.gotmpl
```
