### DISCUSSION TITLE
Add kubeconfig option in helmDefaults to specify configuration file

### DISCUSSION THREAD

**Discussion by deepwzh** [helmfile/helmfile#1879] [Ideas]
I want to add a kubeconfig field in helmDefaults to specify the use of kubeconfig files. Currently, only kubecontext can be specified
By specifying the method in the configuration file, it is possible to avoid missing the target during execution, which can lead to execution errors

```yaml
helmDefaults:
  verify: false
  kubeconfig: ./kubeconfig.yaml
```
