### DISCUSSION TITLE
preapply hook fails for existing namespace

### DISCUSSION THREAD

**Discussion by amamir14** [helmfile/helmfile#1895] [Questions]
I have added a `preapply` hook for a release, this release `needs` another release that creates the namespace. The hook is failing with this error `Error from server (NotFound): namespaces "test" not found`, however if I use the `presync` hook it works fine. The following yaml shows what I am trying to do:
```
releases:
  - name: release-1
     namespace: test
     createNamespace: true
    # other configs

 - name: release-with-hook
    namespace: test
     hooks:
     - events: [ "preapply" ]
       showlogs: true
       command: "kubectl"
       args: [ "wait", "--for=condition=complete", "job/myjob", "-ntest}", "--timeout=600s" ]
```
The same yaml with the `presync` hook works as expected, why does it not work with the `preapply` hook, am I missing something?
