### DISCUSSION TITLE
want to kustomize  a chart with a condition  based onchart value

### DISCUSSION THREAD

**Discussion by cridam** [helmfile/helmfile#1898] [Questions]
Hello,
SInce helmfile is a tool to avoid forking community chart, 

i simply try to apply a kustomize of a chart X, let's say  only if ingress.enabled (value of the X chart)  is true .

i naively proceed like this

```
releases:
- name: X
  namespace: any
  chart: repo/X
  version: 1.0.0
  values:
  - values/default-values.yaml
  jsonPatches:
  - kustomize.yaml.gotmpl
```

and kustomize.yaml.gotmpl

```
{{-  if  .Values.ingress.enabled }}
- target:
     kind: DaemonSet
     name: xxx
   patch:
     path: yyyy
{{- end }}
```

It fails.
```
failed to render kustomize.yaml.gotmpl], because of template: stringTemplate:11:32: executing "stringTemplate" at <.Values.ingress.enabled>: map has no entry for key "ingress"
```

While the value is defined both in the values.yaml  of the original chart, and addded in the default-values.yaml . 
The only case where it is understood (but we don't want this extra work , that may not match if the kustomize part relies on chart template for instance)  is when the ingress.enabled its explicitly writtenin the environment/default flle.

How to proceed with helmfile ?
Notice: that using standard helm with post-render with kustomization work without using helmfile ...
Any comments?
