### DISCUSSION TITLE
support namespace when using additional helmfiles

### DISCUSSION THREAD

**Discussion by felix-sift** [helmfile/helmfile#1899] [Ideas]
don't believe this discussion/feature request exists yet from my searching, though i could fail at searching. :)

currently, adding additional helmfiles in the `helmfiles.yaml` file does not allow for specifying a different namespace. we want to deploy some other helmfile/helm chart to this same namespace in additional to the named releases.

```yaml
releases:
  - snip
    namespace: foobar

helmfiles:
  - path: /some/path
    namespace: foobar
```

**Comment by yxxhero** [comment]
@notwaf what's your user case? you can set the namespace of release in sub-helmfile.

**Reply by felix-sift** [reply]
ah, the release in the sub-helmfile is normally in another ns. we want to deploy that same sub-helmfile, but into the current ns of the current helmfile.

here's an example:
/a/helmfile.yaml
```yaml
releases:
  - snip
    namespace: foobar
    chart: some/chart

helmfiles:
  - path: /b/helmfile.yaml
    namespace: foobar
```

/b/helmfile.yaml
```yaml
releases:
  - snip
    namespace: baz
    chart: another/chart
```
