### DISCUSSION TITLE
Nested States usage

### DISCUSSION THREAD

**Discussion by Amikuto** [helmfile/helmfile#1915] [Questions]
Helmfile Version:
0.170.1

Helm Version:
v3.17.0

---
<b> Hello! I have encountered a lack of information on using Nested Helmfiles...
---

helmfile.yaml
```yaml
helmfiles:
  - path: environments/staging.yaml
  - path: environments/production.yaml
```

environments/staging.yaml
```yaml
environments:
  staging:
    kubeContext: staging-main

---
releases:
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    values:
      - image.tag: "v1.10.0"
      - replicaCount: 1

  - name: nginx-ingress
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    values:
      - controller.replicaCount: 2
      - controller.image.tag: "v1.9.1"
      - controller.service.type: LoadBalancer

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - installCRDs: true
      - image.tag: "v1.11.0"
```

environments/production.yaml
```yaml
environments:
  production:
    kubeContext: prod-main

---
releases:
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    values:
      - image.tag: "v1.10.0"
      - replicaCount: 3

  - name: nginx-ingress
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    values:
      - controller.replicaCount: 4
      - controller.image.tag: "v1.9.1"
      - controller.service.type: LoadBalancer
      - controller.nodeSelector:
          node-role.kubernetes.io/ingress: "true"

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    values:
      - installCRDs: true
      - image.tag: "v1.11.0"
      - replicaCount: 2
```

When I try to run the command
```bash
helmfile -e staging build
```

Output is:
err: no releases found that matches specified selector() and environment(staging), in any helmfile

What could be the reason?
And how can this be implemented correctly?
