### DISCUSSION TITLE
Pass multiple Helm values files to a Kutomized Helm Chart

### DISCUSSION THREAD

**Discussion by marcusnh** [helmfile/helmfile#1930] [Ideas]
I want to be able to pass multiple helm values files to kustomized Helm Chart like this:
```
helmCharts:
  - name: chartName
    repo: https://charts.<domain>.com/chart
    version: 4.5.6
    releaseName: <releaseName>
    namespace: <namespace>
    valuesFile: <../../base-values.yaml>
    additionalValuesFiles:
      - /path/<environment.yaml>
  ```

How can this be done, when the values file is not in the same folder as this kustomize file?
Same problem as [here](https://github.com/roboll/helmfile/issues/2183)
