### DISCUSSION TITLE
Helmfile limitation with empty values

### DISCUSSION THREAD

**Discussion by AbbasHallal** [helmfile/helmfile#194] [Questions] [answered]
redis.yaml
```
releases:
- name: "{{ .Values.releaseName }}"
  chart: incubator/raw
  version: 0.2.5
  namespace:  "{{ .Values.namespace }}"
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: "../../../scripts/getKubernetesAuthSecret.sh"
    args: ["{{ .Values.namespace }}","{{ .Environment.Name }}"]
  values:
  - resources:
    - apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
         name: vault-issuer
      spec:
         vault:
            auth:
              kubernetes:
                mountPath: kubernetes
                role: pki
                secretRef:
                  key: token
                  name: {{ .Values | get "kubernetesAuthSecret" "token" }}
            path: pki/sign/devops
            server: localhost
```
helmfile.yaml
```
environments:
  dev:
    values:
    - environment: dev
    - namespace: myNs
    secrets:
    - secrets.yaml

{{ tpl (readFile "../../bases/redis.yaml") . }}
```
_kubernetesAuthSecret_ is not defined in the helmfile and the script _getKubernetesAuthSecret.sh_ is getting it from the namespace myNS and appending it in helmfile.yaml. The value is added correctly however _spec.vault.auth.kubernetes.secretRef.name= token_. I believe that the template is rendered first before the script and it's ignoring what is coming after. Is there a way to force the chart to have the new value added by the script?

**Comment by philomory** [comment, marked as answer]
This seems like a misuse of hooks; you should probably just be using the `exec` or `envExec` functions, instead, e.g.:

```yaml
  values:
  - resources:
    - apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
         name: vault-issuer
      spec:
         vault:
            auth:
              kubernetes:
                mountPath: kubernetes
                role: pki
                secretRef:
                  key: token
                  name: {{ exec "../../../scripts/getKubernetesAuthSecret.sh" (list .Values.namespace .Environment.Name) }}
            path: pki/sign/devops
            server: localhost
```
... with possibly some small modifications to the script's output.
