### DISCUSSION TITLE
How to pass helm values  when using helmfiles with a nested helmfile ?

### DISCUSSION THREAD

**Discussion by cridam** [helmfile/helmfile#1948] [Questions]
Imagine this kind of solution : 
``` yaml
helmfiles:
 path: 
 - ../helmfile.yaml
 values:
 - ingress:
     enabled: true
```
It appears that values (ingress.enabled) are considered as "state" values by helmfile and are consumed by any template defined in the nested helmfile.
What are the recommended solutions to pass any extra values "ingress.enabled" to the helm command in such context? 
having said that we want to avoid changing the nested file for that ?
