### DISCUSSION TITLE
helmfile template does not add Helm annotations to resources (unlike helmfile sync e.g.)

### DISCUSSION THREAD

**Discussion by TimaevAlexandr** [helmfile/helmfile#1957] [Ideas]
### Description:
When using `helmfile sync`, resources created from charts include Helm annotations like:
```
Annotations:
    deployment.kubernetes.io/revision: 1
    meta.helm.sh/release-name: example
    meta.helm.sh/release-namespace: default

```

However, when using:

```
tmp=$(mktemp)
helmfile template > $tmp
kubectl apply -f $tmp
```

The resulting resources only include:
```
Annotations:
    deployment.kubernetes.io/revision: 1
```

The Helm-specific annotations meta.helm.sh/release-name and meta.helm.sh/release-namespace are missing.

### Expected Behavior
`helmfile template` should either:

- Add these Helm annotations automatically (like `helmfile sync` does), or
- Provide an optional flag to control adding these annotations (e.g., `--add-helm-annotations`).

### Actual Behavior
helmfile template omits these annotations, which causes inconsistencies and may lead to issues in tools that rely on them (e.g., ArgoCD, Flux, or custom controllers that expect Helm-managed resources).

### Manifests to Reproduce
This is a minimal example to demonstrate the issue. The behavior is the same for any Helm chart.
Use the following helmfile.yaml:

./helmfile.yaml
```
releases:
  - name: example
    namespace: default
    chart: ./example
```
    
./example/Chart.yaml:

```
apiVersion: v2
name: example
version: 0.1.0
```
./example/templates/deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
```

**Comment by yxxhero** [comment]
@TimaevAlexandr what's the result of `helm template`?

**Reply by TimaevAlexandr** [reply]
just like this

```
Building dependency release=example, chart=example
Templating release=example, chart=example
---
# Source: example/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: nginx
          image: nginx:latest
```
