### DISCUSSION TITLE
Support the Helmfile filename (path, basename) as built-in object

### DISCUSSION THREAD

**Discussion by mheuser** [helmfile/helmfile#1973] [Ideas]
I'am using the `helmfile.d` mechanism to define my environment. Here I use one `helmfile.yaml.gotmpl` per namespace.

 The structure of the project looks like that:

```bash
> tree .
.
├── bases
│   └── templates.yaml.gotmpl
├── helmfile.d
│   ├── ns1.gotmpl.yaml
│   └── ns2.gotmpl.yaml
└── values
    ├── ns1
    │   └── foo
    │       ├── default.yaml.gotmpl
    │       ├── prod.yaml.gotmpl
    │       └── staging.yaml.gotmpl
    └── ns2
        └── bar
            ├── default.yaml.gotmpl
            ├── prod.yaml.gotmpl
            └── staging.yaml.gotmpl
```

In each of this helmfiles in `helmfile.d` I have the following template set:

```yaml
> cat helmfile.d/ns1.yaml.gotmpl

bases:
- ../bases/templates.yaml.gotmpl
---
templates:
  this:
    namespace: ns1
    inherit:
    - template: default

releases:
- name: foo
  chart: oci://some/chart
  version: 1.2.3
  inherit:
  - template: this
```

```yaml
> cat helmfile.d/ns2.yaml.gotmpl

bases:
- ../bases/templates.yaml.gotmpl
---
templates:
  this:
    namespace: ns2
    inherit:
    - template: default

releases:
- name: bar
  chart: oci://some/chart
  version: 3.2.1
  inherit:
  - template: this
```

With a default template like this:

```yaml
> cat bases/template.yaml.gotmpl

templates:
  default:
    values:
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/default.yaml.gotmpl
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml.gotmpl

```

In the real project there are a lot releases per namespace and also a lot more namespaces. So a lot repedition in defining the template in each helmfile.
What I would like to do is to reuse the helmfile basename to use it e.g. as namespace. Lets assume we have a build-in obejct with the name `Environment.HelmfilePath` which has the full path to the helmfile which is evaluated. Lets also assume we have a function `basename` which act like the shell tool basename.

So the default template could then become something like that:

```yaml
> cat bases/template.yaml.gotmpl

templates:
  default:
    namespace: {{ .Environment.HemfilePath | basename ".gotmpl.yaml" }}
    values:
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/default.yaml.gotmpl
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml.gotmpl

```

And each helmfile looks like that then

```yaml
> cat helmfile.d/ns1.yaml.gotmpl

bases:
- ../bases/templates.yaml.gotmpl
---

releases:
- name: foo
  chart: oci://some/chart
  version: 1.2.3
  inherit:
  - template: default
```

```yaml
> cat helmfile.d/ns2.yaml.gotmpl

bases:
- ../bases/templates.yaml.gotmpl
---

releases:
- name: bar
  chart: oci://some/chart
  version: 3.2.1
  inherit:
  - template: default
```

There is another use case for me where the fine name of the evaluated helmfile. would be a simple fix for the need to have different locations per env for the lockfile so that I can setup renovate grouping per env via lock file path to gets version update PRs per env.

I would like to have a lockfile path per environment. E.g.:

```
> tree  lock/
lock/
├── prod
│   ├── ns1.lock.yaml
│   └── ns2.lock.yaml
└── staging
    ├── ns1.lock.yaml
    └── ns2.lock.yaml
```

From the docs:
```yaml
# Path to alternative lock file. The default is <state file name>.lock, i.e for helmfile.yaml it's helmfile.lock.
lockFilePath: path/to/lock.file
```

So I see no option to just give a folder (Ive tried without success). e.g:

```yaml
lockFilePath: ../lock/{{ Environment.Name }}/
```

So that means I have to set the `lockFilePath` in each helmfile in `helmfie.d/`:

```yaml
> cat helmfile.d/ns1.yaml.gotmpl

bases:
- ../bases/templates.yaml.gotmpl
---
lockFilePath: ../lock/{{ Environment.Name }}/ns1.lock.yaml

templates:
  this:
    namespace: ns1
    inherit:
    - template: default

releases:
- name: foo
  chart: oci://some/chart
  version: 1.2.3
  inherit:
  - template: this
```

Again, with the possibility to have the helmfile name as built-in object I could define `lockFilePath` just one time in the default template and the template and a helmfie would look like that:

```yaml
> cat bases/template.yaml.gotmpl

lockFilePath: ../lock/{{ Environment.Name }}/{{ .Environment.HemfilePath | basename ".gotmpl.yaml" }}.lock.yaml

templates:
  default:
    namespace: {{ .Environment.HemfilePath | basename ".gotmpl.yaml" }}
    values:
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/default.yaml.gotmpl
    - ../values/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml.gotmpl

```

So, feedback would be nice. Or maybe there is already a (undocumented) way the get the name of the helmfile that is evaluated. Or hints how to implement that.
