### DISCUSSION TITLE
Adding extra manifests not bundled with a chart

### DISCUSSION THREAD

**Discussion by joshuabaird** [helmfile/helmfile#1976] [Questions]
I have the need to deploy extra manifests that aren't included with a vendor-provided chart.  I have been able to accomplish this by using a "local" release:

```
releases:
  - name: local
    chart: ./local
    namespace: blah
    values:
      - values/global-local.yaml.gotmpl
      - values/env/{{ .Environment.Name }}.yaml
 ```

I can stick raw templates in the `local/` directory and template them using values defined in `values/global-local.yaml.gotmpl`.  This seems to work fine, although it seems like the templates are getting processed twice, because the templates are rendered with two comments:

```
---
# Source: local/templates/templates/datadog/rbac.yaml
# Source: local/templates/templates/datadog/rbac.yaml
...
```

I then tried to structure the files in `local/` like a "real" Helm chart -- one with `Chart.yaml` and put the templates in the `templates/` directory.  However, when I do this, it seems like I cannot use `{{ (requiredEnv "BLAH") }}` in these templates as it results in this error:

```
STDERR:
  Error: parse error at (local/templates/nodepool/default.yaml.gotmpl:4): function "requiredEnv" not defined
  Use --debug flag to render out invalid YAML
 ```

What is the recommended way to inject extra manifests outside of a chart?  Should files in my `locals/` directory be structured like a real chart or can I just drop raw manifests/templates there?  If so, is there a way to make things like `requiredEnv` work in these templates?
