### DISCUSSION TITLE
Help with Helmfile: How can one release get values (like `replicaCount` or `image.tag`) from another release?

### DISCUSSION THREAD

**Discussion by trevorboydsmith** [helmfile/helmfile#1987] [Questions]
Trying to do this **without globals / defaults / shared values** (just pure Helmfile dependency between releases).

I’m testing with a simple nginx chart created from `helm create foo`. I want:

- `release1` installs first  
- `release2` depends on `release1`  
- `release2` dynamically reads a value from `release1`, like `replicaCount`

Here's the current helmfile.yaml:

```yaml
# helmfile.yaml
releases:
  - name: release1
    chart: ./foo
    values:
      - replicaCount: 3

  - name: release2
    chart: ./foo
    needs:
      - release1
    values:
      - podAnnotations:
          release1_replica_count: "{{ .values.release1.replicaCount }}" # this part is what i am asking for help on 
```

When I do `helmfile apply -i` i expect to see value 3 from release1 but instead i see:

```yaml
# this is what i see
release1_replica_count: '{{ .values.release1.replicaCount }}'
```

Goal: have `release2` resolve `release1`'s values after render (not via shared YAML).  

Can Helmfile do this? Or is this the wrong model?

Appreciate any working example or insight.

p.s. i rewrote to make this shorter/easier to skim and added minimal code to show what i am doing.
