### DISCUSSION TITLE
Add Support for Sprig Template Functions

### DISCUSSION THREAD

**Discussion by ZachThill** [helmfile/helmfile#1999] [Ideas]
Helmfile currently allows you to use Go's `text/template` expressions within your go templates. I would like to request that [github.com/Masterminds/sprig/v3](https://pkg.go.dev/github.com/Masterminds/sprig/v3) be added for the purpose of increasing the amount of template functions one can use to manipulate the rendered data within their helmfile/values.

My use case in particular is that I would like to reference data within my env/cluster values files, and run some simple string replacements like so:

values.yaml
```yaml
someMap:
  someKey: some-value
```

helmfile.yml
```yaml
releases:
  - name: someRelease
    chart: someRepo/someChart
    namespace: someNamespace
    values:
      - config:
          someKey: {{ .Values.someMap.someKey | replace "-" "_" }}
```

Here are Sprigs' docs for more info: https://masterminds.github.io/sprig/
