### DISCUSSION TITLE
Support templating in "dependencies"

### DISCUSSION THREAD

**Discussion by mqmr** [helmfile/helmfile#2022] [Ideas]
[not a contribution]

I've been working on charts' version management using an approach as follows:
```
  prometheus-operator: &prometheus-operator
    name: prometheus-operator
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: |-
      {{ .Values | get "versions.prometheus-operator.chart" }}
```

versions are defined in files per evn, e.g.
```
❯ head common/versions/dev.yaml
versions:
  chart-X:
    chart: 0.1.0
``` 

Although, it works in general, that approach doesn't work for dependencies:
```
  atlantis: &atlantis
    name: atlantis
    namespace: atlantis
    chart: <redacted>
    version: "0.1.0"
    dependencies:
      - chart: runatlantis/atlantis
        version: |-
           {{ .Values | get "versions.atlantis.chart" }}
``` 

... and helmfile fails with:
```
Error: dependency "atlantis" has an invalid version/constraint format: improper constraint: {{ .Values | get "versions.atlantis.chart" }}]
```

Is there any chance helmfile can extend support of templating to "dependencies" of a release?

Thanks
