### DISCUSSION TITLE
Support substitution of chart version in templates

### DISCUSSION THREAD

**Discussion by hans-m-song** [helmfile/helmfile#2056] [Ideas]
Would love the ability to template in the chart version in a similar vein to https://github.com/helmfile/helmfile/issues/1934

Reason being so I can use hooks to automate replacement of CRDs

For example: actions-runner-controllers gha-runner-scale-set

```yaml
releases:
  - name: arc
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    namespace: arc-systems
    version: 0.11.0
    labels:
      deployment: true
    values:
      - ./values/arc.yaml
    hooks:
      - events: [preapply]
        showlogs: true
        command: bash
        args:
          - -c
          - |
            chart=oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
            version={{ .Release.ChartVersion }}
            helm show crds $chart --version $version | kubectl replace --filename -
      - events: [postuninstall]
        showlogs: true
        command: bash
        args:
          - -c
          - |
            chart=oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
            version={{ .Release.ChartVersion }}
            helm show crds $chart --version $version | kubectl delete --filename -
```

wrote up a draft PR here
https://github.com/helmfile/helmfile/pull/2055

**Comment by hans-m-song** [comment]
after some experimentation, i discovered the following works for my particular use case

```yaml
hooks:
  - events: [prepare]
    showlogs: true
    command: bash
    args:
      - -c
      - helm show crds {{`{{ .Release.Chart }}`}} --version {{`{{ .Release.Version }}`}} | kubectl replace --filename -
```

the key being the `ReleaseSpec` values aren't available until the helmfile has been parsed and is evaluating a particular release, hence, you need to escape the braces to delay the evaluation
