### DISCUSSION TITLE
No way to disable vals's `ref+` strings evaluation

### DISCUSSION THREAD

**Discussion by lucasfcnunes** [helmfile/helmfile#2057] [Ideas]
There's a great risk of leaking raw secrets to GitOps when working with https://github.com/digitalis-io/vals-operator.
Pave a way to disable the evaluation of `ref+` using flags, env vars, yaml keys, etc.

*I feel that it would've been great if I had brought this up when this project was still v0. 😅

# Example

```yaml
# helmfile.yaml.gotmpl
repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts
---
DISABLE-VALS-EVALUATION: true # <<< NEEDED FLAG
releases:
  - chart: bedag/raw
    name: helmfile-vals-ref
    namespace: lucasfcnunes-test
    values:
      - resources:
          # INFO: https://github.com/digitalis-io/vals-operator?tab=readme-ov-file#usage
          - apiVersion: digitalis.io/v1
            kind: ValsSecret
            metadata:
              name: helmfile-vals-ref
            spec:
              data:
                VALS_REF_ESCAPED:
                  ref: ref+echo://ref++echo://VALS_REF # <<< KNOWN WAY TO SCAPE
                  encoding: text
                VALS_REF_PLAIN:
                  ref: ref+echo://VALS_REF # <<< SHOULD BE KEPT THIS WAY
                  encoding: text

```

```console
$ helmfile template
Adding repo bedag https://bedag.github.io/helm-charts
"bedag" has been added to your repositories

Templating release=helmfile-vals-ref, chart=bedag/raw
---
# Source: raw/templates/resources.yaml
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  labels:
    app.kubernetes.io/instance: helmfile-vals-ref
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helmfile-vals-ref-raw
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: raw-2.0.0
  name: helmfile-vals-ref
spec:
  data:
    VALS_REF_ESCAPED:
      encoding: text
      ref: ref+echo://VALS_REF
    VALS_REF_PLAIN:
      encoding: text
      ref: VALS_REF
```
