### DISCUSSION TITLE
'{{`{{ .Release.Namespace }}`}}' syntax in hooks doesn't work anymore

### DISCUSSION THREAD

**Discussion by natcl** [helmfile/helmfile#2076] [Questions] [answered]
I'm using gitlab ci with helm and upgraded the cluster applications container which now seems to include helmfile 1.0.0,

I had some hooks with the following syntax to access the namespace:

```yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: sh
    args:
    - createSecret.sh
    - '{{`{{ .Release.Namespace }}`}}'
  ```

which seems to break with 1.x where I now need to use `'{{ .Release.Namespace }}'` instead of `'{{`{{ .Release.Namespace }}`}}'`.
Is this expected ? the documentation still seems to refer to the `'{{`{{ .Release.Namespace }}`}}'` syntax.

thanks for the clarification !

**Comment by yxxhero** [comment]
@natcl could you post an demo?

**Reply by natcl** [reply]
I'm sorry I'm still a bit new with helmfile, what do you mean by a demo ?

**Reply by yxxhero** [reply]
@natcl you helmfile files. so I can know why.

**Reply by natcl** [reply]
Oh sure sorry:

This seems to fail with 1.x
```yaml
repositories:
- name: gitlab
  url: https://charts.gitlab.io

releases:
- name: runner
  namespace: gitlab-managed-apps
  chart: gitlab/gitlab-runner
  version: 0.77.2
  installed: true
  values:
    - values.yaml.gotmpl
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args:
    - apply
    - -f
    - ./manifests
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
```

This seems to work with 1.x
```yaml
repositories:
- name: gitlab
  url: https://charts.gitlab.io

releases:
- name: runner
  namespace: gitlab-managed-apps
  chart: gitlab/gitlab-runner
  version: 0.77.2
  installed: true
  values:
    - values.yaml.gotmpl
  hooks:
  - events: ["presync"]
    showlogs: true
    command: kubectl
    args:
    - apply
    - -f
    - ./manifests
    - -n
    - '{{ .Release.Namespace }}'
```
