### DISCUSSION TITLE
Adding release version for templating in .Release

### DISCUSSION THREAD

**Discussion by Simske** [helmfile/helmfile#2079] [Ideas]
Hi,
it would be great to make the release version accessible in the values/secrets templating via `.Release.Version`.

My usecase example would be selecting remote values/secret files from a git tag tied to the chart version:
```yaml
templates:
  podinfo:
    name: podinfo
    chart: oci://ghcr.io/stefanprodan/charts/podinfo
    valuesTemplate:
      - git::https://github.com/stefanprodan/podinfo.git@/charts/podinfo/values-prod.yaml?ref={{`{{ .Release.Version }}`}}

## the version here might be set environment specific
releases:
  - inherit:
      - template: podinfo
    version: 6.9.0
```

The implementation should be fairly straight forward, I will open a PR shortly.

Related discussions:
- #1934 -> I don't see the blocker here why this should be possible, however in my tests it worked fine.
- #2056
