### DISCUSSION TITLE
Helmfile does not support ArgoCD hooks

### DISCUSSION THREAD

**Discussion by IkePCampbell** [helmfile/helmfile#213] [Ideas]
I know the hooks work locally. But using this Helmfile configuration in ArgoCD:

```
releases:
  - name: "moo"
    namespace: "default"
    chart: "redacted/redacted"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "echo"
        args: ["{{`{{.Release.Name}}`}}"]
```

Results in the chart still deploying, but the hook never fires. I've tried changing it to a global hook, nothing. Tried searching around for other articles/gists/repos for any idea that theres a solution to this.

We definitely would love to have this work in ArgoCD as that would impact a lot of our releases and can streamline some pre/post sync processes!
