### DISCUSSION TITLE
Public helm chart mirroring

### DISCUSSION THREAD

**Discussion by jycamier** [helmfile/helmfile#216] [Ideas]
Helmfile is a good way to know the state of a k8s cluster and today, as the source of truth about what we've in the cluster, a mirroring feature could be very interesting

## Ideas

```yaml
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: mymirror
    url: <my-account>.dkr.ecr.<my-region>.amazonaws.com/helm-mirror
    oci: true
    
releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.5.3
    mirror: mymirror
```

### Ideas about commands

`helmfile mirror`: mirror each release `mirror: mymirror` with the waiting version
`helmfile apply --from-mirror=true` :  apply from mirror when a release is `mirror: mymirror`
