### DISCUSSION TITLE
Support Debug flag in events

### DISCUSSION THREAD

**Discussion by AssafKatz3** [helmfile/helmfile#218] [Ideas]
Hi,
I want to use [helmify](https://github.com/arttor/helmify) (as hook) and want to add '-v' to the command line if the debug mode of Helmfile is on. Currently, I couldn't find any documented support for this.
Thanks

**Comment by yxxhero** [comment]
helmify?

**Reply by AssafKatz3** [reply]
> helmify?

Hi,
Sorry, I want to use it as a hook of Helmfile, I updated the first comment.
Thanks

**Comment by yxxhero** [comment]
@AssafKatz3 can you show a example? Thanks very much.

**Reply by AssafKatz3** [reply]
Hi,
Currently I don't have this code (and it seems that Helmify doesn't produce what I want currently). But it will be similar to [helmify-kustomize](https://helmfile.readthedocs.io/en/latest/#helmfile-kustomize) example.

**Reply by philomory** [reply]
@AssafKatz3 If you wanted to add `-v` as an argument to Helmify (or any other command), can't you just add that to the `args` array in the helm hook? Something like this (again modifying the `helmify-kustomize` example):

```
- name: kustomize
  chart: ./foo
  hooks:
  - events: ["prepare", "cleanup"]
    command: "../helmify"
    args: ["-v", "{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}", "{{`{{.Release.Ch\
art}}`}}", "{{`{{.Environment.Name}}`}}"]
```
