### DISCUSSION TITLE
Please add template hook

### DISCUSSION THREAD

**Discussion by yellowmegaman** [helmfile/helmfile#219] [Ideas]
Thanks for great project!

I'm using helmfile as manifest generator for ArgoCD (as a plugin)

ArgoCD is expecting plugin to output yaml.
When I try to deploy some chart to non-existing namespace, `helmfile template` output doesn't contain namespace, even if `createNamespace` is set to true.

The idea: add `template` hook to print another file:
```yaml
repositories:
  - name: hashicorp
    url: "https://helm.releases.hashicorp.com"

releases:
- name: consul1
  namespace: "consul1"
  chart: "hashicorp/consul"
  version: v0.45.0
  set:
    - name: 'server.replicas'
      value: '1'
    - name: 'client.enabled'
      value: 'false'
  hooks:
  - events: ["template"]
    showlogs: false
    command: "cat"
    args: ["namespace.yaml"]
```
namespace.yaml contains kubernetes namespace definition

Right now I'm handling this in ArgoCD plugin configuration (running cat namespace.yaml && helmfile template), but running this from hook will make configuration lot more portable

Thanks in advance!

**Comment by yxxhero** [comment]
@yellowmegaman Welcome to create a PR. Thanks very much.

**Comment by mumoshu** [comment]
@yellowmegaman Hey! You should be able to add adhoc dependency to the `incubator/raw` chart and add the namespace resource, with something like:

```yaml
- name: consul1
  namespace: "consul1"
  chart: "hashicorp/consul"
  dependencies:
  - name: raw
    chart: incubator/raw
  values:
  - raw:
      resources:
      - |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: myns
```

or add another release dedicated to a namespace creation, and add the dependency to it from the cousul release with `needs`.
