### DISCUSSION TITLE
Add option to ignore missing values files

### DISCUSSION THREAD

**Discussion by hellorill** [helmfile/helmfile#223] [Questions] [answered]
When using predefined helmfile environment values files, if the file does not exist, helmfile fails. It would be great to add the ability to ignore these files.

helmfile.yaml:
```
environments:
  dev:
    values:
    - {{ printf "%s/%s/%s/%s" (exec "pwd" (list) | trim) "clusters" (requiredEnv "CLUSTER_NAME") "values.yaml" }}

helmDefaults:
  wait: true
  historyMax: 5

bases:
- {{ (printf "%s/%s/%s" "clusters" (requiredEnv "CLUSTER_NAME") "releases.helmfile") }}
```

Error message:
```
Failed to retrieve helmfile releases: in ./helmfile.yaml: failed to read clusters/example/releases.helmfile: environment values file matching "/builds/common/clusters/example/values.yaml" does not exist in "."
```

**Comment by yxxhero** [comment, marked as answer]
@hellorill 
you can try to use missingFileHandler.

**Comment by hellorill** [comment]
Tried, it works, thanks!

**Reply by canidam** [reply]
I encounter the same issue, but even with `missingFileHandler: warn` I get an error. My `helmfile.yaml` looks like

```yaml
bases:
- environments.yaml
---
releases:
- name: example
  missingFileHandler: Warn 
.. snip ..
```

and `environments.yaml`

```yaml
environments:
  sta:
    - config/sta.yaml
```

If the file doesn't exist, `helm -e sta diff` fails with

`failed to read environments.yaml: environment values file matching "config/sta.yaml" does not exist in "."`

What have you changed to get this working?
