### DISCUSSION TITLE
Use Charts values.yaml combined with an additional one

### DISCUSSION THREAD

**Discussion by canidam** [helmfile/helmfile#235] [Questions] [answered]
Hi,

I'm trying use the `values.yaml` from a Chart and include an additional (more specific) one with `helmfile`. 
I need to use the Chart `values.yaml` and just override stuff with `helmfile` additional values files.

I tried to achieve it with helmfile _environments_, but it seems to override the Charts `values.yaml` instead of merge. Here's an example

```
# helmfile
bases:
- environments.yaml
---
releases:
- name: nginx
  namespace: nginx
  chart: "../mychart"
  values:
    - image:
        repository: "nginx"
        tag: ""
      nameOverride: "my-nginx"

# environments.yaml
environments:
  default:
    values:
      - defaults.yaml

# defaults.yaml
serviceMonitor:
  enabled: true
```

In my Chart, I have a `serviceMonitor.yaml` file that starts with the statement `{{- if .Values.serviceMonitor.enabled }}`.

In my Chart, I've `values.yaml` define this parameter. When I run `helmfile apply` I encounter this error:
`at <.Values.serviceMonitor.enabled>: nil pointer evaluating interface {}.enabled`

However, if I remove the `bases` config part, helm uses the values coming from `values.yaml` and works as expected.

Is there a way to achieve what I'm trying with `helmfile`?

**Comment by canidam** [comment, marked as answer]
Okay - I've figured it out. My bad.

If anyone encounter this as well, what I needed to do is to add the yaml file under values:

```
releases:
- name: nginx
  namespace: nginx
  chart: "../monochart"
  values:
    - defaults.yaml
    - image:
        repository: "nginx"
        tag: ""
      nameOverride: "my-nginx"
```

and this works as expected.
