### DISCUSSION TITLE
Ubuntu image not pushed, refactoring of images workflow advisable?

### DISCUSSION THREAD

**Discussion by pathob** [helmfile/helmfile#261] [Ideas]
Hi,

I've noticed that the Ubuntu image currently does not get pushed. Is that intended?

I've also noticed that the images workflow uses two different jobs with two different approaches. The `build-test` job uses a matrix strategy like this:

```
    strategy:
      matrix:
       include:
         - dockerfile: Dockerfile
         - dockerfile: Dockerfile.debian
         - dockerfile: Dockerfile.ubuntu
```

The `build` job does not use a matrix strategy, but instead defines two "Build and Push" steps that are basically identical:

```
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push (debian stable-slim)
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-debian-stable-slim:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

The issue with the second step ("Build and Push (debian stable-slim)") is the name of the package. If the name would be more generic, e.g. just "helmfile-debian", it would be possible to use the suffix of the Dockerfile (if any) to generate the names. Then, also the second job could use a matrix strategy to build and push the images and it would be even easier to add more images like the Ubuntu one. Another solution for a generic approach would be to rename the `Dockerfile.debian` to `Dockerfile.debian-stable-slim` but yeah...

Looking forward to hear your feedback!

Patrick
