### DISCUSSION TITLE
Helm values.yaml from URL

### DISCUSSION THREAD

**Discussion by yellowmegaman** [helmfile/helmfile#270] [Questions]
Greetings!

Can someone share an example of using values.yaml from url?
```
releases:
- name: haproxy
  namespace: "haproxy"
  createNamespace: true
  chart: "haproxytech/haproxy"
  version: "v1.14.0"
  atomic: true
  timeout: 300
  values:
    - https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml
```

Like it is working in helm:
```
helm install haproxy --values=https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml haproxytech/haproxy
```

Example above yelds:
```
in ./helmfile.yaml: values file matching "https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml" does not exist in "."
```

Thanks in bunch in advance!

**Comment by philomory** [comment]
I would also find this useful, along with support for `go-getter` syntax (e.g. `git::https://github.com/foo/bar/baz.yaml?ref=refs/tags/tag`) for individual values files.

**Reply by yxxhero** [reply]
Thanks very much. I think the doc should be updated. Can you create a PR for this. Thanks very much again.

**Reply by philomory** [reply]
> Thanks very much. I think the doc should be updated. Can you create a PR for this. Thanks very much again.

@yxxhero why did you mark this as an answer? The feature doesn't exist, there is nothing to document. None of the requested syntaxes actually work.

**Comment by yellowmegaman** [comment]
@philomory but do you know it it's available right now?

**Reply by philomory** [reply]
No, this feature is not presently available.

**Comment by yxxhero** [comment]
@yellowmegaman @philomory sorry. I will work on this feature.

**Comment by yxxhero** [comment]
```
releases:
- name: my-app
  namespace: dev2
  chart: my-app/my-app
  values:
    -  git::https://username@bitbucket.org/my-org/my-app@helm/values.dev2.yaml?ref=my_branch
```
