### DISCUSSION TITLE
Allow description paramter for each release

### DISCUSSION THREAD

**Discussion by AssafKatz3** [helmfile/helmfile#309] [Ideas]
Hi,
This information is useful for marking release by build numbers, enviornment type, installer, etc. This will be simple optional string, under release entry, which will be directly map to helm install/upgrade command parameter.
Thanks

**Comment by yxxhero** [comment]
@AssafKatz3 Please create a example. Thanks very much.

**Comment by AssafKatz3** [comment]
Same example like [getting-started](README.md#getting-started) with it:

```
repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  description:  Automatic build
  set:
  - name: rbac.create
    value: false

```
