### DISCUSSION TITLE
How can I diagnose problem where default environment values from a values file aren't applied to a chart release?

### DISCUSSION THREAD

**Discussion by mojochao** [helmfile/helmfile#330] [Questions] [answered]
I'm using the following tool versions on macOS Big Sur (11.6.6) on Intel arch.

```
helm 3.9.4
helm-diff 3.5.0
helmfile 0.144.0
```

In my `helmfile.yaml` I have the following.

```yaml
environments:
  default:
    values:
      - values.yaml

releases:
  - chart: charts/aws-auth
    name: aws-auth
    namespace: aws-auth
```

My `values.yaml` file contains config for a local `aws-auth` chart.

```yaml
awsAuth:
  mapUsers:
    - groups:
        - system:masters
      userArn: arn:aws:iam::1234567890:user/alice
      userName: alice
    - groups:
        - system:masters
      userArn: arn:aws:iam::1234567890:user/bob
      userName: bob
```

The chart is not really important to spell out, but it defines `awsAuth.mapUsers` and `awsAuth.mapRoles` variables used by the chart to template some CRDs.

With the `helmfile.yaml` shown above, I get no contents rendered with running `helmfile diff`. However, if I change the `helmfile.yaml` to the following, I do get my expected templates rendered.

```yaml
releases:
  - chart: charts/aws-auth
    name: aws-auth
    namespace: aws-auth
    values:
      - values.yaml
```

I'm confused as to why the `values.yaml` file works as expected when passed directly into the chart release block, but not when used by the default environment configured with that same file as shown above first.

Can anyone explain this behavior?  Or better yet, explain to me how I can diagnose it myself with the output using the `-debug` flag?  To me, it looks like it was loaded correctly, but does not seem to be applied to the chart release.

Many thanks in advance!

**Comment by yxxhero** [comment, marked as answer]
@mojochao 
Explain the principle of helmfile in one sentence. Helmfile uses the go template system to generate the chart configuration value of helm.

```
releases:
  - chart: charts/aws-auth
    name: aws-auth
    labels:
      name: aws-auth
    namespace: aws-auth
    values:
      - values.yaml.gotmpl
```
values.yaml.gotmpl is go template file. Its configuration comes from the environment specific configuration in helmfile.
