### DISCUSSION TITLE
kustomize and .Capabilities.APIVersions.Has

### DISCUSSION THREAD

**Discussion by gakesson** [helmfile/helmfile#332] [Ideas]
I noticed that helm charts that contains .Capabilities.APIVersions.Has behaves differently in case kustomize config is used or not.
Assume I have a helmfile similar to below, containing a local Helm chart as well as helmfile kustomize config:
```
releases:
- name: service-a
  namespace: {{ .Namespace }}
  chart: local-chart/
  version: {{ (tpl (readFile "local-chart/Chart.yaml") . | fromYaml).version }}
  transformers:
  - apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: faultWorkaround
    fieldSpecs:
    - create: true
      path: metadata/labels
    labels:
      a-kustomize-label: label-from-kustomize
```

The local Helm chart above contains a single template, using .Capabilities.APIVersions.Has:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: capabilities-based-cm
  namespace: {{ .Release.Namespace }}
{{- if (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
data:
  state: CLUSTER_ACCESSED
{{- else }}
data:
  state: CLUSTER_NOT_ACCESSED
{{- end }}
```

Now, assume that the cluster has the API cert-manager.io/v1 then a `helmfile sync` **without** helmfile kustomize config will write the state CLUSTER_ACCESS into the ConfigMap, whereas a `helmfile sync `**with** kustomize will write CLUSTER_NOT_ACCESSED.
This boils down to how the chart is generated and installed, in which the original chart's templates are first generated through helm template before being processed by kustomize, and then the kustomized chart is getting installed:
1. helm template
2. kustomize build
3. helm upgrade --install

If I instead use `helmfile apply --validate `then the --validate option is passed onto the initial helm template prior to kustomize, so then the API versions are accessible and the expected template is generated. However, the --validate is not available for the sync command (which makes sense unless kustomize is used).

So I would like to explore the possibility if helmfile sync could also have the --validate flag, or if perhaps have a new helmDefaults in which mutating commands (sync, apply, destroy) can always supply the --validate for the helm template when kustomize is used.

I'm also aware that there is a long and ongoing discussion for helm lookup which suffers from similar behavior, which not even --validate helps with [(Unable to debug "lookup" function, as its disabled with helm template)](https://github.com/helm/helm/issues/8137)

Any thoughts on this?
