### DISCUSSION TITLE
how to get the name of  helmfile state yaml file at releases installed condition？

### DISCUSSION THREAD

**Discussion by tanguofu** [helmfile/helmfile#333] [Questions]
As we have one dir  modules  which has two charts `examples1`  `examples2` and the `helmfile.yaml`  
```
modules:
  - examples1
  - examples2
  - helmfile.yaml  
```

the content of  `helmfile.yaml` is  :
```
releases:
  # must be helm chart name
  - name: examples1
    chart: examples1
    installed:  ？ #  install when the root helmfile name is A.yaml

  - name: examples2
    chart: examples2
    installed: ？  # install when the root helmfile name is B.yaml
```

and when deployed  there will be two helmfile.yaml  : `A.yaml` `B.yaml` ; both will include the  `modules/helmfile.yaml`
```
helmfiles:
- modules/helmfile.yaml
```
so how can i get the  the root helmfile name  in the releases ?  
many thanks
