### DISCUSSION TITLE
Is helmfile right for me?

### DISCUSSION THREAD

**Discussion by alop** [helmfile/helmfile#343] [Questions]
My app is currently deployed as a meta chart with subcharts.

My dev environment is actually 16 different namespaces (Large team) - so Dev environments are 99% identical, except for namespace.

My Prod environment is in 8 different regions, so almost identical, but regional differences.

The docs/examples I've read show like "This is my 1 chart, and it's deployed to 1 prod env"
I'm curious if others have used helmfile on a large multi-region env.

**Comment by mgs255** [comment]
We use helmfile at work to deploy to numerous different clusters in multiple regions on EKS.  Our largest production environment is composed of something like 110 distinct services.  We have around 20 production clusters all manged with helmfile.  We don't use sub-charts so I don't really have any experience of those. 

We organise the deployment repository using two variables `ACCOUNT` and `NAMESPACE` and execute helmfile using a build pipeline, e.g:
```
account=$ACCOUNT
environment=$ENVIRONMENT
namespace=$account-$environment
...
helmfile -e $namespace -f accounts/$account/ apply --concurrency 10
```
The directory structure is like this:

* /values/<service-name>.yaml.gotmpl  - contains values template files for individual service definitions 
* /accounts/$account/ - contains a number of "services" files which define which services to run for each account as well as a deployment order, e.g: 0100.base.yaml, 0105.kafka.yaml....  example below.
* /account/$account/$namespace/values/global.yaml - contains a bunch of variables that are specific to that environment.

Example of "services" file:

```
environments:
  {{ .Environment.Name }}:
    values:
    - ./environments/{{ .Environment.Name }}/values/global.yaml

repositories:
- name: "internal-helm-charts"
  url: "s3://internal-helm-charts"
- name: "elastic"
  url: "https://helm.elastic.co"

releases:
  - name: elasticsearch-cluster
    namespace: {{ .Environment.Name }}
    version: 7.12.0
    chart: elastic/elasticsearch
    labels:
      group: base
      app: elasticsearch-cluster
    values:
      - ../../values/elasticsearch-cluster.yaml.gotmpl
    timeout: 1200
    atomic: true

  - name: elasticsearch-exporter
    namespace: {{ .Environment.Name }}
    version: 3.4.0
    chart: internal-helm-charts/elasticsearch-exporter
    labels:
      group: base
      app: elasticsearch-exporter
    values:
      - ../../values/elasticsearch-exporter.yaml.gotmpl
    atomic: true

```
Some downsides we find:
* we are currently using different branches to control the configuration at different stages and it is each to get drift between stages
* For a large environment, some of the operations like lint are slower than we would like, taking around 2 minutes or so.  One of our charts is reused among for many different services, and the same version is downloaded from s3 repeatedly, which is not ideal.

In the main I think this works relatively well.  It certainly is flexible in the way you can share values across environments.
