### DISCUSSION TITLE
How to deal with circular dependencies?

### DISCUSSION THREAD

**Discussion by evgkrsk** [helmfile/helmfile#35] [Questions] [answered]
Usecase: I have **kube-prometheus-stack** release with ingress resources and to implement ingress resources there is **ingress-nginx** release. But I wish to enable **servicemonitor** CRD in ingress-nginx chart to monitor this controller with kube-prometheus-stack. Servicemonitor CRD is implemented by kube-prometheus-stack. Definitely, it is circular dependencies.

For now I forced to deploy these releases in three steps:
1) ingress-nginx with disabled servicemonitor and without dependency
2) kube-prometheus-stack with dependency to ingress
3) ingress-nginx with servicemonitor enabled and with dependency to kube-prometheus-stack

After this steps, I cant enable both "needs" (AFAIR, helmfile fails to run):

```yaml
- name: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  needs:
    - ingress-nginx

- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  # needs:
  #   - kube-prometheus-stack     # circular
```

How to simplify installation of such releases? How to define fact of circular dependency in helmfile.yaml?
