### DISCUSSION TITLE
global prepare hook does not run before sub-helmfiles

### DISCUSSION THREAD

**Discussion by tonygilkerson** [helmfile/helmfile#352] [Questions]
Please look at the following and let me know if I need to crate a bug issue:

The global prepare hook is not running before the releases in the sub-helfiles.  Given the following helmfle.yaml

```yaml
missingFileHandler: Error

hooks:
- events: ["prepare"]
  showlogs: true
  command: "sh"
  args:
  - "-c"
  - exit 1                         # <------------ return an  error

releases:
- name: foo3
  namespace: default
  chart: ../../local-charts/foo3

helmfiles:
- path: ../../apps/app1
  values:
  - {{ $.Values | toYaml | nindent 6}}
- path: ../../apps/app2
  values:
  - {{ $.Values | toYaml | nindent 6}}


environments:
  default:

 ```
 
The following apply works as expected, it throws an error due to the prepare hook

```sh
helmfile -i -f env/env1/helmfile.yaml -l name=foo3 apply
```

However if I include all releases it does not throw an error as expected. It will apply the release in the sub-helmfiles then it throws the error, but now it is too late

```sh
helmfile -i -f env/env1/helmfile.yaml apply
```

He list command does work as expected, it simply throws an error and no releases are listed

```sh
helmfile -i -f env/env1/helmfile.yaml apply
```
