### DISCUSSION TITLE
custom resources need to be create first

### DISCUSSION THREAD

**Discussion by labaq** [helmfile/helmfile#357] [Questions]
i have release need to create custom resource for kind "ClusterIssuer" in version "cert-manager.io/v1"
but have error message when i apply
```
  Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "lets-encrypt-http-issuer" namespace: "" from "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
  ensure CRDs are installed first
```
my config is like this
```
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    set:
    - name: installCRDs
      value: true
    wait: true
  
  - name: loft
    namespace: loft
    chart: loft/loft
    values:
    - cert-values.yaml
```
i'm not sure is that cert-manager have not install CRD yet so the helmfile return error. or the release can't wait another release ready, i have set `wait: true` but it seem not work, or i mistake it?

_UPDATE:_
helm version:
```
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}
```
helmfile version:
```
Helmfile version v0.145.4
```
