### DISCUSSION TITLE
Templating complex values.yaml files

### DISCUSSION THREAD

**Discussion by jefrnc** [helmfile/helmfile#364] [Questions]
Hi!,
I'm trying to set a value to an annotations:

```
    annotations:
      alb.ingress.kubernetes.io/conditions.any: "{{ .Values.otherServiceName    }}"
      alb.ingress.kubernetes.io/conditions.any2: "{{` '{{ .Values.otherServiceName }}' `}}"
      alb.ingress.kubernetes.io/conditions.any3: |-
        {{ .Values.otherServiceName | squote   }}
      alb.ingress.kubernetes.io/conditions.any4: |-
        {{ .Values.otherServiceName    }}     
```
I tried in several ways and I have no luck, only in the annotations part it does not render the value.
It is similar to this bug: https://github.com/roboll/helmfile/issues/700
And it always renders the instruction to me but does not resolve it.

![image](https://user-images.githubusercontent.com/53045966/190021323-ccccbdf9-f25e-4f67-88a0-78f9dc4c57ea.png)

Could someone solve?

Thanks
