### DISCUSSION TITLE
Handle vals failures if a reference is unavailable

### DISCUSSION THREAD

**Discussion by Amos-85** [helmfile/helmfile#391] [Ideas]
In a favor of those issues:
https://github.com/roboll/helmfile/issues/1728
https://github.com/variantdev/vals/issues/52

There is a use case when we want to be able to skip secret reference keys that do not exist.
Assuming we have some central file to manage secrets, we would like to have the ability to skip on missing ref keys if they do not exist.

Option 1:
```
environments:
  {{ .Environment.Name }}:
    values:
    - path: ../providers/{{ .Values.provider }}/secrets.gotmpl
      optional: true
```
Option 2:
`ref+gcpsecrets://blablabla?optional`

More options mentioned on this comment [here](https://github.com/roboll/helmfile/issues/1728#issuecomment-841754632)
