### DISCUSSION TITLE
Allow to set environment variables per hook

### DISCUSSION THREAD

**Discussion by felipecrs** [helmfile/helmfile#437] [Ideas]
As the command and args, setting envs would be nice.

Imagine I have a script like this:

## `cleanup.sh`

```bash
#!/bin/bash

kubectl --namespace="${NAMESPACE}" --context="${CONTEXT}" delete secret blahblah
```

## Old `helmfile.yaml`

With the current version of Helmfile, my Helmfile has to look like this:

```yaml
releases:
  hooks:
    - events:
        - postuninstall
      command: bash
      args:
        - -c
        - |
          export NAMESPACE="{{ .Release.Namespace }}"
          export CONTEXT="{{ $context }}"
          ./cleanup.sh
```

## New `helmfile.yaml`

```yaml
releases:
  hooks:
    - events:
        - postuninstall
      command: ./cleanup.sh
      envs:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: CONTEXT
          value: "{{ $context }}"
```
