### DISCUSSION TITLE
err: no releases found that matches specified selector

### DISCUSSION THREAD

**Discussion by ismailyenigul** [helmfile/helmfile#443] [Questions] [answered]
It seems helmfile version 0.147.0 does not support multiple selector in single selector parameter.

```
$ ./helmfile --version                           
helmfile version 0.147.0
```

`$ helmfile --debug  --environment dev --interactive --selector service=myapp,environment=dev apply`

`err: no releases found that matches specified selector(service=myapp,environment=dev) and environment(dev), in any helmfile`

It works fine with helmfile 0.146.0

```
$ helmfile --version                                                                  
helmfile version 0.146.0

helmfile --debug  --environment dev --interactive --selector service=myapp,environment=dev apply  

Affected releases are:
  app-1 (./charts/myapp) UPDATED

Do you really want to apply?
  Helmfile will apply all your changes, as shown above.
```
Is this bug or new feature?

**Comment by yxxhero** [comment]
@ismailyenigul Please  show your helmfile.

**Reply by yxxhero** [reply]
@ismailyenigul show all debug messages too. Thanks very much.

**Comment by ismailyenigul** [comment]
here is my helmfile.yml
```
bases:
  - vars/secrets.yaml

templates:
  app_default: &app_default
    chart: ./charts/{{ `{{ .Release.Name }}` }}
    secrets:
      - vars/{{ .Environment.Name }}/secrets.yaml
    values:
      - vars/common/configs.yaml
      - vars/{{ .Environment.Name }}/configs.yaml
      - vars/{{ .Environment.Name }}/{{ `{{ .Release.Name }}` }}.values.yaml
    namespace: '{{ env "NAMESPACE" | default "default" }}'
    labels:
      service: "{{ `{{ .Release.Name }}` }}"

  myapp_default: &myapp_default
    chart: ./charts/myapp
    secrets:
      - vars/{{ .Environment.Name }}/secrets.yaml
    values:
      - vars/common/configs.yaml
      - vars/{{ .Environment.Name }}/configs.yaml
      - vars/{{ .Environment.Name }}/myapp.values.yaml
      - vars/{{ .Environment.Name }}/{{ `{{ .Release.Name }}` }}.values.yaml
    namespace: '{{ env "NAMESPACE" | default "default" }}'
    labels:
      service: "myapp"

releases:
  - name: myapp-1
    <<: *myapp_default
    labels:
      environment: {{.Environment.Name}}
      myapp: myapp-1

```
Ps: cleanup up other parts to make simple

debug output(masked secrets)

```
./helmfile --debug  --environment dev --interactive --selector service=myapp,environment=dev apply    
processing file "helmfile.yaml" in directory "."
changing working directory to "/tmp/test"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{dev map[] map[]}, overrode=<nil>
first-pass uses: &{dev map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: bases:
 1:   - vars/secrets.yaml
 2: 
 3: templates:
 4:   app_default: &app_default
 5:     chart: ./charts/{{ .Release.Name }}
 6:     secrets:
 7:       - vars/dev/secrets.yaml
 8:     values:
 9:       - vars/common/configs.yaml
10:       - vars/dev/configs.yaml
11:       - vars/dev/{{ .Release.Name }}.values.yaml
12:     namespace: 'default'
13:     labels:
14:       service: "{{ .Release.Name }}"
15: 
16:   myapp_default: &myapp_default
17:     chart: ./charts/myapp
18:     secrets:
19:       - vars/dev/secrets.yaml
20:     values:
21:       - vars/common/configs.yaml
22:       - vars/dev/configs.yaml
23:       - vars/dev/myapp.values.yaml
24:       - vars/dev/{{ .Release.Name }}.values.yaml
25:     namespace: 'default'
26:     labels:
27:       service: "myapp"
28: 
29: releases:
30:   - name: myapp-1
31:     <<: *myapp_default
32:     labels:
33:       environment: dev
34:       myapp: myapp-1
35: 

error in first-pass rendering: result of "helmfile.yaml.part.0":
 0: bases:
 1:   - vars/secrets.yaml
 2: 
 3: templates:
 4:   app_default: &app_default
 5:     chart: ./charts/{{ .Release.Name }}
 6:     secrets:
 7:       - vars/dev/secrets.yaml
 8:     values:
 9:       - vars/common/configs.yaml
10:       - vars/dev/configs.yaml
11:       - vars/dev/{{ .Release.Name }}.values.yaml
12:     namespace: 'default'
13:     labels:
14:       service: "{{ .Release.Name }}"
15: 
16:   myapp_default: &myapp_default
17:     chart: ./charts/myapp
18:     secrets:
19:       - vars/dev/secrets.yaml
20:     values:
21:       - vars/common/configs.yaml
22:       - vars/dev/configs.yaml
23:       - vars/dev/myapp.values.yaml
24:       - vars/dev/{{ .Release.Name }}.values.yaml
25:     namespace: 'default'
26:     labels:
27:       service: "myapp"
28: 
29: releases:
30:   - name: myapp-1
31:     <<: *myapp_default
32:     labels:
33:       environment: dev
34:       myapp: myapp-1
35: 

first-pass produced: &{dev map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {dev map[] map[]}
second-pass rendering result of "helmfile.yaml.part.0":
 0: bases:
 1:   - vars/secrets.yaml
 2: 
 3: templates:
 4:   app_default: &app_default
 5:     chart: ./charts/{{ .Release.Name }}
 6:     secrets:
 7:       - vars/dev/secrets.yaml
 8:     values:
 9:       - vars/common/configs.yaml
10:       - vars/dev/configs.yaml
11:       - vars/dev/{{ .Release.Name }}.values.yaml
12:     namespace: 'default'
13:     labels:
14:       service: "{{ .Release.Name }}"
15: 
16:   myapp_default: &myapp_default
17:     chart: ./charts/myapp
18:     secrets:
19:       - vars/dev/secrets.yaml
20:     values:
21:       - vars/common/configs.yaml
22:       - vars/dev/configs.yaml
23:       - vars/dev/myapp.values.yaml
24:       - vars/dev/{{ .Release.Name }}.values.yaml
25:     namespace: 'default'
26:     labels:
27:       service: "myapp"
28: 
29: releases:
30:   - name: myapp-1
31:     <<: *myapp_default
32:     labels:
33:       environment: dev
34:       myapp: myapp-1
35: 

first-pass rendering starting for "vars/secrets.yaml.part.0": inherited=&{dev map[] map[]}, overrode=<nil>
first-pass uses: &{dev map[] map[]}
first-pass rendering output of "vars/secrets.yaml.part.0":
 0: environments:
 1:   testbox:
 2:     secrets:
 3:     - vars/testbox/secrets.yaml
 4:   dev:
 5:     secrets:
 6:     - vars/dev/secrets.yaml
 7:   devtest:
 8:     secrets:
 9:     - vars/devtest/secrets.yaml
10:   app:
11:     secrets:
12:     - vars/prod/secrets.yaml
13:   staging:
14:     secrets:
15:     - vars/staging/secrets.yaml
16:   localhost:
17:     secrets:
18:     - vars/localhost/secrets.yaml
19: 

...


Decrypted /tmp/test/vars/dev/secrets.yaml into vars/dev/secret3931000538.yaml
first-pass produced: &{dev map[aws:map...]] map[]}
vals:
map[aws:map[accessKeyId]]
defaultVals:[]
second-pass rendering result of "vars/secrets.yaml.part.0":
 0: environments:
 1:   testbox:
 2:     secrets:
 3:     - vars/testbox/secrets.yaml
 4:   dev:
 5:     secrets:
 6:     - vars/dev/secrets.yaml
 7:   devtest:
 8:     secrets:
 9:     - vars/devtest/secrets.yaml
10:   app:
11:     secrets:
12:     - vars/prod/secrets.yaml
13:   staging:
14:     secrets:
15:     - vars/staging/secrets.yaml
16:   localhost:
17:     secrets:
18:     - vars/localhost/secrets.yaml
19: 

Preparing to decrypt secret /tmp/test/vars/dev/secrets.yaml
Found secret in cache /tmp/test/vars/dev/secrets.yaml
Decrypted /tmp/test/vars/dev/secrets.yaml into vars/dev/secret3246029851.yaml
merged environment: &{dev map[aws:map[accessKeyId:...] map[]}
Preparing to decrypt secret /tmp/test/vars/dev/secrets.yaml
Found secret in cache /tmp/test/vars/dev/secrets.yaml
Decrypted /tmp/test/vars/dev/secrets.yaml into vars/dev/secret3996504513.yaml
merged environment: &{dev map[aws:map[accessKeyId:A]] map[]}
0 release(s) matching service=myapp,environment=dev found in helmfile.yaml

changing working directory back to "/tmp/test"
err: no releases found that matches specified selector(service=myapp,environment=dev) and environment(dev), in any helmfile
```

**Comment by yxxhero** [comment, marked as answer]
see: https://github.com/helmfile/helmfile/issues/394, we upgrade the yaml library into v3. it allows key overrides.

**Reply by yxxhero** [reply]
see: https://github.com/helmfile/helmfile/discussions/443#discussioncomment-3894218

**Comment by yxxhero** [comment]
```yaml
bases:
  - vars/secrets.yaml

templates:
  app_default: &app_default
    chart: ./charts/{{ `{{ .Release.Name }}` }}
    secrets:
      - vars/{{ .Environment.Name }}/secrets.yaml
    values:
      - vars/common/configs.yaml
      - vars/{{ .Environment.Name }}/configs.yaml
      - vars/{{ .Environment.Name }}/{{ `{{ .Release.Name }}` }}.values.yaml
    namespace: '{{ env "NAMESPACE" | default "default" }}'
    labels:
      service: "{{ `{{ .Release.Name }}` }}"

  myapp_default: &myapp_default
    chart: ./charts/myapp
    secrets:
      - vars/{{ .Environment.Name }}/secrets.yaml
    values:
      - vars/common/configs.yaml
      - vars/{{ .Environment.Name }}/configs.yaml
      - vars/{{ .Environment.Name }}/myapp.values.yaml
      - vars/{{ .Environment.Name }}/{{ `{{ .Release.Name }}` }}.values.yaml
    namespace: '{{ env "NAMESPACE" | default "default" }}'
    labels:
      service: "myapp"

releases:
  - name: myapp-1
    <<: *myapp_default
    labels:
      environment: {{.Environment.Name}}
      myapp: myapp-1
      service: "myapp"
```

try update your helmfile as above.
