### DISCUSSION TITLE
Allow to set `helmDefaults.namespace`

### DISCUSSION THREAD

**Discussion by felipecrs** [helmfile/helmfile#447] [Ideas]
If I can set `helmDefaults.kubeContext`,  I guess I should also be able to set `namespace`. The workaround seems to use `helmfile --namespace` OR to set all the `releases[].namespace` to the same value. Using `helmDefaults.args` with `--namespace` does not seem to work all the time (I guess it's filtered out when running the `list` command, for example).

**Comment by wrenix** [comment]
and also inside of environments ;)

so different enviroments could be inside of same cluster: 
```yaml
environments:
  dev:
    kubeContext: cluster-01
    namespace: dev
    values:
     - values/default.yaml
     - values/dev.yaml
  prod:
    kubeContext: cluster-01
    namespace: prod
    values:
     - values/default.yaml
     - values/prod.yaml
```
