### DISCUSSION TITLE
Improve concurrency for independent paths on dependency graph

### DISCUSSION THREAD

**Discussion by pathob** [helmfile/helmfile#452] [Ideas]
Hi @mumoshu @yxxhero 

I've noticed a situation in Helmfile where deployments are unnecessarily slowed down.

given the following situation in Helmfile:

```
releases:
  - name: A

  - name: B

  - name: A1
    needs:
      - A

  - name: A2
    needs:
      - A
```

When `helmfile apply` is executed, it will run the deployments of releases A and B first (as expected). However, the deployment of A might be much faster than the deployment of B, say 3 mins for A and 8 mins for B. What I would expect is that the deployments of A1 and A2 start immediately after the deployment of A is finished. However, the deployments of A1 and A2 will wait until both, A _and_ B have finished.

Is that a bug?

And yeah, I should start developing for Helmfile soon, haha
