### DISCUSSION TITLE
`need` pointing to sub-helmfile not working

### DISCUSSION THREAD

**Discussion by paichinger** [helmfile/helmfile#466] [Questions]
Hello! 
  
I'm having the following setup:

File tree:
```
├── helmfile.yaml
├── manifests
│   └── dummy.yaml
└── sub-helmfiles
    └── sub-helmfile.yaml
  
```
`helmfile.yaml`:
```
helmfiles:
  - sub-helmfiles/sub-helmfile.yaml
releases:
  - name: myapp1
    chart: manifests/
    needs:
      - myapp2
```

`sub-helmfiles/sub-helmfile.yaml`:
```
releases:
  - name: myapp2
    chart: ../manifests/
```

`manifests/dummy.yaml` (Content doesn't really matter, but anyway...):
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account
```

As you can see the realease `myapp1` defined in the main helmfile `needs` the release `myapp2` defined in the sub-helmfile. Now, when I try to template the following:
`helmfile template` 
or
`helmfile -l name=myapp1 template`
or
`helmfile -l name=myapp1 template --include-needs`
I always get the following error:
```
Building dependency release=myapp1, chart=/tmp/chartify2180965982/myapp1
in ./helmfile.yaml: release(s) "myapp1" depend(s) on an undefined release "myapp2". Perhaps you made a typo in "needs" or forgot defining a release named "myapp2" with appropriate "namespace" and "kubeContext"?
```

That raises the suspicion that inter-helmfile needs are not supported. I couldn't find anything about this in the docs, that why I want to start this discussion to verify that case. Maybe also anyone has an idea if there's a workaround for this to achieve the same goal.
  
Thanks in advance for any feedback!

**Comment by paichinger** [comment]
I just found a workaround:
Changed the main helmfile to:
```
releases:
  - name: myapp1
    chart: manifests/
    needs:
      - myapp2
{{ readFile "./sub-helmfiles/sub-helmfile.yaml" }}
```
and got rid of the sub-helmfile feature completely.

**Comment by yxxhero** [comment]
@pjotre86 good catch. this is a good enforcement

**Comment by fafarun** [comment]
Hi,
I have the almost same issue. 

I use the functionality "Separating helmfile.yaml into multiple independent files Glob patterns" and the functionality need

I have this organization :
```
folder app
  folder app01
    00-front.yaml
    01-back.yaml
  folder app02
    00-ui.yaml
```

I had needs in the app02/00-ui.yaml to the release in the app01/00-front.yaml. 

But the needs function not working between different Helmfiles. Is it true ? Or I mad a mistake in my configuration



```
# app02-ui.yaml

bases:
- ../common.yaml
---
releases:  
- name: ca
  namespace: {{ .StateValues.certManager.namespace }}
  version: 1.0.0
  needs:
  - {{ .StateValues.certManager.namespace }}
  chart: ./charts/ca-cert-manager
  inherit:
  - template: common
```

```
# app01/00-front.yaml

bases:
- ../common.yaml
---
repositories:
- name: {{ .StateValues.repositories.public.certmanager.name }}
  url: {{ .StateValues.repositories.public.certmanager.url }}

releases:  
- name: cert-manager
  namespace: {{ .StateValues.certManager.namespace }}
  version: {{ .StateValues.certManager.chartVersion }}
  chart: {{ .StateValues.repositories.public.certmanager.name }}/cert-manager
  inherit:
  - template: common
 ```
