### DISCUSSION TITLE
Templating in local manifests (with chartify)

### DISCUSSION THREAD

**Discussion by uempfel** [helmfile/helmfile#490] [Questions]
Hi,
is it possible to include templating in local manifests?

### Example
I'm trying to template some common variables into small manifests. Those manifests are quite simple, so it isn't really worth creating proper helm charts for them. Consider the following example:
- directory structure:  
```bash
▶ tree .
.
├── helmfile.yaml
└── manifests
    └── pod.yaml
```
- helmfile.yaml:
```yaml helmfile.yaml
releases:
- name: local-manifests
  chart: ./manifests
  set:
  - name: foo
    value: bar
```
- manifests/pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    foo: {{ .Values.bar }}
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
 ```

### Error
However, when I try to render the files, I get the following error:  
```bash
▶ helmfile template                                           
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm template --debug=false --output-dir=/var/folders/7b/ymytn8gd2q1053j9hm72j84m0000gn/T/chartify1052962880/local-manifests/helmx.1.rendered local-manifests /var/folders/7b/ymytn8gd2q1053j9hm72j84m0000gn/T/chartify1052962880/local-manifests --set foo=bar

OUTPUT:
  Error: YAML parse error on manifests/templates/pod.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.bar":interface {}(nil)}
  Use --debug flag to render out invalid YAML]
```
