### DISCUSSION TITLE
Allow using environment variables in more places

### DISCUSSION THREAD

**Discussion by sjdrc** [helmfile/helmfile#502] [Questions] [answered]
I'd specifically like to be able to use `{{ requiredEnv "REPO_PASSWORD" }}` in the username and password fields for repositories.

**Comment by yxxhero** [comment]
@sjdrc such as?

**Reply by sjdrc** [reply]
Currently to specify auth credentials from environment variables I have to do this:
```
repositories:
- name: myrepo
  url: https://{{ requiredEnv "USERNAME" }}:{{ requiredEnv "PASSWORD }}@charts.example.com
```

I want to be able to do this:
```
repositories:
- name: myrepo
  url: https://charts.example.com
  username: {{ requiredEnv "USERNAME" | quote }}
  password: {{ requiredEnv "PASSWORD" | quote }}
```

**Comment by yxxhero** [comment]
@sjdrc 
```yaml
- name: roboll
  url: http://roboll.io/charts
  certFile: optional_client_cert
  keyFile: optional_client_key
  # username is retrieve from the environment with the format <registryNameUpperCase>_USERNAME for CI usage, here ROBOLL_USERNAME
  username: optional_username
  # username is retrieve from the environment with the format <registryNameUpperCase>_PASSWORD for CI usage, here ROBOLL_PASSWORD
```

**Reply by sjdrc** [reply]
Thanks! I totally missed this in the docs - was looking further down https://helmfile.readthedocs.io/en/latest/#using-environment-variables

**Reply by sjdrc** [reply]
This doesn't appear to work.

I have the following environment variables set:
- MYREPO_CHARTS_REPO
- MYREPO_USERNAME
- MYREPO_PASSWORD

```
repositories
- name: myrepo
  url: '{{ requiredEnv "MYREPO_CHARTS_REPO" }}'
releases:
- name: thingo
  namespace: thingo
  chart: myrepo/thingo
```

I get the following error:
```
Adding repo myrepo REDACTED
in /builds/customers/acme/helmfile.yaml: in .helmfiles[0]: in thingo/helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
  /usr/local/bin/helm
ARGS:
  0: helm (4 bytes)
  1: repo (4 bytes)
  2: add (3 bytes)
  3: myrepo (7 bytes)
  4: REDACTED (64 bytes)
  5: --force-update (14 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: looks like "REDACTED" is not a valid chart repository or cannot be reached: failed to fetch REDACTED : 401 Unauthorized
COMBINED OUTPUT:
  Error: looks like "REDACTED" is not a valid chart repository or cannot be reached: failed to fetch REDACTED : 401 Unauthorized
```
