### DISCUSSION TITLE
Reference other variables in values.yaml.gotmpl

### DISCUSSION THREAD

**Discussion by leotomas837** [helmfile/helmfile#521] [Ideas]
Being able to reference other variables in values.yaml.gotmpl. For example:

```
customer: xxxxx
domain: {{ .Values.customer }}.example.com
```

With the following helm [plugin](https://github.com/jkroepke/helm-kubectl), it would enable to produce different `values.yaml` depending on existing configurations (as helm `lookup` does). It would also works with argocd as the plugin works by running `helmfile template`.

With the plugin installed, we would be able to do something like this for example:

```
$> kubectl get node mynode -o jsonpath="{.metadata.labels.kubernetes\.io/os}"
linux

$> cat helmfile.yaml       <-------- It already works thanks to the plugin. It sets 'linux' as .Values.mynode.mysos for the releases
releases:
  - name: temp
    chart: .
    namespace: default
    values:
      - values.yaml.gotmpl
    set:
      - name: mynode.myos
      - file: kubectl:///nodes/mynode/jsonpath={.metadata.labels.kubernetes\\\\.io/os}

$> cat values.yaml.gotmpl      <-------- would work with the change
{{- if eq .Values.mynode.myos "linux" }}       
# do something
{{- else if eq .Values.mynode.myos "windows"}}
# do something else
{{- end }}

$> helmfile template .      <------ would work with the values.yaml.gotmpl working. Note: It already works fine with a working values.yaml.gotmpl
```

Relevant discussions:
https://github.com/roboll/helmfile/issues/2078

**Comment by leotomas837** [comment]
Note: for my use case (with the plugin), of course something like what you can see below does not work, because the value `.Values.mynode.mysos` is generated at runtime by helm: 

```
$> cat helmfile.yaml
releases:
  - name: temp
    chart: .
    namespace: default
    set:
      - name: mynode.myos
      - file: kubectl:///nodes/mynode/jsonpath={.metadata.labels.kubernetes\\\\.io/os}
    values:
      - {{- if eq .Values.mynode.myos "linux" }}       
        # do something
        {{- else if eq .Values.mynode.myos "windows"}}
        # do something else
        {{- end }}
```

**Comment by leotomas837** [comment]
*Closing the idea as not relevant anymore*

For those wanting to use other STATIC values in your values.yaml.gotmpl, see [#2078](https://github.com/roboll/helmfile/issues/2078)

For those wanting to use helm downloader plugins with helmfile, see [#523](https://github.com/helmfile/helmfile/issues/523)

For those wanting to use other values depending on existing resources (as lookup does), please use helmfile go template feature in helmfile.yaml, and function `exec` with a kubectl and a json path format, for example: 

```yaml
...

releases:
  - name: myrelease
    chart: myrepo/mychart
    version: 0.0.0
    namespace: myns
    {{- $os := ((exec "kubectl" (list "get" "node" "dynode" "-o" "jsonpath=\"{.metadata.labels.kubernetes\\.io/os}\"")) | trimPrefix "\"" | trimSuffix "\"") }}
    values:
      - myvalue: {{ if eq $os "linux" }}mylinuxvalue{{ else }}mywindowsvalues{{ end }}
      - values.yaml.gotmpl
...
```
