### DISCUSSION TITLE
readFile with .Release.Name in the path as a part of the release template.

### DISCUSSION THREAD

**Discussion by sf-vorlov** [helmfile/helmfile#530] [Questions]
Hi folks!

I'm converting my existing helm charts to the raw helm chart for all my releases. To keep the templates more or less the same I came up with this solution :

```
releases:
- name: aaaaa
  chart: helmcharts/raw
  values:
  - components/aaaaa/values.yaml
  - {{ toYaml .Values | nindent 4 }} 
  - templates:
    {{- range $_, $file := ( exec "bash" (list "-c" "echo -n components/aaaaa/templates/*yaml") | splitList " " ) }}
    - |
      {{ readFile $file | nindent 6 }}
    {{- end }}

- name: bbbbb
  chart: helmcharts/raw
  values:
  - components/bbbbb/values.yaml
  - {{ toYaml .Values | nindent 4 }}
  - templates:
    {{- range $_, $file := ( exec "bash" (list "-c" "echo -n components/bbbbb/templates/*yaml") | splitList " " ) }}
    - |
      {{ readFile $file | nindent 6 }}
    {{- end }}
```
It works beautifully, but is not very DRY.

So I'm trying to figure out how to template it.  If I do something like this (deliberately removed the toYaml part for now), it does not work:

```
templates:
  common: &common
    {{- $release := `{{ .Release.Name }}`}}
    chart: helmcharts/raw
    values:
    - {{ printf "components/%s/values.yaml" $release }}
    - templates:
      {{- range $_, $file := ( exec "bash" (list "-c" (printf "echo -n components/%s/templates/*yaml" $release )) | splitList " " ) }}
      - |
        {{ readFile $file | nindent 8 }}
      {{- end }}
```
The $release in the range expression is expanded to {{ .Release.Name }}, so the rendering is failing with `error calling readFile: open components/{{: no such file or directory`

Any tips?
