### DISCUSSION TITLE
Error: validation: chart.metadata.version "$NEXT_VERSION" is invalid

### DISCUSSION THREAD

**Discussion by kjq** [helmfile/helmfile#548] [Questions] [answered]
We just moved from roboll/helmfile to the latest version here (0.148.1) and got this error with our first deployment to a fresh EKS cluster:

```
Error: validation: chart.metadata.version "$NEXT_VERSION" is invalid
```

Any quick clues as to what this might be?  It worked before.  

The charts causing the issue use an `ENV` variable for the version like this in the helmfile.yml:

```yaml
  - name: my-chart
    chart: {{ .Values.nexus.repo }}/my-chart
    version: {{ env "MY_CHART_VERSION" }}
```
