### DISCUSSION TITLE
Helmfile github action

### DISCUSSION THREAD

**Discussion by bonddim** [helmfile/helmfile#558] [Ideas]
Purpose to add `helmfile/helmfile-action` to use in workflows.
It should install specified helmfile version (if not installed) and run provided command.

Something like this:
```
- uses: helmfile/helmfile-action@latest
  with:
    version: 'latest' # by default
    command: 'helmfile command'
    args: 'command args'
```
