### DISCUSSION TITLE
adding new manifest to the rendered chart in helmfile release

### DISCUSSION THREAD

**Discussion by KR411-prog** [helmfile/helmfile#571] [Questions]
I have a requirement as below..

We need to include a Kubernetes manifest that gets generated by running script before rendering the chart and then include that manifest during deployment. I tried using Kustomize but if the chart rendered manifests are already present in _templates.yaml file, then I am able to deploy. Otherwise I am not sure how to do that like post-renderer approach.

Tried something like below,
```
`  - name: sample-nginx
    chart: bitnami/nginx
    hooks:
    - events: ["prepare"]         
      showlogs: true
      command: "./sample-helm/sample-nginx/test.sh"
    - events: ["presync"]
      command: "./sample-helm/sample-nginx/test_2.sh"`
```
      
 test.sh contains:
```
 `cat > ./sample-helm/sample-nginx/kustomize/add_resource.yaml << EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-build-robot
automountServiceAccountToken: false
EOF`
```

test_2.sh contains:
```
`#!/bin/bash
tpl="./sample-helm/sample-nginx/kustomize/_templates.yaml"
cat <&0 > "$tpl"`
```

kustomization.yaml contains:
```
resources:
- _templates.yaml
- add_resource.yaml
```
 Any help on this please?
 
(I am thinking may be PR will solve the issue.. https://github.com/helmfile/helmfile/pull/510 ..)
