### DISCUSSION TITLE
Check context is available before applying

### DISCUSSION THREAD

**Discussion by osamamagdy** [helmfile/helmfile#610] [Questions]
We have multiple eks clusters on different accounts on AWS and want to use the same helmfile to deploy on all of them. Before separating them into different accounts we were using this approach 

```
releases:
  # for the prod cluster 
  - name: release-1
    kubeContext: <context of the prod-eks>
    installed: true
    chart: chartrepo
    version: v1.0.0
  # for the qa cluster 
  - name: release-2
    kubeContext: <context of the qa-eks>
    installed: true
    chart: chartrepo
    version: v1.0.0
```
But now when the aws accounts were separated, every account can not list the context of the other cluster and when we try `helm apply` it errors out that it can not get the other context.

How do we approach this? The only way to think of it is to split the helmfiles and only apply each one from its account?
