### DISCUSSION TITLE
Why am I getting this error following the sample guide from the docs?

### DISCUSSION THREAD

**Discussion by kubebn** [helmfile/helmfile#611] [Questions]
This is the sample I want to use:

```
helmDefaults:
  wait: true
  timeout: 600
  recreatePods: true
  force: false

repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

releases:
  - name: external-dns                            
    namespace: external-dns                       
    createNamespace: true                  
    chart: external-dns/external-dns    
    version: 0.13.1                   
    values:
      # Value files passed via --values
      - external-dns.yaml

  - name: cert-manager                        
    namespace: cert-manager                   
    createNamespace: true                  
    chart: jetstack/cert-manager
    version: v1.10.1                 
    set:
      - name: installCRDs
        value: true

  - name: ingress-nginx                      
    namespace: ingress-nginx                 
    createNamespace: true                  
    chart: ingress-nginx/ingress-nginx
    version: 1.5.1               
    values:
      # Value files passed via --values
      - ingress-nginx.yaml

  - name: metrics-server                    
    namespace: kube-system                
    chart: metrics-server/metrics-server
    version: 0.6.2              
```
```
helmfile apply
Adding repo external-dns https://kubernetes-sigs.github.io/external-dns/
"external-dns" has been added to your repositories

Adding repo cert-manager https://charts.jetstack.io
"cert-manager" has been added to your repositories

Adding repo ingress-nginx https://kubernetes.github.io/ingress-nginx
"ingress-nginx" has been added to your repositories

Adding repo metrics-server https://kubernetes-sigs.github.io/metrics-server/
"metrics-server" has been added to your repositories

err: no releases found that matches specified selector() and environment(default), in any helmfile
```

err: no releases found that matches specified selector() and environment(default), in any helmfile - I am bit confused by this error since I am not using any env's.
