### DISCUSSION TITLE
How to get the chart abs path in hook of releases  in helmfile.yaml ?

### DISCUSSION THREAD

**Discussion by tanguofu** [helmfile/helmfile#626] [Questions] [answered]
there is case that i want copy a `job.yaml` into  the chart  to install , and   my helmfile is :
```

releases:
  - name:  aaa
    chart: ../aaa
    namespace: default
    values:
      - ./aaa/values.yaml
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "sh"
        args：
          - “-c”
          - “cp xxx  job.yaml”  
```
So how can i get the abs path of chart `../aaa` , as the chart path maybe flexible placement in some dirs ？

Is it possible to add a global vars such as `.Environment.Name`,  for example  `.Release.chart` to get the chart path relative to `helmfile.yaml`

**Comment by yxxhero** [comment]
@mumoshu I think this is a valuable idea. we can provide more global var to get internal info. WDYT?

**Comment by tanguofu** [comment, marked as answer]
i had found the solution：

the hook will be exec at the `helmfile.yaml` workdir:
```
templates:
  ti_chart_template: &ti_chart_template
    labels:
      helmfile_path: "{{ exec "/bin/bash" (list "-c" "pwd") | trimPrefix (env "PWD") | trimPrefix "/" }}"
```

so the chart path is easy to get in Release by:
```
...
  hooks:
      - events: ["presync"]
        showlogs: true
        command: "/bin/bash"
        args:
          - {{requiredEnv "PWD"}}/script/import.sh
          - '{{`{{.Release.Labels.helmfile_path}}`}}/{{`{{ .Release.Chart}}`}}'

```


```
