### DISCUSSION TITLE
Is the Chart name ignored in Release Templates?

### DISCUSSION THREAD

**Discussion by mmogylenko** [helmfile/helmfile#633] [Questions] [answered]
*Helmfile version*

```bash
helmfile version

▓▓▓ helmfile

  Version            v0.150.0
  Git Commit         "brew"
  Build Date         16 Jan 23 16:34 PST (1 day ago)
  Commit Date        16 Jan 23 16:34 PST (1 day ago)
  Dirty Build        no
  Go version         1.19.5
  Compiler           gc
  Platform           darwin/amd64
```

*Example helmfile*

```yaml
---
helmDefaults:
  createNamespace: false

repositories:
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

templates:
  default:
    chart: jupyterhub/jupyterhub
    version: 1.1.3
    missingFileHandler: Warn
    values:
      - configs/common.yaml
      - configs/{{`{{ .Release.Name }}`}}.yaml

releases:
  - name: dev-hub
    namespace: hub-ns
    #chart: jupyterhub/jupyterhub
    inherit:
      template: default
```

If I try to apply|diff|template I get the following error:

```bash
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: encountered empty chart while reading release "dev-hub" at index 0
```

If we uncomment `chart` in the `dev-hub` release, everything works. 

**Question**: Is that by design?
