### DISCUSSION TITLE
[Fix in v0.151.0] Adding repo when helmfile destroy

### DISCUSSION THREAD

**Discussion by patsevanton** [helmfile/helmfile#636] [Questions]
Hello! Thanks for helmfile!
I have helmfile.yaml
```
helmDefaults:
  wait: true

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: bitnami
    url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
....
```

But helmfile destroy i see
```
Adding repo grafana https://grafana.github.io/helm-charts
"grafana" has been added to your repositories

Adding repo bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
"bitnami" has been added to your repositories
```

Can i disable add repo when helmfile destroy  ?
