### DISCUSSION TITLE
How to override values in environments

### DISCUSSION THREAD

**Discussion by dstockhammer** [helmfile/helmfile#65] [Questions] [answered]
Hi there, not sure if this is a bug or I just completely misunderstand how values are supposed to work.

I have a chart that I want to deploy into multiple environments, which I _assume_ is a relatively common use case. Most of the values are the same, but there are some differences. Here's a trimmed down example:

```yaml
releases:
- name: hello-world
  chart: hello-world
  version: 1.2.3
  values:
    - region: eu-central-1
    - replicas: 3

environments:
  development:
    values:
      - name: xxx

  production:
    values:
      - name: yyy
      - replicas: 9
```

I would expect that the values passed to the chart when deploying would be merged like so:

```yaml
# dev
name: xxx
region: eu-central-1
replicas: 3

# prod
name: yyy
region: eu-central-1
replicas: 9
```

But that's not the case; the values aren't merged at all. After some more trial and error to try and figure this thing out I am now thoroughly confused. Even this doesn't produce the expected result; it looks like no values are passed to the chart at all:

```yaml
releases:
- name: hello-world
  chart: hello-world
  version: 1.2.3

environments:
  development:
    values:
      - name: xxx
      - region: eu-central-1
      - replicas: 3

  production:
    values:
      - name: yyy
      - region: eu-central-1
      - replicas: 9
```

What am I missing? Any help is much appreciated, thanks!

**Comment by jduepmeier** [comment, marked as answer]
Values in the environment blocks and values in the releases block are separated. They are not merged.
But they can be used in the values block. I would separate the values in different files like this.
```yaml
# values-default.yaml
---
region: eu-central-1

# values-development.yaml
---
name: xxx
region: eu-central-1
replicas: 3

# values-production.yaml
---
name: yyy
region: eu-central-1
replicas: 9

# helmfile.yaml
---
environments:
  development: {}
  production: {}

releases:
- name: hello-world
  chart: hello-world
  version: hello-world
  values:
  - values-default.yaml # Contains default values for every environment
  - values-{{ .Environment.Name }}.yaml # This selects the file based on the environment name
```

The environment values can be used in the release value files with `{{ .Values }}`.
Example:
```yaml
# values-default.yaml
---
region: {{ .Values.region }} # This needs an environment values block with region: <region>
