### DISCUSSION TITLE
V1 mode issues (due to no double rendering?)

### DISCUSSION THREAD

**Discussion by SeWieland** [helmfile/helmfile#653] [Questions] [answered]
Hi, and thanks for your effort to make my life in the k8s world a lot easier :)

I'm heavily relying on double rendering in my setup and have no idea how to migrate to V1 easily.

My `service-01.yaml`, `service-02.yaml`, etc helmfiles under `./helmfile.d`  look like this, note the `---` _after_ the bases:

```yaml
bases:
  - ./configuration/environments.yaml

---

releases:
  - name: my-release
    namespace: {{ .Values.namespaces.myRelease }}
    labels:
      tier: static
    chart: ../services/cert-issuer
    version: {{ .Values.versions.myRelease }}
    values:
      - ../services/my-release/values.yaml.gotmpl
```

the environments.yaml looks like this

```yaml
environments:
  development:
    values:
    - ../values/default/general.yaml
    - ../values/development/general.yaml
    - ../values/development/versions.yaml
    kubeContext: dev-cluster
  production:
    values:
    - ../values/default/general.yaml
    - ../values/production/general.yaml
    - ../values/production/versions.yaml
    kubeContext: prod-cluster
```

All values and environment related overwrites were available in the helmfiles.
This worked flawlessly for a very long time now and I would really like to keep our filestructure.
After setting `HELMFILE_V1MODE`, I get `unexpected mapping key` for any templates in the helmfiles.

Renaming them to `service-01.yaml.gotmpl`, `service-02.yaml.gotmpl`, etc did not work either, as it will ignore the files completely.

I suppose this issue should be related to https://github.com/helmfile/helmfile/pull/647.

Any help would be highly appreciated!

_Edit: refined setup description_
