### DISCUSSION TITLE
Some issues with goccy/go-yaml

### DISCUSSION THREAD

**Discussion by SeWieland** [helmfile/helmfile#656] [General]
I would like to share some issues I discovered using the new "goccy/go-yaml" yaml parser that will be the default for V1.

I enabled it using helmfile v0.15.0 and setting `HELMFILE_GOCCY_GOYAML=true` because I use many anchors and aliases and got lots of duplicate key errors.

Sadly, the new yaml parses does not work for me "out of the box" - several issues occured.
I have some modules declared that I render dynamically using the `tpl` function. All these modules behave differently now.

## Example Setup:

I have the following definitions in my values for making my ingress anntotations more DRY, and they make use of some values as well:

```yaml
# The default ingress annotations
.x-default: &default
  nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.authService }}
  nginx.ingress.kubernetes.io/auth-response-headers: Authorization
  acme.cert-manager.io/http01-edit-in-place: "true"
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  cert-manager.io/cluster-issuer: letsencrypt-prod

# Additional "soft" stickyness for performance improvements whenever local session caching is involved 
.x-stickyness: &stickyness
  nginx.ingress.kubernetes.io/affinity: cookie
  nginx.ingress.kubernetes.io/affinity-mode: balanced
  nginx.ingress.kubernetes.io/session-cookie-name: _sticky_session
  nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
  
# Proxy caching can be used for caching static content in nginx
.x-proxy-caching: &caching
  nginx.ingress.kubernetes.io/proxy-buffering: "on"
  
###
# Ingress Annotation Templates
###

ingressAnnotations:
  default:
    << : *default
  caching:
    << : [*default, *caching]
  sticky:
    << : [*default, *stickyness]
```

I use them as follows in my yaml.gotmpl files:

```yaml
ingress:
  enabled: true
  annotations:
    {{ tpl ( .Values.ingressAnnotations.default | toYaml | nindent 4 ) . }}
  rules:
  - host: {{ .Values.domainName }}
    paths:
    {{- range .Values.service.ingressPaths }}
      - {{ . }}
    {{- end }}
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: tls-secret
```

### Merging multiple anchors

With `goccy/go-yaml` I cannot use `.Values.ingressAnnotations.caching` or  `.Values.ingressAnnotations.stickyness` anymore.
With array style anchor merging (`<< : [*default, *stickyness]`) the annotations are not rendered at all **without any error**.

This results in a valid ingress ressource without any annotations + only the diff shows that they are simply not rendered :/

I have to move back to the "old" `%YAML 1.1` declaration syntax (this works)

```yaml
ingressAnnotations:
  default:
    << : *default
  caching:
    << : *default
    << : *caching
  sticky:
    << : *default
    << : *stickyness
``` 

However..

### Some keywords are handeld differently

The merging works again now. But using `.Values.ingressAnnotations.caching` _still results in an error_.
`<$value>: wrong type for value; expected string; got bool`

The debug log shows what happened:
The rendered annotations:

```yaml 
annotations:
  nginx.ingress.kubernetes.io/auth-url: https://myAuthService
  nginx.ingress.kubernetes.io/auth-response-headers: Authorization
  cert-manager.io/cluster-issuer: letsencrypt-prod
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  nginx.ingress.kubernetes.io/proxy-buffering: on
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
``` 

**The quotes of my "on" got stripped and I cannot bring them back**.

I have not yet found any way to work around this issue. The `tpl` function will remove the quotes and any effort to bring them back did not work yet.
But it led to yet another headache.

### Quotes won't work at all

I'm pretty desperate, so I tried the following:

```yaml
.x-proxy-caching: &caching
  nginx.ingress.kubernetes.io/proxy-buffering: '{{ quote "on" }}'
```

So that when I render the string through `tpl` it should just quote the given string, but nope.
I tested quite a bit and it turned out that helmfile will always exit with `error calling tpl: template: stringTemplate:16: unexpected "\\" in operand` for _any function that needs a string input_ in that constellation..
My templates for some common secrets like `'{{ printf "%s%s" .Values.keyVault "secret-ref" | fetchSecretValue }}'` are all broke with goccy/go-yaml..

## Conclusion

The switch to the new yaml parser will most certainly cause a lot of headaches in the community..
And I still do not know if I can use a lot of my "modules" I built for dynamic templating at all in future releases.

I guess the issues I discovered are not fixable in this project, and probably a won't fix in the goccy/go-yaml project.
However I hope these findings will help other users to make the switch to V1 a bit easier.

_Edit:_ minor clarifications
