### DISCUSSION TITLE
readFile doesn't work as expected

### DISCUSSION THREAD

**Discussion by yuvalsimon** [helmfile/helmfile#696] [Questions] [answered]
I try to seperate some common sections of a few helmfiles and put them in a base helmfile, but I have some issues with separating templates. I followed a [tutorial ](https://jorgesnotebook.com/blog/how-to-set-up-your-kluster-with-helmfle/)from 2 years ago and I guess things have changed since then.
I have this files:
helmfile.yaml:
```
{{ readFile "base.yaml" }}

releases:
  - <<: *defaultTmpl
    name:  "grafana"
    chart: "grafana/grafana"
    namespace: "monitoring"
    version: "3.2.5"
```
environments.yaml:
```
environments:
  ci:
    values:
    - cluster_domain: mydomain
```
base.yaml:
```
bases:
  - environments.yaml

---
templates:
  defaultTmpl: &defaultTmpl
    valuesTemplate:
    - {{ .Environment.Name }}.values.yaml
    - cluster_domain: {{ .Values.cluster_domain }}
```

When I run `helmfile build -f helmfile.yaml -e ci` it doesn't recognize `.Environment.Name` and `.Values.cluster_domain`. If I put the content of base.yaml in helmfile.yaml it does work as expected. If I use `{{ tpl (readFile "base.yaml") . }}` it recognizes `.Environment.Name` but not `.Values.cluster_domain`. Is it the expected behavior?

the following is working - I just put the content of base.yaml in helmfile.yaml:
```
bases:
  - environments.yaml

---
templates:
  defaultTmpl: &defaultTmpl
    valuesTemplate:
    - {{ .Environment.Name }}.values.yaml
    - cluster_domain: {{ .Values.cluster_domain }}

releases:
  - <<: *defaultTmpl
    name:  "grafana"
    chart: "grafana/grafana"
    namespace: "monitoring"
    version: "3.2.5"
```

Output when running `helmfile build -f helmfile.yaml -e ci --debug`:
```
rocessing file "helmfile.yaml" in directory "."
changing working directory to "/app"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{ci map[] map[]}, overrode=<nil>
first-pass uses: &{ci map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: 
 1: 
 2: releases:
 3:   - <<: *defaultTmpl
 4:     name:  "grafana"
 5:     chart: "grafana/grafana"
 6:     namespace: "monitoring"
 7:     version: "3.2.5"

could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: reading document at index 1: yaml: unknown anchor 'defaultTmpl' referenced
error in first-pass rendering: result of "helmfile.yaml.part.0":
 0: 
 1: 
 2: releases:
 3:   - <<: *defaultTmpl
 4:     name:  "grafana"
 5:     chart: "grafana/grafana"
 6:     namespace: "monitoring"
 7:     version: "3.2.5"

first-pass produced: &{ci map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {ci map[] map[]}
second-pass rendering result of "helmfile.yaml.part.0":
 0: bases:
 1:   - environments.yaml
 2: 
 3: ---
 4: templates:
 5:   defaultTmpl: &defaultTmpl
 6:     valuesTemplate:
 7:     - {{ .Environment.Name }}.values.yaml
 8:     - cluster_domain: {{ .Values.cluster_domain }}
 9: 
10: releases:
11:   - <<: *defaultTmpl
12:     name:  "grafana"
13:     chart: "grafana/grafana"
14:     namespace: "monitoring"
15:     version: "3.2.5"

err: failed to read helmfile.yaml: reading document at index 2: yaml: line 7: did not find expected key
changing working directory back to "/app"
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 2: yaml: line 7: did not find expected key
```

**Comment by yxxhero** [comment]
please post the log by adding --debug @yuvalsimon

**Reply by yuvalsimon** [reply]
I added the output to the question.
I read about the new feature of `inherit` and it seems to work much better than templates and to solve this case. However I ran into another problem which seems like a bug.
The following template should work but it doesn't (it's taken from the [docs](https://helmfile.readthedocs.io/en/latest/writing-helmfile/#:~:text=templates%3A%0A%20%20default%3A,0%0A%20%20inherit%3A%0A%20%20%20%20template%3A%20default) - it produces an error having an empty `chart` field (which should be taken from the template)
```
templates:
  default:
    chart: stable/{{`{{ .Release.Name }}`}}
    namespace: kube-system

releases:
- name: heapster
  version: 0.3.2
  inherit:
    template: default
- name: kubernetes-dashboard
  version: 0.10.0
  inherit:
    template: default
```

The output when running `helmfile build -f inherit.yaml --debug`:
```
processing file "inherit.yaml" in directory "."
changing working directory to "/app"
first-pass rendering starting for "inherit.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "inherit.yaml.part.0":
 0: templates:
 1:   default:
 2:     chart: stable/{{ .Release.Name }}
 3:     namespace: kube-system
 4: 
 5: releases:
 6: - name: heapster
 7:   version: 0.3.2
 8:   inherit:
 9:     template: default
10: - name: kubernetes-dashboard
11:   version: 0.10.0
12:   inherit:
13:     template: default

first-pass produced: &{default map[] map[]}
first-pass rendering result of "inherit.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "inherit.yaml.part.0":
 0: templates:
 1:   default:
 2:     chart: stable/{{ .Release.Name }}
 3:     namespace: kube-system
 4: 
 5: releases:
 6: - name: heapster
 7:   version: 0.3.2
 8:   inherit:
 9:     template: default
10: - name: kubernetes-dashboard
11:   version: 0.10.0
12:   inherit:
13:     template: default

err: error during inherit.yaml.part.0 parsing: encountered empty chart while reading release "heapster" at index 0
changing working directory back to "/app"
in ./inherit.yaml: error during inherit.yaml.part.0 parsing: encountered empty chart while reading release "heapster" at index 0
```
