### DISCUSSION TITLE
double render issue

### DISCUSSION THREAD

**Discussion by yxxhero** [helmfile/helmfile#707] [General]
From https://github.com/helmfile/helmfile/issues/700. We still need `double render` or another method that can pre-handle environment values.

example:
```
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}
    values:
      - values.yaml.gotmpl
---
environments:
  default:
    values:
      - base.yaml
      - override.yaml
```

if no double render. we can't render the release correctly. because no environment values.

/cc @mumoshu @xiaomudk

**Comment by mumoshu** [comment]
@yxxhero Can you just swap the parts so that the environments are provided to the releases part?

```
environments:
  default:
    values:
      - base.yaml
      - override.yaml

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}
    values:
      - values.yaml.gotmpl
```
