### DISCUSSION TITLE
How to check whether a release label exists before using it?

### DISCUSSION THREAD

**Discussion by btxbtx** [helmfile/helmfile#718] [Questions] [answered]
You can try code like this:

```gotmpl
{{- if Release.Labels.myLabel }}
...
{{- end }}
```

But, if `myLabel` is not defined in the release, this will error out with:

```
failed to render values files "path/to/gotmpl": failed to render [path/to/gotmpl], because of template: stringTemplate:1:47: executing "stringTemplate" at <.Release.Labels.myLabel>: map has no entry for key "myLabel"
```

I've tried creating and overriding commonLabels, i.e.,

```
commonLabels:
  myLabel: "default"
  
  releases:
  - name: some-release
    labels:
      myLabel: "override"
    chart: my-chart
    values:
      - path/to/gotmpl
```

Which would give all releases the label, then I can compare `Release.Labels.myLabel` to the value I'm expecting, but it doesnt seem like `commonLabels` can be overridden.

So, how can I check whether `Release.Labels.myLabel` exists?

**Comment by yxxhero** [comment]
you can try to use `get` template func. https://helmfile.readthedocs.io/en/latest/templating_funcs/#get

**Reply by btxbtx** [reply]
I am running into the same problem. 

A sample way to reproduce:
``` yaml
  releases:
  - name: some-release
    chart: my-chart
    values:
      - path/to/gotmpl
```

In the `path/to/gotmpl`, you could just try:
```gotmpl
  {{- if (get .Release.Labels.myLabel "") }}
  {{- end }}
```

It will fail because `.Release.Labels.myLabel` is not defined.

**Reply by yxxhero** [reply]
Please provide whole helmfile configuration.

**Reply by btxbtx** [reply]
Here is a full working example:

```
./
├── helmfile.yaml
└── label.gotmpl
```

helmfile.yaml
```yaml
releases:
  - name: my-release
    chart: traefik/traefik
    values:
      - label.gotmpl
```

label.gotmpl
```yaml
{{- if (get .Release.Labels.myLabel "") }}
deployment:
    enabled: true
{{ else }}
deployment:
    enabled: false
{{- end }}
```

run `helmfile template`.

Desired:
`deployment.enabled` is set to false.

Actual:
```
in ./helmfile.yaml: failed to render values files "label.gotmpl": failed to render [label.gotmpl], because of template: stringTemplate:1:20: executing "stringTemplate" at <.Release.Labels.myLabel>: map has no entry for key "myLabel"
```

**Reply by yxxhero** [reply]
@btxbtx please see: https://helmfile.readthedocs.io/en/latest/builtin-objects/

**Reply by btxbtx** [reply]
@yxxhero I'm not sure what you're trying to tell me.  I don't see something on that page that helps

**Reply by yxxhero** [reply]
.Release.Labels.myLabel? where did you find the .Release?

**Reply by yxxhero** [reply]
```
Environment: The information about the environment. This is set by the --environment flag. It has several objects inside of it:
Environment.Name: The name of the environment
Values: Values passed into the environment.
StateValues: alias for Values.
Namespace: The namespace to be released into
```

**Reply by btxbtx** [reply]
helmfile.yaml
```yaml
releases:
  - name: my-release
    chart: traefik/traefik
    labels:
      myLabel: "foo"
    values:
      - label.gotmpl
```

label.gotmpl
```go
{{- if .Release.Labels.myLabel }}
{{- end }}
```

Works, but

helmfile.yaml
```yaml
releases:
  - name: my-release
    chart: traefik/traefik
    values:
      - label.gotmpl
```

label.gotmpl
```go
{{- if .Release.Labels.myLabel }}
{{- end }}
```

doesn't.  It will fail with

```
in ./helmfile.yaml: failed to render values files "label.gotmpl": failed to render [label.gotmpl], because of template: stringTemplate:1:15: executing "stringTemplate" at <.Release.Labels.myLabel>: map has no entry for key "myLabel"
```

**Reply by btxbtx** [reply]
https://helmfile.readthedocs.io/en/latest/builtin-objects/#release-template-built-in-objects

`.Release.Labels` is listed.

**Reply by yxxhero** [reply]
```
{{- if (get "Labels.myLabel" nil .Release) }}
deployment:
    enabled: true
{{ else }}
deployment:
    enabled: false
{{- end }}
```

**Reply by btxbtx** [reply]
Did that template for you?  Using the same code, I get:

```
in ./helmfile.yaml: failed to render values files "label.gotmpl": failed to render [label.gotmpl], because of template: stringTemplate:1:8: executing "stringTemplate" at <get "Labels.myLabel" nil .Release>: error calling get: unexpected type(map[string]string) of value for key "myLabel": it must be either map[string]interface{} or any struct
```

**Reply by yxxhero** [reply]
oh. I need a whole example to reproduce your issue.

**Reply by btxbtx** [reply]
The two files I shared above ([this comment](https://github.com/helmfile/helmfile/discussions/718#discussioncomment-5166389)) is a complete example.  You only need those two files.  Just create those files in a directory and run `helmfile template`

**Reply by btxbtx** [reply]
You can try your code out like this:

helmfile.yaml
```yaml
releases:
  - name: my-release
    chart: traefik/traefik
    values:
      - label.gotmpl
```

label.gotmpl
```go
{{- if (get "Labels.myLabel" nil .Release) }}
{{- end }}
```

`helmfile template`
