### DISCUSSION TITLE
Release values inheritance

### DISCUSSION THREAD

**Discussion by Vince-Chenal** [helmfile/helmfile#726] [Ideas]
# Context

Hello,

We have started experimenting with helmfile in our company and intend to use it on a fairly large scale, and we think that for some of our more complex use cases, we have found a possible usability improvement to reduce duplication.
It appears others have also expressed a similar need ([here](https://github.com/roboll/helmfile/issues/2078) or [here](https://github.com/roboll/helmfile/issues/388#issuecomment-1026685709)) in the past, and we’d like to know if our approach makes sense for helmfile and ensure that we have a full understanding of the impact of our proposed changes.

# Problem

We understand that today the layering mechanism allows for reusing previously defined values.

Example:
```
environments:
  default:
    values:
    - value1: somevalue
---
environments:
  default:
    values:
    - value2: {{ .Values.value1 }}
---
releases:
  - name: my-release
    chart: my-chart
    values:
      - finalValue: {{ .Values.value2 }}
```

Some of our more complex use cases require _many_ layers, which makes the corresponding helmfiles quite verbose and unwieldy. We therefore would like your opinion on the proposed improvement, which we believe to be fairly intuitive and concise.

# Proposition

While generating the temporary values files ([here](https://github.com/helmfile/helmfile/blob/main/pkg/state/state.go#L2759-L2817)) it would be feasible to load the rendered yamls in memory (in [RenderedValues](https://github.com/helmfile/helmfile/blob/fc027d153885da1fa3e975c400dba43f29abd9b0/pkg/state/state.go#L134)) so that we can inherit the "previously defined values".

## More complex example:

helmfile.yaml
```
environments:
  dev:
    values:
    - defaults.yaml
  production:
    values:
    - defaults.yaml
    - production-values.yaml
---
releases:
  - name: my-release
    chart: my-chart
    values:
      - common.yaml.gotmpl
      - common-{{ .Environment.Name }}.yaml.gotmpl
      - values.yaml.gotmpl
    missingFileHandler: Debug
```

defaults.yaml
```
projectName: foo
region: bar
domain: .io
```
production-values.yaml
```
domain: .com
```

common.yaml.gotmpl
```
application_url: {{ .Values.projectName }}-{{ .Values.environment }}.{{ .Values.region }}.{{ .Values.domain }}
```

common-production.yaml.gotmpl
```
application_url: {{ .Values.projectName }}{{ .Values.domain }}
```

values.yaml.gotmpl
```
conf: |
    config {
      field1 = 1
    }

    url = {{ .Values.application_url }}
```

The goal here is to have some defaults that define the common way for building the application URL and allow overriding it on a per-environment logic. We could generalize this logic per project, per env, per region...

Here's what we would get depending on the environment:
dev:
```
❯ helmfile template --environment dev .
Building dependency release=my-release, chart=my-chart
Templating release=my-release, chart=my-chart
---
# Source: my-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  foo.json: |
    config {
      field1 = 1
    }
    url = foo-dev.bar.io
```
production:
```
# Source: my-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  foo.json: |
    config {
      field1 = 1
    }
    url = foo.com
```
# Implementation
We have provided a demonstration implementation in [this PR](https://github.com/helmfile/helmfile/pull/725) (we don’t expect it to be mergeable as-is) and we’d be happy to discuss some more about it.

If it makes sense, a similar could be also be used for the `environments` blocks.

**Comment by mumoshu** [comment]
@Vince-Chenal Hey! Thanks a lot for this detailed write-up. It did help me understand the context of this feature request.

To be sure, could you clarify this to be about adding a way to pass **inputs** to a release values template file `values.yaml.gotmpl`, where the **inputs** are `some values generated from environment values`- Is that correct?

**Reply by Vince-Chenal** [reply]
Hey,

Yes it's all about feeding generated values (derived from environment values) to `values.yaml.gotmpl` template.

What we propose here is to offer an alternative to `n successive environment layering blocks` with `n ordered entries in the releases' values section`.

Example with layering:
```
environments:
  default:
    values:
      - values1.yaml
---
environments:
  default:
    values:
      - values2.yaml # requires values from values1.yaml
---
environments:
  default:
    values:
      - values3.yaml # requires values from values2.yaml
---
environments:
  default:
    values:
      - values4.yaml # requires values from values3.yaml
---
...
---
releases:
  - name: my-release
    chart: my-chart
    values:
      - values.yaml.gotmpl
    missingFileHandler: Debug
```

Example with our proposal:
```
environments:
    default:
    ...
---
releases:
  - name: my-release
    chart: my-chart
    values:
      - values1.yaml
      - values2.yaml # requires values from values1.yaml
      - values3.yaml # requires values from values2.yaml
      - values4.yaml # requires values from values3.yaml
      - ...
      - values.yaml.gotmpl
    missingFileHandler: Debug
```

**Reply by mumoshu** [reply]
@Vince-Chenal Hey! Thank you so much for your explanation, and thank you for your interests @hileef @miguelgmcs @clemcvlcs. I understand your motivation now.

My only concern would be **ambiguity**- With the new feature, every `values` entry can depend on zero or more values.yaml and values.yaml.gotmpl files present in earlier values entries.

In contract, it's currently "any values.yaml and values.yaml.gotmpl files can depend on environment values" which is very simple to reason about.

**As a project maintainer, I often get forced to do random debug sessions to figure out why one's helmfile.yaml and values don't work as they intended.** Any new ambiguity makes my experience in the scenario worse. 

And if you're (or going to be) a platform-team person who is responsible for providing support to your colleagues, you might end up in the same situation as me.

So- can we somehow make it more explicit?

What if we introduced a new field that enables you to compose a declarative pipelined generator of release values?

```yaml
releases:
  - name: my-release
    chart: my-chart
    pipeline:
    - name: v2
      render:
        template: values2.yaml.gotmpl
        with:
        - file: values1.yaml
    - name: v3
      render:
        template: values3.yaml.gotmpl
        # Note that each `with` entry can be either `file` or `output`.
        # The former loads a yaml file and make it available via .Values within the template
        # The latter makes outputs from another pipeline step via .Values
        with:
        - output: v2
    - name: all
      render:
        template: values.yaml.gotmpl
        with:
        - output: v1
        - output: v2
        - output: v3
    # This appends the output of "all" step to release's "values"
    - append:
        from: all
        to: values
```

The context behind my proposal is that, I hope you distinguish:

- "file" vs "template" (See "with.file" and "with.output" above)
- "output" vs "input" (See "name" and "with.output" above)
- "intermediate" values vs "final" values (See "append" above)

I personally like everything EXCEPT the last part:

```
    # This appends the output of "all" step to release's "values"
    - append:
        from: all
        to: values
```

This `append` might be unintuitive- This is for backward-compatibility. You'd still use "values" as a way to merge multiple values and values templates into one. This new "pipeline.append" dynamically generates the last "values" entry, so that it's merged with other values as usual.

WDYT?
If you have more explicit and intuitive syntaxes in your mind, I'd love to hear your idea!
Thank you!
