### DISCUSSION TITLE
add skipCrds to helmDefaults structure

### DISCUSSION THREAD

**Discussion by jouve** [helmfile/helmfile#729] [Ideas]
hello,

due to specifities of crds, I prefer to manage them out of helm/helmfile (specific workflow, handled differently depending on the charts (some in crds/, some in templates/, ...).

I add `--skip-crds` to `helmfile` but it would be nice if the options could be added to helmfile.yaml:

```yaml
helmDefaults:
  skipCrds: true
  ...
```
