### DISCUSSION TITLE
Is it possible to define Helm variables in a separate file?

### DISCUSSION THREAD

**Discussion by j-land** [helmfile/helmfile#730] [Questions]
I have a use case where I want to define a single Helm variable and use it in both the helmfile and a [values files template](https://helmfile.readthedocs.io/en/latest/#refactoring-helmfileyaml-with-values-files-templates). In this example, the variable in question is `$ciliumVersion`.

`helmfile.yaml`:
```
{{ tpl (readFile "helm-variables.yaml.gotmpl") . }}

releases:
  - chart: cilium/cilium
    version: {{ $ciliumVersion }}
    name: cilium
    namespace: kube-system
    values:
    - cilium-values.yaml.gotmpl
```

`cilium-values.yaml.gotmpl`:
```
{{ tpl (readFile "helm-variables.yaml.gotmpl") . }}

image:
  repository: 'quay.io/cilium/cilium'
  useDigest: false
  tag: {{ printf "v%s" $ciliumVersion }}
  pullPolicy: IfNotPresent
```

`helm-variables.yaml.gotmpl`:
```
{{- $ciliumVersion := "1.11.12" }}
```

Is this workflow possible? If so, what am I missing?
