### DISCUSSION TITLE
Add possibility to upgrade `appVersion` field

### DISCUSSION THREAD

**Discussion by ngnix** [helmfile/helmfile#734] [Ideas]
Hi helmfile team!

There are different approaches to writing charts for deploying applications into k8s, often devops teams choose a way to support one chart for deploying any stateless applications.

Unfortunately, the `version` and `appversion` chart fields cannot be changed via helm without modifying the charts.

This problem causes certain difficulties when deploying many applications through one chart.

An example of how I would like to see a solution to this problem in helmfile:

```
releases:
  - name: example-app
    namespace: app
    chart: stateless-chart
    version: 1.12.3 # it's are chart version
    appVersion: {{ env "CI_COMMIT_TAG" }} # it's git tag version, for example `3.5.7`
```
Here is example for `helm ls command output`

``` helm ls -a
NAME            NAMESPACE     REVISION  UPDATED     STATUS        CHART                             APP VERSION
example-app  stage               386                                   deployed    stateless-chart-1.0.0     3.5.7
```

This method allow modify label  `app.kubernetes.io/version` to current release number.

Thanks!
