### DISCUSSION TITLE
Multiple releases using the same Chart version results in "Error: link error: cannot rename ... Access is denied."

### DISCUSSION THREAD

**Discussion by gevalo1** [helmfile/helmfile#748] [Questions]
OS: `Windows 10 Pro, 21H2`
Helmfile: `0.151.0`
Helm: `3.11.2`

---

We have a bunch of releases in a Helmfile using the same Chart & version, with different values each time.

The command we use to deploy this Helmfile looks like
```
helmfile -f helmfile.d/environment.yaml sync
```

This has been working fine for a long time, however recently I've been starting to encounter errors like this:
```
STDERR:
  Error: link error: cannot rename C:\Users\...\AppData\Local\Temp\helm\repository\{chart}-{version}.tgz4029608154 to C:\Users\...\AppData\Local\Temp\helm\repository\{chart}-{version}.tgz: rename C:\Users\...\AppData\Local\Temp\helm\repository\{chart}-{version}.tgz4029608154 C:\Users\...\AppData\Local\Temp\helm\repository\{chart}-{version}.tgz: Access is denied.
```

If I change the command to
```
helmfile --concurrency 1 -f helmfile.d/environment.yaml sync
```
Then it all works fine.
But again, it used to work fine without the `concurrency` flag for over a year before.

It seems that multiple renames to the same destination file are happening at the exact same time, causing this error? Not sure why I'm only encountering this issue now though.

---

#### Example Helmfile
(`{repo}`, `{chart}` & `{version}` are the same for each release in this example, `{namespace}` is usually different)
```
repositories:
- name: ___
  url: ___
  username: ___
  password: ___

helmDefaults:
  kubeContext: ___

releases:
- name: ___
  chart: {repo}/{chart}
  version: {version}
  namespace: {namespace}
  createNamespace: true
  values:
    - ../___/___.yaml
    - ../___/___/___.yaml
    - ../___/___/___.yaml

- name: ___
  chart: {repo}/{chart}
  version: {version}
  namespace: {namespace}
  createNamespace: true
  values:
    - ../___/___.yaml
    - ../___/___/___.yaml
    - ../___/___/___.yaml

... lots more of the above ...
```

---

Do you perhaps have any idea for something I could check still or could this be a concurrency issue in Helmfile (or Helm?) after all?
