### DISCUSSION TITLE
Add options to retry failed helm release

### DISCUSSION THREAD

**Discussion by zephyros-dev** [helmfile/helmfile#757] [Ideas]
# Description
- While Helm already support DAG aware installation ordering, sometimes it's not enough since the resources may not be available even after the dependent helm release are marked as success.
- An example: I tried to setup `external-secrets`, and a `ClusterSecretStore` along with it using the raw helm manifest
```
repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: main
    url: https://bedag.github.io/helm-charts/
releases:
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: "0.8.0"
  - name: external-secrets-config
    namespace: external-secrets
    needs:
      - external-secrets/external-secrets
    chart: main/raw
    version: "2.0.0"
    disableValidationOnInstall: true
    values:
      - resources:
          - apiVersion: external-secrets.io/v1beta1
            kind: ClusterSecretStore
            metadata:
              name: cluster-secret-store
```
- Even though I set the dependencies for the `external-secrets-config` to `external-secrets` release, the `external-secrets-config` still fails due to a component in `external-secrets` not being ready even after its helm release status is marked as success. A re-apply does not work since the manifest doesn't change between releases, which force me to do a manual sync to make a new release. Since the components is ready by the time I do the manual sync, the `external-secrets-config` works.

# Proposed solution
- Ideally the root helm release should only return success when all of its components are ready, but I think this can be solved in helmfile by adding a retry option. For example, flux2 can do this: https://github.com/fluxcd/flux2/discussions/743?sort=new

# Reference
- Previous issue in the old repos: https://github.com/roboll/helmfile/issues/1249
