### DISCUSSION TITLE
How can I render raw Go expression into a .gotmpl values file?

### DISCUSSION THREAD

**Discussion by thenayr** [helmfile/helmfile#775] [Questions]
Example:

`Helmfile`
```
releases:
  - name: test
    namespace: test
    chart: test/test
    version: 1
    createNamespace:  true
    values:
      - values.yaml.gotmpl
```
`values.yaml.gotmpl`
```
service:  "{{ printf "{{ .service }}" }}"
```

Rendered template should look like this:

```
service: "{{.service}}
```

Instead it still evaluates the expression and ends up as

```
service: ''
```
