### DISCUSSION TITLE
Migrating pre-0.150 release templates to 0.152.0

### DISCUSSION THREAD

**Discussion by jjungnickel** [helmfile/helmfile#779] [Questions] [answered]
I'm having trouble refactoring our existing releases to the latest helmfile release. I've reduced the existing helmfile definition to a minimal case:
```yaml
templates:
  default:
    missingFileHandler: Warn
    valuesTemplate:
      - fullnameOverride: '{{`{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}`}}'
    values:
       - "../apps/{{`{{ .Release.Name }}`}}.yaml.gotmpl"
    labels:
      app: "{{`{{ .Release.Name }}`}}"

releases:
  - name: my-app
    inherit:
      - template: default
```

This fails as follows:
```> HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile  template --debug
processing file "helmfile.yaml.gotmpl" in directory "."
changing working directory to "<obfuscated>"
rendering starting for "helmfile.yaml.gotmpl.part.0": inherited=&{default map[] map[]}, overrode=<nil>
rendering result of "helmfile.yaml.gotmpl.part.0":
 0: templates:
 1:   default:
 2:     missingFileHandler: Warn
 3:     valuesTemplate:
 4:       - fullnameOverride: '{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}'
 5:     values:
 6:        - "../apps/{{ .Release.Name }}.yaml.gotmpl"
 7:     labels:
 8:       app: "{{ .Release.Name }}"
 9: 
10: releases:
11:   - name: my-app
12:     inherit:
13:       - template: default
14: 

merged environment: &{default map[] map[]}
changing working directory back to "<obfuscated>"
in ./helmfile.yaml.gotmpl: failed executing release templates in "helmfile.yaml.gotmpl": failed executing templates in release "helmfile.yaml.gotmpl"."my-app": failed executing template expressions in release "my-app".values[0] = "fullnameOverride: "{{ .Values | get (printf \"%s.releaseName\" .Release.Name) .Release.Name }}"
": template: stringTemplate:1: unexpected "\\" in operand
```

I'd appreciate any hints in the right direction.

**Comment by yxxhero** [comment]
@jjungnickel is 0.150.0 ok?

**Reply by jjungnickel** [reply]
Unfortunately, no. I had to rewrite the helmfile a bit to get it to parse again until encountering the same error. Quoting the valuesTemplate expression (i.e. ```{{`{{ .Values ... }}`}}``` would simply pass the template as a literal value to helm, so that didn't work, either.

The rewritten helmfile:
```yaml
templates:
  default:
    missingFileHandler: Warn
    valuesTemplate:
      - fullnameOverride: '{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}'
    values:
     - apps/{{ .Release.Name }}.yaml.gotmpl
    labels:
      app: '{{ .Release.Name }}'

releases:
  - name: my-app
    inherit:
      template: default
    chart: bedag/raw
```

and the result with 0.150.0:
```
> HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile  template --debug
processing file "helmfile.yaml" in directory "."
changing working directory to "<omitted>"
merged environment: &{default map[] map[]}
changing working directory back to "<omitted>"
in ./helmfile.yaml: failed executing release templates in "helmfile.yaml": failed executing templates in release "helmfile.yaml"."my-app": failed executing template expressions in release "my-app".values[0] = "fullnameOverride: "{{ .Values | get (printf \"%s.releaseName\" .Release.Name) .Release.Name }}"
": template: stringTemplate:1: unexpected "\\" in operand
```

This looks like some kind of nested quoting issue that I can't quite grok yet

**Comment by yxxhero** [comment]
@jjungnickel please give me a full example. Thanks very much.

**Reply by jjungnickel** [reply]
Given (as `helmfile.yaml.gotmpl`):

```yaml
environments:
  default:
    values:
      - my-app:
          releaseName: foo
---
templates:
  default:
    missingFileHandler: Warn
    valuesTemplate:
      - fullnameOverride: '{{`{{ .Release.Name }}`}}'
    labels:
      app: "{{`{{ .Release.Name }}`}}"
repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts
releases:
  - name: my-app
    chart: bedag/raw
    inherit:
      - template: default

```
this renders fine with 0.152.0: 
```
> HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile build
filepath: helmfile.yaml.gotmpl
helmBinary: helm
environments:
  default:
    values:
    - my-app:
        releaseName: foo
repositories:
- name: bedag
  url: https://bedag.github.io/helm-charts
releases:
- chart: bedag/raw
  missingFileHandler: Warn
  name: my-app
  labels:
    app: my-app
  values:
  - fullnameOverride: my-app
  valuesTemplate:
  - fullnameOverride: my-app
templates:
  default:
    missingFileHandler: Warn
    labels:
      app: "{{ .Release.Name }}"
    valuesTemplate:
    - fullnameOverride: "{{ .Release.Name }}"
renderedvalues:
  my-app:
    releaseName: foo
```
but, if we replace the `fullnameOverride` in `valuesTemplate` with
``` 
- fullnameOverride: '{{`{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}`}}'
```
this fails:
```
> HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile build
in ./helmfile.yaml.gotmpl: failed executing release templates in "helmfile.yaml.gotmpl": failed executing templates in release "helmfile.yaml.gotmpl"."my-app": failed executing template expressions in release "my-app".values[0] = "fullnameOverride: "{{ .Values | get (printf \"%s.releaseName\" .Release.Name) .Release.Name }}"
": template: stringTemplate:1: unexpected "\\" in operand)
```
