### DISCUSSION TITLE
helmfile deps and charts with subcharts

### DISCUSSION THREAD

**Discussion by jouve** [helmfile/helmfile#785] [General]
Hello,

in an airgapped environment,  with the following:
```
releases:
- chart: oci://proxy-of-docker-io/bitnamicharts/postgresql
  name: postgresql
  version: 12.x
```
and bitnami/postgresql having the following dependencies in its Chart.yaml:
```
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.2.4
```

`helmfile deps` will correctly download from the proxy,

extract the tgz, (the tgz. already contains the `common` dependency bundled in `charts/` folder but

helmfile runs `helm dep up` in the extracted folder which will fail to access docker.io to download `common` tgz (because airgapped)

as the common tgz is already in charts/, it would work if `repository` was removed:
```
dependencies:
- name: common
  tags:
  - bitnami-common
  version: 2.2.4
```
will produce:
```
Saving 1 charts
Dependency common did not declare a repository. Assuming it exists in the charts directory
Deleting outdated charts
```

Another issue is that it breaks the promise of immutability of helm charts (I also encoutered the issue where the dependency was not there anymore on its repo).

The issue also happens with using the alternative syntax:
```
repositories:
- name: bitnami
  url: containers.devops.prod.fdj.fr/bitnamicharts
  oci: true
releases:
- chart: bitnami/postgresql
  name: postgresql
  version: 12.x
```

Finally I'm not sure why helmfile is extracting the chart and running `helm dep up` inside (no kustomization, or adding a subchart).
