### DISCUSSION TITLE
`helmfile fetch --output-dir charts` and `helmfile sync` does not use fetched charts

### DISCUSSION THREAD

**Discussion by taemon1337** [helmfile/helmfile#790] [Questions]
I am building a standalone `helmfile` docker image, looks something like this:

```
FROM ghcr.io/helmfile/helmfile:canary

WORKDIR /helm
ENV TARGET_ENV=local

COPY helmfile.yaml ${WORKDIR}/helmfile.yaml
COPY helm.d ${WORKDIR}/helm.d
COPY charts ${WORKDIR}/charts
COPY env ${WORKDIR}/env

RUN helmfile -e ${TARGET_ENV} deps
RUN helmfile -e ${TARGET_ENV} fetch --output-dir ${WORKDIR}/charts

ENTRYPOINT ["helmfile"]
CMD ["sync", "-e", "${TARGET_ENV}", "--skip-deps"]
```

The `charts/` directory has some custom local charts in it and the image builds as expected, adding a folder structure for each fetched chart defined in a helmfile.

The `charts` directory has the following folder structure for each fetched chart:

```
charts/
  replicator-system/
    kubernetes-replicator/
      mittwald/
        kubernetes-replicator/
          2.7.3/
            kubernetes-replicator/
  <release-namespace>/
    <release-name>/
      <repository-name>/
        <chart-name>/
          <chart-version>/
            <chart>/
```

The issue is that when I run the image (offline), `helmfile` is still trying to download the chart as it doesn't appear to be able to find it.  The `helmfile.yaml` will reference it like `<repository-name>/<chart-name>` but will never seem to use the fetched chart, I assume because it isn't pointing at the `charts` directory path.

I've tried many number of ways to refer to the chart or fetch the chart to a different location but none seem compatible.

I was considering using `gotmpl` to set a `CHARTS_DIR` env var so in "online mode" it could download the charts from the specified repo and then `fetch` would store them locally and could be used later to install them in "offline mode", is this possible?

Am I missing something?  The offline docs just say "Once you download all required charts into your machine, you can run `helmfile sync --skip-deps` to deploy your apps" so maybe you cannot use `fetch` to download them, I'm not sure though that would make sense.

The top level helmfile is:
```
helmfiles:
  - path: helm.d/*/helmfile.yaml
    values:
      - {{ requiredEnv "WORKDIR" }}/env/{{ .Environment.Name }}.yaml
```
and one of the more specific ones is:
```
repositories:
  - name: mittwald
    url: https://helm.mittwald.de
    
releases:
  - name: kubernetes-replicator
    condition: replicator.enabled
    chart: mittwald/kubernetes-replicator
    version: 2.7.3
    namespace: replicator-system
    missingFileHandler: Warn
    values:
      - values.yaml
      - values-{{ .Environment.Name }}.yaml
```
