### DISCUSSION TITLE
values file does not exist in "."

### DISCUSSION THREAD

**Discussion by pelegz** [helmfile/helmfile#792] [Questions]
Hello,

I'm trying to simply install a chart from my private repository hosted on Bitbucket.
Helmfile version: v0.152.0

helmfile.yaml:

```
helmDefaults:
  createNamespace: true
  timeout: 600
  atomic: true

repositories:
- name: my-app
  url: git+https://username@bitbucket.org/C-B4/my-app@helm?ref=my_branch

releases:
- name: my-app
  namespace: dev2
  chart: my-app/my-app
  values:
    - ./values.dev2.yaml
```
Getting:

`helmfile apply --wait`

```
Adding repo my-app git+https://username@bitbucket.org/C-B4/my-app@helm?ref=my_branch
"my-app" has been added to your repositories

in ./helmfile.yaml: failed processing release my-app: values file matching "./values.dev2.yaml" does not exist in "."
```

I know for certain that values.dev2.yaml are present in the helm folder in the my_branch branch.

I've tried:
```
  values:
    - ./values.dev2.yaml
 
  values:
    - ./helm/values.dev2.yaml
   
  values:
   - values.dev2.yaml
```

Not sure what's the relative path it's looking at.

What could be the issue here? 

Thanks
