### DISCUSSION TITLE
Support for merging values from releases files and other helmfiles

### DISCUSSION THREAD

**Discussion by bsgrigorov** [helmfile/helmfile#800] [Ideas]
Can we add support to merge values of maps from different files e.g.:

helmfile.yaml
```
releases:
- name: test-chart
  namespace: test
  chart: my-chart
  version: 0.0.2
  values:
  - environments/{{ .Environment.Name }}/test-chart.values.yaml.gotmpl

---
releases:
- name: test-chart2
  namespace: test
  chart: my-chart
  version: 0.0.1
  values:
  - environments/{{ .Environment.Name }}/test-chart.values.yaml.gotmpl
```
This only produces 1 release instead of merging them.
