### DISCUSSION TITLE
Chart dependencies version templating

### DISCUSSION THREAD

**Discussion by j-mercier** [helmfile/helmfile#805] [Ideas]
I have a release that requires different version of the same dependency for different environments. Currently dependencies are declared in the chart.yaml file, but it is not possible to template the version.
Would it be possible to declare those dependencies in the release section of helmfile.yaml so that we could use a different version if needed for a given environment?

Example:
Environment: dev
Dependency: dep1
Version 1

Environment: prod
Dependency: dep1
Version 2

**Comment by yxxhero** [comment]
@j-mercier please provider more details.

**Reply by j-mercier** [reply]
Chart.yaml
```
...
dependencies:
  - name: chart1
    version: 1.7.0
    repository: x
  - name: chart1
    version: 1.8.0
    repository: xxx
 ```
 
helmfile.yaml
```
environments:
  dev:
    values:
       - chart1-version: 1.8.0
 prod:
    values:
       - chart1-version: 1.7.0

...

``` 

How can i template the char1-version into the Chart.yaml. That would be convenient if we could do it in the release section:
```
releases:
  - name: xx
    namespace: xx
    chart: .
    values:
      - values.yaml.gotmpl
    dependencies:
      - name: chart1
        version: {{ .Values.chart1-version}}
        repository: x
```
