### DISCUSSION TITLE
pre-install script

### DISCUSSION THREAD

**Discussion by woodcockjosh** [helmfile/helmfile#806] [Ideas]
I would like a pre-install script to install crds before I run helmfile diff so that the command does not fail. thanks

my script looks something like this : 
```shell
helm show crds "$1" > crds.raw.yaml
sed 's/apiVersion\: apiextensions/\-\-\-\napiVersion\: apiextensions/g' crds.raw.yaml > crds.yaml
kubectl apply -f crds.yaml
rm crds.yaml crds.raw.yaml
```

and I want to run it like this: 
```yaml
  - chart: charts/certs
    name: certs
    namespace: infrastructure
    hooks:
      - pre-install: ./pre-install-crds.sh charts/certs
```
