### DISCUSSION TITLE
[Feature] Support functions written by KCL to mutate or validate manifests for Helmfile

### DISCUSSION THREAD

**Discussion by Peefy** [helmfile/helmfile#827] [Ideas]
I was very glad to find the Helmfile project and browse all its documents. I found that it coincided with what we wanted to do.

Specifically, we have just opened our domain language project [KCL](https://github.com/KusionStack/KCLVM), which is specifically used for configuration writing and policy verification in cloud-native and Kubernetes scenarios. However, it is obviously not enough to use only one language for Kubernetes configuration management until we find Helmfile. We want to develop KCL plug-ins for Helmfile to write KCL functions to mutate or validate manifests, so we want to keep in touch with you through this discussion.

In addition, we have completed initial KCL plugin support for KPT, Helm, and Kustomize.

+ [Kustomize KCL Plugin](https://github.com/KusionStack/kustomize-kcl)
+ [Helm KCL Plugin](https://github.com/KusionStack/helm-kcl)
+ [KPT KCL Plugin](https://github.com/KusionStack/kpt-kcl-sdk)

The documents of KCL are [here](https://kcl-lang.io/). Looking forward to receiving your feedback. ❤️

**Comment by yxxhero** [comment]
@Peefy please provider more details.

**Reply by Peefy** [reply]
> @Peefy please provider more details.

❤️ Thank you for your reply. I will prepare some details as soon as possible, including user stories and the scheme design in the discussion.

**Reply by yxxhero** [reply]
I saw you in helm. 👍

**Comment by Peefy** [comment]
I have opened an issue https://github.com/KusionStack/KCLVM/issues/519 to describe the overall user story and design. At present, it is still relatively elementary. I want to share it for you to see @yxxhero .

**Comment by Peefy** [comment]
I have added some use cases for both helmfile-kcl-plugin about mutation and validation. @yxxhero If you are interested, you can also participate in the discussion. Thank you.

**Reply by yxxhero** [reply]
where is the link of helmfile-kcl-plugin so that I can review the content?

**Reply by Peefy** [reply]
> where is the link of helmfile-kcl-plugin so that I can review the content?

Sorry, I forgot to put links.

User Story and Design: https://github.com/KusionStack/KCLVM/issues/519
Examples: https://github.com/KusionStack/krm-kcl/pull/2

**Reply by yxxhero** [reply]
@Peefy I think it's very cool. If you need my help. please free to ping me.

**Comment by yxxhero** [comment]
@Peefy I think we can see the transformer logic in the Charyify project. currently, it only supports Kustomize project.

**Comment by Peefy** [comment]
Hi @yxxhero. I have preliminarily implemented the helmfile-kcl-plugin. One possible example is as follows (`helmfile.yaml`):

```yaml
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
  transformers:
  # Use KCL Plugin to mutate or validate Kubernetes manifests.
  - apiVersion: krm.kcl.dev/v1alpha1
    kind: KCLRun
    metadata:
      name: "set-annotation"
      annotations:
        config.kubernetes.io/function: |
          container:
            image: docker.io/kcllang/kustomize-kcl:v0.1.2
    spec:
      source: |
        [resource | {if resource.kind == "Deployment": metadata.annotations: {"managed-by" = "helmfile-kcl"}} for resource in option("resource_list").items]
```

However, I've got the following errors:

```bash
$ helmfile apply

Adding repo prometheus-community https://prometheus-community.github.io/helm-charts
"prometheus-community" has been added to your repositories

in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize build /var/folders/lq/b_20m8117pq2p_dk4n0x37d80000gp/T/chartify4017396382/prometheus/prom-norbac-ubuntu/prometheus --output /var/folders/lq/b_20m8117pq2p_dk4n0x37d80000gp/T/chartify4017396382/prometheus/prom-norbac-ubuntu/prometheus/all.patched.yaml

OUTPUT:
  Error: external plugins disabled; unable to load external plugin 'KCLRun']
```

Is there a way to add the `--enable-alpha-plugins` flag to the kustomzie command in the helmfile tool?
