### DISCUSSION TITLE
Get the current kubeContext of the environment

### DISCUSSION THREAD

**Discussion by SeWieland** [helmfile/helmfile#829] [Questions] [answered]
Hi!

I was wondering if it's possible to dynamically retrieve the current kubeContext of the active environment.

Example using the imaginary "`{{.Environment.KubeContext}}`" in some hooks for kubectl (provisioning a very small yaml file):

`environments.yaml`
```yaml
environments:
  dev:
    values:
    - ../values/default.yaml
    - ../values/dev.yaml
    kubeContext: dev-cluster
  prod:
    values:
    - ../values/default.yaml
    - ../values/prod.yaml
    kubeContext: prod-cluster
```

`helmfile.yaml`
```yaml
bases:
  - ./environments.yaml

---
releases:
  - name: myService
    namespace: my-ns
    installed: true
    chart: mychart
    version: "1.2.3"
    values:
      - ../services/my-service/values.yaml.gotmpl
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./custom-storage-class.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "./custom-storage-class.yaml"
          - "--context"
          - "{{`{{.Environment.KubeContext}}`}}"
```

Can this be done differently somehow already? I know that there is a "`{{.Release.KubeContext}}`" available, however it is empty if not set directly on the release itself.

Thanks for any suggestions on the issue!
