### DISCUSSION TITLE
exec function passing arguments to shell script

### DISCUSSION THREAD

**Discussion by kiran312-byte** [helmfile/helmfile#833] [Questions] [answered]
I am trying to pass value from Environment values.yaml to shell script to get the version of server using curl command. The value is passed on to the script since I can echo first argument in script but curl does not recognize ${endpoint} and returns null. I can also echo $endpoint (returns "serverInfo") . Is there something I am missing

**helmfile.yaml:**
```
{{ $version := exec "./get-version.sh" (list "{{ .Environment.Values.env.urlendpoint }}" ) }}
environments:
  default:
    values:
    -./environments/values.yaml
```

**values.yaml**
```
env:
  urlendpoint: "serverInfo"
```

**get-version.sh**
```
endpoint=$1
curl -s -L [https://testserver.com/${endpoint}](https://testserver.com/$%7Bendpoint%7D) # returns version of the server
```

**Comment by yxxhero** [comment]
@raje312 please provider more info and logs. so I can reproduce your issue and then help you.

**Reply by kiran312-byte** [reply]
I think I know the root cause:
parameter {{ .Environment.Values.env.urlendpoint }}  is not resolved before passing

$1 in script is still {{ .Environment.Values.env.urlendpoint }}    but end of the helmfile execution, it gets resolved

**Comment by yxxhero** [comment]
@raje312 please format your code.

**Reply by kiran312-byte** [reply]
I formatted the code (used add code option). I could not add tabs

**Comment by yxxhero** [comment]
helmfile.yaml:
```
{{ $version := exec "./get-version.sh" (list .Environment.Values.env.urlendpoint) }}
environments:
  default:
    values:
    -./environments/values.yaml
```

**Reply by kiran312-byte** [reply]
I tried that before. I get error
./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:5:120: executing "stringTemplate" at <.Environment.Values.env.urlendpoint>: map has no entry for key "env"

**Reply by yxxhero** [reply]
@raje312 please give me a full example. thanks.

**Reply by kiran312-byte** [reply]
```
environments:
  default:
    values:
    - /environments/values.yaml
    secrets:
    - /secrets/secret-properties.yaml
 
{{ $version := exec "./get-version.sh" (list "{{ .Environment.Values.env.urlendpoint }}" ) }}

releases:
  - name: config-setup
    namespace: helmtest
    wait: true
    waitForJobs: true
    timeout: 1200
    labels:
      name: config-setup-label
    values:
      - /test-{{ $version | trim }}-config-value.yaml.gotmpl
    secrets:
      - /secrets/secret-properties.yaml
```

**Reply by kiran312-byte** [reply]
Above is my helmfile and I am trying to get the the version from script file and use it in values so that it picks up gotmpl file corresponding to server version

**Comment by yxxhero** [comment, marked as answer]
```
environments:
  default:
    values:
    - /environments/values.yaml
    secrets:
    - /secrets/secret-properties.yaml
---
 
{{ $version := exec "./get-version.sh" (list .Values.env.urlendpoint ) }}

releases:
  - name: config-setup
    namespace: helmtest
    wait: true
    waitForJobs: true
    timeout: 1200
    labels:
      name: config-setup-label
    values:
      - /test-{{ $version | trim }}-config-value.yaml.gotmpl
    secrets:
      - /secrets/secret-properties.yaml
```
