### DISCUSSION TITLE
output of helmfile hook script execution

### DISCUSSION THREAD

**Discussion by kiran312-byte** [helmfile/helmfile#839] [Questions]
Is there a way I can capture output of script in helmfile hook in a variable and pass it on to the values. I am trying to get the version of the server in script get-version.sh and use the version value to pick appropriate config-values.yaml.gotmpl file
  

```
- name: config-setup
    namespace: helmtest
    chart: ../config-cli
    installed: true
    hooks:
    **-** events: ["prepare"]
      showlogs: true
      command: "./get-version.sh"
      args: ["{{`{{.Environment.Values.env.baseUrl}}`}}","{{`{{.Environment.Values.env.adminuser}}`}}","{{`{{.Environment.Values.env.adminpassword}}`}}" ]
    labels:
      name: config-setup
    values:
      - /environment/{{ **#output of the script version here#** }}-config-values.yaml.gotmpl
```
