### DISCUSSION TITLE
Force flags / Get flags inside hook

### DISCUSSION THREAD

**Discussion by nboyet** [helmfile/helmfile#842] [Questions]
Hello,

I use helmfile to sync in different environment.

I would like to know if there is a way to force the flag '-i' after checking which '.Environment.Name' it is ?

I've tested hooks, but there is no way (or maybe I've missed it) to know which flags are sent or to force a flag.

Do you have a solution for this ? I've seen it was discussed in the [issue 1767 from the old repo](https://github.com/roboll/helmfile/issues/1767)

**Comment by yxxhero** [comment]
@nboyet could you provide some example?

**Comment by nboyet** [comment]
Yes of course.

If I do :

```shell
helmfile sync -e prod -f my_app.yaml
```
The sync will be done in prod environment, without confirmation. 

I've checked to prevent this with hooks like this : 

```yaml
  hooks:
  - events:
    - prepare
    showlogs: true
    command: ../scripts/check-prod.sh
    args:
    - "{{`{{ .Environment.Name }}`}}"
    - "{{`{{ .HelmfileCommand }}`}}"
```

Which check if the environment is prod and if the command is a "sync". If both are true, it warns the user. 
But it's only a warn and the sync will be done in any cases.

So I would like a way to force the "--interactive" flag. 

BTW, I don't want to use alias such as 
```shell
alias helmfile="helmfile -i"
```
:)
