### DISCUSSION TITLE
How to install a chart from GitHub

### DISCUSSION THREAD

**Discussion by kjq** [helmfile/helmfile#843] [Questions] [answered]
If there is a chart I would like to install from GitHub can I do this with Helmfile?

https://github.com/tektoncd/operator/tree/main/chart

Additionally, is there a way for me to use Helmfile to apply raw manifests (i.e. operators, etc.) so that I can manage deployments from one place?

**Comment by yxxhero** [comment]
git::https://github.com/cloudposse/helmfiles.git@releases/echo-server/helmfile.yaml?ref=master

**Comment by kjq** [comment]
Using the repository above, what is an example of how to pull that in using Helmfile or if that is even possible...

I should note, that chart is just a regular Helm chart, not a Helmfile.

**Comment by kjq** [comment, marked as answer]
This is what ended up working for me:

```yaml
repositories:
- name: tekton
  url: git+https://github.com/tektoncd/operator.git@chart?ref=v0.64.0

releases:
  - name: tekton-operator
    chart: "tekton/tekton-operator"
    namespace: pipeline
    installed: {{ env "TEKTON_INSTALLED" | default .Values.installed }}
    cleanupOnFail: true
    disableValidationOnInstall: true
    labels:
      operator: true
      tier: cluster
    values:
      - values.gotmpl
```
