### DISCUSSION TITLE
Remote template function

### DISCUSSION THREAD

**Discussion by tomassatka** [helmfile/helmfile#845] [Ideas]
Hi @mumoshu 

I would have a question/feature request. Here is the gist:

I am a member of centralised team supporting other teams to create and deploy helm charts containing their applications. Would like to provide common function/template that other teams could simply use. 

To be more precise something like this to be shared:
```
releases:
{{- range .Values.releases }}
  - name: {{ .name }}
  {{- if contains "$" .namespace }}
    namespace: {{ .namespace | replace "$RELEASE_BRANCH" (requiredEnv "RELEASE_BRANCH") }}
  {{- else }}
    namespace: {{ .namespace }}
  {{- end }}
    chart: {{ .chart }}
  {{- if (hasKey . "version")}}
    {{- if hasPrefix "$" .version }}
    version: {{ requiredEnv (.version | replace "$" "") }}
    {{- else }}
    version: {{ .version }}
    {{- end }}
  {{- end }}
  {{- if (hasKey . "needs") }}
    needs: 
    {{- range .needs }}
      - {{ . }}
    {{- end }}
  {{- end }}    
    values: 
      - "env/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.values.yaml.gotmpl"
{{- end }}
```

then the clients would only use something like plain helmfile and path supports reading from remote GitHub-releases: 
```
helmfiles:
  - path: ../../tools/helmfile-commons/helmfiles/releases.yml
    values:
      - env/{{ .Environment.Name }}/releases.yaml
```

and refer to releases as declarative lists in release.yaml per environment:
```
releases:
  oauth2-proxy:
    name: oauth2-proxy
    namespace: website-dev
    version: 3.5.0
    chart: bitnami/oauth2-proxy

  website:
    name: website
    namespace: website-dev
    version: $WEBSITE_VERSION
    chart: techx/website
    needs:
      - oauth2-proxy 
```

Now the issue is that the values supplied per release is relative to subhelmfile not to original helmfile. And to add them all would result into one large merge (I assume). So that is not something I would like. So the question would be if using this approach if there is a way how the subhelmfile could be able to read value files parent relative to parent helmfile.

Other approach that I saw was proposed for such common functions is `readFile`. However readFile supports only reading of local files and not from remote repo release. 

Any suggestion or idea how to proceed?

**Comment by tomassatka** [comment]
As stated the second option goes more to the direction that is mentioned here: https://github.com/roboll/helmfile/issues/1146

So we can apply something like:
```
{{ tpl (readFile "../../tools/helmfile-commons/helmfiles/releases.yml") . }}
```
But as said limitation here is the readFile that can read only local files not the remote ones..

**Comment by jouve** [comment]
this is already supported with the [go-getter](https://github.com/hashicorp/go-getter) syntax (I use it with git for example):
``` 
helmfiles:
  - path: git::https://domain/repo.git@helmfile.yaml?ref=master
    values:
    - ...
```
