### DISCUSSION TITLE
Error when installing Traefik 23.0.1 but installing 20.8.0 is fine

### DISCUSSION THREAD

**Discussion by lucj** [helmfile/helmfile#848] [Questions]
Hello,
I'm not sure what has changed on Traefik side regarding CRDs, but I cannot install Traefik 23.0.1 with the following Helmfile:

```
repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik
    labels:
      app: traefik
    chart: traefik/traefik
    version: ~23.0.1
```

It complains because of CRDs not existing:

```
Adding repo traefik https://traefik.github.io/charts
"traefik" has been added to your repositories

Comparing release=traefik, chart=traefik/traefik
in ./helmfile.yaml: command "/Users/luc/.rd/bin/helm" exited with non-zero status:

PATH:
  /Users/luc/.rd/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: traefik (7 bytes)
  5: traefik/traefik (15 bytes)
  6: --version (9 bytes)
  7: ~23.0.1 (7 bytes)
  8: --namespace (11 bytes)
  9: traefik (7 bytes)
  10: --detailed-exitcode (19 bytes)
  11: --color (7 bytes)
  12: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "traefik-dashboard" namespace: "traefik" from "": no matches for kind "IngressRoute" in version "traefik.io/v1alpha1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  ********************
  	Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "traefik-dashboard" namespace: "traefik" from "": no matches for kind "IngressRoute" in version "traefik.io/v1alpha1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error
```

The installation of Traefik 23.0.1 directly with Helm is working fine:

```
helm install my-traefik traefik/traefik --version 23.0.1

NAME: my-traefik
LAST DEPLOYED: Fri May  5 10:04:40 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Traefik Proxy v2.10.1 has been deployed successfully
on default namespace !
```

Also, installing a previous version of Traefik with the following Helmfile went just fine though:
```
repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik
    labels:
      app: traefik
    chart: traefik/traefik
    version: ~20.8.0
```

Any ideas what I'm missing ?

**Comment by yxxhero** [comment]
@lucj What are the differences between CRDS in versions 23.0.1 and 20.8.0?

**Comment by lucj** [comment]
@yxxhero I'm sorry I have no idea, I just noticed this new release cannot be installed with Helmfile :(

**Comment by yxxhero** [comment]
@lucj Ok. I will find the key issue. wait for my feedback. thanks so much.

**Comment by lucj** [comment]
Hello @yxxhero,
did you manage to reproduce the problem ? Also, do you think this is an issue or should this stay in the discussion ?
Thanks a lot for your help

**Reply by yxxhero** [reply]
@lucj I am busy recently. I will see what happened in a few days. Thanks so much.

**Comment by yxxhero** [comment]
@lucj there are new CRDs in 23.0.1. so when `helmfile diff`, it can't find the newest `CRD`. so it failed. https://github.com/traefik/traefik-helm-chart/tree/v22.0.1#upgrading-crds

**Comment by lucj** [comment]
hi @yxxhero in fact I have the error when installing Traefik (helm chart version 23.0.1), I mean I do not try to upgrade from 20.8.0 to 23.0.1.
Thanks a lot for your help

**Comment by yxxhero** [comment]
@lucj I review the code of the Traefik chart. start with [v23.0.1](https://github.com/traefik/traefik-helm-chart/releases/tag/v23.0.1), the crds are generated by the Kustomize.

```bash
kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/
```
```
 # Apply resources from a directory containing kustomization.yaml - e.g. dir/kustomization.yaml
  kubectl apply -k dir/
```

**Comment by lucj** [comment]
@yxxhero thanks a lot, so this  mean this can be done though a preinstall hook in the helmfile ?

**Comment by yxxhero** [comment]
@lucj It's valuable to make an effort in doing that.

**Comment by lucj** [comment]
Hi @yxxhero, I confirm this is working fine with the following helmfile:
```
repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik
    labels:
      app: traefik
    chart: traefik/traefik
    version: ~23.0.1
    hooks:
    - events: ["prepare"]
      showlogs: true
      command: "/bin/bash"
      args:
      - "-ec"
      - |
        kubectl apply --server-side --force-conflicts -k https://github.com/traefik/traefik-helm-chart/traefik/crds/
```
Thanks a lot for your help
