### DISCUSSION TITLE
Releases inherit of map deprecation warning

### DISCUSSION THREAD

**Discussion by bvanelli** [helmfile/helmfile#849] [Questions] [answered]
I cannot find any source, discussion or related issue to this deprecation warning:

```
releases[].inherit of map({Template:database Except:[]}) has been deprecated and will be removed in v0.152.0. Wrap it into an array: yaml: unmarshal errors:
  line 25: cannot unmarshal !!map into []state.Inherit
```

What is it even supposed to mean? I tried refactoring the templates to be a list but without any success.

**Comment by yxxhero** [comment]
Wrap it into an array.

**Comment by bvanelli** [comment, marked as answer]
I just released this is silly, as the documentation has been updated since the first time I had this issue:

Do the following change:

### From

```
releases:
  - name: heapster
    version: 0.3.2
    inherit:
      template: default
```

### To

```
releases:
  - name: heapster
    version: 0.3.2
    inherit:
      - template: default
```
