### DISCUSSION TITLE
config item `insecureSkipTLSVerify` unavailable

### DISCUSSION THREAD

**Discussion by Git4Mark** [helmfile/helmfile#888] [Questions] [answered]
i want to skip tls verify, so i set the insecureSkipTLSVerify: true, but i got errror
helmfile version: 0.154.0
helmfile.yaml
```
helmDefault:
  insecureSkipTLSVerify: true
releases:
- name: demo
  chart: cnp/demo
  version: 0.1.0
```
error msg:
```
line 2: field insecureSkipTLSVerify not found in type state.HelmSpec
```
