### DISCUSSION TITLE
Helmfile apply excessive memory consumption

### DISCUSSION THREAD

**Discussion by dougalrea** [helmfile/helmfile#912] [Questions]
We are using helmfile to deploy to an EKS cluster in AWS.

We are seeing that the number of charts in the helmfile is proportional to the memory used when running `helmfile apply`.

In some circumstances, when deploying a helmfile with up to 50 charts, we are seeing memory usage (on the client running helmfile, not within Kubernetes) hit up to 7GB. This feels like a lot, but we'd like to confirm whether this is expected for helmfile.

If it is to be expected, what is `helmfile` doing to require so much memory?

**Comment by yxxhero** [comment]
@dougalrea thanks for your feedback. could you provider some screenshots or some logs?

**Reply by dougalrea** [reply]
We're running the `helmfile apply` from within a Lambda function. We allocate an amount of memory to the function. We can see that the function successfully starts running `helmfile apply` but then the host kills the command (`return code: -9`) and we can see that the failed Lambda function has used all available memory. The logs aren't particularly useful in this instance as the command is killed.

We get the following log which indicates Lambda OOM ([see here](https://aws.plainenglish.io/3-mind-blowing-aws-lambda-errors-and-workarounds-for-them-449c123835e3#:~:text=Runtime%20exited%20with%20error%3A%20signal%3A%20killed)):
`Error: Runtime exited with error: signal: killed`
 
We also see the concluding log from Lambda confirming full memory capacity was reached:
```
REPORT RequestId: a228b8e8-1c8a-4fa7-90b5-6a9a7e2155de	Duration: 1904.64 ms	Billed Duration: 1905 ms	Memory Size: 3500 MB	Max Memory Used: 3500 MB
```
After a little more testing it seems that even with higher memory allocations, up to eg 7 GB, `Max Memory Used` doesn't exceed around 3.75 GB for a helmfile of 50 charts, but the deployment still fails (likely due to a separate bottleneck at that point). Even then - is it expected that almost 4GB memory would be required for a helmfile of 50 charts?

**Reply by yxxhero** [reply]
@dougalrea I don't think that helmfile requires so much memory. maybe this is a bug.

**Reply by yxxhero** [reply]
@dougalrea what's the format of your chart? local dir or helm chart like `raw/raw`?

**Reply by dougalrea** [reply]
Not sure what you mean by `raw/raw`? We save the helmfile to a local dir available within AWS Lambda with a format the contents like the following:

```
helmDefaults:
    timeout: 600

releases:
- chart: <chart-name>
    name: <service-name>
    namespace: <namespace>
    version: X.Y.Z
    wait: <true/false>
- chart: <chart-name-2>
    ... etc

repositories:
- name: <repo-name>
    url: <repo-url>
```

**Reply by yxxhero** [reply]
```
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus. # raw/raw here.
  set:
  - name: rbac.create
    value: false
```
