### DISCUSSION TITLE
Sub helm releases not rendered using nested states

### DISCUSSION THREAD

**Discussion by anirbandas18** [helmfile/helmfile#934] [Questions] [answered]
Hi,

I am using a main helmfile with a sub helm file using the **helmfiles** directive of helmfile within the parent helmfile. Below are excerpts from my helmfiles. 

### Setup:

`sub-helmfile.yaml`

```
---
environments:
  qa:
    missingFileHandler: Error
    # values eligible for overriding by dependant charts
    values:
      - service:
         feature1:
           enabled: false
         feature2:
           enabled: true
---

# repositories defined but omitted for brevity

# common labels defined but omitted for brevity

releases:
  - name: service
    namespace: service
    chart: service
    version: 0.1.0
    labels:
      priority: 1
      layer: 0
    values:
      - ../values/base.yaml.gotmpl
      - ../values/secrets.yaml.gotmpl
      # pass down values to be overridden with tree structure
      - service:
          feature1:
            enabled: {{ $.Values.service.feature1.enabled }}
          feature2:
            enabled: {{ $.Values.service.feature2.enabled }}
```

`main-helmfile.yaml`

```
---
environments:
  qa:
    missingFileHandler: Error
---

# repositories defined but omitted for brevity

# common labels defined but omitted for brevity

# releases defined but omitted for brevity since they are directly not related to sub-helmfile

# reference from main-helmfile to sub-helmfile

helmfiles:
  - path: git::https://gitlab-server/team/project.git@helmfile.d/sub-helmfile.yaml?ref=main
    selectors:
      - layer=0
    values:
      - ../overrides-values.yaml.gotmpl

```

`overrides-values.yaml.gotmpl`

```

service:
  feature1:
     enabled: true
  feature2:
     enabled: false

```

`Values.service` tree is taken from the file referenced through the option --state-values-file when running helmfile template command to be passed in the go template syntax within the `main-helmfile.yaml`.

### Observations:

Releases from `main-helmfile.yaml` is rendered when running `helmfile --debug --state-values-file ../resources/facts.yaml -e live template --output-dir ../out/live` but no releases from `sub-helmfile.yaml` are not rendered.

### Objective:

Is this behaviour expected by design or do I need to configure something more in order to make the `sub-helmfile.yaml` render its releases?
