### DISCUSSION TITLE
helmfile environments

### DISCUSSION THREAD

**Discussion by wisp888** [helmfile/helmfile#953] [Questions]
templates/configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfgmap2
data:
  test: {{ .Values.test }}
```
-----------------------------------------------
values.yaml
```
test: default
```
-----------------------------------------------
values-gz.yaml
```
test: gz
```
-----------------------------------------------
helmfile.yaml
```
helmBinary: /sbin/helm

---
environments:
  default:
    values:
    - "/data/helm_test/wisp/values.yaml"
  gz:
    values:
    - "/data/helm_test/wisp/values-gz.yaml"

---
releases:
  - name: wisp
    namespace: default
    chart: /data/helm_test/wisp
    values:
    - "/data/helm_test/wisp/values.yaml"
    missingFileHandler: Error
```
-----------------------------------------------
when run "helmfile -e gz template"
```
Templating release=wisp, chart=/data/helm_test/wisp
---
# Source: wisp/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wisp-cfgmap2
data:
  test: default
```
why "test" do not eq "gz" ??

**Comment by yxxhero** [comment]
```
helmBinary: /sbin/helm

---
environments:
  default:
    values:
    - "/data/helm_test/wisp/values.yaml"
  gz:
    values:
    - "/data/helm_test/wisp/values-gz.yaml"

---
releases:
  - name: wisp
    namespace: default
    chart: /data/helm_test/wisp
    values:
    # here. you can use go template.
    - "/data/helm_test/wisp/values.yaml"
    missingFileHandler: Error
```
