### DISCUSSION TITLE
[Feature] Adding a new template function for arithmetic and quantity for resources

### DISCUSSION THREAD

**Discussion by mighty1231** [helmfile/helmfile#975] [Ideas]
## Objective

Some arithemetics may make easier to manage resources.

## Design

1. `add`, `sub`, `div`, `mul`, `max`, `min` for basic arithmetics
2. `parseQuantity` receives quantity string, generates integer.

    -  `{{ parseQuantity "129M" }}` should generate 129000000

3. `evalQuantity` receives the integer value with unit, generates quantity string.

   - `{{ evalQuantity 129000000 "M" }}` should generate 129M

## Usecase

Use them with some arithemetic operations, assume I have total memory 160Gi available, and apply for a release with 1/3 of it.

```yaml
# helmfile.yaml
environments:
  default:
    totalResourceMemory: 160Gi
---
releases:
   - name: ...
     values:
       - main:
           resources:
              requests:
                memory: {{ parseQuantity .Values.totalResourceMemory | div 3 | evalQuantity "M" }}
```

## Reference

[kubernetes quantity syntax](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/)
