### DISCUSSION TITLE
Using inherit templates and adding values in the release

### DISCUSSION THREAD

**Discussion by MO2k4** [helmfile/helmfile#990] [Questions]
Hi 🤘

i am currently in the process of moving my helmfile to the latest version and i want to use release templates and i am some kind of stuck

i want to use something like this:

```yaml
templates:
  default:
    namespace: demo-{{.Environment.Name}}
  api:
    inherit:
    - template: default
    values:
    - values.yaml.gotmpl
    - values-api.yaml.gotmpl

releases:
  - name: rest-api-{{.Environment.Name }}
    chart: rest-api-{{.Values.chartBase}}
    inherit:
    - template: api
    values:
    - env:
      SOME_ENV_VAR: value
```

and with this, i overwrite the template values. is there a way to not overwrite the values and instead to append certain values to the default in the release? Do i use this correctly or am i completely on the wrong way?

**Comment by yxxhero** [comment]
@mumoshu you are the best one to answer the issue.

**Comment by MO2k4** [comment]
I've found a solution inside a bug -.-

```yaml
templates:
  default: &default
    namespace: demo-{{.Environment.Name}}
  api:
    <<: *default
    valuesTemplate:
      - values.yaml.gotmpl
      - values-api.yaml.gotmpl

releases:
  - name: rest-api-{{.Environment.Name }}
    chart: rest-api-{{.Values.chartBase}}
    inherit:
    - template: api
    values:
    - env:
      SOME_ENV_VAR: value
```
