### ISSUE TITLE
Access Release Name

### ISSUE THREAD

**Issue by adecchi-2inno** [helmfile/helmfile#1000]
### Operating system

Mac

### Helmfile Version

0.156.0

### Helm Version

v3.12.3

### Bug description

When try to use the following syntax:
`{{ if eq "dev" .Environment.Name }}{{ .Release.Name | trimSuffix "microservices-" }}{{ else }}{{ .Environment.Name }}{{ end }}
` 

At **namespace** I got the error:

`executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type *state.EnvironmentTemplateData`

### Example helmfile.yaml

```
  - name: ms-api-fe
    <<: *argocd-apps
    namespace: '{{ if eq "dev" .Environment.Name }}{{ .Release.Name | trimSuffix "ms-" }}{{ else }}{{ .Environment.Name }}{{ end }}'
    disableValidation: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "backend"
```

### Error message you've seen (if any)

`executing "stringTemplate" at <.Release.Name>: can't evaluate field Release in type *state.EnvironmentTemplateData`

### Steps to reproduce

n/a

### Working Helmfile Version

0.156.0

### Relevant discussion

n/a

**Comment by yxxhero** [comment]
https://helmfile.readthedocs.io/en/latest/builtin-objects/

**Comment by adecchi-2inno** [comment]
@yxxhero thank you for your response.

That configuration is what I used to configure:
`
namespace: '{{ if eq "dev" .Environment.Name }}{{ .Release.Name | trimSuffix "ms-" }}{{ else }}{{ .Environment.Name }}{{ end }}'`

But It does not work.

**Comment by yxxhero** [comment]
`.Release.Name` where do you find this? @adecchi-2inno

**Comment by adecchi-2inno** [comment]
@yxxhero you are right! It is not defined :)

**Comment by adecchi-2inno** [comment]
@yxxhero 

In this example, it is defined for example:

```
releases:
  - name: microservices-api-fe
    <<: *argocd-apps
    namespace: '{{ if eq "dev" .Environment.Name }}{{ .Release.Name | trimSuffix "ms-" }}{{ else }}{{ .Environment.Name }}{{ end }}'
    disableValidation: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "backend"
```

but does not work

**Comment by adecchi-2inno** [comment]
I could Fixed using single quote and tilde.
Example:

```
releases:
  - name: ms-api-fe
    <<: *argocd-apps
    namespace: '{{ `{{ if eq "dev" .Environment.Name }}{{ .Release.Name }}{{ else }}{{ .Environment.Name }}{{ end }}` }}'
    disableValidation: true
```
