### ISSUE TITLE
`include-needs` also includes transitive release-dependencies

### ISSUE THREAD

**Issue by pathob** [helmfile/helmfile#1003]
### Operating system

Docker

### Helmfile Version

0.156.0

### Helm Version

3.9.0

### Bug description

As stated in the [Helmfile CLI documentation](https://helmfile.readthedocs.io/en/latest/#selectors-and-needs), `--include-needs` should only include direct dependencies whereas `--include-transitive-needs` would include direct and transitive dependencies.

I'm a super newbie to Go and in my projects we are currently only using `--include-transitive-needs`, but I've already wondered how `--include-needs` is supposed to work after looking at the code [here](https://github.com/helmfile/helmfile/blob/cbb6561a8651601e5f47adafe06ff2fe1688d38a/pkg/app/app.go#L190), [here](https://github.com/helmfile/helmfile/blob/cbb6561a8651601e5f47adafe06ff2fe1688d38a/pkg/app/app.go#L256), [here](https://github.com/helmfile/helmfile/blob/cbb6561a8651601e5f47adafe06ff2fe1688d38a/pkg/app/app.go#L328), [here](https://github.com/helmfile/helmfile/blob/cbb6561a8651601e5f47adafe06ff2fe1688d38a/pkg/app/app.go#L385) and [here](https://github.com/helmfile/helmfile/blob/cbb6561a8651601e5f47adafe06ff2fe1688d38a/pkg/app/app.go#L421). I guess `--include-needs` is broken since [this change last year](https://github.com/helmfile/helmfile/commit/bc255f3e510bcf4ea130f2d8ce3d8d6360027f34).

Look at [these jobs](https://github.com/pathob/helmfile-issues/actions/runs/6099591475) for [this helmfile.yaml](https://github.com/pathob/helmfile-issues/blob/dd3afed1f6e3d0d089967608c5fbbec4b02d1531/helmfile.yaml) where only releases 2 and 3 should be templated / linted: 

I guess apply, diff, sync etc. are affected too.

### Example helmfile.yaml

```
repositories:
  - name: aservo
    url: https://aservo.github.io/charts

releases:
  - chart: aservo/util
    version: 0.0.1
    name: release1
    namespace: default

  - chart: aservo/util
    version: 0.0.1
    name: release2
    namespace: default
    needs:
      - release1

  - chart: aservo/util
    version: 0.0.1
    name: release3
    namespace: default
    needs:
      - release2
```

### Error message you've seen (if any)

None

### Steps to reproduce

helmfile <template|lint|?> -l name=release3 --include-needs

### Working Helmfile Version

0.147.0 (probably)
