### ISSUE TITLE
Array Maps at Values sentences

### ISSUE THREAD

**Issue by adecchi-2inno** [helmfile/helmfile#1021]
### Operating system

Mac

### Helmfile Version

0.156.0

### Helm Version

v3.12.3

### Bug description

I am using a helm template to create an ArgoCD application. This template it is working.
My intention is to be able to send an array of map to the be process by my ArgoCD template.
So, looks like I am not sending a correct array of map.

Here is my release using the template:

```
  - name: demo
    <<: *argocd-apps
    namespace: demo
    disableValidation: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "frontend"
    setTemplate:
        - name: source.helm.parameters
        values:
            - name: demo
            - version: v2
```

When execute helmfile i get:

```
  line 1073: cannot unmarshal !!map into string
  line 1074: cannot unmarshal !!map into string
```

Is possible to send an Array of Map using the `values` sentences 

### Example helmfile.yaml

Here is the release, where I try to send a Map of Map in the `values` sentences 

```
  - name: demo
    <<: *argocd-apps
    namespace: demo
    disableValidation: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "frontend"
    setTemplate:
        - name: source.helm.parameters
        values:
            - name: demo
            - version: v2
```

### Error message you've seen (if any)

```
  line 1073: cannot unmarshal !!map into string
  line 1074: cannot unmarshal !!map into string
```

### Steps to reproduce

n/a

### Working Helmfile Version

0.156.0

### Relevant discussion

n/a

**Comment by yxxhero** [comment]
@adecchi-2inno could you post a demo project?

**Comment by adecchi-2inno** [comment]
@yxxhero 
 This an example the argocd application:
 
 
```
project: pts
source:
  repoURL: 'https://github.com/xxxxx'
  path: helmfiles/microservices/abc
  targetRevision: main
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: name
        value: demo
      - name: version
        value: v2
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
```
