### ISSUE TITLE
fix: lock file is not generated

### ISSUE THREAD

**Issue by jjangga0214** [helmfile/helmfile#1027]
### Operating system

macOS Ventura 13.5.2(22G91)

### Helmfile Version

```bash
  Version            v0.157.0
  Git Commit         "brew"
  Build Date         09 Sep 23 23:06 KST (1 week ago)
  Commit Date        09 Sep 23 23:06 KST (1 week ago)
  Dirty Build        no
  Go version         1.21.1
  Compiler           gc
  Platform           darwin/arm64
```

### Helm Version

```bash
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

### Bug description

lock file is not created

### Example helmfile.yaml

(*`greeter` is just an example.*)

```yaml
environments:
  local:
    values:
      - ./values.local.yaml

releases:
  - name: greeter
    chart: ./greeter
    namespace: default
    condition: greeter.enabled
    values:
      - ./values/greeter.local.yaml
```

### Error message you've seen (if any)

None

### Steps to reproduce

`helmfile deps`, `helmfile apply`

### Working Helmfile Version

I do not know.
