### ISSUE TITLE
stderr from hooks are not displayed in logs

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#1029]
### Operating system

Ubuntu 20.04 LTS

### Helmfile Version

0.157.0

### Helm Version

3.12.3

### Bug description

stderr from hooks are not displayed in logs even if `showlogs: true`.

### Example helmfile.yaml

```yaml
releases:
  - name: raw
    chart: https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
    wait: true
    hooks:
      - events:
          - postsync
        showlogs: true
        command: bash
        args:
          - -c
          - |
            echo stdout logs
            echo stderr logs >&2
```

### Error message you've seen (if any)

```
Upgrading release=raw, chart=https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
Release "raw" has been upgraded. Happy Helming!
NAME: raw
LAST DEPLOYED: Mon Sep 18 12:06:04 2023
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None

Listing releases matching ^raw$
raw     default         4               2023-09-18 12:06:04.15286643 -0300 -03  deployed        raw-v0.3.2                 


hook[postsync] logs | stdout logs
hook[postsync] logs | 

UPDATED RELEASES:
NAME   CHART                                                                          VERSION   DURATION
raw    https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz   v0.3.2          1s
```

As you can see, `stderr` is not shown.

### Steps to reproduce

N/A

### Working Helmfile Version

N/A
