### ISSUE TITLE
hooks with `showlogs: true` display logs even if nothing is outputted

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#1036]
### Operating system

Ubuntu 20.04 LTS

### Helmfile Version

0.157.0

### Helm Version

3.12.3

### Bug description

Even when the hook does not output anything to the logs, Helmfile still displays a line of it in the logs. Example:

```console
$ helmfile sync
Upgrading release=raw, chart=https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
Release "raw" does not exist. Installing it now.
NAME: raw
LAST DEPLOYED: Wed Sep 20 11:12:36 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

Listing releases matching ^raw$
raw     default         1               2023-09-20 11:12:36.962219161 -0300 -03 deployed        raw-v0.3.2                 


hook[postsync] logs | 

UPDATED RELEASES:
NAME   CHART                                                                          VERSION   DURATION
raw    https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz   v0.3.2          2s
```

I'm specifically talking about the `hook[postsync] logs | ` line, which was not supposed to be there since the hook doesn't output anything to the logs.

This is even more bad when running `helmfile build`, since such line will be part of helmfile's stdout and thus would break the YAML syntax. The workaround in that case is `helmfile build -q`.

### Example helmfile.yaml

```yaml
releases:
  - name: raw
    chart: https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
    wait: true
    hooks:
      - events:
          - postsync
        showlogs: true
        command: "true"
```

### Error message you've seen (if any)

N/A

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

### Relevant discussion

N/A
