### ISSUE TITLE
helmfile deps - Error: could not find : no matching version

### ISSUE THREAD

**Issue by rupurt** [helmfile/helmfile#1049]
### Operating system

Ubuntu 20.04 LTS

### Helmfile Version

0.156.0

### Helm Version

v3.12.2

### Bug description

Can't generate `helmfile.lock` from `helmfile deps`

### Example helmfile.yaml

```yaml
repositories:
  # minio
  - name: minio
    url: git+https://github.com/minio/operator@helm?ref=master
  # cert manager
  - name: jetstack
    url: https://charts.jetstack.io
  # kafka
  - name: redpanda
    url: https://charts.redpanda.com
  # cloudnative postgres
  - name: cnpg
    url: git+https://github.com/cloudnative-pg/charts@charts/cloudnative-pg?ref=main
  # observability
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # minio
  - name: minio-operator
    namespace: minio-operator
    createNamespace: true
    chart: minio/operator
  # TODO:
  # - figure out why the tenant doesn't work???
  # - name: minio-tenant
  #   namespace: minio-tenant
  #   createNamespace: true
  #   chart: minio/tenant
  # cert manager
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    set:
      - name: installCRDs
        value: true
  # redpanda
  - name: redpanda-operator
    namespace: redpanda
    createNamespace: true
    chart: redpanda/operator
  # cloudnative postgres
  - name: cnpg
    namespace: cnpg-system
    createNamespace: true
    chart: cnpg/cloudnative-pg
  # observability
  - name: grafana
    namespace: observability
    createNamespace: true
    chart: grafana/grafana
```

### Error message you've seen (if any)

```shell
Adding repo minio git+https://github.com/minio/operator@helm?ref=master
"minio" has been added to your repositories

Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

Adding repo redpanda https://charts.redpanda.com
"redpanda" has been added to your repositories

Adding repo cnpg git+https://github.com/cloudnative-pg/charts@charts/cloudnative-pg?ref=main
"cnpg" has been added to your repositories

Adding repo grafana https://grafana.github.io/helm-charts
"grafana" has been added to your repositories

Updating dependency /tmp/nix-shell.iMzTMN/2149760593
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "redpanda" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "dagster" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "lsstsqre" chart repository
...Successfully got an update from the "strimzi" chart repository
...Successfully got an update from the "apache-airflow" chart repository
...Successfully got an update from the "argo" chart repository
...Successfully got an update from the "lakefs" chart repository
...Successfully got an update from the "datahub" chart repository
...Successfully got an update from the "stackable-stable" chart repository
...Successfully got an update from the "flyteorg" chart repository
...Successfully got an update from the "cnpg" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "minio" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 5 charts
Downloading grafana from repo https://grafana.github.io/helm-charts
Save error occurred:  could not find : no matching version

in ./helmfile.yaml: unable to update deps: unable to update 4 deps: command "/home/alex/.nix-profile/bin/helm" exited with non-zero status:

PATH:
  /home/alex/.nix-profile/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: update (6 bytes)
  3: /tmp/nix-shell.iMzTMN/2149760593 (32 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: could not find : no matching version

COMBINED OUTPUT:
  Hang tight while we grab the latest from your chart repositories...
  ...Successfully got an update from the "redpanda" chart repository
  ...Successfully got an update from the "jetstack" chart repository
  ...Successfully got an update from the "dagster" chart repository
  ...Successfully got an update from the "grafana" chart repository
  ...Successfully got an update from the "lsstsqre" chart repository
  ...Successfully got an update from the "strimzi" chart repository
  ...Successfully got an update from the "apache-airflow" chart repository
  ...Successfully got an update from the "argo" chart repository
  ...Successfully got an update from the "lakefs" chart repository
  ...Successfully got an update from the "datahub" chart repository
  ...Successfully got an update from the "stackable-stable" chart repository
  ...Successfully got an update from the "flyteorg" chart repository
  ...Successfully got an update from the "cnpg" chart repository
  ...Successfully got an update from the "bitnami" chart repository
  ...Successfully got an update from the "minio" chart repository
  Update Complete. ⎈Happy Helming!⎈
  Saving 5 charts
  Downloading grafana from repo https://grafana.github.io/helm-charts
  Save error occurred:  could not find : no matching version
  Error: could not find : no matching version
```

### Steps to reproduce

helmfile deps

### Working Helmfile Version

-

**Comment by yxxhero** [comment]
assign to me.

**Comment by yxxhero** [comment]
@rupurt could you give a minimal demo to reproduce this issue? thanks so much.

**Comment by yxxhero** [comment]
```
releases:
  # minio
  - name: minio-operator
    namespace: minio-operator
    createNamespace: true
    chart: minio/operator
  # redpanda
  - name: redpanda-operator
    namespace: redpanda
    createNamespace: true
    chart: redpanda/operator
```

see the above. they have the same chart name. `operator`

ChartName identifies the dependant chart. In Helmfile, ChartName for `chart: stable/envoy` would be just `envoy`.
It can't be collided with other charts referenced in the same helmfile spec.
That is, collocating `chart: incubator/foo` and `chart: stable/foo` isn't allowed. Name them differently for a work-around.

**Comment by yxxhero** [comment]
@rupurt

**Comment by yxxhero** [comment]
```
name: helmfile
version: 1.0.0
apiVersion: v2
dependencies:
- name: operator
  repository: git+https://github.com/minio/operator@helm/operator?ref=master
  version: '*'
- name: operator
  repository: https://charts.redpanda.com
  version: '*'
```
Chart.yaml

it will fail when running `helm dependency update . --debug`. so I think we should post an issue in helm.
