### ISSUE TITLE
When installed is false chart should not be fetch [reopen]

### ISSUE THREAD

**Issue by seboudry** [helmfile/helmfile#1053]
### Operating system

Ubuntu 23.04

### Helmfile Version

v0.157.0

### Helm Version

v3.13.0

### Bug description

Reopen issue https://github.com/roboll/helmfile/issues/1232

We got an use case where we don't want multiple releases to be deployed on an environment.
And the versions are not knowned so we don't want the charts to be fetched.

### Example helmfile.yaml

Basic example to reproduce:

```yaml
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: loki
    installed: false
    chart: grafana/loki
    version: bar
```

### Error message you've seen (if any)

```
$ helmfile template
Adding repo grafana https://grafana.github.io/helm-charts
"grafana" has been added to your repositories

in helmfile.d/helmfile.yaml: [no resolved dependency found for "loki", running "helmfile deps" may resolve the issue]
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A
