### ISSUE TITLE
Double escape backward slash with `HELMFILE_V1MODE=true`

### ISSUE THREAD

**Issue by z0rc** [helmfile/helmfile#1079]
### Operating system

MacOS 14.0

### Helmfile Version

v0.157.0

### Helm Version

v3.13.1

### Bug description

With `HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=false helmfile template | grep css -A5 -B5` result is okay:
```
          string_attribute:
            enabled_regex_matching: true
            invert_match: true
            key: http.url
            values:
            - \.(js|css|json)
          type: string_attribute
    receivers:
      jaeger:
        protocols:
          grpc:
```

With `HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile template | grep css -A5 -B5` result is not okay, double escape `\\.` is generated:
```
          string_attribute:
            enabled_regex_matching: true
            invert_match: true
            key: http.url
            values:
            - \\.(js|css|json)
          type: string_attribute
    receivers:
      jaeger:
        protocols:
          grpc:
```

I wasn't able to find how wrap or escape this string to avoid double escaping and preserve single slash. I tried single quotes, double quotes and go template literals like:
```
{{` \.(js|css|json) `}}
```
to no avail.

### Example helmfile.yaml

It's `helmfile.yaml.gotmpl`

```
repositories:
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
- name: opentelemetry-collector
  namespace: opentelemetry
  chart: open-telemetry/opentelemetry-collector
  version: 0.72.0
  disableValidationOnInstall: true
  values:
  - mode: deployment
    config:
      processors:
        tail_sampling:
          policies:
          - name: drop_noisy_traces_by_url
            type: string_attribute
            string_attribute:
              key: http.url
              values:
              - \.(js|css|json) # <--- this line is problematic
              enabled_regex_matching: true
              invert_match: true
```

### Error message you've seen (if any)

None

### Steps to reproduce

See `Bug description` example helmfile

### Working Helmfile Version

v0

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/656

**Comment by z0rc** [comment]
I guess helmfile does some unmarshall-marshal process with yaml. I kinda reproduced this here https://go.dev/play/p/bHQbbYDBBo-, but it isn't clear if this is something of expected go-yaml behavior and whether it can be adjusted on helmfile side.

**Comment by z0rc** [comment]
Not stale. (i hate this bot)

**Comment by z0rc** [comment]
Not stale.

**Comment by z0rc** [comment]
Not stale.

**Comment by z0rc** [comment]
Not stale.

**Comment by MaksimAniskov** [comment]
I hit this bump too. +1 Really appreciate someone's addressing this problem

**Comment by ProbstDJakob** [comment]
Same here. We had some RegEx defined and it silently double escaped them since the packaged version in `alpine` Linux builds it with the go ld flag `-X github.com/helmfile/helmfile/pkg/runtime.v1Mode=true`. This lead to a bricked deployment as the WAL storage of postgres has run full and the configured alert rules did not work because of the double escaped RegEx string.

Is there any way to prioritize this a bit more? Maybe other people have similar problems but did not notice it by now.

I currently do not have much time, thus helping with this one would require a bit help to find the location which is probably the reason for the bug.

**Comment by yxxhero** [comment]
HELMFILE_GOCCY_GOYAML=false

**Comment by ProbstDJakob** [comment]
If this is a response to my comment, I am already aware of that environment variable and added it to our GitLab CI job, but what I meant was, that in order to help fixing the bug in the code I need to know where to search.

**Comment by yxxhero** [comment]
@ProbstDJakob it maybe the issue of yaml parser.

**Comment by ProbstDJakob** [comment]
Of the dependency or https://github.com/helmfile/helmfile/blob/main/pkg/yaml/yaml.go?

**Comment by yxxhero** [comment]
yeah. we use both of github.com/goccy/go-yaml and gopkg.in/yaml.v2.

**Comment by ProbstDJakob** [comment]
Yes, I know but I do not get what you are trying to tell me. I currently do not have much time but fixing this would be worth investing some of my time. The problem is I do not know anything about the code base of `helmfile`, so in order to help fixing this bug and not investing too much time it would be great if you (or anyone else) could help me find the bug so I can try to fix it and open a PR. I read this issue and the [linked one](https://github.com/helmfile/helmfile/issues/1508), therefore I am aware of both dependencies used for `yaml` and that they are chosen based on whether version 1 is used/emulated or what the enviable variable `HELMFILE_GOCCY_GOYAML` is set to.

**Comment by ProbstDJakob** [comment]
That's what I thought as well but I wasn't sure, thanks. I will look into the code, but it may take some time since I am currently overloaded with work. So if someone else is willing to take over, I won't be mad ^^

**Comment by z0rc** [comment]
I looked into this a bit more. Marshalling output from goccy/go-yaml technically matches go/yaml output, see https://go.dev/play/p/d5RQ2vH33hS
```
goccy/go-yaml:
a:
- "\\.js"

gopkg.in/yaml.v2:
a:
- \.js
```

But it seems helmfile ignores escape in double-quoted string, and uses it as is, instead of doing unescape in process.

**Comment by z0rc** [comment]
@yxxhero @mumoshu can you please take a look here? This issue is major blocker for v1, it's breaking bug, that will trigger once people start to use v1 and it's easy missable by end user. In the same time given the nature of yaml escapes and how they used in regexes, this bug has potential of breaking chart installations.

**Comment by dipeti** [comment]
We're also seeing the same issue with escaping backslash after upgrading to v1. Here's a bit of code to reproduce the problem:
```
unzip backslash-escaping-issue.zip && cd backslash-escaping-issue
helmfile template
```
[backslash-escaping-issue.zip](https://github.com/user-attachments/files/18144032/backslash-escaping-issue.zip)

OUTPUTS:

```yaml
➜  HELMFILE_GOCCY_GOYAML=true helmfile template
---
# Source: my-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  myregex_1: something\\.public\\.requests

➜  HELMFILE_GOCCY_GOYAML=false helmfile template
---
# Source: my-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  myregex_1: something\.public\.requests
```




```
helmfile version
  Version            1.0.0-rc.8
  Git Commit         370b004
  Build Date         05 Dec 24 08:18 -05 (1 week ago)
  Commit Date        04 Dec 24 19:23 -05 (1 week ago)
  Dirty Build        no
  Go version         1.23.1
  Compiler           gc
  Platform           darwin/arm64
```
