### ISSUE TITLE
YAML document start marker causes WARNING: environments and releases cannot be defined within the same YAML part

### ISSUE THREAD

**Issue by jim-barber-he** [helmfile/helmfile#1093]
### Operating system

Debian stable (12 bookworm)

### Helmfile Version

0.158.0

### Helm Version

v3.13.1

### Bug description

I have found that having the leading document start marker `---` in `helmfile.yaml` is causing the following warning even though the `environment` section is separated from the other sections.
```
WARNING: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part
```

Removing the first document start marker solves it, however tools like `yamllint` expect that to be there by default (for example).

So this causes the warning:
```
---
environments:
  ...
---
releases:
  ...
```
While this does not.
```
environments:
  ...
---
releases:
  ...
```

### Example helmfile.yaml

```
---
environments:
  prod:
  test:

---
helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: false

releases:
  - name: sre
    chart: ./helm/charts/sre
    labels:
      app: sre
    namespace: {{ env "RELEASE_NAMESPACE" | default "sre" }}
    values:
      - helm/vars/cronjobs.yaml.gotmpl
      - helm/vars/values.yaml.gotmpl

  - name: system-reserved-resources
    chart: ./helm/charts/system-reserved-resources
    labels:
      app: sre
    namespace: {{ env "RELEASE_NAMESPACE" | default "sre" }}
    values:
      - helm/vars/system-reserved.yaml.gotmpl
```

### Error message you've seen (if any)

```
WARNING: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part
```

### Steps to reproduce

Details above

### Working Helmfile Version

Whatever version before this warning was added to prepare for helmfile v1.
