### ISSUE TITLE
diffArgs passed to `helm list` when running `helmfile apply` with false `installed` conditions

### ISSUE THREAD

**Issue by mgalliou** [helmfile/helmfile#1095]
### Operating system

Ubuntu 22.04.3 LTS

### Helmfile Version

0.158.0

### Helm Version

3.13.1

### Bug description

When running the command `helmfile apply` with a helmfile containing release(s) with `installed` conditions as false, if `helmDefault.diffArgs` is set, helmfile pass the diffArgs values to the `helm list` command.

### Example helmfile.yaml

```yaml
helmDefaults:
  diffArgs:
   - "--three-way-merge"

repositories:
  - name: deliveryhero 
    url: https://charts.deliveryhero.io/
      
releases: 
  - name: wiremock
    chart: deliveryhero/wiremock
    installed: false
```

### Error message you've seen (if any)

```txt
Listing releases matching ^wiremock$
in ./helmfile.yaml: command "/home/linuxbrew/.linuxbrew/bin/helm" exited with non-zero status:

PATH:
  /home/linuxbrew/.linuxbrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^wiremock$ (10 bytes)
  4: --uninstalling (14 bytes)
  5: --deployed (10 bytes)
  6: --failed (8 bytes)
  7: --pending (9 bytes)
  8: --three-way-merge (17 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown flag: --three-way-merge

COMBINED OUTPUT:
  Error: unknown flag: --three-way-merge
```

### Steps to reproduce

See Bug description and exemple helmfile.yaml

### Working Helmfile Version

N/A
