### ISSUE TITLE
Incompatibility between `installed: false` and `helmfile diff --args`

### ISSUE THREAD

**Issue by dvarrazzo** [helmfile/helmfile#1115]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.157.0

### Helm Version

3.12.3

### Bug description

The `--args` passed to `helmfile diff` is also passed to `helm list`, which is invoked apparently when a resource has `installed: false`, leading to failure.

### Example helmfile.yaml

```yaml
releases:
  - name: akv2k8s
    namespace: default
    chart: spvapi/akv2k8s
    version: 2.3.2
    installed: false
  
repositories:
  - name: spvapi
    url: https://charts.spvapi.no
```

### Error message you've seen (if any)

```
Adding repo spvapi https://charts.spvapi.no
"spvapi" has been added to your repositories

Listing releases matching ^akv2k8s$
in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^akv2k8s$ (9 bytes)
  4: --namespace (11 bytes)
  5: default (7 bytes)
  6: --uninstalling (14 bytes)
  7: --deployed (10 bytes)
  8: --failed (8 bytes)
  9: --pending (9 bytes)
  10: --normalize-manifests (21 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown flag: --normalize-manifests

COMBINED OUTPUT:
  Error: unknown flag: --normalize-manifests
```

### Steps to reproduce

`helmfile diff  --args "--normalize-manifests"`

### Working Helmfile Version

No idea
