### ISSUE TITLE
Helmfile's `insecureSkipTLSVerify` option yields errors due to upstream bug in helm-diff

### ISSUE THREAD

**Issue by tjanson** [helmfile/helmfile#1122]
### Operating system

macOS 14

### Helmfile Version

v0.158.1

### Helm Version

v3.13.1

### Bug description

Enabling `insecureSkipTLSVerify` currently leads to [a bug in helm-diff](https://github.com/databus23/helm-diff/issues/503), with error `unknown flag: --insecure-skip-tls-verify`.
This is not Helmfile's fault, but it affects Helmfile users.
It seems the issue was introduced in Helm v3.10 (see discussion above).

### Example helmfile.yaml

```yaml
helmDefaults:
  insecureSkipTLSVerify: true

repositories:
- name: bitnami
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami

releases:
- name: example-release
  chart: bitnami/wordpress
```

### Error message you've seen (if any)

```
Adding repo bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
"bitnami" has been added to your repositories

Comparing release=example-release, chart=bitnami/wordpress
in ./helmfile.yaml: command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: example-release (15 bytes)
  5: bitnami/wordpress (17 bytes)
  6: --insecure-skip-tls-verify (26 bytes)
  7: --detailed-exitcode (19 bytes)
  8: --color (7 bytes)
  9: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown flag: --insecure-skip-tls-verify

COMBINED OUTPUT:
  Error: unknown flag: --insecure-skip-tls-verify
```

### Steps to reproduce

helmfile apply

### Working Helmfile Version

Helm v3.9

### Relevant discussion

https://github.com/databus23/helm-diff/issues/503
