### ISSUE TITLE
`.HelmfileCommand` is exposed to hooks but not exposed to other templates

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#1135]
### Operating system

Ubuntu 22.04 LTS

### Helmfile Version

0.158.1

### Helm Version

3.13.2

### Bug description

I can use `.HelmfileCommand` in hooks, which is good. However it would be very useful to use .HelmfileCommand outside hooks too.

### Example helmfile.yaml

```yaml
releases:
  - name: raw
    chart: https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
    hooks:
      - name: release-level
        events:
          - presync
        showlogs: true
        command: echo
        args:
          # This works
          - ".HelmfileCommand is '{{`{{.Helmfile.Command}}`}}'"
    {{ if eq .HelmfileCommand "sync" }}
    # do something, but this does not work
    {{ end }}

```

### Error message you've seen (if any)

```
in ./helmfile.yaml.gotmpl: error during helmfile.yaml.gotmpl.part.0 parsing: template: stringTemplate:11:52: executing "stringTemplate" at <.Helmfile.Command>: can't evaluate field Helmfile in type *state.EnvironmentTemplateData
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A
