### ISSUE TITLE
`commonLabels` not applied on releases

### ISSUE THREAD

**Issue by mgalliou** [helmfile/helmfile#1137]
### Operating system

Ubuntu 22.04.3 LTS

### Helmfile Version

0.158.1

### Helm Version

3.13.2

### Bug description

After running `helmfile apply` on the helmfile below, running `helm list -l helmfile=test` should list the installed release as if it was installed with `helm install wiremock deliveryhero/wiremock -l helmfile=test`, but this is not the case.

### Example helmfile.yaml

```yaml
commonLabels:
  helmfile: test

repositories:
  - name: deliveryhero 
    url: https://charts.deliveryhero.io/
      
releases: 
  - name: wiremock
    chart: deliveryhero/wiremock
```

### Error message you've seen (if any)

N/A

### Steps to reproduce

See Bug description and exemple helmfile.yaml

### Working Helmfile Version

I havn't tried this feature prior.
