### ISSUE TITLE
"Re-using environment state in sub-helmfiles" kubeContext not working

### ISSUE THREAD

**Issue by wrenix** [helmfile/helmfile#1213]
### Operating system

NixOS

### Helmfile Version

v0.158.1

### Helm Version

v3.13.2

### Bug description

configured kubeContext is not used (always default).

In Documentation describted "Re-using environment state in sub-helmfiles", which i found here:

Advanced Features > Best Practices Guide > Re-using environment state in sub-helmfiles

https://helmfile.readthedocs.io/en/stable/writing-helmfile/#re-using-environment-state-in-sub-helmfiles

Does not work:

#### `helmfile.yaml`

```yaml
environments:
  stage:
    kubeContext: stage
    values:
    - env/stage.yaml
  prod:
    kubeContext: prod
    values:
    - env/prod.yaml

---

helmfiles:
  - path: sub-helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 6 }}
```

#### `sub-helmfile.yaml`

```yaml
releases:
  - name: "a"
    chart: "a/a"
    installed: {{ .Values.enabled }}
```

#### `env/prod.yaml`

```yaml
enabled: true
```

#### `env/stage.yaml`

```yaml
enabled: false
```

### Error message you've seen (if any)

-

### Steps to reproduce

helmfile -e prod list

### Working Helmfile Version

maybe never, see #948 and not working #947

**Comment by jouve** [comment]
.Values is only environments[].values and environments[].secret , so I don't think it's possible currently

**Comment by wrenix** [comment]
hmm, that could be the problem - do we like to change it?

**Comment by bdalpe** [comment]
I've also been looking into this, as I've been seeing the same behavior. Multiple comments in the old repo by @mumoshu seem to indicate this is by design. I'm still trying to figure out a simple solution...

> But beware, as far as I remember --kube-context or --namespace doesn't work correctly with sub-helmfiles. As they only affect the parent helmfile.yaml. Not very sure what to do for those, though.

* https://github.com/roboll/helmfile/issues/443#issuecomment-457123421

> One of the rules of helmfile is that each sub-helmfile should be usable independently. So let's assume that your sub-helmfile should be complete on its own i.e. should work without inheritance at all.

* https://github.com/roboll/helmfile/issues/725#issuecomment-506101418

> To make each (sub-)helmfile modular, environment values are not automatically inherited to sub-helmfiles.

* https://github.com/roboll/helmfile/issues/1045#issuecomment-568144432

**Comment by genofire** [comment]
Okay again, should we give the `helmfiles` the option to set kubeContext (and namespaces):

here a example to bypass it (if the options whould exists):
```yaml
helmfiles:
  - path: sub-helmfile.yaml
    kubeContext: {{ .Environment.KubeContext }}
    namespace: {{ .Environment.Namespace }}
    values:
      - {{ toYaml .Values | nindent 6 }}
```
