### ISSUE TITLE
helmfile does no use helmfile.lock when using ad-hoc kustimzation

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#1229]
### Operating system

-

### Helmfile Version

v0.159.0

### Helm Version

v3.13.2

### Bug description

when using a kustomization, helmfile does not respect the helmfile.lock

### Example helmfile.yaml

``` 
repositories:
- name: passbolt
  url: https://download.passbolt.com/charts/passbolt

releases:
- name: passbolt
  chart: passbolt/passbolt
  strategicMergePatches:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: passbolt-sec-tls
    data:
      ca.crt: null
      ca.key: null
      server-key.pem: null
      server.crt: null
      tls.crt: null
      tls.key: null

```

helmfile.lock
```
version: v0.159.0
dependencies:
- name: passbolt
  repository: https://referentiel-livraison.devops.prod.fdj.fr/repository/passbolt-helm-proxy
  version: 0.3.3
digest: sha256:61fc8e83addf9d8d3326a7ab52ddcaca0f409e8bf753e6529f972b6d34683299
generated: "2023-12-15T13:23:34.596704+01:00"
```

### Error message you've seen (if any)

helmfile template => see that generated manifests use     helm.sh/chart: passbolt-0.4.4

remove the strategicMergePatches and it works again :     helm.sh/chart: passbolt-0.3.3

### Steps to reproduce

-

### Working Helmfile Version

tbd
