### ISSUE TITLE
race condition in remote cache with go-getter

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#1239]
### Operating system

osx

### Helmfile Version

v0.159.0

### Helm Version

-

### Bug description

this first time I run helmfile template (or any command rendering values) , it fails :
```
err: [get: error downloading '[https://xxx/some/repo/common/common.git':](https://xxx/some/repo/common.git%27:) /usr/local/bin/git exited with 128: fatal: destination path '/Users/uuu/Library/Caches/helmfile/values/xxx' already exists and is not an empty directory.
```

running with `--debug` , I notice that the git repo is cloned/cached a 1st time, then a second time with the above error.

running with `--concurrency=1`, I have no error.

I'm guessing some kind of [tocttou](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) if this part of code executes in parallel https://github.com/helmfile/helmfile/blob/main/pkg/state/storage.go#L63C29-L63C34

### Example helmfile.yaml

```
- name: postgresql
  chart: bitnami/postgresql
  version: 13.2.22
  values:
  - git::https://xxx/some/repo/common.git@postgresql.yaml
  - postgresql.yaml.gotmpl
- name: redis
  chart: bitnami/redis
  version: 18.4.0
  values:
  - git::https://xxx/some/repo/common.git@redis.yaml
  - redis.yaml.gotmpl
```

### Error message you've seen (if any)

err: [get: error downloading '[https://xxx/some/repo/common/common.git':](https://xxx/some/repo/common.git%27:) /usr/local/bin/git exited with 128: fatal: destination path '/Users/uuu/Library/Caches/helmfile/values/xxx' already exists and is not an empty directory.

### Steps to reproduce

-

### Working Helmfile Version

-
