### ISSUE TITLE
.Values are not available for a local chart

### ISSUE THREAD

**Issue by teodorkostov-es** [helmfile/helmfile#125]
### Operating system

Arch Linux

### Helmfile Version

0.144.0

### Helm Version

3.9.0

### Bug description

`.Values` are not available for a local chart.

```yaml
environments:
  default:
    values:
      - etcd:
          replicaCount: 1
          global:
            storageClass: manual
          persistence:
            storageClass: manual
            size: 4Gi

releases:
  - name: local-chart
    namespace: local
    chart: ./charts/local-chart
    condition: local.enabled
    values:
      - etcd: {{ toYaml .Values.etcd | nindent 10 }}
```

```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:49:31: executing "stringTemplate" at <.Values.etcd>: map has no entry for key "etcd"
```

### Steps to reproduce

http://here
