### ISSUE TITLE
failure in hook should not prevent next hooks to execute

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#1252]
### Operating system

Ubuntu 20.04 LTS

### Helmfile Version

v0.160.0

### Helm Version

v3.13.2

### Bug description

When a hook fails, all next hooks should execute. However, the failure should be propagated to the `.Event.Error`, so that hooks can decide what to do when an error happened.

I believe that's exactly the point behind `.Event.Error`.

### Example helmfile.yaml

```yaml
releases:
  - name: raw
    chart: https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
    wait: true
    hooks:
      - name: first-hook
        events:
          - postsync
        showlogs: true
        command: "false"
      - name: second-hook
        events:
          - postsync
        showlogs: true
        command: "echo"
        args:
          - "this should execute, but it does not"
```

### Error message you've seen (if any)

```console
❯ helmfile sync
Upgrading release=raw, chart=https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
Release "raw" does not exist. Installing it now.
NAME: raw
LAST DEPLOYED: Tue Dec 26 10:21:27 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

Listing releases matching ^raw$
raw     default         1               2023-12-26 10:21:27.258526025 -0300 -03 deployed        raw-v0.3.2                 


hook[postsync] logs | 

UPDATED RELEASES:
NAME   CHART                                                                          VERSION   DURATION
raw    https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz   v0.3.2          2s

in ./helmfile.yaml: failed processing release raw: hook[first-hook]: command `false` failed: command "/usr/bin/false" exited with non-zero status:

PATH:
  /usr/bin/false

ARGS:
  0: false (5 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1
```

### Steps to reproduce

See helmfile.yaml above

### Working Helmfile Version

N/A

**Comment by xiaomudk** [comment]
@felipecrs In Helmfile, each hook is a self-contained entity, and there is no communication between multiple hooks. If you need to handle errors, it should be done within a single hook. Are there any other real-world scenarios where errors need to be passed between hooks?

**Comment by felipecrs** [comment]
In my case, yes.

For all releases I have in my hemfile, I have a presync and a postsync hook that starts collecting some logs (pre) and finishes (post).

Something like:

```yaml
releases:
  - name: raw
    chart: https://github.com/dysnix/charts/releases/download/raw-v0.3.2/raw-v0.3.2.tgz
    wait: true
    hooks:
      - name: start-logs-capture
        events:
          - presync
        command: ./start_logs_capture.sh
      - name: check-service
        events:
          - postsync
        showlogs: true
        command: "echo"
        args:
          - "this commands checks if service is up, fails otherwise"
      - name: stop-logs-capture
        events:
          - postsync
        command: ./stop_logs_capture.sh
```

And multiply that pattern to a lot of releases. I even have template releases that automatically adds such start-logs-capture and stop-logs-capture hook to all releases in my helmfile.

However, as you can probably tell, if the "check-service" command fails, the "stop-logs-capture" hook would never execute. And that's not good. :(
