### ISSUE TITLE
Documentation Discrepancy: Inconsistency in Support for 'condition' Flag in Helmfile Dependencies

### ISSUE THREAD

**Issue by njegosrailic** [helmfile/helmfile#1258]
### Operating system

MacOS Ventura 13.6 (22G120)

### Helmfile Version

v0.160.0

### Helm Version

v3.12.3

### Bug description

Hi,

According to the [docs](https://github.com/helmfile/helmfile/blob/main/docs/advanced-features.md#adding-dependencies-without-forking-the-chart):

>An example `helmfile.yaml` that adds a `stable/envoy` dependency to the release `foo` looks like the following:
>```yaml
>repositories:
>- name: stable
>  url: https://charts.helm.sh/stable
>
>releases:
>- name: foo
>  chart: ./path/to/foo
>  dependencies:
>  - chart: stable/envoy
>    version: 1.5
>```
>When Helmfile encounters releases[].dependencies, it creates another temporary chart from ./path/to/foo and adds the following dependencies to the Chart.yaml, so that you don't need to fork the chart.

However, when I tried that:
```console
failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 43: field condition not found in type state.Dependency
```

Which makes sense based on this [source code](https://github.com/helmfile/helmfile/blob/3c5c400ffc531f3e5000fd3561e526150a7f4d71/pkg/state/helmx.go#L14).

My question would be, are we going to support the condition flag? If so, I'm not sure how complex it would be to implement this, but I can look into it. Otherwise, I can submit a PR to fix the docs.

### Example helmfile.yaml

```yaml
repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
    
releases:
  - name: "istio-control-plane"
    namespace: "istio-system"
    labels:
      subsystem: "istio"
    dependencies:
      - alias: istiod-1-19
        chart: istio/istiod
        version: 1.19.5
        condition: revision.1-19.enabled
```

### Error message you've seen (if any)

```console
 failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 43: field condition not found in type state.Dependency
```

### Steps to reproduce

It seems that the condition flag isn't supported.

### Working Helmfile Version

v0.160.0

**Comment by yxxhero** [comment]
@mumoshu

**Comment by yxxhero** [comment]
@njegosrailic you can try to implement the feature.

**Comment by kxkcx** [comment]
> @njegosrailic you can try to implement the feature.

Is it okay if I try to implement it?

**Comment by njegosrailic** [comment]
I'll give it a try.

**Comment by njegosrailic** [comment]
@michaelarnauts I didn't have time to dedicate to this issue.

Because this is a Go template, something like this should work:

```yaml

repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
    
releases:
  - name: "istio-control-plane"
    namespace: "istio-system"
    labels:
      subsystem: "istio"
    dependencies:
      {{ if .Values.revision.1-19.enabled }}
      - alias: istiod-1-19
        chart: istio/istiod
        version: 1.19.5
      {{ end }}
      {{ if .Values.revision.1-20.enabled }}
      - alias: istiod-1-20
        chart: istio/istiod
        version: 1.20.0
      {{ end }}
```
