### ISSUE TITLE
releases[].condition does not allow nested values

### ISSUE THREAD

**Issue by teodorkostov-es** [helmfile/helmfile#126]
### Operating system

Arch Linux

### Helmfile Version

0.144.0

### Helm Version

3.9.0

### Bug description

```yaml
environments:
  default:
    values:
      - etcd:
          replicaCount: 1
          global:
            storageClass: manual
          persistence:
            enabled: true
            storageClass: manual
            size: 4Gi

releases:
  - name: local-chart
    namespace: local
    chart: ./charts/local-chart
    condition: etcd.persistence.enabled # <--- HERE
    values:
      - etcd: {{ toYaml .Values.etcd | nindent 10 }}
```

Using `etcd.persistence.enabled` should be perfectly file. Allowing only a top level value to have `enabled` is kind of discriminatory.

### Steps to reproduce

http://here

**Comment by mumoshu** [comment]
@teodorkostov-es Environment values and release values are two different things in Helmfile. What you refer in `condition` is the latter, release values. You'd need to define it under `releases[].values`. Seeing your example, apparently you already understand that?

Just try running `helmfile build` to see how the release values are rendered. it does include `etcd.persistence.enabled` so it should just work.

```
helmfile -f helmfile.126.yaml build
---
#  Source: helmfile.126.yaml

filepath: helmfile.126.yaml
helmBinary: helm
environments:
  default:
    values:
    - etcd:
        global:
          storageClass: manual
        persistence:
          enabled: true
          size: 4Gi
          storageClass: manual
        replicaCount: 1
releases:
- chart: ./charts/local-chart
  condition: etcd.persistence.enabled
  name: local-chart
  namespace: local
  values:
  - etcd:
      global:
        storageClass: manual
      persistence:
        enabled: true
        size: 4Gi
        storageClass: manual
      replicaCount: 1
templates: {}
renderedvalues:
  etcd:
    global:
      storageClass: manual
    persistence:
      enabled: true
      size: 4Gi
      storageClass: manual
    replicaCount: 1
```

If you're still curious, please provide the full step to reproduce the issue.
