### ISSUE TITLE
helmfile parses commented releases and issues errors if a value was renamed

### ISSUE THREAD

**Issue by teodorkostov-es** [helmfile/helmfile#127]
### Operating system

Arch Linux

### Helmfile Version

0.144.0

### Helm Version

3.9.0

### Bug description

Why?

```yaml
environments:
  default:
    values:
      - hello: world

releases:
...
#  - name: hello
#    namespace: hello
#    chart: ./charts/hello
#    values:
#      - hello: {{.Values.whatever}}
```

### Steps to reproduce

http://here
