### ISSUE TITLE
Function `trunc` not defined in helper templates using new `include` function

### ISSUE THREAD

**Issue by nikolaik** [helmfile/helmfile#1276]
### Operating system

MacOS Sonoma

### Helmfile Version

0.160.0

### Helm Version

3.13.2

### Bug description

I'm testing out the new `include` function in my helmfile.yaml and tried using functions like `trunc` in the helper template. Should this be supported?

### Example

```yaml
#helmfile.yaml
releases:
  - name: x
    chart: y/z
    values:
      - some_value: {{ include "test_helper" }}
```
```
# _helpers.tpl
{{ define "test_helper"}}
{{ .name | trunc }}
{{- end }}
```
### Error message you've seen (if any)

```
error during helmfile.yaml.part.0 parsing: failed to parse helper template _helpers.tpl: template: stringTemplate:2: function "trunc" not defined
```

### Steps to reproduce

helmfile diff

### Working Helmfile Version

N/A

### Relevant links

https://github.com/helmfile/helmfile/pull/1187
