### ISSUE TITLE
Mysterious errors on releases reorder

### ISSUE THREAD

**Issue by teodorkostov-es** [helmfile/helmfile#128]
### Operating system

Arch Linux

### Helmfile Version

0.144.0

### Helm Version

3.9.0

### Bug description

```yaml
repositories:
  - name: apisix
    url: https://charts.apiseven.com

missingFileHandler: Error

environments:
  default:
    values:
      - etcd:
          replicaCount: 1
          global:
            storageClass: manual
          persistence:
            storageClass: manual
            size: 4Gi
      - etcdStorage:
          enabled: true

releases:
  - name: etcd-storage
    namespace: apisix
    chart: ./charts/etcd-storage
    condition: etcdStorage.enabled # should be etcd.persistance.enabled but requires helmfile fix
    values:
      - etcd: {{ toYaml .Values.etcd | nindent 10 }}

  - name: apisix
    namespace: apisix
    chart: apisix/apisix
    values:
      - etcd: {{ toYaml .Values.etcd | nindent 10 }}
      - ingress-controller:
          enabled: true
          config:
            apisix:
              serviceNamespace: apisix
...
```

I have 3 charts. Third chart is a deployment with a service. The `etcd-storage` is just a manually defined `PersistentVolume`.

`helmfile template` works just fine.

Running like this causes `Error: Failed to render chart: exit status 1: Error: failed to download "apisix/apisix"`.

Reordering the first 2 charts causes `Error: Failed to render chart: exit status 1: Error: Kubernetes cluster unreachable: Get "https://k8s:6443/version": dial tcp: lookup k8s on <gateway-ip>:53: read udp <host-ip>:49631-><gateway-ip>:53: i/o timeout`.

`helmfile apply` with commented `etcd-storage` chart works just fine. Running `apply` with all 3 chars afterwards works just fine as well.

### Steps to reproduce

http://here
