### ISSUE TITLE
Helmfile still trying to use "Helm chart pull" instead of just "Helm Pull" with newer versions of helm.

### ISSUE THREAD

**Issue by JMoore31** [helmfile/helmfile#1289]
### Operating system

Windows 10

### Helmfile Version

0.160.0

### Helm Version

v3.14.0-rc.1

### Bug description

Hello,
When I try to use an OCI repository (harbor), there is an error where it still attempts to use "helm chart pull", when helm has been updated to only require "helm pull". (This was changed in helm 3.7)

### Example helmfile.yaml

```

repositories:
  - name: harbor 
    url: harbor.example/charts
    oci: true
    caFile: ca.crt

releases:
  - name: mongodb
    chart: harbor/mongodb
    version: 13.16.3
    namespace: mongodb
    values:
      - ./values/default/mongodb

```

### Error message you've seen (if any)

```
PS C:\Users\JMoore31\Desktop\test> helmfile sync -l name=mongodb
Pulling harbor.example/charts/mongodb:13.16.3
in ./helmfile.yaml: [release "mongodb": command "C:\\Users\\JMoore31\\Documents\\Helm\\helm.exe" exited with non-zero status:

PATH:
  C:\Users\JMoore31\Documents\Helm\helm.exe

ARGS:
  0: helm (4 bytes)
  1: chart (5 bytes)
  2: pull (4 bytes)
  3: harbor.example/charts/mongodb:13.16.3 (44 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown command "chart" for "helm"
  Run 'helm --help' for usage.

COMBINED OUTPUT:
  Error: unknown command "chart" for "helm"
  Run 'helm --help' for usage.]
```

### Steps to reproduce

Use an oci registry, and try to pull from it with helm >= 3.7

### Working Helmfile Version

It is the helm version that is the issue, however if I turn helm back to before 3.7 I get a different error where the fix is "Update helm"
