### ISSUE TITLE
Relative path in `environments.*.values` not working in multi-file setup.

### ISSUE THREAD

**Issue by Kellen275** [helmfile/helmfile#1304]
### Operating system

Ubuntu 22.04.2 LTS

### Helmfile Version

0.158.1

### Helm Version

v3.13.2

### Bug description

 In my example below, the path to `values.yaml` specified in `base.yaml` is relative to the `helmfile.yaml`, not the `base.yaml`.

### Example helmfile.yaml

Given the following file structure
```shell
.
├── base.yaml
├── values.yaml
└── release
    └── helmfile.yaml
```
With the following file contents
**helmfile.yaml**
```yaml
bases:
  - ../base.yaml
releases:
  - name: release
    chart: .
```
**base.yaml**
```yaml
environments:
  dev:
    values:
      - values.yaml
```
**values.yaml**
```yaml
foo: bar
```

### Error message you've seen (if any)

```shell
$ helmfile lint -e dev -f release/helmfile.yaml
in ./helmfile.yaml: failed to read ../base.yaml: environment values file matching "values.yaml" does not exist in "."
```

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/1301

**Comment by chrisdoherty4** [comment]
This looks like expected behavior. The values are relative to the `helmfile.yml`, not the file being included via `bases`.

**Comment by Kellen275** [comment]
Perhaps I'm misinterpreting https://helmfile.readthedocs.io/en/latest/#paths-overview then.
> Relative paths referenced in the Helmfile manifest itself are relative to that manifest

Is the following not considered a "Helmfile manifest"?
```yaml
environments:
  dev:
    values:
      - values.yaml
```
