### ISSUE TITLE
Can't use chart version other than X.Y.Z

### ISSUE THREAD

**Issue by mamat489** [helmfile/helmfile#1335]
### Operating system

Windows 10 - Cygwin Bash

### Helmfile Version

0.161.0

### Helm Version

v3.13.3

### Bug description

I'm trying to use semver range (like >=0.14 , * ) but when trying to mkdir the folder it fail.

### Example helmfile.yaml

```yaml
- chart: oci://xxx.com/charts/xx
  version: '*'  <==
  namespace: xx
  name: xyy
  values:
  - image:
      registry: onpremise-registry
      repository: xx/yy
      tag: latest
      pullPolicy: Always
      pullSecrets:
      - pull-secret-raw
    args:
    - yy
```

### Error message you've seen (if any)

```bash
helmfile template

Pulling xxx/charts/yyy:*

PATH:
  C:\ProgramData\chocoportable\bin\helm.exe

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://xxx/charts/yyy(49 bytes)
  3: --version (9 bytes)
  4: * (1 bytes)
  5: --destination (13 bytes)
  6: C:\Users\aa\Documents\Logiciels\cygwin\tmp\helmfile718317249\yyyy\aaa\yyy\* (94 bytes)
  7: --untar (7 bytes)


STDERR:
  Pulled: xxx/charts/yyy:0.5.2
  Error: failed to untar (mkdir): mkdir C:\Users\aa\Documents\Logiciels\cygwin\tmp\helmfile718317249\yyyy\aaa\yyy\* : La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.


### Steps to reproduce

Using all semver notation except exact one.

### Working Helmfile Version

N/A

### Relevant discussion

_No response_
