### ISSUE TITLE
Regression in v0.162.0: helmfile deps uses the wrong path for kustomizations

### ISSUE THREAD

**Issue by jeliebig** [helmfile/helmfile#1402]
### Operating system

Arch Linux

### Helmfile Version

v0.162.0

### Helm Version

v3.14.2

### Bug description

After updating from `v0.161.0` I've been unable to run `helmfile deps` successfully. It always errors when running the helm upgrade commands for kustomizations.

From the output you can see that it tries to run the upgrade command on the original kustomization path instead of the generated temporary chart like it used to.

### Example helmfile.yaml

```yaml
repositories:
  # Only required because helmfile deps doesn't execute without them
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: test
    chart: ./test
````

### Error message you've seen (if any)

````
in ./helmfile.yaml: command "/usr/bin/helm" exited with non-zero status:

PATH:
  /usr/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: update (6 bytes)
  3: ./test (6 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Chart.yaml file is missing

COMBINED OUTPUT:
  Error: Chart.yaml file is missing
````

### Steps to reproduce

https://github.com/jeliebig/helmfile-deps-kustomization-issue

### Working Helmfile Version

0.161.0
