### ISSUE TITLE
Local ad-hoc chart dependencies not working as described by documentation

### ISSUE THREAD

**Issue by AlexDCraig** [helmfile/helmfile#1407]
### Operating system

MacOS

### Helmfile Version

v0.162.0

### Helm Version

v3.14.3

### Bug description

According to the [https://github.com/helmfile/helmfile/blob/main/docs/advanced-features.md#adding-dependencies-without-forking-the-chart](docs), you can mark a Helm chart as a dependency after the fact using Helmfile. But when I attempt to do so, I get unexpected results.

For one, ``version`` is not indicated as required. But when I don't use it, I get:

````shell
OUTPUT:
  Error: dependency "istio-operator" has an invalid version/constraint format: improper constraint: ]
````

For two, when I include ``version``, I get the following error:

````shell
  Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: istio-operator
````

### Example helmfile.yaml

````yaml
  - name: istio-operator
    chart: ./charts/istio-operator
    namespace: istio-operator

  - name: istio-profile
    chart: ./charts/istio-profile
    dependencies:
      - chart: ./charts/istio-operator
        version: 6.0.2
````

Chart.yaml for istio-operator:

````yaml
apiVersion: v1
name: istio-operator
version: 6.0.2
appVersion: 1.19.3
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/1.19.3/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
````

Chart.yaml for istio-profile:

````yaml
apiVersion: v2
name: istio-profile
version: 6.0.2
appVersion: 1.19.3
description: Helm chart for deploying a profile for the Istio operator
keywords:
  - istio
  - operator
  - profile
sources:
  - https://github.com/istio/istio/tree/1.19.3/operator
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
````

### Error message you've seen (if any)

Included in bug description.

### Steps to reproduce

Will make this if we determine this issue isn't completely user error.

### Working Helmfile Version

Not aware of one.
