### ISSUE TITLE
Helmfile does not delete custom object

### ISSUE THREAD

**Issue by hconnan** [helmfile/helmfile#1427]
### Operating system

macOS 14.3 (23D56) M1 Pro

### Helmfile Version

v0.163.1

### Helm Version

version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.22.1"}

### Bug description

I am using helmfile to deploy Victoria Metrics.

When I delete the release which matches the vmcluster stack, this release is deleted as expected. But helmfile does not delete the `vmcluster` object in the namespace associated to this release.

Is helmfile able to delete custom objects ?

For the context, we deploy the Victoria Metrics stacks using helmfile into a GKE cluster.

### Example helmfile.yaml

FYI some data are anonymous.

This is the helmfile:

```yaml
bases:
  - bases/environments.yaml
  - bases/helmDefaults.yaml
  - bases/repositories.yaml

{{ readFile "bases/templates.yaml" }}

releases:
  - name: vm-operator
    chart: vm/victoria-metrics-operator
    namespace: monitoring-{{`{{ .Environment.Name }}`}}
    labels:
      monitoring: operator
    <<: *default
  - name: vm-cluster
    chart: vm/victoria-metrics-k8s-stack
    namespace: monitoring-{{`{{ .Environment.Name }}`}}
    labels:
      monitoring: cluster
    <<: *default
```

In config/release/vm-cluster, we got this `comon.gotpl` file:

```
# -----------------------------------------------------------------------------
# VM Cluster
# -----------------------------------------------------------------------------
serviceAccount:
  create: true
  name: {{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.cluster.storage.serviceAccount }}

vmcluster:
  enabled: true
  spec:
    retentionPeriod: {{ .Values.cluster.retentionPeriod | quote }}
    replicationFactor: {{ .Values.cluster.replicationFactor }}
    serviceAccountName: {{ .Release.Name }}
    vmstorage:
      replicaCount: {{ .Values.cluster.storage.replicaCount }}
      extraArgs:
        search.maxUniqueTimeseries: "0"
      image:
        tag: {{ .Values.cluster.image.version }}-cluster
      {{- if .Values.cluster.storage.enableSnapshotRestore }}
      initContainers:
        - name: restore-snapshot
          image: "victoriametrics/vmrestore:{{ .Values.cluster.image.version }}"
          command:
            - /bin/sh
            - -c
            # ./vmrestore -src=<storageType>://<path/to/backup> -storageDataPath=<local/path/to/restore>
            - "/vmrestore-prod -storageDataPath=/vm-data -src=gs://{{ .Values.cluster.storage.bucket_backup_metrics }}/vmstorage-snapshots/{{ .Values.cluster.storage.restoreDate | default "latest" }}/{{ .Release.Namespace }}-$POD_NAME"
          volumeMounts:
            - mountPath: /vm-data
              name: vmstorage-db
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      {{- end }}
      # if enableSnapshot
      {{- if .Values.cluster.storage.enableSnapshot }}
      containers:
        - name: hourly-sidecar-backup
          command:
            - /bin/sh
            - -c
            - |
              sleep 40
              while true; do
                  # every hour we create a snapshot and upload it to latest
                  /vmbackup-prod \
                      -storageDataPath=/vm-data \
                      -snapshot.createURL=http://localhost:8482/snapshot/create \
                      -dst=gs://{{ .Values.cluster.storage.bucket_backup_metrics }}/vmstorage-snapshots/latest/{{ .Release.Namespace }}-$POD_NAME
                  # if its 5am we also upload the daily snapshot
                  if [ $(date +%H) -eq "05" ]; then
                     /vmbackup-prod \
                        -storageDataPath=/vm-data \
                        -snapshot.createURL=http://localhost:8482/snapshot/create \
                        -dst=gs://{{ .Values.cluster.storage.bucket_backup_metrics }}/vmstorage-snapshots/daily-$(date +%d-%m-%Y)/{{ .Release.Namespace }}-$POD_NAME
                  fi
                  sleep 1h
              done
          image: "victoriametrics/vmbackup:{{ .Values.cluster.image.version }}"
          volumeMounts:
            - mountPath: /vm-data
              name: vmstorage-db
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      {{- end }}
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: {{ .Values.cluster.storage.size }}
      resources:
        requests:
          cpu: "4"
          memory: "16000Mi"
        limits:
          cpu: "4"
          memory: "16000Mi"
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }} 
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }} 
    vmselect:
      replicaCount: {{ .Values.cluster.select.replicaCount }}
      extraArgs:
        search.maxLabelsAPIDuration: "30s"
        search.maxLabelsAPISeries: "30000000"
        search.maxUniqueTimeseries: "0"
        search.maxSeries: "30000000"
        search.maxQueueDuration: "30s"
      image:
        tag: {{ .Values.cluster.image.version }}-cluster
      resources:
        limits:
          cpu: "1"
          memory: "1000Mi"
        requests:
          cpu: "0.5"
          memory: "500Mi"
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }} 
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }} 
    vminsert:
      replicaCount: {{ .Values.cluster.insert.replicaCount }}
      extraArgs:
        maxLabelsPerTimeseries: "10000000"
      image:
        tag: {{ .Values.cluster.image.version }}-cluster
      resources:
        limits:
          cpu: "2"
          memory: 1000Mi
        requests:
          cpu: "1.5"
          memory: "500Mi"
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }} 
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }} 
    
  ingress:
    storage:
      enabled: false
    select:
      enabled: {{ .Values.cluster.ingress.select.enabled }}
      hosts: 
        - {{ .Values.cluster.ingress.select.host }}
      ingressClassName: {{ .Values.cluster.ingressClassName }}
      tls: 
        - secretName: {{ .Values.cluster.tlsSecretName }} 
    insert:
      enabled: {{ .Values.cluster.ingress.insert.enabled }}
      hosts: 
        - {{ .Values.cluster.ingress.insert.host }}
      ingressClassName: {{ .Values.cluster.ingressClassName }}
      tls: 
        - secretName: {{ .Values.cluster.tlsSecretName }} 

# -----------------------------------------------------------------------------
# VMAgent
# -----------------------------------------------------------------------------
vmagent:
  enabled: true
  spec:
    selectAllByDefault: true
    scrapeInterval: 30s
    replicaCount: 2
    resources:
      limits:
        cpu: "1000m"
        memory: 1000Mi
      requests:
        cpu: "100m"
        memory: "300Mi"
    image:
      tag: {{ .Values.cluster.image.version }}
    externalLabels:
      cluster: infra
      environment: {{ .Environment.Name }}
    ignoreNamespaceSelectors: false
    serviceScrapeNamespaceSelector:
      matchLabels: 
        kubernetes.io/metadata.name: monitoring-{{ .Environment.Name }}
    extraArgs:
      {{- toYaml .Values.cluster.agent.extraArgs | nindent 6 }}
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 6 }} 
    tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}
    inlineRelabelConfig:
      - source_labels: [service]
        target_label: gce_instance

# -----------------------------------------------------------------------------
# VMAlert
# -----------------------------------------------------------------------------
vmalert:
  enabled: true
  spec:
    selectAllByDefault: true
    extraArgs:
      notifier.blackhole: "true"
    replicaCount: 2
    image:
      tag: {{ .Values.cluster.image.version }}
    logLevel: INFO
    logFormat: json
    resources:
        limits:
          cpu: "100m"
          memory: 200Mi
        requests:
          cpu: "50m"
          memory: "100Mi"
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 8 }} 
    tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
    inlineRelabelConfig:
      - source_labels: [service]
        target_label: gce_instance
  ingress:
    enabled: {{ .Values.cluster.ingress.alert.enabled }}
    hosts: 
      - {{ .Values.cluster.ingress.alert.host }}
    ingressClassName: {{ .Values.cluster.ingressClassName }}
    tls: 
      - secretName: {{ .Values.cluster.tlsSecretName }} 


# -----------------------------------------------------------------------------
# Additionnal scraping
# -----------------------------------------------------------------------------
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  nameOverride: "kube-state-metrics-{{ .Environment.Name }}"
  rbac:
    useClusterRole: true
  enabled: true
  replicas: 1
  namespaces: "monitoring-{{ .Environment.Name }}"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
kubelet:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false
defaultRules:
  create: false
  rules:
    etcd: false
    general: false
    k8s: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubelet: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    node: false
    vmagent: false
    vmsingle: false
    vmhealth: false
    vmcluster: false
    alertmanager: false

## enable vm operator crds from k8s-stack
crds:
  enabled: false
```

In environments/staging, we have the `cluster.yaml` file which contains the values:

```yaml
cluster:
  ingress:
    select:
      enabled: true
      host: "vmselect-staging.victoria-metrics.services.local"
    insert:
      enabled: true
      host: "vminsert-staging.victoria-metrics.services.local"
    alert:
      enabled: true
      host: "vmalert-staging.victoria-metrics.services.local"
  storage:
    serviceAccount: test@test.iam.gserviceaccount.com
    bucket_backup_metrics: test
  name: vm-cluster
  image: 
    repository: victoriametrics/victoria-metrics
    version: v1.99.0
  retentionPeriod: "3"
  replicationFactor: 2
  storage:
    enableSnapshotRestore: false
    enableSnapshot: true
    # latest or dd-mm-YYYY
    restoreDate: latest
    replicaCount: 3
    size: 2000Gi # vmstorage disk size (this comment is for monitoring team... do not remove)
  insert:
    replicaCount: 2
  select:
    replicaCount: 2
  agent: # Extra args for every agent deployed
    extraArgs:
      enableTCP6: "true"
      promscrape.suppressScrapeErrorsDelay: 120s
      promscrape.maxScrapeSize: "33554432"
  ingressClassName: "traefik"
  tlsSecretName: tls-certs
```

### Error message you've seen (if any)

N/A

### Steps to reproduce

From the`helm` folder, run: `helmfile apply -e staging -l 'monitoring=cluster'`

### Working Helmfile Version

N/A
