### ISSUE TITLE
needs evaluated even if 'installed: false'

### ISSUE THREAD

**Issue by jim-barber-he** [helmfile/helmfile#1464]
### Operating system

Debian stable (12 bookworm)

### Helmfile Version

0.163.1

### Helm Version

v3.14.4

### Bug description

If a release in `helmfile.gotmpl.yaml` has a `needs` statement but also its `installed` directive evaluates to `false` then the release referenced by the needs still gets installed.

### Example helmfile.yaml

For example we had the following where the `installed` is evaluated on each cluster where only our monitoring cluster sets `DEPLOY_ELASTALERT` to `true`.
On the other clusters it'll still install the content from the `elastalert-additions` release even though `elastalert` is not being installed.

```yaml
  - name: elastalert-additions
    namespace: elastalert
    chart: ./helm/charts/elastalert-additions
    values:
      - helm/vars/elastalert.yaml.gotmpl
  
  - name: elastalert
    namespace: elastalert
    chart: elastalert2/elastalert2
    installed: {{ (env "DEPLOY_ELASTALERT") | default "false" }}
    labels:
      app: elastalert
    needs:
      - elastalert/elastalert-additions
    values:
      - helm/vars/elastalert.yaml.gotmpl
```

I can fix this by adding the following to the `elastalert-additions` release as well:
```
    installed: {{ (env "DEPLOY_ELASTALERT") | default "false" }}
```
However then on the clusters where `installed` evaluates to `false` the following warning is produced:
```
WARNING: release elastalert needs elastalert-additions, but elastalert-additions is not installed due to installed: false. Either mark elastalert-additions as installed or remove elastalert-additions from elastalert's needs
```

### Error message you've seen (if any)

No error messages. Just that it is installing "needed" releases for releases where `installed: false` is in place.
Sometimes that in itself can lead to other unrelated errors (say the cluster involved doesn't has the necessary namespace for that release for example).
All the detail is above.

### Steps to reproduce

See above.

### Working Helmfile Version

This probably never worked.

**Comment by yxxhero** [comment]
@jim-barber-he PR is welcome.

**Comment by jim-barber-he** [comment]
Would if I could. I don't know `go`.

**Comment by yxxhero** [comment]
@jim-barber-he thanks. could you give me some example.

**Comment by jim-barber-he** [comment]
Ok

Here's an example of using the `deliveryhero/cluster-overprovisioner` Helm chart that deploys the `registry.k8s.io/pause:3.9` image that basically does nothing but sit there.
That image runs with a custom priority class.

Below I've tried to create a self contained `helmfile.yaml` file with values to demonstrate the problem.

```yaml
releases:

  - name: prerequisites
    namespace: example
    chart: deliveryhero/cluster-overprovisioner
    values:
      - deployments:
          - replicaCount: 1
            resources:
              requests:
                cpu: 10m
                memory: 8Mi
        priorityClassDefault:
          enabled: false
        priorityClassOverprovision:
          name: prerequisites
        serviceAccount:
          create: false
          name: default

  - name: example
    namespace: example
    chart: deliveryhero/cluster-overprovisioner
    installed: false
    needs:
      - example/prerequisites
    values:
      - deployments:
          - replicaCount: 1
            resources:
              requests:
                cpu: 10m
                memory: 8Mi
        priorityClassDefault:
          enabled: false
        priorityClassOverprovision:
          name: example
        serviceAccount:
          create: false
          name: default

repositories:

  - name: deliveryhero
    url: https://charts.deliveryhero.io/
```

There is a release called `example` that needs a release called `prerequisites`.
These would be deployed into a namespace called `example`.
I've set `installed: false` for the `example` release since I don't want it to install, and by extension that means I don't want `prerequisites` installed.

Running a deploy like so:
```
helmfile --interactive apply -l name=example apply --include-needs
```
Results in it wanting to install the `prerequisites` release.
```
$ helmfile --interactive apply -l name=example apply --include-needs
Adding repo deliveryhero https://charts.deliveryhero.io/
"deliveryhero" has been added to your repositories

Comparing release=prerequisites, chart=deliveryhero/cluster-overprovisioner
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
example, prerequisites, PriorityClass (scheduling.k8s.io) has been added:
- 
+ # Source: cluster-overprovisioner/templates/priorityclass-overprovision.yaml
+ apiVersion: scheduling.k8s.io/v1
+ kind: PriorityClass
+ metadata:
+   name: prerequisites
+   labels:
+     app.kubernetes.io/name: cluster-overprovisioner
+     helm.sh/chart: cluster-overprovisioner-0.7.11
+     app.kubernetes.io/instance: prerequisites
+     app.kubernetes.io/version: "3.9"
+     app.kubernetes.io/managed-by: Helm
+ value: -1
+ globalDefault: false
+ description: "Priority class used for overprovision pods"
example, prerequisites-cluster-overprovisioner-, Deployment (apps) has been added:
- 
+ # Source: cluster-overprovisioner/templates/deployments.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: "prerequisites-cluster-overprovisioner-"
+   namespace: example
+   labels:
+     app.kubernetes.io/name: cluster-overprovisioner
+     helm.sh/chart: cluster-overprovisioner-0.7.11
+     app.kubernetes.io/instance: prerequisites
+     app.kubernetes.io/version: "3.9"
+     app.kubernetes.io/managed-by: Helm
+     app.cluster-overprovisioner/deployment: 
+ spec:
+   strategy:
+     type: Recreate
+   replicas: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: cluster-overprovisioner
+       app.kubernetes.io/instance: prerequisites
+       app.cluster-overprovisioner/deployment: 
+   template:
+     metadata:
+       labels:
+         app.kubernetes.io/name: cluster-overprovisioner
+         helm.sh/chart: cluster-overprovisioner-0.7.11
+         app.kubernetes.io/instance: prerequisites
+         app.kubernetes.io/version: "3.9"
+         app.kubernetes.io/managed-by: Helm
+         app.cluster-overprovisioner/deployment: 
+     spec:
+       serviceAccountName: default
+       priorityClassName: prerequisites
+       securityContext:
+         {}
+       containers:
+         - name: cluster-overprovisioner
+           image: "registry.k8s.io/pause:3.9"
+           imagePullPolicy: IfNotPresent
+           resources:
+             requests:
+               cpu: 10m
+               memory: 8Mi

Listing releases matching ^example$
Affected releases are:
  prerequisites (deliveryhero/cluster-overprovisioner) UPDATED

Do you really want to apply?
  Helmfile will apply all your changes, as shown above.

 [y/n]: n
```

**Comment by philomory** [comment]
To give another example, I've got a setup like the following:

```yaml
releases:
  - name: vizier
    installed: {{ .Values.pixie.enabled }}
    namespace: pl
    createNamespace: true
    chart: pixie-vizier/pixie-vizier
    values: ...
  - name: newrelic-pixie
    installed: {{ and .Values.pixie.enabled .Values.newrelic.pixie.enabled }}
    needs:
      - pl/vizier
      - newrelic/newrelic-bundle
    namespace: pl
    chart: newrelic/newrelic-pixie
    values: ...
```
( `newrelic/newrelic-bundle` release not pictured here because it's not really relevant)

If `.Values.pixie.enabled` is false, then neither `vizier` nor `newrelic-pixie` should end up installed. But I still get a warning printed:
> WARNING: release newrelic-pixie needs vizier, but vizier is not installed due to installed: false. Either mark vizier as installed or remove vizier from newrelic-pixie's needs

This doesn't make sense, as, while `newrelic-pixie` _does_ need Vizier, and I'm not installing Vizier, I'm not installing `newrelic-pixie` _either_, so the fact that I'm not installing Vizier seems irrelevant.
