### ISSUE TITLE
repo not found when helmfiles

### ISSUE THREAD

**Issue by equick** [helmfile/helmfile#1495]
### Operating system

MacOS

### Helmfile Version

v0.164.0

### Helm Version

3.14.4

### Bug description

I'm trying to set up sub helmfiles as described in https://helmfile.readthedocs.io/en/latest/shared-configuration-across-teams/ in order to split the releases into their own files instead of grouping them all together in the main helmfile.
When running helm apply, it reports the repo is not found, however this works fine is the configuration is all bundled into one file.

### Example helmfile.yaml

* helmfile.yaml
```
helmDefaults:
  createNamespace: true

repositories:
- name: release-charts
  url: 101010101.dkr.ecr.eu-west-1.amazonaws.com/scanned/release/helm-charts
  oci: true

helmfiles:
- myapp.yaml
```
* myapp.yaml
```
releases:
- name: myapp
  namespace: myns
  version: 1.0.0
  values:
    - values.yaml
```

### Error message you've seen (if any)

```
✗ helmfile apply
Comparing release=myapp, chart=release-charts/myapp in ./helmfile.yaml: in .helmfiles[0]: in ./myapp.yaml: command "/Users/equick/homebrew/bin/helm" exited with non-zero status:

PATH:
  /Users/equick/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: myapp (18 bytes)
  5: release-charts/myapp (33 bytes)
  6: --version (9 bytes)
  7: 0.0.1 (11 bytes)
  8: --namespace (11 bytes)
  9: myns (18 bytes)
  10: --values (8 bytes)
  11: /var/folders/nj/cr4qbgmx2pn98hlfv9tqj05r0000gp/T/helmfile301527272/myns-myapp-values-777859ff78 (122 bytes)
  12: --detailed-exitcode (19 bytes)
  13: --color (7 bytes)
  14: --reset-values (14 bytes)

 ERROR:
 exit status 1

 EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: repo release-charts not found
  Error: plugin "diff" exited with error
```

### Steps to reproduce

https://github.com/equick/helmfile-releases/tree/main

### Working Helmfile Version

v0.164.0

**Comment by sebastienrospars** [comment]
I have the same issue when I declare an OCI repository in dedicated file ecr-oci.yaml.gotmpl : 
```
repositories:
  - name: ecr-oci
    url: "000000000000.dkr.ecr.eu-west-1.amazonaws.com"
    oci: true
    username: 'AWS'
    password: '{{ requiredEnv "ECR_PASSWORD" }}'
```
and I use it 

```
bases:
  - config/environments.yaml
  - config/ecr-oci.yaml.gotmpl

---

releases:
  - name: "aws-storage-class-{{ .Environment.Name }}"
    namespace: "kube-system"
    labels:
      chart: "raw"
      namespace: "kube-system"
    chart: "ecr-oci/raw"
    installed: {{ hasKey .Values "enableAwsStorageClass" }}
    {{- if hasKey .Values "enableAwsStorageClass" }}
    version: "1.0.0"
    {{- end }}
    values:
      - config/07-aws-storage-class/default.yaml.gotmpl
```

When I don't use the repository and i put directly the oci url it's work : 

```
bases:
  - config/environments.yaml

---

releases:
  - name: "aws-storage-class-{{ .Environment.Name }}"
    namespace: "kube-system"
    labels:
      chart: "raw"
      namespace: "kube-system"
    chart: "oci://000000000000.dkr.ecr.eu-west-1.amazonaws.com/raw"
    installed: {{ hasKey .Values "enableAwsStorageClass" }}
    {{- if hasKey .Values "enableAwsStorageClass" }}
    version: "1.0.0"
    {{- end }}
    values:
      - config/07-aws-storage-class/default.yaml.gotmpl
```

**Comment by dmurphy-ambra** [comment]
I just wanted to note that this appears to be a new bug introduced since version 0.158.1 . That version works for us, but version 1.0rc0 does not work with this configuration.

We use the same config as @equick, where the repos.yaml has the repository and the "oci" flag.

It looks like to me that the oci flag is now ignored and helmfile uses HTTP, which of course won't work.

```
STDERR:
  time="2024-05-17T13:28:17-04:00" level=info msg="Error logging in to endpoint, trying next endpoint" error="login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request"
  Error: login attempt to https:/000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request

COMBINED OUTPUT:
  time="2024-05-17T13:28:17-04:00" level=info msg="Error logging in to endpoint, trying next endpoint" error="login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request"
  Error: login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request
in ./helmfile.yaml.gotmpl: command "/usr/local/bin/helm" exited with non-zero status:
```

**Comment by yxxhero** [comment]
got it. I will try fix it today.

**Comment by yxxhero** [comment]
> I just wanted to note that this appears to be a new bug introduced since version 0.158.1 . That version works for us, but version 1.0rc0 does not work with this configuration.
> 
> We use the same config as @equick, where the repos.yaml has the repository and the "oci" flag.
> 
> It looks like to me that the oci flag is now ignored and helmfile uses HTTP, which of course won't work.
> 
> ```
> STDERR:
>   time="2024-05-17T13:28:17-04:00" level=info msg="Error logging in to endpoint, trying next endpoint" error="login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request"
>   Error: login attempt to https:/000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request
> 
> COMBINED OUTPUT:
>   time="2024-05-17T13:28:17-04:00" level=info msg="Error logging in to endpoint, trying next endpoint" error="login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request"
>   Error: login attempt to https://000000000000.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request
> in ./helmfile.yaml.gotmpl: command "/usr/local/bin/helm" exited with non-zero status:
> ```

please post a example.

**Comment by dmurphy-ambra** [comment]
@yxxhero our example is the same the others. here it is:

helmfile.gotmpl.yaml
```
bases:
  - "bases/repos.yaml"
  - "bases/environments.yaml"
---
helmDefaults:
  atomic: true
  createNamespace: true
  cleanupOnFail: true
  timeout: 300
  wait: true
---
releases:
{{- range $release, $config := .Values.releases }}
  {{- if $config.enabled }}
- name: {{ $release }}
  chart: {{ $config.chartRepo }}/{{ $config.chart }}
  version: {{ $config.chartVersion }}
  namespace: {{ $config.namespace}}
  needs:
  {{- range $need := $config.needs }}
    - {{ $need }}
  {{- end }}
  values:
    - environments/common/{{ $config.chart }}.yaml.gotmpl
    - environments/{{ $.Environment.Name }}/{{ $config.chart }}.yaml.gotmpl
  {{- end }}
{{- end }}
```

and bases/repos.yaml:
```
---
repositories:
  - name: ambra-tools-ecr
    url: 000000000000.dkr.ecr.us-east-2.amazonaws.com
    oci: true
    username: 'AWS'
    password: '{{ requiredEnv "ECR_PASSWORD" }}'
  - name: minio
    url: https://charts.min.io/
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
```
