### ISSUE TITLE
Unclear error message when rendering go templates without gotmpl extension in 1.0.0-rc.0 release

### ISSUE THREAD

**Issue by johnyb** [helmfile/helmfile#1498]
### Operating system

MacOS, Debian (most likely independent of OS)

### Helmfile Version

1.0.0-rc.0

### Helm Version

3.14.4

### Bug description

After the upgrade to 1.0.0-rc.0 release, our helmfiles don't render any longer but an error message is shown. See below for a minimal example.

This only happens for ambiguous yaml. If the template is wrapped in a string, as you'd normally do in this context (see “test2” in the example helmfile), you don't even get an error message, but the string is rendered as `{{ .Values.testValue }}`, so no templating applied. Both variants render the same (`uiae` in this case) with 0.164.0 and earlier.

### Example helmfile.yaml

```yaml
repositories:
  - name: dex
    url: https://charts.dexidp.io
---
environments:
  default:
    values:
      - testValue: uiae
---

releases:
  - name: test
    chart: dex/dex
    values:
      - test: {{ .Values.testValue }}
        test2: "{{ .Values.testValue }}"
```

### Error message you've seen (if any)

in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: [6:16] unexpected mapping key
       3 |   - name: test
       4 |     chart: dex/dex
       5 |     values:
    >  6 |       - test: {{ .Values.testValue }}

### Steps to reproduce

example helmfile is a boiled down, minimal version of what breaks. Run `helmfile diff` with the helmfile.yaml above. The dex example repository is just added to have a chart to reference. It's not really needed, but I couldn't find a better way :)

### Working Helmfile Version

0.164.0
