### ISSUE TITLE
Dynamic included values doesn't work anymore in helmfile v1.0.0-rc1

### ISSUE THREAD

**Issue by steffakasid** [helmfile/helmfile#1515]
### Operating system

MacOS Sonoma 14.4.1

### Helmfile Version

v1.0.0-rc1

### Helm Version

v3.14.4

### Bug description

When using helmfile v1.0.0-rc1 or  v0.164.0 (with HELMFILE_V1MODE=true). The following doesn't work anymore:
```
releases:
  - name: "{{ requiredEnv "CHART_NAME" }}"
    chart: ./maas-openshift
    version: "{{ requiredEnv "HELM_CHART_VERSION" }}"
    namespace: "{{ requiredEnv "MONITORING_NAMESPACE" }}"
    values:
      - {{ toYaml .Values  | indent 8 | trim }}
```

Also `name: "{{ requiredEnv "CHART_NAME" }}"` must be quoted in v1.0.0-rc1 which was not necessary in v0.164.0. This seems to be the same issue (even if easier to solve).

### Example helmfile.yaml
```
---
helmDefaults:
  createNamespace: false
  cleanupOnFail: true
  wait: true
  timeout: 1200

values:
  - somedefaults: blub

environments:
  default:
    values:
      - ingress:
          enabled: true
          className: nginx-intranet
          hosts:
            - k8s-dashboard-eks-test.somedomain

        networkPolicy:
          enabled: true

---
repositories:
  - name: kubernetes-dashboard
     url: https://kubernetes.github.io/dashboard/

releases:
  - name: kubernetes-dashboard
    namespace:k8s-dashboard
    version: 6.0.8
    chart: kubernetes-dashboard/kubernetes-dashboard
    values:
      - {{ toYaml .Values  | indent 8 | trim }}
```

### Error message you've seen (if any)
```
in ./test-helmfile.yaml: failed to read test-helmfile.yaml: reading document at index 1: [14:10] unexpected mapping key
      11 |     version: 6.0.8
      12 |     chart: kubedashboard-helm-virtual/kubernetes-dashboard
      13 |     values:
    > 14 |       - {{ toYaml .Values  | indent 8 | trim }}
```
### Steps to reproduce

HELMFILE_V1MODE=true helmfile -f test-helmfile.yaml template

### Working Helmfile Version

v0.164.0
