### ISSUE TITLE
`_*.tpl` files in root directory are not loaded when rendering release values.

### ISSUE THREAD

**Issue by bromine0x23** [helmfile/helmfile#1530]
### Operating system

Windows 10 21H2

### Helmfile Version

0.164.0

### Helm Version

v3.14.4

### Bug description

`_*.tpl` files in root directory are not loaded when rendering release values.

### Example helmfile.yaml

```yaml
# helmfile.yaml.gotmpl
releases:
- name: '{{ include "echo" (dict "Echo" "my-release") }}'
  chart: charts/raw
  values:
  - values/configmap.gotmpl

---
# _helpers.tpl
{{- define "echo" -}}
{{ .Echo | trim }}
{{- end }}

---
# values/configmap.gotmpl
templates:
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ include "echo" (dict "Echo" "my-metadata") }}
  data:
    name: {{ include "echo" (dict "Echo" "my-name") }} 
```

### Error message you've seen (if any)
> Building dependency release=my-release, chart=charts/raw
> in ./helmfile.yaml.gotmpl: failed to render values files "values\\configmap.gotmpl": failed to render values\\configmap.gotmpl], because of template: stringTemplate:6:13: executing "stringTemplate" at <include "echo" (dict "Echo" "my-metadata")>: error calling include: template: no template "echo" associated with template "stringTemplate"

### Steps to reproduce

Run `helmfile template`

### Working Helmfile Version

0.164.0
