### ISSUE TITLE
Wildcard helmfile path not working on windows

### ISSUE THREAD

**Issue by pecanw** [helmfile/helmfile#1560]
### Operating system

Windows 11

### Helmfile Version

0.155.0+

### Helm Version

3.15.0

### Bug description

Helmfile doesn't find referenced "sub" helmfiles when running on **windows**.

It was working up to the version 0.154.0, however after upgrading to any higher version (including latest stable 0.165.0) the helmfiles are not found.

### Example helmfile.yaml

```yaml
environments:
  live:
  test:
---
helmfiles:
  - ./namespaces/myapp/apps/*/helmfile.yaml
```

### Error message you've seen (if any)

err: no releases found that matches specified selector() and environment(test), in any helmfile

### Steps to reproduce

Just put any helmfile into a subpath, e.g. namespaces/myapp/apps/app1/helmfile.yaml and run the  helmfile list -f ./helmfile.yaml -e test

### Working Helmfile Version

0.154.0
