### ISSUE TITLE
0.166 release is broken, no artifacts

### ISSUE THREAD

**Issue by golonzovsky** [helmfile/helmfile#1598]
### Helmfile Version

0.166 https://github.com/helmfile/helmfile/releases/tag/v0.166.0

### Bug description

0.166 release  has no artifacts but marked as `latest`. Github actions which use default settings are failing (404 on pulling executables from latest) 

Seems goreleaser is confused with RC https://github.com/helmfile/helmfile/actions/runs/9679430115/job/26705400894

### Error message you've seen (if any)

```
Run helmfile/helmfile-action@v1.9.1
Install helmfile
  Attempting to download helmfile v0.166.0...
  Error: Unexpected HTTP response: 404
  ```

### Steps to reproduce

run https://github.com/helmfile/helmfile-action with default settings

### Working Helmfile Version

v0.165.0 https://github.com/helmfile/helmfile/releases/tag/v0.165.0

### Relevant discussion

Consider pinning `v0.165.0` in your pipelines until fixed

```yaml
 uses: helmfile/helmfile-action@v1.9.1
  with:
    helmfile-version: 'v0.165.0' # 0.166 is broken, temporary pin
```
