### ISSUE TITLE
`init` does not detect missing `kustomize`

### ISSUE THREAD

**Issue by Kakadus** [helmfile/helmfile#1605]
### Operating system

Arch

### Helmfile Version

0.159.0

### Helm Version

v3.14.3

### Bug description

I don't have `kustomize` installed. Running `helmfile apply` failes because it is not installed. Yet, `helmfile init` does not even check for it being installed and echos `helmfile initialization completed!`.

When using corresponding keys, `helmfile init` should check for `kustomize` and download it.

As a consequence, https://github.com/helmfile/helmfile-action might fail as well, because `kustomize` might not be installed, and setting `helmfile-auto-init` cannot fix that (I did not test that though).

### Example helmfile.yaml

```yaml
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: raw1
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: FOO
  strategicMergePatches:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        bar: BAR
```

### Error message you've seen (if any)

helmfile init : 
```txt
helmfile initialization completed!
```

helmfile apply: 
```txt
Adding repo incubator https://charts.helm.sh/incubator
"incubator" has been added to your repositories

in ./helmfile.yaml: [exec: "kustomize": executable file not found in $PATH

COMMAND:
  kustomize version

OUTPUT:
]
```

### Steps to reproduce

1. Uninstll `kustomize`
2. `helmfile init --force`
3. `helmfile apply`
4. ERROR

demo helmfile: https://github.com/helmfile/helmfile/tree/master/test/advanced/helmfile.yaml

### Working Helmfile Version

n/a
