### ISSUE TITLE
Value `"true"` is not being sent to kubernetes

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [helmfile/helmfile#1606]
### Operating system

summerwind/actions-runner:v2.301.1-ubuntu-20.04 (Github actions)

### Helmfile Version

v0.156.0

### Helm Version

v3.12.3

### Bug description

We are using [retool’s](https://github.com/tryretool/retool-helm) chart on v6.1.1. As far as I can tell there's nothing wrong with the chart as the value is being displayed correctly when running `helmfile apply`.

When applying configuration I can see that it’s supposed to be:

```yaml
- name: "POSTGRES_SSL_ENABLED"
  value: "true"
```

However when it get’s to kubernetes it’s being show as just:

```yaml
- name: "POSTGRES_SSL_ENABLED"
```

### Example helmfile.yaml

```yaml
env:
  POSTGRES_SSL_ENABLED: "true"
```

There are some sensitive information on the rest of the chart configuration, can only share this part.

### Error message you've seen (if any)

There are no error messages, it's applying but with incorrect information.

### Steps to reproduce

-

### Working Helmfile Version

-

**Comment by yxxhero** [comment]
@brunomiranda-hotmart sorry. I couldn't get you. please post a demo.

**Comment by brunomiranda-hotmart** [comment]
Hey @yxxhero while producing more steps to reproduce it _worked_, I'm currently a little bit lost to where to issue is.

# Steps to Reproduce

1. Create a helm chart using command: `helm create test-chart`
2. Add an env section to containers like so:

```yaml
          env:
            - name: DEBUG
              value: "true"
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            {{- with .Values.environmentVariables }}
{{ toYaml . | indent 12 }}
            {{- end }}
```

3. Package the chart using the command `helm package test-chart`
4. Create a helmfile config:

```yaml
releases:
- name: foo
  chart: ./test-chart-0.1.0.tgz
  values:
  - ./chart-values.yaml
```

5. Create the file `chart-values.yaml` with this config:

```yaml
env:
  POSTGRES_SSL_ENABLED: "true"

environmentVariables:
  - name: "POSTGRES_SSL_ENABLED_2"
    value: "true"
```

6. Run `helmfile apply`

## Behavior with retool chart

Environment variables like `POSTGRES_SSL_ENABLED` will be created but without a value. Example:
```yaml
