### ISSUE TITLE
Vals Sops: Error getting data key: 0 successful groups required, got 0

### ISSUE THREAD

**Issue by ServiceTeamPZ** [helmfile/helmfile#1614]
### Operating system

Mac / Linux

### Helmfile Version

0.166.0

### Helm Version

3.15.2

### Bug description

After updating from 0.165.0 which works fine, loading secrets from sops via val doesnt work anymore.

### Example helmfile.yaml
```
environments:
  default:
    values:
      - sopsfile: "ref+sops://{{ requiredEnv "SOPS_FILE" }}?format=yaml"
      - secrets:
          ARTIFACTORY_TOKEN: '{{ .Values.sopsfile  }}/#ARTIFACTORY_TOKEN'
---
releases:
  -
    name: service1
    namespace: service1
    chart: some_repo/service1
    version: {{ requiredEnv "HELM_CHART_VERSION" }}
    createNamespace: true
    missingFileHandler: Info
    values:
      - ./config/default-values.yaml
      - ./config/values.{{ requiredEnv "K8SNAME" }}.yaml.gotmpl

repositories:
  - name: stpzvirtual
    url: https://artifactory.example.com:443/artifactory/some_repo
    username: some_username
    password:  {{ .Environment.Values.secrets.ARTIFACTORY_TOKEN | fetchSecretValue}}


helmDefaults:
  kubeContext: {{ requiredEnv "K8SNAME" }}
  devel: true

```
### Error message you've seen (if any)

in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:17:66: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops:///common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN: Error getting data key: 0 successful groups required, got 0

### Steps to reproduce

already done

### Working Helmfile Version

0.166.0
