### ISSUE TITLE
Vals Sops: Error getting data key: 0 successful groups required, got 0

### ISSUE THREAD

**Issue by dl-mai** [helmfile/helmfile#1615]
### Operating system

Mac / Linux

### Helmfile Version

0.166.0

### Helm Version

3.15.2

### Bug description

After updating from 0.165.0 which works fine, loading secrets from sops via val doesnt work anymore.

### Example helmfile.yaml

```
environments:
  default:
    values:
      - sopsfile: "ref+sops://{{ requiredEnv "SOPS_FILE" }}?format=yaml"
      - secrets:
          ARTIFACTORY_TOKEN: '{{ .Values.sopsfile  }}/#ARTIFACTORY_TOKEN'
---
releases:
  -
    name: service1
    namespace: service1
    chart: some_repo/service1
    version: {{ requiredEnv "HELM_CHART_VERSION" }}
    createNamespace: true
    missingFileHandler: Info
    values:
      - ./config/default-values.yaml
      - ./config/values.{{ requiredEnv "K8SNAME" }}.yaml.gotmpl

repositories:
  - name: stpzvirtual
    url: https://artifactory.example.com:443/artifactory/some_repo
    username: some_username
    password:  {{ .Environment.Values.secrets.ARTIFACTORY_TOKEN | fetchSecretValue}}


helmDefaults:
  kubeContext: {{ requiredEnv "K8SNAME" }}
  devel: true

```

### Error message you've seen (if any)

in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:17:66: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops:///common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN: Error getting data key: 0 successful groups required, got 0

### Steps to reproduce

run helmfile write-values 

### Working Helmfile Version

0.166.0

**Comment by yxxhero** [comment]
@dl-mai need more logs by add --debug flag. thanks so much.

**Comment by patrickdomnick** [comment]
Hey we have the same issue and I did just apply the debug flag. There wasn't really more information on the error:

```
err: release "service" in "helmfile.yaml" failed: failed processing release service: failed to render values files "service.yaml": expand sops://secrets/service-secret.json?format=json: Error getting data key: 0 successful groups required, got 0
in helmfile.yaml: failed processing release service: failed to render values files "service.yaml": expand sops://secrets/service-secret.json?format=json: Error getting data key: 0 successful groups required, got 0
```

The SOPS file is encrypted by AWS KMS and the problem only occurs with Helmfile 0.166.0.
I omitted the rendered values since they contain secrets from AWS Secretsmanager which can still be decrypted.

**Comment by dl-mai** [comment]
Sorry for the delay. Added logs with debug flag:
```
processing file "helmfile.yaml" in directory "."
changing working directory to "/Users/johndoe/development/my_project/k8s-cluster/my_cluster/my_service"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default  map[] map[]}, overrode=<nil>
first-pass uses: &{default  map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: environments:
 1:   default:
 2:     values:
 3:       - sopsfile: "ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml"
 4:       - secrets:
 5:           ARTIFACTORY_TOKEN_STAGE: '<no value>/#ARTIFACTORY_TOKEN_STAGE'

replaced <no value>s to workaround https://github.com/golang/go/issues/24963 to address https://github.com/roboll/helmfile/issues/553:
  strings.Join({
  	... // 81 identical bytes
  	"mai/development/my_project/shared-values/common-secrets.yaml?fo",
  	"rmat=yaml\"\n      - secrets:\n          ARTIFACTORY_TOKEN_STAGE: '",
- 	"<no value>",
  	"/#ARTIFACTORY_TOKEN_STAGE'",
  }, "")

first-pass produced: &{default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
vals:
map[secrets:map[ARTIFACTORY_TOKEN_STAGE:/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: environments:
 1:   default:
 2:     values:
 3:       - sopsfile: "ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml"
 4:       - secrets:
 5:           ARTIFACTORY_TOKEN_STAGE: 'ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE'

merged environment: &{default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
first-pass rendering starting for "helmfile.yaml.part.1": inherited=&{default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}, overrode=<nil>
first-pass uses: &{default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
first-pass rendering input of "helmfile.yaml.part.1":
 0: releases:
 1:   -
 2:     name: my_service
 3:     namespace: my_service
 4:     chart: my_helm_repo/my_service
 5:     version: {{ requiredEnv "HELM_CHART_VERSION" }}
 6:     createNamespace: true
 7:     missingFileHandler: Info
 8:     values:
 9:       - ./config/default-values.yaml
10:       - ./config/values.{{ requiredEnv "K8SNAME" }}.yaml.gotmpl
11:
12: repositories:
13:   - name: my_helm_repo
14:     url: https://bahnhub.tech.rz.db.de:443/artifactory/stpz-helm-virtual
15:     username: techuser-stage-stpz
16:     password:  {{ .Environment.Values.secrets.ARTIFACTORY_TOKEN_STAGE | fetchSecretValue}}
17:
18:
19: helmDefaults:
20:   kubeContext: {{ requiredEnv "K8SNAME" }}
21:   devel: true
22:

template syntax error: template: stringTemplate:17:72: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE: Error getting data key: 0 successful groups required, got 0
first-pass rendering output of "helmfile.yaml.part.1":
 0: releases:
 1:   -
 2:     name: my_service
 3:     namespace: my_service
 4:     chart: my_helm_repo/my_service
 5:     version: 0.46.7
 6:     createNamespace: true
 7:     missingFileHandler: Info
 8:     values:
 9:       - ./config/default-values.yaml
10:       - ./config/values.my_cluster-tsta.yaml.gotmpl
11:
12: repositories:
13:   - name: my_helm_repo
14:     url: https://bahnhub.tech.rz.db.de:443/artifactory/stpz-helm-virtual
15:     username: techuser-stage-stpz
16:     password:

first-pass produced: &{default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
first-pass rendering result of "helmfile.yaml.part.1": {default  map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml] map[]}
vals:
map[secrets:map[ARTIFACTORY_TOKEN_STAGE:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE] sopsfile:ref+sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml]
defaultVals:[]
second-pass rendering failed, input of "helmfile.yaml.part.1":
 0: releases:
 1:   -
 2:     name: my_service
 3:     namespace: my_service
 4:     chart: my_helm_repo/my_service
 5:     version: {{ requiredEnv "HELM_CHART_VERSION" }}
 6:     createNamespace: true
 7:     missingFileHandler: Info
 8:     values:
 9:       - ./config/default-values.yaml
10:       - ./config/values.{{ requiredEnv "K8SNAME" }}.yaml.gotmpl
11:
12: repositories:
13:   - name: my_helm_repo
14:     url: https://bahnhub.tech.rz.db.de:443/artifactory/stpz-helm-virtual
15:     username: techuser-stage-stpz
16:     password:  {{ .Environment.Values.secrets.ARTIFACTORY_TOKEN_STAGE | fetchSecretValue}}
17:
18:
19: helmDefaults:
20:   kubeContext: {{ requiredEnv "K8SNAME" }}
21:   devel: true
22:

err: error during helmfile.yaml.part.1 parsing: template: stringTemplate:17:72: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE: Error getting data key: 0 successful groups required, got 0
changing working directory back to "/Users/johndoe/development/my_project/k8s-cluster/my_cluster/my_service"
in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:17:72: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops:///Users/johndoe/development/my_project/shared-values/common-secrets.yaml?format=yaml/#ARTIFACTORY_TOKEN_STAGE: Error getting data key: 0 successful groups required, got 0
```

**Comment by yxxhero** [comment]
@patrickdomnick I will fix this.

**Comment by yxxhero** [comment]
we are using https://github.com/getsops/sops/releases/tag/v3.9.0, maybe we should see the new sops docs.

**Comment by yxxhero** [comment]
@patrickdomnick @dl-mai  could you show your sops file content? so I can debug it and find the reason.

**Comment by dl-mai** [comment]
I have created a simplified sops file witih gpg and interestingly this worked correctly.  It seems like it is an issue when using aws kms for encryption. 

```
ARTIFACTORY_TOKEN_STAGE: ENC[AES256_GCM,data:<encoded_stuff>,type:str]
sops:
    kms:
        - arn: kms_arn
          role: role_arn
          created_at: "2024-06-17T17:54:57Z"
          enc: <encoded stuff>
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-17T18:51:02Z"
    mac: ENC[AES256_GCM,data:encoded_stuff,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
```
