### ISSUE TITLE
`--args` parameters doesn't work along with a kustomize patch

### ISSUE THREAD

**Issue by llavaud** [helmfile/helmfile#1623]
### Operating system

MacOS sonoma

### Helmfile Version

v0.166.0

### Helm Version

v3.15.2

### Bug description

When using a `strategicMergePatches`, the arguments (`--args`) passed through the helmfile CLI are not passed for the first `helm template` rendering, they are used only on the latest `helm template` rendering that occurs on the kustomize output (`all.patched.yaml`) but for example an `--api-versions` override here is useless...

See the following debug output:
```
running helm template --debug=false --output-dir=/var/folders/kf/vwr6x12s6j1_6v0j44v300800000gn/T/chartify951191064/foo/helmx.1.rendered foo /var/folders/kf/vwr6x12s6j1_6v0j44v300800000gn/T/chartify951191064/foo

running kustomize build /var/folders/kf/vwr6x12s6j1_6v0j44v300800000gn/T/chartify951191064/foo --output /var/folders/kf/vwr6x12s6j1_6v0j44v300800000gn/T/chartify951191064/foo/all.patched.yaml --enable-alpha-plugins

exec: helm template foo /var/folders/kf/vwr6x12s6j1_6v0j44v300800000gn/T/chartify951191064/foo --api-versions=v1/myApi --debug
```

### Example helmfile.yaml

```yaml
---
releases:
  - name: foo
    chart: ../chart
    strategicMergePatches:
      - apiVersion: policy/v1
        kind: PodDisruptionBudget
        metadata:
          name: foo
          namespace: bar
          annotations:
            patch: ok
```

`helmfile template . --args --api-versions="v1/myApi"`

### Error message you've seen (if any)

overriding an api-versions through the CLI is not take into account when used along a kustomize patch

### Steps to reproduce

https://github.com/LVD-Consulting/helmfile-bug-args

### Working Helmfile Version

none
