### ISSUE TITLE
Regression between 0.167.0 and 1.0.0-rc3? Templating in helmfile.yaml

### ISSUE THREAD

**Issue by rossnet** [helmfile/helmfile#1650]
### Operating system

Ubuntu 22.04.3 LTS

### Helmfile Version

0.167.0 and 1.0.0-rc3

### Helm Version

3.14.2

### Bug description

I am not sure if it is a regression between 0.167.0 and 1.0.0-rc3 I am experiencing or works as designed (with perspective to 1.0.0). The shown approach causing the error helps us supporting Helmfile (our primary way of deploying things) as well as GitOps strategies like ArgoCD and it seems to break when upgrading to 1.0.0(-rc3).

### Example helmfile.yaml

```
---
environments:
  dev:
    values:
      - "helmfile/environments/dev/*.yaml.gotmpl"
  test:
    values:
      - "helmfile/environments/test/*.yaml.gotmpl"
  prod:
    values:
      - "helmfile/environments/prod/*.yaml.gotmpl"
---
# yamllint disable
helmfiles:
  - path: "./helmfile_generic.yaml"
    values:
      - {{ toYaml .Values | nindent 8 }}
# {{/*
#
#   Use this format from a remote repository
#
#   - path: "git::https://host/repo.git@helmfile_generic.yaml?ref=tag"
#     values:
#       - {{ toYaml .Values | nindent 8 }}
# */}}
...
```

### Error message you've seen (if any)

```
- Helmfiling now namespace <namespace> onto domain <namespace>.<domain>
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: [5:10] unexpected mapping key
       2 | helmfiles:
       3 |   - path: "./helmfile_generic.yaml"
       4 |     values:
    >  5 |       - {{ toYaml .Values | nindent 8 }}
                    ^
       6 | # {{/*
       7 | #
       8 | #  
```

### Steps to reproduce

https://gitlab.opencode.de/bmi/opendesk/deployment/opendesk/-/blob/main/helmfile.yaml

### Working Helmfile Version

0.167.0
