### ISSUE TITLE
jsonPatches is ignored when using helmfile version 0.167.1

### ISSUE THREAD

**Issue by benathere** [helmfile/helmfile#1680]
### Operating system

 Alpine 3.20.1

### Helmfile Version

0.167.1

### Helm Version

3.15.4

### Bug description

Previously, our team was using helmfile v0.157.0 and helm v3.14.3 in a custom docker image that we use locally and in our deployment environment. We upgraded to the latest release `0.167.1` and helm 3.15.4, skipping some versions just to get up-to-date. However, the main reason we wanted to update was to get the `deleteWait` feature that was introduced in v0.160.0. Nevertheless, we upgraded to 0.167.1 and re-ran `helmfile init --force` in our dockerfile

I noticed that once using this version, the `jsonPatches` property on our releases were getting ignored in both `helmfile apply` and `helmfile template` commands.

If I rolled back to install helmfile v0.160.0, but left hellm at 3.15.4, it resolved the issue, and i could get back jsonPatches again.

---
### Example helmfile.yaml
```
# test.yaml
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
values:
  - awsAccountId: "222222222222"
---
releases:
- name: raw2
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          irsa.amazonaws.com/audience: https://identity.my-company.com
          irsa.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/irsa-role
          irsa.amazonaws.com/sts-regional-endpoints: "true"
        name: my-irsa-role
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
      spec:
        template:
          spec:
            containers:
              image: alpine:latest
              name: my-app
  jsonPatches:
    - target:
        version: v1
        kind: ServiceAccount
        name: my-irsa-role
      patch:
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1role-arn
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1audience
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1sts-regional-endpoints
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: "arn:aws:iam::{{ .Values.awsAccountId }}:role/eks-role"
  strategicMergePatches:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/arch: "amd64"
```
### Error message you've seen (if any)

No error messages are shown.

### Steps to reproduce

1. Copy the above helmfile locally
2. Run `helmfile template -f helmfile.yaml` using version 0.167.1
3. Notice output does not contain patches for the ServiceAccount

### Working Helmfile Version

0.160.0

**Comment by yxxhero** [comment]
@benathere could you post some debug log? thanks so much.

**Comment by benathere** [comment]
[strategicMergePatchOverwritesJsonPatch_0_167_1.log](https://github.com/user-attachments/files/16763672/strategicMergePatchOverwritesJsonPatch_0_167_1.log)

command run: `helmfile --debug template -f test.yaml &>> strategicMergePatchOverwritesJsonPatch_0_167_1.log`

```yaml
# test.yaml
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
values:
  - awsAccountId: "222222222222"
---
releases:
- name: raw2
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          irsa.amazonaws.com/audience: https://identity.my-company.com
          irsa.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/irsa-role
          irsa.amazonaws.com/sts-regional-endpoints: "true"
        name: my-irsa-role
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
      spec:
        template:
          spec:
            containers:
              image: alpine:latest
              name: my-app
  jsonPatches:
    - target:
        version: v1
        kind: ServiceAccount
        name: my-irsa-role
      patch:
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1role-arn
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1audience
      - op: remove
        path: /metadata/annotations/irsa.amazonaws.com~1sts-regional-endpoints
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: "arn:aws:iam::{{ .Values.awsAccountId }}:role/eks-role"
  strategicMergePatches:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
      spec:
        template:
          spec:
            nodeSelector:
              kubernetes.io/arch: "amd64"
```

**Comment by yxxhero** [comment]
https://github.com/helmfile/chartify/pull/85
https://github.com/helmfile/chartify/pull/84

**Comment by yxxhero** [comment]
@benathere I found the reason.

**Comment by yxxhero** [comment]
@benathere you can only use one of jsonPatches and strategicMergePatches.

**Comment by yxxhero** [comment]
@benathere I will optimize this issue.

**Comment by yxxhero** [comment]
```
generated and using kustomization.yaml:
kind: ""
apiversion: ""
resources:
- templates/resources.yaml
patches:
- target:
    kind: ServiceAccount
    name: my-irsa-role
    version: v1
  
  path: jsonpatches/patch.0.yaml
patches:
- path: strategicmergepatches/patch.0.yaml
```
