### ISSUE TITLE
Two releases using the same chart in different version fails

### ISSUE THREAD

**Issue by kevinleturc** [helmfile/helmfile#1682]
### Operating system

MacOS 14.3 / OracleLinux 9

### Helmfile Version

v0.167.1

### Helm Version

v3.15.4

### Bug description

We have two releases in our `helmfile.yaml` that use the same chart but in a different version.

Everything used to work as expected but we recently upgraded Helmfile and start having the issue below:
```bash
$ helmfile deps
Adding repo elastic https://helm.elastic.co/
"elastic" has been added to your repositories

Updating dependency /tmp/3432046083
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "elastic" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading elasticsearch from repo https://helm.elastic.co/
Deleting outdated charts

in ./helmfile.yaml: unable to update deps: no resolved dependency found for "elasticsearch", running "helmfile deps" may resolve the issue
```

After digging a bit, we found that the regression is present since Helmfile [v0.161.0](https://github.com/helmfile/helmfile/releases/tag/v0.161.0).

I created a regression test https://github.com/kevinleturc/helmfile/pull/1 that I wanted to fix but I'm struggling to find where the issue can be and where to start looking at (I have few Go knowledges). I would be happy to have another look if you have some pointers to give.

### Example helmfile.yaml
```
repositories:
- name: elastic
  url: https://helm.elastic.co/

releases:
- name: elasticsearch7
  chart: elastic/elasticsearch
  version: 7.17.3
- name: elasticsearch8
  chart: elastic/elasticsearch
  version: 8.5.1

```
### Error message you've seen (if any)

```
in ./helmfile.yaml: unable to update deps: no resolved dependency found for "elasticsearch", running "helmfile deps" may resolve the issue
```

### Steps to reproduce

https://github.com/kevinleturc/helmfile/pull/1

### Working Helmfile Version

v0.160.0
