### ISSUE TITLE
helmfile list returns incorrect labels when a selector is used

### ISSUE THREAD

**Issue by luispabon** [helmfile/helmfile#1753]
### Operating system

Ubuntu 24.04

### Helmfile Version

0.169.1

### Helm Version

3.13.1

### Bug description

When using "helmfile list" with a selector, the labels field is populated with other release metadata that isn't labels. For instance:

```
~ helmfile list        
NAME  	NAMESPACE	ENABLED	INSTALLED	LABELS                   	CHART        	VERSION
my-app	apps     	true   	true     	app:my-app,group:das-apps	charts/my-app	       
~ helmfile list --selector=app=my-app 
NAME  	NAMESPACE	ENABLED	INSTALLED	LABELS                                                           	CHART        	VERSION
my-app	apps     	true   	true     	app:my-app,chart:my-app,group:das-apps,name:my-app,namespace:apps	charts/my-app	       
```

### Example helmfile.yaml

```yaml
---
releases:
  - name: my-app
    namespace: apps
    chart: charts/my-app
    installed: true
    labels:
      app: my-app
      group: das-apps
```

### Error message you've seen (if any)

n/a

### Steps to reproduce

n/a

### Working Helmfile Version

n/a
