### ISSUE TITLE
OCI ad-hoc dependencies don't work like regular ad-hoc dependencies

### ISSUE THREAD

**Issue by dschmidt** [helmfile/helmfile#1756]
### Operating system

openSUSE Tumbleweed

### Helmfile Version

1.0.0-rc.7

### Helm Version

version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}

### Bug description

When I use an OCI repository in an ad-hoc dependency I see an error like this:
```
in ./helmfile.yaml.gotmpl: [failed reading adhoc dependencies: exit status 1

COMMAND:
  helm repo list

OUTPUT:
  Error: no repositories to show]
``` 

I have found a workaround that semi-works, by specifying
```
chart: "oci://{{ .Values.imageRegistry.domain }}/bitnami/postgresql"
```
in the dependency, it does work - but I cannot specify `skipTLSVerify: true` there.

I would anyhow expect that I can just use the OCI repository just like any repository by just specifying `name/chart`, like it's documented (including the skipTLSVerify option).

### Example helmfile.yaml

repositories:
    - name: bitnami-mirror
      url: "{{ .Values.imageRegistry.domain }}/bitnami"
      oci: true
      skipTLSVerify: true

releases:
  - name: whatever
    namespace: whatever
    chart: ./charts/whatever
    dependencies:
      - chart: "bitnami-mirror/postgresql"
        version: "15.5.27"

### Error message you've seen (if any)

see above

### Steps to reproduce

i don't have a public oci registry for reproducing this

### Working Helmfile Version

0.169 and 1rc7 both fail

**Comment by artemis-mike** [comment]
I've got the same issue. 

Error for helmfild diff
```
STDERR:
  Error: Failed to render chart: exit status 1: Error: an error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redis-chart
  Error: plugin "diff" exited with error
```

```
repositories:
  - name: hostingmaloonde
    url: registry-1.docker.io/<private-registry>
    oci: true
    username: {{ env "DOCKER_USERNAME" }}
    password: {{ env "DOCKER_PASSWORD" }}
[...]
releases:
  - name: oauth2-proxy
    namespace: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: 10.1.4
    condition: oauth2-proxy.enabled
    dependencies:
      - chart: oci://registry-1.docker.io/<private-registry>/redis-chart
        version: 23.0.7
    values:
    - ../values/common/{{`{{ .Release.Name }}`}}.yaml
    - ../values/templates/release-values.gotmpl
[...]
```

Installing redis as independent release via oci works just fine.
