### ISSUE TITLE
Cannot apply transformers if Helm chart is empty

### ISSUE THREAD

**Issue by dippynark** [helmfile/helmfile#1757]
### Operating system

macOS Sonoma

### Helmfile Version

 1.0.0-rc.7

### Helm Version

v3.10.1

### Bug description

We have a number of charts that install addons into various clusters. Some of these charts render no resources for clusters for which we don't want to install the corresponding addon. However, for such charts, transformers fail to be applied with the following error:

```
assertion failed: unexpected dir entry "" it must be the abs path to the output directory
```

This appears to be a bug in chartify: https://github.com/helmfile/chartify/blob/6fbcd045d33e638ed6453b62bb2f044af5604e52/replace.go#L144

### Example helmfile.yaml

```yaml
releases:
- name: test
  chart: ./chart
  transformers:
  - apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: unused
    labels:
      foo: bar
    fieldSpecs:
    - path: spec/groups/rules/labels
      create: true
```

The `chart` directory contains the following files:

Chart.yaml:

```yaml
apiVersion: v2
type: application
name: test
version: 0.1.0
```

values.yaml

```yaml
enabled: false
```

templates/configmap.yaml

```yaml
{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
{{- end }}
```

I then get the following error:

```sh
% helmfile template -f config/helmfile/helmfile.yaml
in config/helmfile/helmfile.yaml: [assertion failed: unexpected dir entry "" it must be the abs path to the output directory]
```

Removing the transformer works as expected

Changing `enabled: true` in values.yaml also works as expected

### Error message you've seen (if any)

Provided above

### Steps to reproduce

Provided above

### Working Helmfile Version

N/A
