### ISSUE TITLE
kubeVersion is calculated incorrectly

### ISSUE THREAD

**Issue by RuStyC0der** [helmfile/helmfile#1778]
### Operating system

Manjaro Linux (kernel 6.6.54-2-MANJARO)

### Helmfile Version

0.169.1 (commit 8b16d36)

### Helm Version

v3.16.1

### Bug description

When I'm trying to install helm release(nginx ingress in my case) I get error
`Error: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0` despite my k8s version is `v1.30.6`

When I install same chart with bare helm all works fine

### Example helmfile.yaml

```repositories:
- name: "ingress-nginx"
  url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx-development
    labels:
      app: ingress-nginx-development
    wait: true
    chart: ingress-nginx/ingress-nginx
    disableValidationOnInstall: true
    version: 4.11.2
    namespace: ingress
```

### Error message you've seen (if any)

```
command "/usr/bin/helm" exited with non-zero status:

PATH:
  /usr/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: ingress-nginx-development (25 bytes)
  5: ingress-nginx/ingress-nginx (27 bytes)
  6: --version (9 bytes)
  7: 4.11.2 (6 bytes)
  8: --disable-validation (20 bytes)
  9: --namespace (11 bytes)
  10: ingress (7 bytes)
  11: --detailed-exitcode (19 bytes)
  12: --color (7 bytes)
  13: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  ********************
        Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: Error: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

### Steps to reproduce

helmfile apply

### Working Helmfile Version

not sure, I checked v0.150.0 but issue was still there

**Comment by RuStyC0der** [comment]
Found out that it can be fixed by adding `kubeVersion: v1.30`, like this
```
kubeVersion: v1.30
repositories:
- name: "ingress-nginx"
  url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx-development
    labels:
      app: ingress-nginx-development
    wait: true
    chart: ingress-nginx/ingress-nginx
    disableValidationOnInstall: true
    version: 4.11.2
    namespace: ingress
```
