### ISSUE TITLE
relative paths in included (base) helmfile should be relative to that helmfile itself. 

### ISSUE THREAD

**Issue by kundeng** [helmfile/helmfile#1784]
### Operating system

mac

### Helmfile Version

0.168

### Helm Version

3.16.1

### Bug description

**Bug Report: Incorrect Relative Path Resolution in Base Helmfile**

* * *

**Summary:**

When using the `bases:` feature in Helmfile to include base helmfiles, relative paths specified within these base helmfiles are incorrectly resolved relative to the main `helmfile.yaml` or the current working directory (PWD), instead of being relative to the base helmfile's own location. This causes errors when Helmfile tries to locate files referenced in the base helmfile using relative paths.

* * *

**Details:**

**Issue Description:**

In a Helmfile setup that utilizes the `bases:` directive to include base helmfiles for modularity and reusability, relative paths within the base helmfiles are not resolved as expected. Instead of resolving paths relative to the location of the base helmfile, Helmfile resolves them relative to the directory of the main `helmfile.yaml` or the current working directory. This behavior causes Helmfile to fail when it cannot find the files specified by these relative paths.

**User's Exact Setup:**

**Main `helmfile.yaml`:**

```yaml
helmDefaults:
  cleanupOnFail: false
  verify: true
  wait: true                      # Ensure deployments complete before moving on
  waitForJobs: true               # Wait for any jobs associated with the release
  timeout: 600                    # Increase timeout for complex deployments
  recreatePods: false
  force: false
  historyMax: 10
  createNamespace: true
  devel: false
  reuseValues: false
  skipDeps: false
  cascade: background
  insecureSkipTLSVerify: false

bases:
  - repos.yaml                       # Load shared repositories
  - templates/default-template.yaml  # Load shared template with values and secrets
  - .helmfile-local/helmfile.yaml    # Load personal configurations dynamically

missingFileHandler: Warn          # Suppresses warnings if `.helmfile-local/` is missing

environments:
  dev:
    values:
      - environments/global-env-defaults.yaml  # Global defaults
      - environments/dev-values.yaml           # Development-specific overrides

---
releases:

  - name: splunk-operator-{{ .Environment.Name }}
    namespace: "{{ .StateValues.SPLUNK_OPERATOR_NAMESPACE }}"
    chart: splunk/splunk-operator
    version: "{{ .StateValues.SPLUNK_OPERATOR_VERSION }}"
    inherit:
      - template: default

  - name: splunk-standalone-{{ .Environment.Name }}
    namespace: "{{ .StateValues.SPLUNK_NAMESPACE }}"
    chart: splunk/splunk-enterprise
    inherit:
      - template: default
```

**Base Helmfile (`.helmfile-local/helmfile.yaml`):**

```yaml
environments:
  mymac:
    values:
      - environments/dev-values.yaml           # Base dev environment values
      - .helmfile-local/mymac-values.yaml      # Employee-specific overrides

    kubeContext: "devs"
```

**Issue Encountered:**

When running Helmfile commands, errors occur indicating that Helmfile cannot find the files specified in the base helmfile's `values:` section. Specifically, the relative paths in the base helmfile (`environments/dev-values.yaml` and `.helmfile-local/mymac-values.yaml`) are not resolved relative to the base helmfile's location (`.helmfile-local/`), but relative to the main `helmfile.yaml` or the current working directory.

* * *

**Steps to Reproduce:**

1.  **Directory Structure:**
    
    ```arduino
    project-root/
    ├── helmfile.yaml
    ├── repos.yaml
    ├── templates/
    │   └── default-template.yaml
    ├── environments/
    │   ├── global-env-defaults.yaml
    │   └── dev-values.yaml
    ├── .helmfile-local/
    │   ├── helmfile.yaml
    │   └── mymac-values.yaml
    ├── releases/
    │   ├── splunk-operator/
    │   │   └── values.yaml
    │   └── splunk-standalone/
    │       └── values.yaml
    ```
    
2.  **Main `helmfile.yaml` (As Provided Above)**
    
3.  **Base Helmfile (`.helmfile-local/helmfile.yaml`) (As Provided Above)**
    
4.  **Run Helmfile Command:**
    
    From the `project-root` directory, execute:
    
    ```bash
    helmfile --environment mymac sync
    ```
    
5.  **Observe the Error:**
    
    Helmfile outputs an error similar to:
    
    ```bash
    in .helmfile-local/helmfile.yaml: failed to read environments/dev-values.yaml: no such file or directory
    ```
    
    This indicates that Helmfile is unable to locate the `environments/dev-values.yaml` file as specified in the base helmfile.
    

* * *

**Analysis:**

*   Helmfile is incorrectly resolving the relative paths specified in the base helmfile relative to the main `helmfile.yaml` or the current working directory, instead of the base helmfile's own directory (`.helmfile-local/`).
*   This causes Helmfile to fail when it cannot find the files specified in the base helmfile.

**Expected Behavior:**

*   Relative paths in the base helmfile (`.helmfile-local/helmfile.yaml`) should be resolved relative to the directory where that base helmfile resides.
*   This allows the base helmfile to reference files like `environments/dev-values.yaml` and `.helmfile-local/mymac-values.yaml` relative to its own location, ensuring modularity and reusability.

**Actual Behavior:**

*   Helmfile attempts to resolve the paths relative to the main `helmfile.yaml` location or the current working directory.
*   As a result, Helmfile cannot find the files, leading to errors.

* * *

**Impact:**

*   **Modularity Issues:** Base helmfiles cannot be self-contained, reducing reusability across different projects or environments.
*   **Maintenance Overhead:** Users must adjust relative paths in base helmfiles depending on where they are included, leading to duplication and potential errors.
*   **Unexpected Failures:** Helmfile commands fail when they cannot locate files, disrupting deployment processes and automation pipelines.

* * *

**Workarounds:**

1.  **Use Absolute Paths:**
    
    *   Modify the base helmfile to use absolute paths or paths relative to the main `helmfile.yaml`.
    *   **Drawback:** Reduces portability and requires changes when moving the base helmfile or working in different environments.
2.  **Adjust Paths in Base Helmfile:**
    
    *   Manually update the paths in the base helmfile to account for the directory hierarchy (e.g., prefix paths with `../`).
    *   **Drawback:** Increases complexity and can be error-prone, especially if the directory structure changes.
3.  **Flatten the Configuration:**
    
    *   Avoid using `bases:` and instead merge configurations into a single `helmfile.yaml`.
    *   **Drawback:** Loses the benefits of modularity and separation of concerns.

* * *

**Suggested Resolution:**

*   **Update Helmfile's Path Resolution Logic:**
    
    *   Modify Helmfile so that when processing base helmfiles included via the `bases:` directive, any relative paths within those base helmfiles are resolved relative to the directory where the base helmfile resides.
    *   This behavior would align with user expectations and common practices in configuration management tools.
    *   It would allow base helmfiles to be truly modular and reusable without needing to adjust paths based on where they are included.

* * *

**Environment Details:**

*   **Helmfile Version:** (Please specify the version where the issue occurs)
*   **Helm Version:** (Please specify the Helm version used)
*   **Operating System:** (e.g., macOS 12.5, Ubuntu 20.04)
*   **Kubernetes Cluster:** (Version and relevant details)

* * *

**Reproduction Repository:**

A minimal repository demonstrating the issue can be provided upon request to facilitate troubleshooting and validation.

### Example helmfile.yaml

main helmfile:
```helmDefaults:
bases:
  - repos.yaml                       # Load shared repositories
  - templates/default-template.yaml  # Load shared template with values and secrets
  - .helmfile-local/helmfile.yaml    # Load personal configurations dynamically

missingFileHandler: Warn          # Suppresses warnings if `.helmfile-local/` is missing

...
```

# the included helmfile at .helmfile-local/helmfile.yaml:
```
environments:
  mymac:
    values:
      - environments/dev-values.yaml           # Base dev environment values
      - .helmfile-local/mymac-values.yaml    # Employee-specific overrides

    kubeContext: "devs"
  ```
  
  

  

### Error message you've seen (if any)

can only find environments/dev-values.yaml  specified this way.  Can't use relative path "../environments/dev-values.yaml". 

### Steps to reproduce

???

### Working Helmfile Version

N/A
