### ISSUE TITLE
Error: Failed to render chart: exit status 1

### ISSUE THREAD

**Issue by GiovanniLeo** [helmfile/helmfile#1790]
### Operating system

Mac OS Sequoia 15.0.1

### Helmfile Version

 v0.169.1

### Helm Version

v3.16.2

### Bug description

I got a render error when i try to install a grafana helm chart, that not happened when I tried to install the aws alb controller chart.

### Example helmfile.yaml

```
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: storage
    namespace: motor-control
    chart: ./storage

  - name: alloy
    namespace: monitoring
    chart: grafana/alloy
    values:
      - grafana/alloy/values.yaml
```

### Error message you've seen (if any)

```
Comparing release=alloy, chart=/var/folders/6m/_rf_lvpd1bz05zsczr48860c0000gn/T/chartify1492755826/monitoring/alloy, namespace=monitoring
in ./helmfile.yaml: command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: alloy (5 bytes)
  5: /var/folders/6m/_rf_lvpd1bz05zsczr48860c0000gn/T/chartify1492755826/monitoring/alloy (84 bytes)
  6: --namespace (11 bytes)
  7: monitoring (10 bytes)
  8: --values (8 bytes)
  9: /var/folders/6m/_rf_lvpd1bz05zsczr48860c0000gn/T/helmfile3071393145/monitoring-alloy-values-57f9fb8489 (102 bytes)
  10: --detailed-exitcode (19 bytes)
  11: --color (7 bytes)
  12: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [apiVersion not set, kind not set]
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  ********************
        Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [apiVersion not set, kind not set]
  Error: plugin "diff" exited with error
```

### Steps to reproduce

Try to run the the helmfile that I provided

### Working Helmfile Version

N/A

### Relevant discussion

- https://github.com/roboll/helmfile/issues/1222
-  https://github.com/roboll/helmfile/issues/1195
