### ISSUE TITLE
When using 2 different vault secret paths one of them returns 403 Unauthorized

### ISSUE THREAD

**Issue by digitalray** [helmfile/helmfile#1796]
### Operating system

macOS 15.1 24B83 arm64

### Helmfile Version

0.169.1

### Helm Version

v3.16.3

### Bug description

When referencing 2 different vault secrets paths such as below:

`ref+vault://kv-v2/application/nonprod/devops?proto=http#/alert-url`
`ref+vault://kv-v2/application/nonprod/dev/prometheus?proto=http#/grafana-admin-user`

The app throws the following error:

```shell
err: error during kube-prometheus-stack-helmfile.yaml.part.1 parsing: template: stringTemplate:54:62: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand vault://kv-v2/application/nonprod/devops?proto=http#/alert-url: Error making API request.

URL: GET https://vault.local/v1/sys/internal/ui/mounts/kv-v2/application/nonprod/devops
Code: 403. Errors:

* permission denied
```

However if we use 2 of the same vault secrets paths as below, we do not get any errors
`ref+vault://kv-v2/application/nonprod/dev/prometheus?proto=http#/grafana-admin-user`
`ref+vault://kv-v2/application/nonprod/dev/prometheus?proto=http#/grafana-admin-password`

Tried with lower helmfile versions with no luck

### Example helmfile.yaml

```yaml
---
environments:
  default:
    values:
      - alertmanager:
          alert_webhook: ref+vault://kv-v2/application/nonprod/devops?proto=http#/alert-url
      - grafana:
          admin_user: ref+vault://kv-v2/application/nonprod/dev/prometheus?proto=http#/grafana-admin-user
---
releases:
  - name: kube-prometheus-stack-grafana
    installed: true
    namespace: monitoring
    chart: ../charts/secret
    version: 1.0.4
    values:
      - secretData:
          admin-user: {{ .Values.grafana.admin_user | fetchSecretValue }}
          alert-url: {{ .Values.grafana.alert_webhook | fetchSecretValue }}
```

### Error message you've seen (if any)

```shell
err: error during kube-prometheus-stack-helmfile.yaml.part.1 parsing: template: stringTemplate:54:62: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand vault://kv-v2/application/nonprod/devops?proto=http#/alert-url: Error making API request.

URL: GET https://vault.local/v1/sys/internal/ui/mounts/kv-v2/application/nonprod/devops
Code: 403. Errors:

* permission denied
changing working directory back to "/Users/digitalray/repos/kubernetes/environments/dev/prometheus-operator"
in ./kube-prometheus-stack-helmfile.yaml: error during kube-prometheus-stack-helmfile.yaml.part.1 parsing: template: stringTemplate:54:62: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand vault://kv-v2/application/nonprod/devops?proto=http#/alert-url: Error making API request.

URL: GET https://vault.local/v1/sys/internal/ui/mounts/kv-v2/application/nonprod/devops
Code: 403. Errors:

* permission denied
```

### Steps to reproduce

Use example above to do helmfile -f helmfile diff

### Working Helmfile Version

n/a
