### ISSUE TITLE
vals refs are evaluated without fetchSecretValue / expandSecretRefs

### ISSUE THREAD

**Issue by daveneeley** [helmfile/helmfile#1808]
### Operating system

Ubuntu 22.04 (wsl2)

### Helmfile Version

0.167.1

### Helm Version

3.15.4

### Bug description

I am getting started with `vals` for [remote secret management in helmfile](https://helmfile.readthedocs.io/en/latest/remote-secrets/). It seems that anything starting with `ref+` is immediately expanded and evaluated, even without using `fetchSecretValue` or `expandSecretRefs`.  I had expected that without use of those functions that helmfile would only render the string, not expand it and check the remote source.

The example helmfile is a slightly modified version of [the one in the docs](https://helmfile.readthedocs.io/en/latest/remote-secrets/). 

### Example helmfile.yaml

```
repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  default:
    values:
      - service:
          password: ref+vault://svc/#pass
          login: ref+vault://svc/#login
---
releases:
  - name: service
    namespace: default
    labels:
      cluster: services
      secrets: vault
    chart: stable/svc
    version: 0.1.0
    values:
      - service:
          # these should render strings, not try to expand ref+vault://svc/#login
          login: {{ .Values.service.login }} 
          password: {{ .Values.service.password | quote }}
```

### Error message you've seen (if any)

```
Adding repo stable https://charts.helm.sh/stable
"stable" has been added to your repositories

in ./helmfile.yaml: expand vault://svc/#pass: Get "https://127.0.0.1:8200/v1/sys/internal/ui/mounts/svc": dial tcp 127.0.0.1:8200: connect: connection refused
```

### Steps to reproduce

`helmfile template` with the included helmfile.yaml

### Working Helmfile Version

The error message is the same from at least 0.125.9 and also 0.169.0. Prior to 0.125 the chart in the example doesn't resolve correctly.
