### ISSUE TITLE
`--values` flag not used with jsonPatches

### ISSUE THREAD

**Issue by xabufr** [helmfile/helmfile#1810]
### Operating system

Debian 12/nix

### Helmfile Version

v0.169.0 & master

### Helm Version

v3.16.2

### Bug description

When running `helmfile template --values XXX`, the `--values` flag is not propagated on releases that are patched with Kustomize.

```yaml
# values.yaml
---
configmapData:
  test: toto
```

```bash
helmfile template . --values ./values.yaml
```

Expected output:

```yaml
---
# Source: configmap/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    aaa: bbb
  labels:
    app: test
    chart: configmap
    release: test
    heritage: Helm
  name: test
data:
  test:
    toto
```

Result:

```yaml
---
# Source: configmap/templates/patched_resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    aaa: bbb
  labels:
    app: test
    chart: configmap
    heritage: Helm
    release: test
  name: test
```

If I remove the `jsonPatches` section from helmfile.yaml, the `--values` works as expected.

### Example helmfile.yaml

```yaml
---
repositories:
  - name: k8s-as-helm
    url: https://ameijer.github.io/k8s-as-helm
releases:
  - name: test
    chart: k8s-as-helm/configmap
    version: 1.0.3
    jsonPatches:
      - target:
          version: v1
          kind: ConfigMap
          name: test
        patch:
          - op: add
            path: /metadata/annotations/aaa
            value: bbb
```

### Error message you've seen (if any)

no error

### Steps to reproduce

included

### Working Helmfile Version

none
