### ISSUE TITLE
Possible unmarshalling error

### ISSUE THREAD

**Issue by DragD** [helmfile/helmfile#1829]
### Operating system

Ubuntu 24.04

### Helmfile Version

0.169.1

### Helm Version

3.16.3

### Bug description

Having a file "config-instances.yaml" like:

```yaml    
instanceOne:
  instanceOne-A:
    key1:  val-1
    key2:  val-2
  instanceOne-B:
    key1:  val-3
    key2:  val-4
```
and attempting to produce values with `helmfile write-values` result in error `values file matching "map[key1:val-1 key2:val-2]" does not exist in "."` . Expected is to produce values with the content of `instanceOne-A`.

The only way so far to achieve the expected result is to use yq in the helmfile like:
`{{ $someConfig := exec "sh" (list "-c" "cat config-instances.yaml | yq '.instanceOne.instanceOne-A | . style = \"flow\"' " ) }}`

On the other hand, when the last line in the helmfile is replaced with `- key1: {{ $someConfig  | get "key1" }}` , values are produced as fine.

### Example helmfile.yaml

```yaml
---
releases:
{{ $instances := readFile "config-instances.yaml"  | fromYaml }}
{{ $someConfig := $instances | get "instanceOne" | get "instanceOne-A" }}

  - name: try
    chart: ./try
    values:
      - {{ $someConfig }}
```

### Error message you've seen (if any)

```shell
in ./helmfile.yaml: values file matching "map[key1:val-1 key2:val-2]" does not exist in "."
```

### Steps to reproduce

helmfile write-values --output-file-template="values-A.yaml"

### Working Helmfile Version

none
