### ISSUE TITLE
State values not available in templated values for sub-helmfiles

### ISSUE THREAD

**Issue by tomraithel** [helmfile/helmfile#1832]
### Operating system

macOS

### Helmfile Version

v0.169.1

### Helm Version

v3.16.2

### Current behaviour
When a templated values file is provided to the `helmfiles[n].values` property, it has no access to the current state-values `{{ .Values.xyz }}`. 

### Expected behaviour
I would expect, that the state values are available and can be used in the same way as it works for `releases[n].values`

### Example helmfile.yaml

Example `helmfile.yaml`:
```yaml
environments:
  default:
    values:
      - foo: "bar"

helmfiles:
  - path: ./helmfiles/sub-helmfile.yaml
    values:
      - values.yaml.gotmpl # {{.Values.foo}} is not avaliable here within!
```

Example `values.yaml.gotmpl`
```yaml
foo: {{ .Values.foo }} # Does not work
```

### Error message you've seen (if any)

```
failed to render [/path/to/values.yaml.gotmpl], because of template: stringTemplate:1:15: executing "stringTemplate" at <.Values.foo>: map has no entry for key "foo"
```

### Steps to reproduce

https://github.com/tomraithel/sub-helmfile-demo

### Working Helmfile Version

n/a

**Comment by tomraithel** [comment]
Can I have feedback on this? Is this working as intended?

**Comment by yxxhero** [comment]
```
environments:
  default:
    # here foo is not a key of values?
    # values:
    #   foo: bar
    values:
      - foo: "bar"

helmfiles:
  - path: ./helmfiles/sub-helmfile.yaml
    values:
      - values.yaml.gotmpl # {{.Values.foo}} is not avaliable here within!
```

**Comment by yxxhero** [comment]
@tomraithel

**Comment by yxxhero** [comment]
@tomraithel oh. sorry. I got the issue. ignore my answer.

**Comment by yxxhero** [comment]
@tomraithel from the code. it is not be supported. maybe it's a bug.

**Comment by yxxhero** [comment]
# One important aspect of using values here is that they first need to be defined in the values section
  # of the origin helmfile, so in this example key1 needs to be in the values or environments.NAME.values of path/to/subhelmfile.yaml
  # Inline state values merged into the nested state's values

**Comment by yxxhero** [comment]
@tomraithel the `values` is used for overriding the nested state.

**Comment by tomraithel** [comment]
@yxxhero thanks for your reply.

The thing is, that overriding itself works - but not in combination with a templated values file in the root helmfile.
Take my example repo, If you modify the `/helmfile.yaml` and replace it with inline values, it works:

```
    values:
      - foo: "root-foo"
```

IMHO the behaviour should be the same no matter where the values come from

**Comment by yxxhero** [comment]
Helmfile is designed to run independently. If you rely on root status, this will prevent sub-helmfiles from running independently.

@tomraithel

**Comment by tomraithel** [comment]
Yeah but sub-helmfile is in my case not depending on root values. It's just that root-helmfile uses a template values file to pass values to the sub-helmfile instead of plain values. 
It's basically like a function call where root-helmfile provides the arguments and if root-helmfile would not provide them, the default values from sub-helmfile would be used.

**Comment by tomraithel** [comment]
@yxxhero is there any updated on this?

**Comment by yxxhero** [comment]
@mumoshu WDYT?

**Comment by cb645j** [comment]
@tomraithel did you get this working? I think im having a similiar issue but im trying to pass values.yaml files instead and dont have agotmpl.  My issue https://github.com/helmfile/helmfile/issues/1890

**Comment by tomraithel** [comment]
> [@tomraithel](https://github.com/tomraithel) did you get this working?

@cb645j no, we shipped around this issue for now by passing in the values directly

**Comment by pspurlock** [comment]
This issue seems close to what I'm experiencing when upgrading to v1. This used to work until upgrading to v1:

```
missingFileHandler: Error

helmfiles:
{{ range .Values.myApps }}
- path: ../../apps/{{ . }}
  values:
  - {{ $.Values | toYaml | nindent 6}}
{{ end }}

environments:
  default:
    missingFileHandler: Error
    values:
      - ../../common/state-default-values.yaml
      - ./state-values.yaml
```

Now helmfile will error stating no entry for key myApps. I don't see a way around it beyond explicitly stating the values in my helmfile, which I don't want to do since they are used in multiple areas.

**Comment by eigood** [comment]
The following simple scenario doesn't seem useful to me.  The context available to the yaml.gotmpl is empty, so no conditional logic can happen.  At the least, I'd expect to see `foo:bar` from the `toYaml|nindent` logic.

```yaml
# helmfile.yaml.gotmpl
environments:
  default:
    values:
      - foo: bar
 
helmfiles:
  - path: foo-helmfile.yaml.gotmpl
    values:
      - values/debug-context.yaml.gotmpl

# values/debug-context.yaml.gotmpl
values: {{ .Values | toYaml | nindent 2 }}
environment: {{ .Environment | toYaml | nindent 2 }}
```
