### ISSUE TITLE
OCI Registry authentication

### ISSUE THREAD

**Issue by cyrus-mc** [helmfile/helmfile#1847]
### Operating system

darwin/arm64

### Helmfile Version

v0.169.2

### Helm Version

v0.169.2

### Bug description

According to the documentation on OCI registries - https://helmfile.readthedocs.io/en/latest/#oci-registries - authentication details can be stored in environment variables REGISTRYNAME_USERNAME|PASSWORD.

I have the following repository configured:

```
repositories:
  - name: ociregistry
    oci: true
    url: quay.io/ORG_NAME

releases:
  - name: releaseX
    chart: ociregistry/some-chart
    version: X.Y.Z
```

I then export OCIREGISTRY_USERNAME and OCIREGISTRY_PASSWORD. But in doing so I get 401 error when trying to pull the chart.

I have tried leaving the ORG_NAME off the URL and instead adding it onto the chart (e.g: ociregistry/ORG_NAME/some-chart) but get the same result. The credentials are valid for that registry since I can login to the registry using helm registry login quay.io -u USERNAME and then helmfile commands succeed. 

### Example helmfile.yaml

```
repositories:
  - name: ociregistry
    oci: true
    url: quay.io/ORG_NAME

releases:
  - name: releaseX
    chart: ociregistry/some-chart
    version: X.Y.Z
```

### Error message you've seen (if any)

```
Pulling quay.io/ORG_NAME/SOME_CHART:4.8.0
Pulling registry-1.docker.io/bitnamicharts/redis:20.6.0
in ./helmfile.yaml: [release "xxxxxx": command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://quay.io/ORG_NAME/SOME_CHART (42 bytes)
  3: --version (9 bytes)
  4: 4.8.0 (5 bytes)
  5: --destination (13 bytes)
  6: /var/folders/pr/96mq1ylj31xgxy0hj53ql8tw0000gn/T/helmfile419419267/xxxx/xxxxx/SOME_CHART/4.8.0 (129 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unexpected status from HEAD request to https://quay.io/v2/ORG_NAME/SOME_CHART/manifests/4.8.0: 401 Unauthorized

COMBINED OUTPUT:
  Error: unexpected status from HEAD request to https://quay.io/v2/ORG_NAME/SOME_CHART/manifests/4.8.0: 401 Unauthorized]
```

### Steps to reproduce

N/A

### Working Helmfile Version

v0.169.2
