### ISSUE TITLE
Helmfile should respect the planHttp option and modify its commands to helm accordingly

### ISSUE THREAD

**Issue by purpleclay** [helmfile/helmfile#1857]
### Operating system

Amazon Linux 2

### Helmfile Version

v0.169.2

### Helm Version

v3.16.3

### Bug description

Setting the `plainHttp` within a `helmfile.yaml` is ignored and not respected. This is evident when it is added to both a `release` and a `repository`. This flag is essential as Helm provides native HTTP support for local OCI repositories.To demonstrate the problem:

1. Spin up a local registry:
   ```sh
   docker run -d -p 5000:5000 --restart always --name registry registry:2
   ```

1. Pull an existing chart and publish it into your local OCI registry for use by helmfile:
   ```sh
   helm pull oci://registry-1.docker.io/bitnamicharts/postgresql
   helm push --plain-http postgresql-16.3.5.tgz oci://localhost:5000/charts
   ```

1. Create the following `helmfile.yaml`:
   ```yaml
   releases:
     - name: postgresql
       namespace: default
       chart: oci://registry:5000/charts/postgresql
       version: "*"
       plainHttp: true
   ```

1. Create a Kubernetes cluster using `k3d` or any other tool that you prefer, and sync the helmfile:
   ```sh
   k3d cluster create demo
   helmfile apply
   ```

### Example helmfile.yaml

```yaml
releases:
- name: postgresql
  namespace: default
  chart: oci://registry:5000/charts/postgresql
  version: "*"
  plainHttp: true
```

### Error message you've seen (if any)

```sh
Pulling localhost:5000/charts/postgresql:*
in ./helmfile.yaml: [release "postgresql": command "/nix/store/fkn0vawlzw4cyih8y3036ydm6rxdif2j-helm-3.16.4/bin/helm" exited with non-zero status:

PATH:
  /nix/store/fkn0vawlzw4cyih8y3036ydm6rxdif2j-helm-3.16.4/bin/helm

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://localhost:5000/charts/postgresql (37 bytes)
  3: --version (9 bytes)
  4: * (1 bytes)
  5: --destination (13 bytes)
  6: /tmp/nix-shell.8u86qt/helmfile2694484463/default/postgresql/postgresql/_ (72 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Get "https://localhost:5000/v2/charts/postgresql/tags/list": http: server gave HTTP response to HTTPS client

COMBINED OUTPUT:
  Error: Get "https://localhost:5000/v2/charts/postgresql/tags/list": http: server gave HTTP response to HTTPS client]
```

### Steps to reproduce

Steps above

### Working Helmfile Version

N/A

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/1364

**Comment by purpleclay** [comment]
After conducting more testing, the following workaround can be used:

```yaml
repositories:
  - name: charts
    url: localhost:5000/charts
    oci: true
    plainHttp: true

releases:
- name: postgresql
  namespace: default
  chart: charts/postgresql
  version: "*"
```
This allows the `helmfile sync` command to work as expected. But defining the repository is optional as explicit `oci://` references can be used within a release.
