### ISSUE TITLE
helmfile build fail with repo not found when using dependencies

### ISSUE THREAD

**Issue by Vince-Chenal** [helmfile/helmfile#1859]
### Operating system

Ubuntu 22.04.5 LTS

### Helmfile Version

0.169.2

### Helm Version

version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

### Bug description

When using `repositories` and `dependencies` in releases, `helmfile build` reports a `repo <repo> not found` error.

Example:

helmfile.yaml
```
repositories:
  - name: examples
    url: https://helm.github.io/examples

releases:
  - name: hello
    chart: examples/hello-world
    version: 0.1.0
    dependencies:
      - chart: examples/hello-world
        version: 0.1.0
```
command:
```
> helmfile build
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm fetch examples/hello-world --untar -d /tmp/chartify1620448177/hello --version 0.1.0

OUTPUT:
  Error: repo examples not found]
```

If I remove the dependency from the release:
```
> helmfile build
---
#  Source: /home/vchenal/dev/test-helmfile/helmfile.yaml

filepath: helmfile.yaml
helmBinary: helm
kustomizeBinary: kustomize
repositories:
- name: examples
  url: https://helm.github.io/examples
releases:
- chart: examples/hello-world
  version: 0.1.0
  name: hello
templates: {}
renderedvalues: {}
```

If I run `helmfile repos` before running `helmfile build` (and keeping the dependency) it's slow (maybe running `helm repo update` behind the scene?) but it works:
```
> helmfile repos
Adding repo examples https://helm.github.io/examples
"examples" has been added to your repositories

> helmfile build
---
#  Source: /home/vchenal/dev/test-helmfile/helmfile.yaml

filepath: helmfile.yaml
helmBinary: helm
kustomizeBinary: kustomize
repositories:
- name: examples
  url: https://helm.github.io/examples
releases:
- chart: examples/hello-world
  chartPath: /tmp/chartify2228205010/hello/hello-world
  version: 0.1.0
  name: hello
  dependencies:
  - chart: examples/hello-world
    version: 0.1.0
    alias: ""
templates: {}
renderedvalues: {}
```

The bug seems related to this one: https://github.com/helmfile/helmfile/issues/1756

### Example helmfile.yaml

```
repositories:
  - name: examples
    url: https://helm.github.io/examples

releases:
  - name: hello
    chart: examples/hello-world
    version: 0.1.0
    dependencies:
      - chart: examples/hello-world
        version: 0.1.0
```

### Error message you've seen (if any)

```
> helmfile build
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm fetch examples/hello-world --untar -d /tmp/chartify1620448177/hello --version 0.1.0

OUTPUT:
  Error: repo examples not found]
```

### Steps to reproduce

explained in the description

### Working Helmfile Version

did not test previous versions
