### ISSUE TITLE
Helmfile does not correctly handle development versions of charts

### ISSUE THREAD

**Issue by purpleclay** [helmfile/helmfile#1864]
### Operating system

macOS 15.1 (Sequoia)

### Helmfile Version

v0.169.2

### Helm Version

v3.16.4

### Bug description

Helm supports publishing and pulling development releases (i.e. prerelease versions) of charts. Looking through the helmfile documentation, its config also states support through the `devel` option, which ultimately maps to the `--devel` flag to both the `helm` and `helm-diff` CLIs.

The only caveat to using the `--devel` flag is that a version should not be provided using the `--version` flag. If one is provided, it takes precedence.

`helmfile` is ignoring the presence of the `devel` option within the `getOCIQualifiedChartName` method in `state.go`.

To replicate this behaviour:

1. Spin up a local registry:
   ```sh
   docker run -d -p 5000:5000 --restart always --name registry registry:2
   ```

1. Pull an existing chart and publish it into your local OCI registry for use by helmfile:
   ```sh
   helm pull oci://ghcr.io/stefanprodan/charts/podinfo
   helm push --plain-http podinfo-6.7.1.tgz oci://localhost:5000/charts --version 6.7.1-1736671323
   ```

1. Create the following `helmfile.yaml`:
   ```yaml
   repositories:
      - name: charts
        url: localhost:5000/charts
        oci: true
        plainHttp: true

   releases:
     - name: podinfo
       namespace: default
       chart: charts/podinfo
       devel: true
   ```

1. Create a Kubernetes cluster using `k3d` or any other tool that you prefer, and sync the helmfile:
   ```sh
   k3d cluster create demo
   helmfile apply
   ```

### Example helmfile.yaml

```yaml
repositories:
  - name: charts
    url: localhost:5000/charts
    oci: true
    plainHttp: true

releases:
  - name: podinfo
    namespace: default
    chart: charts/podinfo
    devel: true
```

### Error message you've seen (if any)

```sh
$ helmfile sync
in ./helmfile.yaml: [release "podinfo": the version for OCI charts should be semver compliant, the latest tag is not supported anymore for helm >= 3.8.0]
```

### Steps to reproduce

See steps within bug description

### Working Helmfile Version

N/A
