### ISSUE TITLE
Kustomize transformers preventing dependency update

### ISSUE THREAD

**Issue by zoonage** [helmfile/helmfile#1880]
### Operating system

OSX Sonoma

### Helmfile Version

v0.170.0

### Helm Version

v3.17.0

### Bug description

Full demo as a tarball available here [demo.tar.gz](https://github.com/user-attachments/files/18465882/demo.tar.gz)

1. `tar -xvzg demo.tar.gz`
2. `cd demo`
3. `helmfile template` -> should work
4. Uncomment the `transformers` section of `helmfile.yaml`
5. `helmfile template` -> should fail with the error below

```
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm dependency up /var/folders/kw/h0jsz1bs2rg00nyq6lwpd9pr0000gn/T/chartify2403749751/monitoring/sentry

OUTPUT:
  Error: directory /var/folders/kw/h0jsz1bs2rg00nyq6lwpd9pr0000gn/T/chartify2403749751/monitoring/library not found]
```

### Example helmfile.yaml

```
releases:
- chart: ./charts/service
  name: sentry
  namespace: monitoring
  transformers:
  - apiVersion: builtin
    fieldSpecs:
    - create: true
      path: metadata/labels
    kind: LabelTransformer
    labels:
      component: abc
    metadata:
      name: label-enforcer
```

### Error message you've seen (if any)

```
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm dependency up /var/folders/kw/h0jsz1bs2rg00nyq6lwpd9pr0000gn/T/chartify2403749751/monitoring/sentry

OUTPUT:
  Error: directory /var/folders/kw/h0jsz1bs2rg00nyq6lwpd9pr0000gn/T/chartify2403749751/monitoring/library not found]
```

### Steps to reproduce

See bug description

### Working Helmfile Version

Went back to 0.147.0 and was still unable to find a working version

**Comment by zoonage** [comment]
I had a dig through the code and I think this is an issue in chartify? I'm not 100% confident in my reading of it though

**Comment by yxxhero** [comment]
@zoonage yeah. PR is welcome.

**Comment by muffl0n** [comment]
Having the same issue when running `helmfile -f kanister.yaml.gotmpl -e test build` when using `transformers`:
```
bases:
  - environments/test.yaml
---
repositories:
  - name: kanister
    url: https://charts.kanister.io/

helmDefaults:
  kubeContext: "{{ .Environment.Values.kubeContext }}"

releases:
  - name: kanister
    namespace: kanister
    chart: kanister/kanister-operator
    version: {{ .Environment.Values | get "versions.kanister" }}
    missingFileHandler: Warn
    values:
      - defaults/kanister.yaml.gotmpl
    transformers:
      - apiVersion: builtin
        kind: AnnotationsTransformer
        metadata:
          name: notImportantHere
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        fieldSpecs:
          - kind: Deployment
            path: metadata/annotations
            create: true
```
