### ISSUE TITLE
Chartify Issue when using charts with child/parent import-values requirement

### ISSUE THREAD

**Issue by scodeman** [helmfile/helmfile#1893]
### Operating system

Ubuntu 20.04.4 LTS

### Helmfile Version

v0.163.1

### Helm Version

v3.14.4

### Bug description
Unmarshalling issue when using transformer on open-webui chart

I am using the following helmfile.yaml  to release openwebui and I wanted to add securityContext missing in the pipeline dependency deployment with a transformer
```yaml
---
repositories:
- name: openwebui
  url: https://helm.openwebui.com
releases:
- name: openwebui
  chart: openwebui/open-webui
  version: 5.4.0
  transformers: 
   - apiVersion: builtin
     kind: ValueAddTransformer
     metadata:
       name: add-security-context-runAsNonRoot
     targets:
       - fieldPath: spec/template/spec/securityContext/runAsNonRoot
         selector:
           kind: Deployment
           name: open-webui-pipelines
     value: true
```

Running `helmfile template -f helmfile.yaml --debug` it ends up producing the following error which I can't relate with the chart
```
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string
```

Log:
```
processing file "helmfile.yaml" in directory "."
changing working directory to "/Users/fmadiot/Developer"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default  map[] map[]}, overrode=<nil>
first-pass uses: &{default  map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: ---
 1: repositories:
 2: - name: openwebui
 3:   url: https://helm.openwebui.com
 4: releases:
 5: - name: air-openwebui
 6:   chart: openwebui/open-webui
 7:   version: 5.4.0
 8:   transformers: 
 9:    - apiVersion: builtin
10:      kind: ValueAddTransformer
11:      metadata:
12:        name: add-security-context-runAsNonRoot
13:      targets:
14:        - fieldPath: spec/template/spec/securityContext/runAsNonRoot
15:          selector:
16:            kind: Deployment
17:            name: open-webui-pipelines
18:      value: true
19: 

first-pass produced: &{default  map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default  map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: ---
 1: repositories:
 2: - name: openwebui
 3:   url: https://helm.openwebui.com
 4: releases:
 5: - name: air-openwebui
 6:   chart: openwebui/open-webui
 7:   version: 5.4.0
 8:   transformers: 
 9:    - apiVersion: builtin
10:      kind: ValueAddTransformer
11:      metadata:
12:        name: add-security-context-runAsNonRoot
13:      targets:
14:        - fieldPath: spec/template/spec/securityContext/runAsNonRoot
15:          selector:
16:            kind: Deployment
17:            name: open-webui-pipelines
18:      value: true
19: 

merged environment: &{default  map[] map[]}
helm:EKqxT> v3.17.0+g301108e
helm:EKqxT> 
Chartify process for openwebui/open-webui
running helm fetch openwebui/open-webui --untar -d /var/folders/c9/pfj7cpvn0f7c9ppckdlwf2w80000gp/T/chartify1662720699/air-openwebui --version 5.4.0
Removed /var/folders/c9/pfj7cpvn0f7c9ppckdlwf2w80000gp/T/helmfile3504693638/air-openwebui-values-6dbb8899db
Removed /var/folders/c9/pfj7cpvn0f7c9ppckdlwf2w80000gp/T/helmfile3504693638
err: [release air-openwebui: updating requirements: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string]
changing working directory back to "/Users/fmadiot/Developer"
in ./helmfile.yaml: [release air-openwebui: updating requirements: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string]
```

### Example helmfile.yaml

```yaml
---
repositories:
- name: openwebui
  url: https://helm.openwebui.com
releases:
- name: openwebui
  chart: openwebui/open-webui
  version: 5.4.0
  transformers: 
   - apiVersion: builtin
     kind: ValueAddTransformer
     metadata:
       name: add-security-context-runAsNonRoot
     targets:
       - fieldPath: spec/template/spec/securityContext/runAsNonRoot
         selector:
           kind: Deployment
           name: open-webui-pipelines
     value: true
```

### Error message you've seen (if any)

```
err: [release air-openwebui: updating requirements: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string]
changing working directory back to "/Users/fmadiot/Developer"
in ./helmfile.yaml: [release air-openwebui: updating requirements: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string]
```

### Steps to reproduce

helmfile template -f helmfile.yaml --debug

### Working Helmfile Version

v0.163.1
