### ISSUE TITLE
upper repositories not read

### ISSUE THREAD

**Issue by cridam** [helmfile/helmfile#1909]
### Operating system

Ubuntu 

### Helmfile Version

0.170.1

### Helm Version

3.17.0

### Bug description

helmfile doesn't read upper repositories before fetching sub files

To overpass, you need to define all the repositories n every subfiles ....  
Is there any way to force reading upper before ?

### Example helmfile.yaml

```
repositories:
  - name: myrepo # to be replaced with sandbox or local testing
    username: {{ requiredEnv "ARTIFACTORY_DEVELOPER_USER" }}
    password: {{ requiredEnv "ARTIFACTORY_DEVELOPER_TOKEN" }}
    url: https://xxxx

helmfiles:
- path: ../helmfile.yaml
  values:
  - kast.yaml
```

### Error message you've seen (if any)

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: myrepo/ingress (12 bytes)
  3: --version (9 bytes)
  4: 2.6.0+4.11.3 (12 bytes)
  5: --untar (7 bytes)
  6: --untardir (10 bytes)
  7: /tmp/helmfile3239661788/default/ingress/myrepo/ingress/2.6.0+4.11.3 (65 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: repo myrepo not found

COMBINED OUTPUT:
  Error: repo myrepo not found]

### Steps to reproduce

follow before

### Working Helmfile Version

0.170.1
