### ISSUE TITLE
Unable to use  {{ .Release.Version }}

### ISSUE THREAD

**Issue by cridam** [helmfile/helmfile#1934]
### Operating system

N/A

### Helmfile Version

latest

### Helm Version

N/A

### Bug description

Try to extract Release.Version info to format a property. While {{ .Release.Name }} is fine, but i got error <.Release.Version>: can't evaluate field Version in type state.releaseTemplateDataRelease

Reproduce with the helmfile.yaml below and **helmfile lint** 
FYI: {{ Release.Version  }} looks resolvable when defining in hook using `{{ .Release.Version }}`

### Example helmfile.yaml

```
releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 45.17.0
    values:
    - "{{ .Release.Name }}-{{ .Release.Version }}.yaml" # fails
    - "{{ .Release.Name }}.yaml" # is fine
```

### Error message you've seen (if any)

`
in ./helmfile.issue.yaml: failed executing release templates in "helmfile.issue.yaml": failed executing templates in release "helmfile.issue.yaml"."kube-prometheus-stack": failed executing template expressions in release "kube-prometheus-stack".values[0] = "{{ .Release.Name }}-{{ .Release.Version }}.yaml": template: stringTemplate:1:31: executing "stringTemplate" at <.Release.Version>: can't evaluate field Version in type state.releaseTemplateDataRelease

### Steps to reproduce

N/A

### Working Helmfile Version

latest
