### ISSUE TITLE
helmfile concurency do not work on complicated structure

### ISSUE THREAD

**Issue by zystem** [helmfile/helmfile#1968]
### Operating system

any Linux

### Helmfile Version

0.171.0

### Helm Version

v3.9.2

### Bug description

Then I run 
`helmfile -e testing -f main.yaml apply --concurrency=4`
I have no concurrency. All releases are in sequence.

### Example helmfile.yaml

main.yaml
```
---
bases:
  - environments.yaml
---
helmfiles:
  - backend.yaml
  - frontend.yaml
```
backend.yaml
```
---
bases:
  - environments.yaml
---
helmfiles:
  - backend1.yaml
  - backend2.yaml
```
frontend.yaml
```
---
bases:
  - environments.yaml
---
helmfiles:
  - frontend1.yaml
  - frontend2.yaml
```
all backends and frontends are standard helmfiles
```
---
bases:
  - environments.yaml
---
releases:
  - name: backend1
    namespace: default
    chart: ./charts/backend1
    version:
    values:
```

### Error message you've seen (if any)

no errors. Just nothing run in parallel
show-dag looks like
```
GROUP RELEASE          DEPENDENCIES
1     default/backend1
GROUP RELEASE           DEPENDENCIES
1     default/backend2
GROUP RELEASE          DEPENDENCIES
1     default/frontend1
GROUP RELEASE          DEPENDENCIES
1     default/frontend2
```

### Steps to reproduce

see above

### Working Helmfile Version

no
