### ISSUE TITLE
helmfile template: skipSchemaValidation=true not working with transformers

### ISSUE THREAD

**Issue by fuog** [helmfile/helmfile#1971]
### Operating system

Ubuntu 22.04.5 LTS

### Helmfile Version

1.0.0-rc.12

### Helm Version

v3.17.2

### Bug description

Hi,

I'm currently running into an issue that forces me to use `skipSchemaValidation: true` (see case https://github.com/kubernetes-sigs/external-dns/issues/5206 ). However, I've noticed that this feature doesn't work with `transformers: `. As soon as I remove transformers: .., rendering works normally again.

### Example helmfile.yaml

The generated error simply appears as if skip validation isn't active.

```yaml
releases:
  - name: "somename"
    namespace: "system-externaldns"
    chart: local-package-registry/external-dns
    version: 1.16.0
    skipSchemaValidation: true   # <----
    transformers:                           # <----
      - releases/externaldns/transformers/label_removal.yaml.gotmpl
    values:
      - releases/externaldns/externaldns.yaml.gotmpl
```

### Error message you've seen (if any)

```
OUTPUT:
  Error: values don't meet the specifications of the schema(s) in the following chart(s):
  external-dns:
  - fullnameOverride: Invalid type. Expected: null, given: string]
```
Note: The error itself is due to the Helmchart, but the fact that Helmfile ignores skip validation with transformers has nothing to do with the Helmchart

### Steps to reproduce

https://github.com/fuog/helmfile-issue-1

### Working Helmfile Version

-
