### ISSUE TITLE
Using jsonPatches changes which subprogram renders the chart

### ISSUE THREAD

**Issue by jennydaman** [helmfile/helmfile#1977]
### Operating system

NixOS

### Helmfile Version

v0.171.0

### Helm Version

version.BuildInfo{Version:"v3.17.2", GitCommit:"v3.17.2", GitTreeState:"", GoVersion:"go1.24.1"}

## Background

It is well-known that the Helm `lookup` function, commonly used by bitnami charts, is sometimes unsupported by third-party tools for Helm (see https://github.com/databus23/helm-diff/issues/460).

Consider the helmfile.yaml below. It works when you run

```shell
helmfile apply
```

But to upgrade the release, it is necessary to use the parameter `--diff-args=--dry-run=server` (or set `helmDefaults.diffArgs: [ --dry-run=server ]`). For example, running the command `helmfile diff --show-secrets` shows that the password's value will be changed everytime, but `helmfile diff --show-secrets --diff-args=--dry-run=server` works as expected where there are no diffs to show.

## This Bug

In the example helmfile.yaml below, uncomment the `patch` section, then try running `helmfile diff`. Regardless of whether you pass `--diff-args=--dry-run=server`, the password value will be randomized each time you invoke `helmfile`.

I am not sure what the order of operations is with kustomize, chartify, and helm-diff. What I think is happening is normally, helm-diff appears first in the pipeline, but with `jsonPatches`, it appears later and the `lookup` function does not work as expected.

### Example helmfile.yaml

```yaml
releases:
  - name: postgresql
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.6.0
    # jsonPatches:
    #   - target:
    #       version: v1
    #       kind: StatefulSet
    #       name: postgresql
    #     patch:
    #       - op: replace
    #         path: /metadata/labels~1hello
    #         value: world
```

### Error message you've seen (if any)

N/A

### Steps to reproduce

See description

### Working Helmfile Version

N/A

**Comment by FuxMak** [comment]
Bump, as this is is still causing issues with the `lookup` function.

The workaround is still as follows:

```yaml
helmDefaults:
  diffArgs:
    - "--dry-run=server"
```
