### ISSUE TITLE
Cannot use fetchSecretValue to load sops encrypted yaml without explicitly specifying format

### ISSUE THREAD

**Issue by lukasdietrich** [helmfile/helmfile#2001]
### Operating system

openSUSE Tumbleweed

### Helmfile Version

v0.171.0

### Helm Version

v3.17.2

### Bug description

If I want to include a sops encrypted yaml file inside a value template, the file is interpreted as json.

When I explicitly set the `?format=yaml` option, the template function works as expected.

### Example helmfile.yaml

```yaml
# ./helmfile.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    createNamespace: true
    values:
      - ./cert-manager.d/values.yaml.gotmpl
```

```yaml
# ./cert-manager.d/values.yaml.gotmpl
# ERROR

extraObjects:
  - | {{ "ref+sops://cert-manager.d/cloudflare-api-token.yaml" | fetchSecretValue | nindent 4 }}
```

```yaml
# ./cert-manager.d/values.yaml.gotmpl
# SUCCESS

extraObjects:
  - | {{ "ref+sops://cert-manager.d/cloudflare-api-token.yaml?format=yaml" | fetchSecretValue | nindent 4 }}
```

### Error message you've seen (if any)

```
in ./helmfile.yaml: failed processing release cert-manager: failed to render values files "cert-manager.d/values.yaml.gotmpl": failed to render [cert-manager.d/values.yaml.gotmpl], because of template: stringTemplate:15:4: executing "stringTemplate" at <fetchSecretValue>: error calling fetchSecretValue: expand sops://cert-manager.d/cloudflare-api-token.yaml: Error unmarshalling input json: invalid character 'a' looking for beginning of value
```

### Steps to reproduce

helmfile -f helmfile.yaml diff

### Working Helmfile Version

--

### Relevant discussion

--
