### ISSUE TITLE
`fromYaml` only supports objects

### ISSUE THREAD

**Issue by ProbstDJakob** [helmfile/helmfile#2012]
### Operating system

N/A

### Helmfile Version

0.171.0

### Helm Version

N/A

### Bug description

The current implementation of the template function [`fromYaml`](https://github.com/helmfile/helmfile/blob/24f900ac9b64a49d39474a9863b0232e72e924b6/pkg/tmpl/context_funcs.go#L310-L323) does not support other types than objects and thus yaml files containing for example arrays as top level item can not be deserialised.

### Example helmfile.yaml

```yaml
environments:
  default:
    values:
      - example: |
          []

---

releases:
  - name: example
    chart: example
    values:
      - {{- .Values.example | fromYaml | nindent 8 }}
```

### Error message you've seen (if any)

```raw
in ./helmfile.yaml.gotmpl: error during helmfile.yaml.gotmpl.part.1 parsing: template: stringTemplate:6:30: executing "stringTemplate" at <fromYaml>: error calling fromYaml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]interface {}, offending yaml: []
```

### Steps to reproduce

Run `helmfile template --file helmfile.yaml.gotmpl`

### Working Helmfile Version

N/A
