### ISSUE TITLE
helm template doesn't honor namespace configuration

### ISSUE THREAD

**Issue by abstractalchemist** [helmfile/helmfile#2020]
### Operating system

Fedora 23

### Helmfile Version

1.0.0.-rc12

### Helm Version

v3.15.4

### Bug description

```helmfile template``` doesn't properly honor namespace configurations in the helmfile configuration.  I know that ```helm template``` doesn't honor the ```-n``` option when generating manifests either, but still, this seems to be an oversight ( ? ), or at the very least, should probably be documented somewhere.  

At least for me, this runs counter to expectations for the tool.

### Example helmfile.yaml

```
repositories:
- name: openebs
  url: https://openebs.github.io/openebs
releases:
- name: openebs
  namespace: openebs
  chart: openebs/openebs
  version: 4.1.0
  values:
  - openebs-values.yaml
  createNamespace: true
```

I would expect running ```helmfile template``` against this would generate templates that have include the namespace property in the metadata.

### Error message you've seen (if any)

None

### Steps to reproduce

running helmfile template against this 

### Working Helmfile Version

None
