### ISSUE TITLE
Auto discovery of helmfile.d files regressed

### ISSUE THREAD

**Issue by jess-belliveau** [helmfile/helmfile#2052]
### Operating system

Sonoma 14.6.1

### Helmfile Version

v1.1.0 and v.1.0.0

### Helm Version

v3.18.0

### Bug description

Upgrading to v1.x.x seems to regress auto-discovery of helmfile configs stored in the `helmfile.d` dir.

We have a structure like this:

```
├── helmfile.d
│   ├── 00-karpenter.gotmpl
│   ├── 01-datadog.gotmpl
│   ├── 02-service-mesh.gotmpl
│   ├── 03-ingress-nginx.gotmpl
│   ├── 04-external-dns.gotmpl
```

Each of these files was previously of filetype `.yaml`. Under previous versions we could run `helmfile` commands without specifying `-f` and all files would be acted upon.

With the upgrade to v1.0.0 and v.1.1.0 we renamed the files to `.gotmpl`. We have noticed a change in behaviour where now files are not autodiscoverd.

v0.171.0 example, note no `-f` arg set:

```
➜ helmfile lint --environment lint
Adding repo bedag-helm-charts https://bedag.github.io/helm-charts/
"bedag-helm-charts" has been added to your repositories

Pulling public.ecr.aws/karpenter/karpenter:1.3.3
Fetching bedag-helm-charts/raw
Fetching bedag-helm-charts/raw
Linting release=karpenter, chart=/var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile1748382594/karpenter/karpenter/karpenter/1.3.3/karpenter
==> Linting /var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile1748382594/karpenter/karpenter/karpenter/1.3.3/karpenter

1 chart(s) linted, 0 chart(s) failed

Linting release=nodepool, chart=/var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile1748382594/karpenter/nodepool/bedag-helm-charts/raw/latest/raw
==> Linting /var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile1748382594/karpenter/nodepool/bedag-helm-charts/raw/latest/raw

1 chart(s) linted, 0 chart(s) failed
```

v1.1.0 example:

```
➜ helmfile lint --environment lint
err: no releases found that matches specified selector() and environment(lint), in any helmfile
```

You can force a sub-command to work by specifying the filename, but this seems a regression:

```
➜ helmfile lint --environment lint -f helmfile.d/00-karpenter.gotmpl
Adding repo bedag-helm-charts https://bedag.github.io/helm-charts/
"bedag-helm-charts" has been added to your repositories

Fetching bedag-helm-charts/raw
Fetching bedag-helm-charts/raw
Pulling public.ecr.aws/karpenter/karpenter:1.3.3
Linting release=karpenter, chart=/var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile2638057042/karpenter/karpenter/karpenter/1.3.3/karpenter
==> Linting /var/folders/5m/b4sq5m7n3wnfrdmdf7tdp7cr0000gn/T/helmfile2638057042/karpenter/karpenter/karpenter/1.3.3/karpenter

1 chart(s) linted, 0 chart(s) failed
```

### Example helmfile.yaml

```
environments:
  default:
    values:
      - s3://{{ requiredEnv "HELMS3BUCKET" }}/values.yaml # This file is generated by Terraform
      - ../values/common.yaml # Globally common values
      - ../values/{{ include "getStage" (requiredEnv "ENV_NAME") }}/default.yaml # Stage specific defaults
      - ../values/{{ include "getStage" (requiredEnv "ENV_NAME") }}/{{ requiredEnv "ENV_NAME"}}.yaml # Cluster specific overrides
  lint:
    values:
      - ../lint-values.yaml
---
repositories:
  - name: bedag-helm-charts
    url: https://bedag.github.io/helm-charts/
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
---
releases:
  - name: karpenter
    chart: karpenter/karpenter
    namespace: karpenter
    version: {{ .Values | get "karpenterVersion" "1.3.3" }}
    createNamespace: false
    labels:
      component: karpenter
    wait: true
```

### Error message you've seen (if any)

```
➜ helmfile lint --environment lint
err: no releases found that matches specified selector() and environment(lint), in any helmfile
```

### Working Helmfile Version

v0.171.0
