### ISSUE TITLE
Immediate panic when HELMFILE_DISABLE_INSECURE_FEATURES environment variable is set to true

### ISSUE THREAD

**Issue by JimmyAllnighter** [helmfile/helmfile#2070]
### Operating system

Windows, Fedora

### Helmfile Version

v1.1.1, v0.168.0, probably more

### Helm Version

3.15.2, 3.16.1, but does not seem to be applicable in this case

### Bug description

When the environment variable `HELMFILE_DISABLE_INSECURE_FEATURES` is set to `true`, helmfile panics and exits with a stack trace.

I have reproduced this issue in multiple scenarios, including inside an empty directory. It appears that almost every command causes the same panic to occur.

Unfortunately, I am unable to provide a stack trace due to... work :eyes:. Instead, here is a set of steps that should produce the same results as what I am describing:

1. In a fresh terminal, create a new directory and enter it
2. Set `HELMFILE_DISABLE_INSECURE_FEATURES` to `true`
3. Run something like `helmfile write-values`

First line of output should read:

```
panic: Remote sources are disabled due to ‘DISABLE_INSECURE_FEATURES’
```

...followed by the stack trace.

### Example helmfile.yaml

No helmfile needed, but even the most basic one will do.

### Error message you've seen (if any)

panic: Remote sources are disabled due to ‘DISABLE_INSECURE_FEATURES’

(followed by a stack trace that I am regrettably unable to provide)

### Steps to reproduce

see issue description

### Working Helmfile Version

currently unknown

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/2069

**Comment by yxxhero** [comment]
@JimmyAllnighter what's your helmfile files?

**Comment by JimmyAllnighter** [comment]
> [@JimmyAllnighter](https://github.com/JimmyAllnighter) what's your helmfile files?

Unable to provide originals, but they are roughly:


`helmfile.yaml` or `helmfile.yaml.gotmpl` depending on scenario + contents.
```yaml
helmDefaults:
  createNamespace: false

environments:
  dev:
    values:
      - values/environments/dev/values.yaml

---

releases:
  - name: example-thingy
    chart: repo/example-chart
    version: 1.2.3
    namespace: {{ requiredEnv “NAMESPACE_VAR” }}  # tried with and without this, and did add .gotmpl extension for attempts with it
    values:
      - values/values.yaml.gotmpl
```

`values/environments/dev/values.yaml`
```yaml
envExampleKey: envExampleValue
```

`values/values.yaml.gotmpl`
```yaml
someChartValue: {{ .Values.envExampleKey }}
```

The actual files don’t have any wacky template function usage. I have even taken out parts of them, up to and including entire files to reduce potential areas for failure, hence why I ended up with an empty directory. Theoretically, these examples shouldn’t be required to replicate this bug, unless there’s trouble replicating the issue described.
