### ISSUE TITLE
Namespace value from default context not being propagated

### ISSUE THREAD

**Issue by dfilipov-glitnor** [helmfile/helmfile#2078]
### Operating system

Ubuntu 24.04 LTS

### Helmfile Version

helmfile version 1.1.0

### Helm Version

version.BuildInfo{Version:"v3.17.0", GitCommit:"301108edc7ac2a8ba79e4ebf5701b0b6ce6a31e4", GitTreeState:"clean", GoVersion:"go1.23.4"}

### Bug description

When running `helmfile apply -e dev` and trying to reference `{{ .Release.Namespace }}` in my `mongo/{{ .Environment.Name }}.yaml.gotmpl` like so:

`MONGO_HOST: "{{.Release.Namespace }}.svc.cluster.local/admin"` I get a nil value, this is also show when I tried to template with passing `{{ .Release }}` to see what is being propagated and I get `namespace: `

This however works when I explicitly pass the `--namespace` flag to helmfile like so `helmfile apply -e dev --namespace test-namespace`

I also tried working around this by passing set to my releases, but still no luck
```
set:
  namespace: {{ .Namespace }}
```

### Example helmfile.yaml

```
releases:
  - name: mongodb-cluster
    chart: .
    atomic: true
    missingFileHandler: Warn
    values:
      - mongo/common.yaml.gotmpl
      - mongo/{{ .Environment.Name }}.yaml.gotmpl
```

### Error message you've seen (if any)

I'm getting `{{ .Release.Namespace }}` set to nil, so any templates depending on it are returning errors

### Steps to reproduce

Try and reference the {{ .Release.Namespace }} in a *.yaml.gotmpl values file, when helmfile is run with the implicit namespace, not explicitly set with --namespace

### Working Helmfile Version

helmfile version 1.1.0
