### ISSUE TITLE
helm arguments passed via --args do not take precedence over helmDefaults.args

### ISSUE THREAD

**Issue by jayme-github** [helmfile/helmfile#2084]
### Operating system

Debian stable

### Helmfile Version

0.171.0

### Helm Version

v3.17.0

### Bug description

Specifying helm arguments on the command line (like: `helmfile -e dev sync --args '--kubeconfig=~/.kube/config'`) prepends them to args specified in the helmfile (`helmDefaults.args`) instead of overriding or appending them while the documentation states that is supposed to happen:
https://github.com/helmfile/helmfile/blob/95777777cf9c74405cf0c5f9731621fa2b22ded3/docs/index.md?plain=1#L180-L183

`GetArgs` joins cli provided args and `helmDefaults.args` if both are provided and makes `helmDefaults.args` take precedence by putting them last:
https://github.com/helmfile/helmfile/blob/95777777cf9c74405cf0c5f9731621fa2b22ded3/pkg/app/app.go#L2260-L2273 

### Example helmfile.yaml

```yaml
environments:
  dev:
    values:
      - replicaCount: 1
        service:
          type: ClusterIP
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: my-nginx
    namespace: default
    chart: bitnami/nginx
    version: 15.5.2
---
helmDefaults:
  args:
    - "--kubeconfig=/nonexistent/{{ .Environment.Name }}.config"
```

### Error message you've seen (if any)

```
ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: my-nginx (8 bytes)
  4: bitnami/nginx (13 bytes)
  5: --version (9 bytes)
  6: 15.5.2 (6 bytes)
  7: --create-namespace (18 bytes)
  8: --namespace (11 bytes)
  9: default (7 bytes)
  10: --reset-values (14 bytes)
  11: --history-max (13 bytes)
  12: 10 (2 bytes)
  13: --kubeconfig=~/.kube/config (27 bytes)
  14: --kubeconfig=/nonexistent/dev.config (36 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Kubernetes cluster unreachable: stat /nonexistent/dev.config: no such file or directory

COMBINED OUTPUT:
  Error: Kubernetes cluster unreachable: stat /nonexistent/dev.config: no such file or directory

```

### Steps to reproduce

Use the helmfile.yaml and command provided in this task

### Working Helmfile Version

none
