### ISSUE TITLE
In OCI mode, when the url in repositories contains a semicolon, OCI Url and Version will parse error

### ISSUE THREAD

**Issue by xiaomudk** [helmfile/helmfile#244]
### Operating system

macOS 11.4

### Helmfile Version

v0.145.2

### Helm Version

v3.9.1

### Bug description

In OCI mode, when the url in repositories contains semicolon :, OCI Url and Version will parse error

### Example helmfile.yaml

```
repositories:
 - name: my-oci-repo
   url: "registry:443/helm-charts"
   oci: true

releases:
- name: nginx
  chart: my-oci-repo/nginx-ingress
  version: 0.14.0
  set:
  - name: controller.hostNetwork
    value: true
```

### Error message you've seen (if any)

```                   
Pulling registry:443/helm-charts/nginx-ingress:0.14.0
Exporting registry:443/helm-charts/nginx-ingress:0.14.0
Error: in examples/helmfile.yaml: [release "nginx": command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: oci://registry (14 bytes)
  3: --version (9 bytes)
  4: 443/helm-charts/nginx-ingress (29 bytes)
  5: --destination (13 bytes)
  6: /var/folders/r1/6m48m2zj0dd2973tyc9lgxtm0000gp/T/chart3285243845 (64 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: invalid_reference: missing repository

COMBINED OUTPUT:
  Error: invalid_reference: missing repository]
in examples/helmfile.yaml: [release "nginx": command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: fetch (5 bytes)
  2: oci://registry (14 bytes)
  3: --version (9 bytes)
  4: 443/helm-charts/nginx-ingress (29 bytes)
  5: --destination (13 bytes)
  6: /var/folders/r1/6m48m2zj0dd2973tyc9lgxtm0000gp/T/chart3285243845 (64 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: invalid_reference: missing repository

COMBINED OUTPUT:
  Error: invalid_reference: missing repository]
```

### Steps to reproduce

None

### Working Helmfile Version

None
