### ISSUE TITLE
Releases being included without matching environment

### ISSUE THREAD

**Issue by dackroyd** [helmfile/helmfile#271]
### Operating system

MacOS Monterey 12.3

### Helmfile Version

Helmfile version 0.0.0-dev, main branch @ 9af8f1286a7d3804fffe5ee0fbf5e661f23c3693

### Helm Version

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.18.4"}

### Bug description

With multiple helmfile specifying releases for different environments, all releases are being included despite not matching the environment specified on the command line.

### Example helmfile.yaml

```
environments:
  development: {}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: cache
    namespace: my-app
    chart: bitnami/redis
    version: 17.0.7
```

```
environments:
  test: {}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: database
    namespace: my-app
    chart: bitnami/postgres
    version: 11.6.22
```

### Error message you've seen (if any)

No error message, results are unexpected

### Steps to reproduce

https://github.com/dackroyd/helmfile-release-environment-bug

### Working Helmfile Version

helmfile version v0.145.2
