### ISSUE TITLE
How can you inject arbitrary resources into a chart without forking it?

### ISSUE THREAD

**Issue by leotavares** [helmfile/helmfile#277]
### Operating system

Ubuntu 22.04 LTS

### Helmfile Version

0.145.2

### Helm Version

3.9.2

### Bug description

When trying to inject a resource into a release it simply ignores.
However, when I add the following to helmfile.yaml it creates the resource:

```yaml
- name: raw1
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: grafana-selfsigned-ca
        namespace: gloo-system
      spec:
        isCA: false
        commonName: "grafana.sendcloud"
        secretName: grafana-selfsigned-ca
        dnsNames:
        - grafana.sendcloud
        issuerRef:
          name: selfsigned-issuer-ca
          kind: Issuer
```

### Example helmfile.yaml
```yaml
repositories:
  - name: gloo
    url: https://storage.googleapis.com/solo-public-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
- name: gloo-edge
  namespace: gloo-system
  chart: gloo/gloo
  version: '1.12.2'
  needs:
    - cert-manager/cert-manager
  values:
  - resources:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: grafana-selfsigned-ca
      spec:
        isCA: false
        commonName: "grafana.sendcloud"
        secretName: grafana-selfsigned-ca
        dnsNames:
        - grafana.sendcloud
        issuerRef:
          name: selfsigned-issuer-ca
          kind: Issuer
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.9.1
  set:
  - name: installCRDs
    value: true
- name: kube-prometheus-stack
  namespace: prometheus
  chart: prometheus-community/kube-prometheus-stack
  needs:
    - cert-manager/cert-manager
    - gloo-system/gloo-edge
```

### Error message you've seen (if any)

None, it just doesn't create

### Steps to reproduce

helmfile sync

### Working Helmfile Version

None
