### ISSUE TITLE
Selector break repository/chart syntax with OCI

### ISSUE THREAD

**Issue by tgaudillat02** [helmfile/helmfile#310]
### Operating system

Ubuntu 20.04

### Helmfile Version

0.145.3

### Helm Version

3.9.3

### Bug description

Sync, Diff, template fonction is break with OCI chart when using --selector.

Helm version : 3.8.0
Helmfile version : 0.144.0
Repository : Azure Container Registry

Here the templating without selector
```

Logging in to registry
Login Succeeded

Pulled: xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Digest: sha256:f19d9413523a99b0a1a351999e0b1c6ab8f3729623077a8fee65a2b629ddac1b

Exporting xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Pulled: xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Digest: sha256:f19d9413523a99b0a1a351999e0b1c6ab8f3729623077a8fee65a2b629ddac1b

Templating release=cfg-shared-configs, **chart=/tmp/helmfile636816509/cfg-shared-configs/cfg-shared-configs/1.0.0/cfg-shared-configs**
---
# Source: cfg-shared-configs/templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap

...

```

Here the template with --selector (chart=cfg-shared-configs)

```
Logging in to registry
Login Succeeded

Pulling xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Exporting xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Pulled: xxx.azurecr.io/helm/cfg-shared-configs:1.0.0
Digest: sha256:f19d9413523a99b0a1a351999e0b1c6ab8f3729623077a8fee65a2b629ddac1b

Exporting npd03cacnacrgen.azurecr.io/helm/cfg-shared-configs:1.0.0
Pulled: npd03cacnacrgen.azurecr.io/helm/cfg-shared-configs:1.0.0
Digest: sha256:f19d9413523a99b0a1a351999e0b1c6ab8f3729623077a8fee65a2b629ddac1b

Templating release=cfg-shared-configs, chart=acr/cfg-shared-configs
in ./helmfile.yaml: command "/usr/local/helm/helm" exited with non-zero status:

PATH:
  /usr/local/helm/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: cfg-shared-configs (18 bytes)
  3: acr/cfg-shared-configs (22 bytes)
  4: --version (9 bytes)
  5: 1.0.0 (5 bytes)
  6: --namespace (11 bytes)
  7: perf3 (5 bytes)
  8: --values (8 bytes)
  9: /tmp/helmfile639927867/perf3-cfg-shared-configs-values-b68dc94b7 (64 bytes)
  10: --timeout=30m0s (15 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: failed to download "acr/cfg-shared-configs" at version "1.0.0"

COMBINED OUTPUT:
  Error: failed to download "acr/cfg-shared-configs" at version "1.0.0"
```

### Example helmfile.yaml

Helmfile.yaml: 

```
repositories:
  - name: acr
    oci: true
    url: {{ requiredEnv "ACR_URL" | quote }}
    username: {{ requiredEnv "ACR_USER" | quote }}
    password: {{ requiredEnv "ACR_PASSWORD" | quote }}

bases:
  # Tools releases template
  - releases/tool-release.gotmpl
```

tool-release.gotmpl:

```
# configmap Release Templating

releases:
{{- if hasKey .Environment.Values "configmap" }}

# Loop on configmap dictionary to prepare release for each of the configmap-* charts
{{ range $chart, $params := .Environment.Values.configmap }}

  - name: {{ $chart }}
  
    chart: acr/{{ $chart }}

    labels:
      chart: {{ $chart }}
{{- end }}
{{- end }}
```

### Error message you've seen (if any)

STDERR:
  Error: failed to download "acr/cfg-shared-configs" at version "1.0.0"

COMBINED OUTPUT:
  Error: failed to download "acr/cfg-shared-configs" at version "1.0.0"

### Steps to reproduce

Private repository

### Working Helmfile Version

No one

**Comment by tgaudillat02** [comment]
Find a way out by forcing the namespace but still a bug.

**Comment by yxxhero** [comment]
@tgaudillat02 Sorry. I will try to fix this. Or do you have free to create a PR for this?

**Comment by retraut** [comment]
Have the same issue
Helmfile Version
`0.145.4`
Helm Version
`3.8.2`

**Comment by retraut** [comment]
It will be cool if you can create PR for this issue @yxxhero

**Comment by yxxhero** [comment]
@retraut @tgaudillat02    ok. I will do it. Thanks very much.

**Comment by mumoshu** [comment]
@yxxhero Did you already figure out how we can fix this?

It should export the OCI chart into a temporary directory like `/tmp/helmfile636816509/cfg-shared-configs/cfg-shared-configs/1.0.0/cfg-shared-configs` shown in the first example. It isn't referring to the exported dir in the second example. It might have something to do with the issue, but I'm still unsure what kind of bug can cause that...

**Comment by yxxhero** [comment]
@mumoshu I haven't started yet.

**Comment by yxxhero** [comment]
@retraut @tgaudillat02 who can show a whole example? So I can reproduce this issue. Thanks very much.

**Comment by allinonedashboard** [comment]
facing  the similar issue 
Error: failed to download "bitnami/ingress-nginx" at version "4.2.5"
Do i need to add it manually the helm repo add?

**Comment by allinonedashboard** [comment]
if i do helmfile -f helmfile.yaml repos before apply its adding the repos

**Comment by yxxhero** [comment]
I will fix this in this weekend.

**Comment by tgaudillat02** [comment]
Thx a lot :).

**Comment by yxxhero** [comment]
@tgaudillat02 I cant reproduce your issue. see my example:

helmfile:
```
repositories:
  - name: acr
    oci: true
    url: localhost:5000/acr

bases:
  # Tools releases template
  - releases/tool-release.gotmpl
```
releases/tool-release.gotmpl:
```
environments:
  test:
    values:
      - test.yaml

releases:
{{- if hasKey .Environment.Values "configmap" }}

# Loop on configmap dictionary to prepare release for each of the configmap-* charts
{{ range $chart, $params := .Environment.Values.configmap }}

  - name: {{ $chart }}

    chart: acr/{{ $chart }}
    version: {{ $params.version }}

    labels:
      chart: {{ $chart }}
{{- end }}
{{- end }}
```

test.yaml:
```
configmap:
  acrapp:
    version: 0.1.0
```
