### ISSUE TITLE
Commands' -n option no longer recognized

### ISSUE THREAD

**Issue by gakesson** [helmfile/helmfile#311]
### Operating system

Ubuntu 20.04.4 LTS

### Helmfile Version

0.145.3

### Helm Version

3.9.0

### Bug description

If I using the associated helmfile.yaml run **helmfile --namespace hello-there list** it will as expected print:
```
NAME     	NAMESPACE  	ENABLED	INSTALLED	LABELS	CHART        	VERSION
service-a	hello-there	true   	true     	      	incubator/raw	
```

However, if I only specify the shorthand option for namespace using **helmfile -n hello-there list** an error is raised:
`Error: unknown shorthand flag: 'n' in -n`

Using the -n option was at least working in 0.142.0 and should work according to documentation.

### Example helmfile.yaml

```
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
releases:
- name: service-a
  chart: incubator/raw
  namespace: {{ .Namespace }}
```

### Error message you've seen (if any)

Error: unknown shorthand flag: 'n' in -n

### Steps to reproduce

N/A

### Working Helmfile Version

0.142.0
