### ISSUE TITLE
`needs` fails if you specify a release which has not been parsed yet

### ISSUE THREAD

**Issue by WoodyWoodsta** [helmfile/helmfile#323]
### Operating system

macOS 12.5.1

### Helmfile Version

v0145.4

### Helm Version

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### Bug description

I have multiple helmfiles in my project. Some releases in those helmfiles "need" other releases. There is a singular helmfile at the root, which references helmfiles by means of the `helmfiles` configuration property.

If a release needs another which has not yet been reached, helmfile fails. This means I have to make sure I order the `helmfiles` in a specific way to get `needs` dependencies to work. With glob patterns, this is not possible, and sometimes it's logically impossible as there could be a non-trivial dependency tree.

In my mind (and I'm surprised it isn't this way) it seems as though helmfile needs to gather all releases and do the dependency resolution afterwards.

Have I misunderstood the use of `needs` or is this just a limitation of the implementation?

### Example helmfile.yaml

```yaml
# Root helmfile
helmfiles:
  - apps/*/helmfile.yml

---

# apps/myapp1/helmfile.yml
releases:
  - name: myapp1
    needs:
      - myapp2

---

# apps/myapp2/helmfile.yml
releases:
  - name: myapp2

```

### Error message you've seen (if any)

```
Error: in ./helmfile.yaml: in .helmfiles[0]: in apps/***/helmfile.yml: release(s) "***/***" depend(s) on an undefined release "***/***". Perhaps you made a typo in "needs" or forgot defining a release named "***" with appropriate "namespace" and "kubeContext"?
in ./helmfile.yaml: in .helmfiles[0]: in apps/***/helmfile.yml: release(s) "***/***" depend(s) on an undefined release "***/***". Perhaps you made a typo in "needs" or forgot defining a release named "networking" with appropriate "namespace" and "kubeContext"?
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A
