### ISSUE TITLE
Diff selector does not work on "installed: false" releases

### ISSUE THREAD

**Issue by diversario** [helmfile/helmfile#327]
### Operating system

macOS 12.5.1, alpine 3.13

### Helmfile Version

0.145.4

### Helm Version

3.5.3

### Bug description

`--selector` option with `diff` command does not narrow the diff to the selected release when the release is set to not installed by `installed: false` key; this includes running with `--skip-needs=true  --include-needs=false` flags. Diff appears to run for all releases in the same helmfile as the targeted release, including the targeted release (so it still reports it as deleted). The selector being used is a basic `name=foo` selector that should match only one release.

### Example helmfile.yaml

- name: ingress-nginx-enabled
  namespace: default
  chart: ingress-nginx/ingress-nginx

- name: ingress-nginx-disabled
  namespace: default
  installed: false
  chart: ingress-nginx/ingress-nginx

### Error message you've seen (if any)

no error messages

### Steps to reproduce

Have a helmfile with multiple releases. Set `installed: false` on one, run `helmfile --selector name=nameofthedisabledrelease diff --skip-needs`

### Working Helmfile Version

n/a

**Comment by Nick-Triller** [comment]
The issue is still relevant.

**Comment by mumoshu** [comment]
@Nick-Triller Thanks a lot for reporting! This does sound like a bug. We should indeed be able to use helmfile-diff to review deletions and later run helmfile-destroy with a selector to delete the releases one-by-one. Apparently, it's impossible according to what you observed and reported here.

**Comment by mumoshu** [comment]
Well, I've tested the case with helmfile 0.145.4, 0.145.5, and the edge and it all worked as I have expected. I'm now unsure what the "problem" you're seeing exactly.

Let's say I have this:

```
repositories:
- name: stable
  url: https://charts.helm.sh/stable
releases:
- name: mysql
  chart: stable/mysql
  installed: false
```

If you've already installed the `mysql` release and then updated helmfile.yaml to have `installed: false`, running `helmfile -l name=mysql diff  --skip-needs` does show the release as "to be deleted". That's expected.

```
Affected releases are:
  mysql (stable/mysql) DELETED
```

> does not narrow the diff to the selected release

So this doesn't happen for me. It does narrow the diff to the selected release.

**Comment by diversario** [comment]
So, I'm not saying that diff does not work. It works. I do see the release as being uninstalled, basically everything is as you would expect, _except_ that the diff runs for _all_ releases in the helmfile in which the affected release is located. So the selector does not quite work.
We have our releases split over several helmfiles, so in this case I see diffs being calculated for all releases in the same helmfile where I updated one release to be `installed: false`. That's why I see the diff for the targeted release (so that's good), plus diffs for the releases in the same helmfile (not so good).

**Comment by mumoshu** [comment]
>  the diff runs for all releases in the helmfile in which the affected release is located

Thanks a lot for your claritication! I was able to reproduce it.

So I have:

```
repositories:
- name: stable
  url: https://charts.helm.sh/stable
releases:
- name: a
  chart: stable/mysql
  installed: false
- name: b
  chart: stable/mysql
```

`helmfile -l name=a diff --skip-needs` and `helmfile -l name=a diff` shows diff only for `b` even though I've specified `-l name=a`. This isn't expected.

When I omitted `installed: false`:

```
repositories:
- name: stable
  url: https://charts.helm.sh/stable
releases:
- name: a
  chart: stable/mysql
- name: b
  chart: stable/mysql
```

`helmfile -l name=a diff --skip-needs` and `helmfile -l name=a diff` shows diff only for `a` as I've specified `-l name=a`. This is expected.

So yeah, it does look like it has something to do with `installed: false`... Great. I'll see what's going on.
