### ISSUE TITLE
missingFileHandler: Warn is ignored when ref is incorrect

### ISSUE THREAD

**Issue by rishm069** [helmfile/helmfile#392]
### Operating system

ghcr.io/helmfile/helmfile:v0.145.2

### Helmfile Version

0.145.2

### Helm Version

3.9.0

### Bug description

When `missingFileHandler` option is set to `Warn` in the environments file as follows:
```
environments:
  {{ env "ENVIRONMENT" }}:
    missingFileHandler: Warn
```
and in `values` section there is a remote git-value that points to non-existing ref:
e.g. `develop` doesn't exist
```
    values:
      - git::https://****@gitlab.com/service.git@service/values.yaml?ref=develop
```
The error is thrown instead of a warning and `helmfile apply` command fails.

### Example helmfile.yaml

```
environments:
  {{ env "ENVIRONMENT" }}:
    missingFileHandler: Warn
    values:
      - git::https://****@gitlab.com/service.git@service/values.yaml?ref=develop
```

### Error message you've seen (if any)

```
$ helmfile apply
in ./helmfile.yaml: in .helmfiles[0]: in /builds/helmfile.yaml: failed to read environments.yaml: failed to load environment values file "": failed to load []: open : no such file or directory
```

### Steps to reproduce

https://gist.github.com/rishm069/97445e47b316653bdb7d8d053ad6462d

### Working Helmfile Version

NA
