### ISSUE TITLE
allow key overrides

### ISSUE THREAD

**Issue by kaktus42** [helmfile/helmfile#394]
### Operating system

MacOS Montery 12.5.1

### Helmfile Version

helmfile version v0.145.2

### Helm Version

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.19"}

### Bug description

See: https://github.com/roboll/helmfile/issues/657

This fails with "already set in map"

### Example helmfile.yaml

```
templates:
  default: &default
    labels:
      sync: everyday
charts:
  - name: test
    <<: *default
    chart: test
    labels:
      sync: thur
```

### Error message you've seen (if any)

already set in map

### Steps to reproduce

override an existing value in a yaml file

### Relevant discussion

https://github.com/roboll/helmfile/issues/657
