### ISSUE TITLE
helmfile gets stuck during repo adding step if chart has dependensies 

### ISSUE THREAD

**Issue by violaodorata** [helmfile/helmfile#397]
### Operating system

 MacOS 12.6

### Helmfile Version

v0.146.0

### Helm Version

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### Bug description

`helmfile apply` command gets stuck during the repo adding step when we have dependencies block in a chart.

### Steps to reproduce

We have two types of Git repositories. 
The first one is a chart repository. 
For example:
- templates
- Chart.yaml
- ..

Chart.yaml file can have dependencies block like in the example below:
```
....
dependencies:
  - name: common
    version: 1.0.0
    repository: "@common"
```
The second repository type (values repo) has the next structure:
- helmfile.yaml
- values.jaml

Helmfile.yaml  example:

```
repositories:
  - name: component-repo
    url: git+ssh://git@{component_repo_path}
  - name: common
    url: git+ssh://git@{common_path}

releases:
  - name: project-service
    namespace: ..
    chart: component-repo/component
    values:
      - values.yaml
```
If we run `helmfile apply`, the command will be stuck during the repo adding a step for a chart with dependencies block.

### Error message you've seen (if any)

`❯ helmfile apply`
Adding repo  component-repo git+ssh://{repo_path}
........ it will be stuck here

### Working Helmfile Version

v0.146.0
