### ISSUE TITLE
Write-values and output file templating error

### ISSUE THREAD

**Issue by corinz** [helmfile/helmfile#409]
### Operating system

MacOS 12.5

### Helmfile Version

v0.146.0

### Helm Version

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### Bug description

Attempting to execute
```
helmfile -e prod write-values --output-file-template releases/helm-{{ .Environment.Name }}.yaml
```
and getting an error
```
in ./helmfile.yaml: parsing output-file template
```
the same error in helmfile v0.145.4 was
```
Error: in ./helmfile.yaml: parsing output-file template
in ./helmfile.yaml: parsing output-file template
```

### Example helmfile.yaml
```
releases:
- name: services
  namespace: services
  chart: ./
  missingFileHandler: Warn
  values:
  - values.default.yaml
  - values.{{ .Environment.Name }}.yaml
  secrets:
  - secrets.default.yaml
  - secrets.{{ .Environment.Name }}.yaml
environments:
  default:
    kubeContext: disabled
  prod:
    kubeContext: kind-local
```
### Error message you've seen (if any)

Shown above

### Steps to reproduce

Not a public repo but described in detail above

### Working Helmfile Version

n/a
