### ISSUE TITLE
Helmfile does not handle termination signals when Helm is still running

### ISSUE THREAD

**Issue by steved** [helmfile/helmfile#416]
### Operating system

MacOS 12

### Helmfile Version

0.146.0

### Helm Version

3.10.0

### Bug description

When running Helm releases with `wait: true`, if an interrupt or term signal is sent to Helmfile while it's installing will not result in Helm being stopped.

### Example helmfile.yaml

Any release with `wait: true`, e.g:
```
releases:
- name: sleep
  namespace: default
  chart: sleep/
  wait: true
```

### Error message you've seen (if any)

No error message

### Steps to reproduce

https://github.com/steved/helmfile-wait-interrupt

### Working Helmfile Version

N/A
