### ISSUE TITLE
`.Release.Revision` does not work with chartify / ad-hoc dependencies

### ISSUE THREAD

**Issue by pathob** [helmfile/helmfile#430]
### Operating system

Docker (Ubuntu)

### Helmfile Version

0.147.0

### Helm Version

3.9.0

### Bug description

When chartify / ad-hoc dependencies are being used, `.Release.Revision` always evaluates to 1.

This currently breaks our GitLab deployment, where a Kubernetes job cannot be updated because it's name depends on the revision. See https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/gitlab/charts/migrations/templates/_helpers.tpl

In order to reproduce this, just run `helmfile apply` with the below helmfile.yaml. Then, update the image version to e.g. alpine:3.16 and run `helmfile apply` again.

### Example helmfile.yaml

```
repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - chart: incubator/raw
    version: 0.2.5
    name: test
    values:
      - templates:
          - |
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: {{`{{ .Release.Name }}`}}-job-{{`{{ .Release.Revision }}`}}
            spec:
              template:
                spec:
                  containers:
                  - name: alpine
                    image: alpine:3.15
                    command: ["printenv"]
                  restartPolicy: Never
              backoffLimit: 4
        adhoc:
          templates:
            - |
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: raw
    dependencies:
      - chart: incubator/raw
        version: 0.2.5
        alias: adhoc
```

### Error message you've seen (if any)

```
Error: UPGRADE FAILED: cannot patch "test-job-1" with kind Job: Job.batch "test-job-1" is invalid: spec.template: Invalid value: core.PodTemplateSpec(...)
```

### Steps to reproduce

See above

### Working Helmfile Version

-
