### ISSUE TITLE
0.147.0 fails to execute diff

### ISSUE THREAD

**Issue by chillum** [helmfile/helmfile#445]
### Operating system

Windows 11 21H2

### Helmfile Version

Helmfile version 0.147.0

### Helm Version

```go
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}
```

### Bug description

after upgrading helmfile from 0.145.4 to 0.147.0 I get an error with the helmfile that previously worked.
reproducable both with helm-diff 3.5.0 and 3.6.0.

I run `helmfile diff` and get the error.

### Example helmfile.yaml

```yaml
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 4.8.3
```

### Error message you've seen (if any)

```
STDERR:
  Error: Failed to render chart: exit status 1: Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: argo%5Cargo-cd
  Error: plugin "diff" exited with error
```

### Steps to reproduce

provided inline

### Working Helmfile Version

0.145.4
