### ISSUE TITLE
The `test` option has become fussy with command line option ordering

### ISSUE THREAD

**Issue by jim-barber-he** [helmfile/helmfile#450]
### Operating system

Debian stable (bullseye 11)

### Helmfile Version

0.147.0

### Helm Version

v3.10.1

### Bug description

Running
```
helmfile -e $ENVIRONMENT_NAME -l name=$RELEASE test
```
results in the error:
```
err: no releases found that matches specified selector() and environment(-l), in any helmfile
```

But running it like so:
```
helmfile test -e $ENVIRONMENT_NAME -l name=$RELEASE
```
works:
```
$ helmfile test -e test -l name=catalyst
Building dependency release=catalyst, chart=helm/chart/catalyst
Testing catalyst
```

I'm not sure what version this broke at, but it was working for version 0.145.2 of helmfile (with helm 3.9.2).

### Example helmfile.yaml

```
---
environments:
  prod:
  test:

helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: false
  timeout: {{ env "HELM_TIMEOUT" | default "600" }}

releases:
  - name: catalyst
    chart: ./helm/chart/catalyst
    namespace: {{ env "RELEASE_NAMESPACE" | default "catalyst" }}
    values:
      - helm/vars/values.yaml.gotmpl
```

### Error message you've seen (if any)

```
err: no releases found that matches specified selector() and environment(-l), in any helmfile
```

### Steps to reproduce

Any helm chart that has a `tests` directory with tests to run

### Working Helmfile Version

0.145.2
