### ISSUE TITLE
helmfile template --args swallows args

### ISSUE THREAD

**Issue by joshuasimon-taulia** [helmfile/helmfile#454]
### Operating system

OSX 10.14.6 (18G9323), Ubuntu 22.04.1 LTS

### Helmfile Version

0.147.0, 0.144.7

### Helm Version

v3.9.0

### Bug description

`helmfile template` seems to be excluding additional `--api-versions` flags from `args`
```shell
helmfile template --args "--api-versions=networking.k8s.io/v1 --api-versions=networking.k8s.io/v1/Ingress" | grep -i extensions/v1beta1
Adding repo runatlantis https://runatlantis.github.io/helm-charts
"runatlantis" has been added to your repositories

Templating release=atlantis, chart=runatlantis/atlantis
exec: helm template atlantis runatlantis/atlantis --version 4.1.2 --namespace atlantis --values /var/folders/bp/4mgw9f094872yc6v7gyzqqt1frkjzj/T/helmfile311979473/atlantis-atlantis-values-6d77d594d8 --values /var/folders/bp/4mgw9f094872yc6v7gyzqqt1frkjzj/T/helmfile3484799294/atlantis-atlantis-values-6db6b56d9d --api-versions=networking.k8s.io/v1

apiVersion: extensions/v1beta1
```
in the first example, ` --api-versions=networking.k8s.io/v1/Ingress` is not correctly passed to `helmfile template` resulting in the wrong api version rendered on the ingress object **apiVersion: extensions/v1beta1**

```shell
helmfile template --args "--api-versions=networking.k8s.io/v1/Ingress --api-versions=networking.k8s.io/v1" | grep -i extensions/v1beta1
Adding repo runatlantis https://runatlantis.github.io/helm-charts
"runatlantis" has been added to your repositories

Templating release=atlantis, chart=runatlantis/atlantis
exec: helm template atlantis runatlantis/atlantis --version 4.1.2 --namespace atlantis --values /var/folders/bp/4mgw9f094872yc6v7gyzqqt1frkjzj/T/helmfile1042919175/atlantis-atlantis-values-6d77d594d8 --values /var/folders/bp/4mgw9f094872yc6v7gyzqqt1frkjzj/T/helmfile1300626385/atlantis-atlantis-values-6db6b56d9d --api-versions=networking.k8s.io/v1/Ingress
```
possibly related to https://github.com/helmfile/helmfile/issues/450, https://github.com/spf13/cobra/pull/1781, and https://github.com/travisghansen/argo-cd-helmfile/issues/23

### Example helmfile.yaml

```
filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: atlantis
repositories:
- name: runatlantis
  url: https://runatlantis.github.io/helm-charts
releases:
- chart: runatlantis/atlantis
  version: 4.1.2
  name: atlantis
  values:
  - jx-values.yaml
  - atlantis-values.yaml.gotmpl
templates: {}
renderedvalues: {}
```

### Error message you've seen (if any)

errors occur when trying to apply the above ingress to a k8s 1.22+ cluster

### Steps to reproduce

above

### Working Helmfile Version

same thing happens on v0.138.7
