### ISSUE TITLE
Chartify not applied to "needed" releases

### ISSUE THREAD

**Issue by pjotre86** [helmfile/helmfile#455]
### Operating system

Linux Mint 20.3

### Helmfile Version

0.147.0

### Helm Version

3.8.2

### Bug description

Assume you have release A which points to a folder containing plain k8s manifests. Then you have release B which depends on release A (usings `needs`). Now you want to deploy the release B with `--include-needs`, like:
  
`helmfile -l name=releaseB sync --include-needs`
  
### Expected behavior:
Release A is created and applied first using chartify. Then release B is applied.
### Actual behavior:
Release A fails saying:
`Error: Chart.yaml file is missing`
  
### Remark
If I just deploy release A (something like `helmfile -l name=releaseA sync`) it works. Chartify is chiming in, everything fine!

### Example helmfile.yaml

```
repositories:
  - name: azuredisk-csi-driver
    url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
releases:
  - name: azuredisk-csi-storageclass
    chart: ./azuredisk-csi-storageclass
  - name: azuredisk-csi-driver
    chart: azuredisk-csi-driver/azuredisk-csi-driver
    needs:
      - azuredisk-csi-storageclass
```
while the folder `./azuredisk-csi-storageclass` just contains a simple storageclass, like:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

### Error message you've seen (if any)

Templating release=azuredisk-csi-storageclass, chart=./azuredisk-csi-storageclass
in ./helmfile.yaml: in .helmfiles[1]: in saasops/storage-drivers.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: azuredisk-csi-storageclass (26 bytes)
  3: ./azuredisk-csi-storageclass (28 bytes)
  4: --namespace (11 bytes)
  5: persistence (11 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Chart.yaml file is missing

COMBINED OUTPUT:
  Error: Chart.yaml file is missing

### Steps to reproduce

helmfile -l name=azuredisk-csi-driver sync --include-needs

### Working Helmfile Version

Not sure if it ever worked.
