### ISSUE TITLE
Ad-hoc dependencies using kustomization no longer work

### ISSUE THREAD

**Issue by eigood** [helmfile/helmfile#472]
### Operating system

Debian Bullseye

### Helmfile Version

0.145.0

### Helm Version

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### Bug description

https://github.com/roboll/helmfile/issues/1762#issuecomment-1221450013

### Example helmfile.yaml

Example given in the description

### Error message you've seen (if any)

Error message linked in the descrpition

### Steps to reproduce

NA

### Working Helmfile Version

NA

**Comment by mumoshu** [comment]
@eigood Well, the linked comment seems to be indicating that you can't add a directory containing raw manifests(not a local chart) as an ad-hoc dependency, right? The ad-hoc dependency is handled by Helm so it's how it's currently supposed to work.

**Comment by mumoshu** [comment]
Updated the issue title to reflect the real issue. It's never supposed to work this way. Probably this is a feature request, not a bug report.

**Comment by johejo** [comment]
This is workaround that I found.

Use raw as main works fine.

Of course raw also can be a kustomize directory that is not a helm chart.

```
$ tree raw
raw
├── Chart.yaml
├── charts
├── templates
│   ├── _helpers.tpl
│   └── extra-manifest.yaml
└── values.yaml

2 directories, 4 files
```

```
$ cat raw/values.yaml
extraObjects: []

$ cat raw/templates/extra-manifest.yaml
{{ range .Values.extraObjects }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
```

```yaml
releases:
  - name: bar
    chart: ./raw
    namespace: bar
    dependencies:
      - chart: foo/bar
        alias: bar
        version: 0.1.0
    values:
      - extraObjects:
          - apiVersion: v1
            kind: ConfigMap
             # ....
      - bar:
          # bar's values
          x: y
          # ...
```
