### ISSUE TITLE
System path added to requiredEnv if env starts with slash

### ISSUE THREAD

**Issue by strainovic** [helmfile/helmfile#481]
### Operating system

Windows 10

### Helmfile Version

0.146.0

### Helm Version

3.10.1

### Bug description

When we set env variable TEST='/path' and refer to it with "{{ requiredEnv `TEST` }}", within git bash, output in the rendered manifest will get `C:/Program Files/Git/path`. If we remove the slash, the manifest will get `path`.

Any explanation for this?

Thanks

### Example helmfile.yaml

not relevant

### Error message you've seen (if any)

none

### Steps to reproduce

-

### Working Helmfile Version

unknown

**Comment by yxxhero** [comment]
@strainovic please show your helmfile. So I will check what happened.

**Comment by strainovic** [comment]
```console
helm create test
```

Content of `helmfile.yaml`

```
releases:
- name: test
  chart: ./test
  values:
  - ingress:
      enabled: true
      hosts:
        - host: chart-example.local
          paths:
            - path: "{{ requiredEnv `TEST_PATH` }}"
              pathType: ImplementationSpecific
```

```console
export TEST_PATH='/aaa'
helmfile template
```

```yaml
---
# Source: test/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  labels:
    helm.sh/chart: test-0.1.0
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: C:/Program Files/Git/aaa
            pathType: ImplementationSpecific
            backend:
              service:
                name: test
                port:
                  number: 80
```

As you can see, path has value of `C:/Program Files/Git/aaa`

I ran this from the GitBash shell.

**Comment by yxxhero** [comment]
try:
```
{{ requiredEnv "TEST_PATH"  | quote }}
```

**Comment by strainovic** [comment]
```yaml
releases:
- name: test
  chart: ./test
  values:
  - ingress:
      enabled: true
      hosts:
        - host: chart-example.local
          paths:
            - path: {{ requiredEnv "TEST_PATH" | quote }}
              pathType: ImplementationSpecific
```

```yaml
# Source: test/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  labels:
    helm.sh/chart: test-0.1.0
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: C:/Program Files/Git/aaa
            pathType: ImplementationSpecific
            backend:
              service:
                name: test
                port:
                  number: 80
```
