### ISSUE TITLE
needs resolution failure when using template

### ISSUE THREAD

**Issue by mjhuber** [helmfile/helmfile#49]
### Operating system

macOS 12.3.1

### Helmfile Version

v0.143.4

### Helm Version

3.8.1

### Bug description

when a defined release is using a template, resolution of `needs` can fail unless `kubeContext` is defined explicitly in the release.  For example, given this helmfile below I receive the following error:

```bash
❯ helmfile -e stage -l app=cert-manager diff --skip-deps
in ./helmfile.yaml: release(s) "cert-manager/letsencrypt-setup" depend(s) on an undefined release "my_kubeconfig_name/cert-manager/cert-manager". Perhaps you made a typo in "needs" or forgot defining a release named "cert-manager" with appropriate "namespace" and "kubeContext"?
```

```yaml
environments:
  stage:
    kubeContext: my_kubeconfig_name
    values:
    - environments/default/default.yml
    - environments/stage/stage.yml

templates:
  default: &default
    missingFileHandler: Warn
    namespace: "{{`{{ .Release.Name }}`}}"
    values:
      - "./environments/default/{{`{{ .Release.Name }}`}}.values.yml"
      - "./environments/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.values.yml"
      - "./environments/default/{{`{{ .Release.Name }}`}}.values.yml.gotmpl"
      - "./environments/{{`{{ .Environment.Name }}`}}/{{`{{ .Release.Name }}`}}.values.yml.gotmpl"
    labels:
      app: "{{`{{ .Release.Name }}`}}"

- name: letsencrypt-setup
  <<: *default
  needs:
  - "{{.Values.kubeContext}}/cert-manager/cert-manager"
  namespace: cert-manager
  chart: org/letsencrypt-setup
  version: 1.0.0
  installed: {{.Values.LetsEncryptSetup}}
  values:
  - environments/default/letsencrypt-setup.values.yml
  - environments/{{ .Environment.Name }}/letsencrypt-setup.values.yml
  - gcpCredentials: {{.Values.externalDnsServiceAccountKey | fetchSecretValue | quote}}

- name: cert-manager
  <<: *default
  chart: jetstack/cert-manager
  version: v1.7.2
  installed: {{.Values.CertManager}}
```

however, if I add the field `kubeContext` to the release, it works:
```yaml
- name: cert-manager
  <<: *default
  chart: jetstack/cert-manager
  version: v1.7.2
  installed: {{.Values.CertManager}}
  kubeContext: my_kubeconfig_name
```

### Steps to reproduce

see description
