### ISSUE TITLE
State values not treating "yes" and "no" as boolean values in gotmpl files

### ISSUE THREAD

**Issue by tonygilkerson** [helmfile/helmfile#491]
### Operating system

macOS Monterey Version 12.6

### Helmfile Version

v0.147.0

### Helm Version

3.10.1

### Bug description

The following state value `foo: no` when used in an if-statement does not work.  It is treating the value as a string and because it is non-nil it is truthy, it should be false. 

I can confirm that this bug does not exist in helmfile v0.146.0

### helmfile

```yaml
missingFileHandler: Error

releases:
- name: foo
  chart: ./charts/foo
  values:
  - foo-values.yaml.gotmpl

environments:
  default:
    values:
      - flag: no
```

### foo-values.yaml.gotmpl file specified on the release

```yaml
#  foo-values.yaml.gotmpl
{{- if .Values.flag }}
ifResult: "if evaluated to TRUE with .Values.flag={{ .Values.flag }}"    <----evaluates to TRUE when flag=no
{{ else }}
ifResult: "if evaluated to FALSE with .Values.flag={{ .Values.flag }}"
{{- end }}
```

### chart's template file

```yaml
ifResult: {{ .Values.ifResult }}
```

### Error message you've seen (if any)

There is no error message, this is a logic error:

With a state value of `foo: no` this is the result

```sh
$ helmfile template
Building dependency release=foo, chart=charts/foo
Templating release=foo, chart=charts/foo
---
# Source: foo/templates/test.yaml
ifResult: if evaluated to TRUE with .Values.flag=no
```

The correct output is should be `ifResult: if evaluated to FALSE with .Values.flag=no`

### Steps to reproduce

https://github.com/tonygilkerson/helmfile-bug/blob/main/README.md

### Working Helmfile Version

v0.146.0
