### ISSUE TITLE
yaml merge keys is broken

### ISSUE THREAD

**Issue by franco87** [helmfile/helmfile#493]
### Operating system

Ubuntu 20.04

### Helmfile Version

0.147.0

### Helm Version

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

### Bug description

The merge keys feature is broken when using yaml anchors. The keys are not merged but overrode. Might be related with #396

### Example helmfile.yaml

```
templates:
  default: &default
    labels:
      project: "myProject"
      group: "myGroup"


releases:
  - <<: *default
    name: "release1"
    labels:
      app: "myapp"
    chart: "test"
  - <<: *default

    name: "release2"
    labels:
      app: "myapp"
    chart: "test"

```

### Error message you've seen (if any)

Labels from the template have gone
``` 
➜ helmfile_0.147.0 list
NAME            NAMESPACE       ENABLED INSTALLED       LABELS          CHART   VERSION
release1                        true    true            app:myapp       test
release2                        true    true            app:myapp       test
```

```
➜ helmfile_0.146.0 list
NAME            NAMESPACE       ENABLED INSTALLED       LABELS                                          CHART   VERSION
release1                        true    true            app:myapp,group:myGroup,project:myProject       test
release2                        true    true            app:myapp,group:myGroup,project:myProject       test
```

### Steps to reproduce

merge keys using yaml anchors

### Working Helmfile Version

0.146.0

**Comment by yxxhero** [comment]
see: https://github.com/go-yaml/yaml/issues/915
[merge key](https://yaml.org/type/merge.html)

**Comment by yxxhero** [comment]
This is expected behavior. in YAML 1.2 @franco87

**Comment by franco87** [comment]
Thanks @yxxhero 

I let here for other people a way to address this issue. Just avoid deep merges using multiple templates with just one level.

```
templates:
  default_release: &default_release
    namespace: "myNamespace"
  default_labels:
    labels: &default_labels
      project: "myProject"
      group: "myGroup"

releases:
  - name: "release1"
    << : *default_release
    labels:
      <<: *default_labels
      app: "myapp"
    chart: "test"
  - name: "release2"
    << : *default_release
    labels:
      <<: *default_labels
      app: "myapp"
    chart: "test"
```
