### ISSUE TITLE
helmfile template fails when selector matches a chart fetched with go-getter 

### ISSUE THREAD

**Issue by joshuasimon-taulia** [helmfile/helmfile#498]
### Operating system

OSX 10.14.6 (18G9323), Ubuntu 22.04.1 LTS

### Helmfile Version

build from main branch, 0.147.0, 0.144.7

### Helm Version

v3.9.0, v3.10.1

### Bug description

when using `helmfile --debug  -l name=acme-jx template` to select a chart that is fetched using go-getter syntax, `helmfile template` results in the following error

```
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
```

I tried adding `skipDeps: true` to the release as suggested in one of the below issues, but it doesn't help

the most recent related issues i see are
https://github.com/roboll/helmfile/issues/1847
https://github.com/roboll/helmfile/pull/1852
and
https://github.com/roboll/helmfile/pull/1408
https://github.com/roboll/helmfile/pull/1548

### Example helmfile.yaml

commented out unnecessary lines to make it easier to repro
```
filepath: ""
# environments:
#   default:
#     values:
#     - jx-values.yaml
namespace: istio-system
repositories:
- name: istio
  url: https://istio-release.storage.googleapis.com/charts
releases:
- chart: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
#  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  labels:
    values.jenkins-x.io: lock
    version.jenkins-x.io: lock
  skipDeps: true
#  values:
#  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
#  - jx-values.yaml
- chart: istio/base
  version: 1.12.2
  name: istio-base
templates: {}
renderedvalues: {}
```

### Error message you've seen (if any)

```
processing file "helmfile.yaml" in directory "."
changing working directory to "/Users/joshua.simon/Github/gitops-dev/helmfiles/istio-system"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: filepath: ""
 1: # environments:
 2: #   default:
 3: #     values:
 4: #     - jx-values.yaml
 5: namespace: istio-system
 6: repositories:
 7: - name: istio
 8:   url: https://istio-release.storage.googleapis.com/charts
 9: releases:
10: - chart: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
11: #  condition: jxRequirementsIngressTLS.enabled
12:   name: acme-jx
13:   labels:
14:     values.jenkins-x.io: lock
15:     version.jenkins-x.io: lock
16:   skipDeps: true
17: #  values:
18: #  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
19: #  - jx-values.yaml
20: - chart: istio/base
21:   version: 1.12.2
22:   name: istio-base
23: templates: {}
24: renderedvalues: {}

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: filepath: ""
 1: # environments:
 2: #   default:
 3: #     values:
 4: #     - jx-values.yaml
 5: namespace: istio-system
 6: repositories:
 7: - name: istio
 8:   url: https://istio-release.storage.googleapis.com/charts
 9: releases:
10: - chart: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
11: #  condition: jxRequirementsIngressTLS.enabled
12:   name: acme-jx
13:   labels:
14:     values.jenkins-x.io: lock
15:     version.jenkins-x.io: lock
16:   skipDeps: true
17: #  values:
18: #  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
19: #  - jx-values.yaml
20: - chart: istio/base
21:   version: 1.12.2
22:   name: istio-base
23: templates: {}
24: renderedvalues: {}

merged environment: &{default map[] map[]}
helm:YLBCb> v3.10.1+g9f88ccb
Adding repo istio https://istio-release.storage.googleapis.com/charts
exec: helm repo add istio https://istio-release.storage.googleapis.com/charts --force-update
helm:iUPJG> "istio" has been added to your repositories
"istio" has been added to your repositories

getter: git
scheme: https
user:
host: github.com
dir: /joshuasimon-taulia/acme.git
file: charts/acme
home: /Users/joshua.simon/Library/Caches/helmfile
getter dest: istio-system/acme-jx/https_github_com_joshuasimon-taulia_acme_git.ref=master
cached dir: /Users/joshua.simon/Library/Caches/helmfile/istio-system/acme-jx/https_github_com_joshuasimon-taulia_acme_git.ref=master
1 release(s) matching name=acme-jx found in helmfile.yaml

processing 1 groups of releases in this order:
GROUP RELEASES
1     istio-system/acme-jx

processing releases in group 1/1: istio-system/acme-jx
Templating release=acme-jx, chart=git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
exec: helm template acme-jx git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master --namespace istio-system --debug
helm:cUPkT> install.go:192: [debug] Original chart version: ""
helm:cUPkT> Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
helm:cUPkT> helm.go:84: [debug] non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:248
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	helm.sh/helm/v3/pkg/action/install.go:757
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:204
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
err: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: acme-jx (7 bytes)
  3: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master (74 bytes)
  4: --namespace (11 bytes)
  5: istio-system (12 bytes)
  6: --debug (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  install.go:192: [debug] Original chart version: ""
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.go:84: [debug] non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:248
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
  helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
  	helm.sh/helm/v3/pkg/action/install.go:757
  main.runInstall
  	helm.sh/helm/v3/cmd/helm/install.go:204
  main.newTemplateCmd.func2
  	helm.sh/helm/v3/cmd/helm/template.go:82
  github.com/spf13/cobra.(*Command).execute
  	github.com/spf13/cobra@v1.5.0/command.go:872
  github.com/spf13/cobra.(*Command).ExecuteC
  	github.com/spf13/cobra@v1.5.0/command.go:990
  github.com/spf13/cobra.(*Command).Execute
  	github.com/spf13/cobra@v1.5.0/command.go:918
  main.main
  	helm.sh/helm/v3/cmd/helm/helm.go:83
  runtime.main
  	runtime/proc.go:250
  runtime.goexit
  	runtime/asm_amd64.s:1594

COMBINED OUTPUT:
  install.go:192: [debug] Original chart version: ""
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.go:84: [debug] non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:248
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
  helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
  	helm.sh/helm/v3/pkg/action/install.go:757
  main.runInstall
  	helm.sh/helm/v3/cmd/helm/install.go:204
  main.newTemplateCmd.func2
  	helm.sh/helm/v3/cmd/helm/template.go:82
  github.com/spf13/cobra.(*Command).execute
  	github.com/spf13/cobra@v1.5.0/command.go:872
  github.com/spf13/cobra.(*Command).ExecuteC
  	github.com/spf13/cobra@v1.5.0/command.go:990
  github.com/spf13/cobra.(*Command).Execute
  	github.com/spf13/cobra@v1.5.0/command.go:918
  main.main
  	helm.sh/helm/v3/cmd/helm/helm.go:83
  runtime.main
  	runtime/proc.go:250
  runtime.goexit
  	runtime/asm_amd64.s:1594
changing working directory back to "/Users/joshua.simon/Github/gitops-dev/helmfiles/istio-system"
in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: acme-jx (7 bytes)
  3: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master (74 bytes)
  4: --namespace (11 bytes)
  5: istio-system (12 bytes)
  6: --debug (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  install.go:192: [debug] Original chart version: ""
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.go:84: [debug] non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:248
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
  helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
  	helm.sh/helm/v3/pkg/action/install.go:757
  main.runInstall
  	helm.sh/helm/v3/cmd/helm/install.go:204
  main.newTemplateCmd.func2
  	helm.sh/helm/v3/cmd/helm/template.go:82
  github.com/spf13/cobra.(*Command).execute
  	github.com/spf13/cobra@v1.5.0/command.go:872
  github.com/spf13/cobra.(*Command).ExecuteC
  	github.com/spf13/cobra@v1.5.0/command.go:990
  github.com/spf13/cobra.(*Command).Execute
  	github.com/spf13/cobra@v1.5.0/command.go:918
  main.main
  	helm.sh/helm/v3/cmd/helm/helm.go:83
  runtime.main
  	runtime/proc.go:250
  runtime.goexit
  	runtime/asm_amd64.s:1594

COMBINED OUTPUT:
  install.go:192: [debug] Original chart version: ""
  Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.go:84: [debug] non-absolute URLs should be in form of repo_name/path_to_chart, got: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:248
  helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
  	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
  helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
  	helm.sh/helm/v3/pkg/action/install.go:757
  main.runInstall
  	helm.sh/helm/v3/cmd/helm/install.go:204
  main.newTemplateCmd.func2
  	helm.sh/helm/v3/cmd/helm/template.go:82
  github.com/spf13/cobra.(*Command).execute
  	github.com/spf13/cobra@v1.5.0/command.go:872
  github.com/spf13/cobra.(*Command).ExecuteC
  	github.com/spf13/cobra@v1.5.0/command.go:990
  github.com/spf13/cobra.(*Command).Execute
  	github.com/spf13/cobra@v1.5.0/command.go:918
  main.main
  	helm.sh/helm/v3/cmd/helm/helm.go:83
  runtime.main
  	runtime/proc.go:250
  runtime.goexit
  	runtime/asm_amd64.s:1594
```

### Steps to reproduce

`helmfile --debug  -l name=acme-jx template` using above helmfile

### Working Helmfile Version

n/a

**Comment by yxxhero** [comment]
@joshuasimon-taulia 
1. install helm-git plugin
2. use format: git+https://github.com/reactiveops/polaris@deploy/helm?ref=master

thanks very much.

**Comment by joshuasimon-taulia** [comment]
is go-getter syntax deprecated?

**Comment by yxxhero** [comment]
@joshuasimon-taulia it seems like not be supported. remote helmfile can use go-getter syntax.

**Comment by yxxhero** [comment]
@joshuasimon-taulia did you use this syntax ever?

**Comment by joshuasimon-taulia** [comment]
it works without the `-l name=acme-jx` selector using the above helmfile.yaml
ex: `helmfile template`

```
Adding repo istio https://istio-release.storage.googleapis.com/charts
"istio" has been added to your repositories

Building dependency release=acme-jx, chart=/Users/joshua.simon/Library/Caches/helmfile/acme-jx/https_github_com_joshuasimon-taulia_acme_git.ref=master/charts/acme
Templating release=acme-jx, chart=/Users/joshua.simon/Library/Caches/helmfile/acme-jx/https_github_com_joshuasimon-taulia_acme_git.ref=master/charts/acme
---
# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-dev-myorg-com-p"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-dev-myorg-com-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.dev.myorg.com"
  dnsNames:
    - "*.dev.myorg.com"
    - "dev.myorg.com"
---
...
```

**Comment by yxxhero** [comment]
@joshuasimon-taulia ok. I will work on this.

**Comment by yxxhero** [comment]
@joshuasimon-taulia by the way. Could you try use the main branch to test. Thanks very much.

**Comment by joshuasimon-taulia** [comment]
the `helmfile` binary i used for these tests was built from the main branch

**Comment by joshuasimon-taulia** [comment]
im investigating the interaction between [state.PrepareCharts](https://github.com/helmfile/helmfile/blob/ce6f8fc9ecbfff2c2149303e9f48684a96712db5/pkg/state/state.go#L1033-L1300) and [state.SelectReleasesWithOverrides](https://github.com/helmfile/helmfile/blob/ce6f8fc9ecbfff2c2149303e9f48684a96712db5/pkg/state/state.go#L2086-L2093). i don't see anything obviously wrong

**Comment by yxxhero** [comment]
@joshuasimon-taulia Thanks very much. I will solve this issue.

**Comment by yxxhero** [comment]
```bash
filepath: ""
# environments:
#   default:
#     values:
#     - jx-values.yaml
repositories:
- name: istio
  url: https://istio-release.storage.googleapis.com/charts
releases:
- chart: git::https://github.com/joshuasimon-taulia/acme.git@charts/acme?ref=master
#  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  namespace: istio-system
  labels:
    values.jenkins-x.io: lock
    version.jenkins-x.io: lock
  skipDeps: true
#  values:
#  - ../../versionStream/charts/jxgh/acme-jx/values.yaml.gotmpl
#  - jx-values.yaml
- chart: istio/base
  version: 1.12.2
  namespace: istio-system
  name: istio-base
templates: {}
renderedvalues: {}
```

**Comment by yxxhero** [comment]
@joshuasimon-taulia namespace

**Comment by yxxhero** [comment]
@joshuasimon-taulia please try to use https://github.com/helmfile/helmfile/pull/499.

**Comment by joshuasimon-taulia** [comment]
success!
```
helmfile-template-fix  -l name=acme-jx template
Adding repo istio https://istio-release.storage.googleapis.com/charts
"istio" has been added to your repositories

Building dependency release=acme-jx, chart=/Users/joshua.simon/Library/Caches/helmfile/istio-system/acme-jx/https_github_com_joshuasimon-myorg_acme_git.ref=master/charts/acme
Templating release=acme-jx, chart=/Users/joshua.simon/Library/Caches/helmfile/istio-system/acme-jx/https_github_com_joshuasimon-myorg_acme_git.ref=master/charts/acme
---
# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-dev-myorg-com-p"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-dev-myorg-com-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.dev.myorg.com"
  dnsNames:
    - "*.dev.myorg.com"
    - "dev.myorg.com"
---
# Source: acme/templates/cert-manager-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "trololol@myorg.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
          - "*.dev.myorg.com"
          - "dev.myorg.com"
      # ACME DNS-01 provider configurations
      dns01:
        cloudDNS:
          # The project in which to update the DNS zone
          project: "myorg-dev"
```
thank you!
