### ISSUE TITLE
Environment values not available when using bases

### ISSUE THREAD

**Issue by jakubbujny** [helmfile/helmfile#506]
### Operating system

MacOS 12.6.1

### Helmfile Version

v0.147.0

### Helm Version

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}

### Bug description

I try to use value from env file to set if chart should be installed or not via flag
```    installed: {{.Values.XXX.enabled}} ```

while using `bases` feature it fails.

### Example helmfile.yaml

Helmfile
```
bases:
  - base.yaml
environments:
  staging:
    values:
      - values.yaml

releases:
  - name: datadog-agent
    chart: datadog/datadog
    version: 2.37.9
    wait: true
    condition: dd.enabled
    installed: {{.Values.dd.enabled}}
 ```

values.yaml
```
dd:
  enabled: true
```

base.yaml
```
repositories:
  - name: datadog
    url: https://helm.datadoghq.com
```

### Error message you've seen (if any)

in ./helmfile_base.yaml: error during helmfile_base.yaml.part.0 parsing: template: stringTemplate:16:24: executing "stringTemplate" at <.Values.dd.enabled>: map has no entry for key "dd"

### Steps to reproduce

steps to reproduce already provider

### Working Helmfile Version

unknown

**Comment by yxxhero** [comment]
```yaml
bases:
  - base.yaml
environments:
  staging:
    values:
      - values.yaml
---
releases:
  - name: datadog-agent
    chart: datadog/datadog
    version: 2.37.9
    wait: true
    condition: dd.enabled
    installed: {{.Values.dd.enabled}}
```
