### ISSUE TITLE
"helmDefaults.args" does not enable duplicates

### ISSUE THREAD

**Issue by leotomas837** [helmfile/helmfile#508]
### Operating system

macOS Monterey 12.3.1

### Helmfile Version

0.147.0, darwin arm64

### Helm Version

3.10.1

### Bug description

`helmDefaults.args` does not enable duplicates. I am using the [helm-kubectl](https://github.com/jkroepke/helm-kubectl) plugin and as a consequence I ended up with a `helmfile.yaml` containing the following (roughly):

```
helmDefaults:
  args:
    - "--set-file=resources.requests.cpu=kubectl://myns/mynode/myname/jsonpath={'103m'}"
    - "--set-file=replicaCount=kubectl://myns/mynode/myname/jsonpath={'2'}"
```

The first arg is passed and works as expected but not the second one. If I comment the first arg, the second arg is passed and works as expected too.

By executing `helmfile template . --debug --enable-live-output`, I can see that only one `--set-file` is passed to `helm template`, see the logs message in the right section.

You can even try with dummy args as 

```
helmDefaults:
  args:
    - "--myarg"
    - "--myarg"
```

### Example helmfile.yaml

```
helmDefaults:
  args:
    - "--myarg"
    - "--myarg"

repositories:
  - name: patch-operator
    url: https://redhat-cop.github.io/patch-operator

releases:
  - name: patch-operator
    chart: patch-operator/patch-operator
    version: v0.1.9
    namespace: myns
```

### **Run the following command on the `helmfile.yaml` above.**

```
$> helmfile template . --debug --enable-live-output
[...]
exec: helm template patch-operator patch-operator/patch-operator --version v0.1.9 --namespace myns --myarg
[...]
```

### Steps to reproduce

See 'Example helmfile.yaml' and 'Error message you've seen'

### Working Helmfile Version

NA

### Relevant discussion

With this simple change, the mentioned plugin would enable a helm 'lookup' function equivalent in helmfile that many want, like here:
https://github.com/roboll/helmfile/issues/1097
