### ISSUE TITLE
Remote/helm plugin values.yaml not working

### ISSUE THREAD

**Issue by leotomas837** [helmfile/helmfile#523]
### Operating system

macOS Monterey 12.3.1

### Helmfile Version

0.148.1, darwin arm64

### Helm Version

3.10.1

### Bug description

Remote values.yaml not working, and of course it does not work with a downloader plugin too. It should work because it works with `helm --values` (both remote and downloader plugin), and the helmfile doc says:

```yaml
...
releases:
   ...
    # Values files used for rendering the chart
    values:
      # Value files passed via --values
      - vault.yaml
...
```

### Example helmfile.yaml

```yaml
releases:
  - name: temp
    chart: .
    namespace: default
    values:
      - "https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/values.yaml"
```

### Error message you've seen (if any)

```
in ./helmfile.yaml: [values file matching "https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/values.yaml" does not exist in "."]
```

### Steps to reproduce

Empty dir with the `helmfile.yaml` example, run `helmfile template .`.

### Working Helmfile Version

NA

### Relevant discussion

NA

**Comment by leotomas837** [comment]
By looking at the go tests, it looks like helmfile remote `values.yaml` work with a different syntax from helm. I put the syntax below for those looking for it, and I think that it would bring some clarity with an example in the doc and a sentence or two on the syntax difference.
I am still trying to make it working with a downloader plugin though, not sure yet that it works in that case.

```
releases:
  - name: temp
    chart: .
    namespace: default
    values:
      - "https://github.com/argoproj/argo-helm.git@charts/argo-cd/values.yaml?ref=argo-cd-5.13.8"
```
