### ISSUE TITLE
Issue with helm dependency build . --skip-refresh (see also #444)

### ISSUE THREAD

**Issue by BernhardGruen** [helmfile/helmfile#526]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.148.1

### Helm Version

3.10.2

### Bug description

It seems there are some edge cases with the newly (in #444) introduced `--skip-refresh` parameter to helm dependency build if one is using a local chart (like `.` for current directory) that is using a remote chart (like bitnami/postgresql) as a fully qualified dependency (https://charts.bitnami.com/bitnami). The issue seems to only occur if the dependency chart repository was not declared upfront inside helmfile.yaml. But as we don't know which chart repositories any developer could use, we can't add them to `helmfile.yaml` beforehand.

If the parameter `---skip-refresh` is removed everything works correctly again. Therefore I propose an option to disable this parameter if needed. Maybe it could also be disabled by default for local charts as only those charts could possibly contain unresolved dependencies.

If a local chart does not depend on a fully qualified remote chart, everything works correctly too.

Is there another way to circumvent this issue?

### Example helmfile.yaml

helmfile.yaml:
```yaml
repositories:
  - name: helmlib
    url: https://.../api/v4/projects/852/packages/helm/stable

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: "600"
  historyMax: 5

releases:
  - name: "local-chart"
    namespace: "test-namespace"
    chart: "."
    createNamespace: false
    missingFileHandler: "Info"
    values:
      - values.yaml
      - values.gotmpl
```

Chart.yaml:
```yaml
apiVersion: v2
name: my-test
description: Test Chart
type: application
version: 0.2.0
appVersion: 0.0.1

dependencies:
  - name: helmlib
    version: 4.x.x
    repository: alias:helmlib
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
```

### Error message you've seen (if any)

```
Adding repo helmlib https://.../api/v4/projects/852/packages/helm/stable
"helmlib" has been added to your repositories
Building dependency release=local-chart, chart=.
in ./helmfile.yaml: [building dependencies of local chart: command "/usr/bin/helm" exited with non-zero status:
PATH:
  /usr/bin/helm
ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: . (1 bytes)
  4: --skip-refresh (14 bytes)
ERROR:
  exit status 1
EXIT STATUS
  1
STDERR:
  Error: no cached repository for helm-manager-54d2620bbb6f1bb3f35d4c7f945bfa25077949488dcbb0a4d01c90f2c35baa59 found. (try 'helm repo update'): open /root/.cache/helm/repository/helm-manager-54d2620bbb6f1bb3f35d4c7f945bfa25077949488dcbb0a4d01c90f2c35baa59-index.yaml: no such file or directory
  ```
  

### Steps to reproduce

sorry not available at the moment

### Working Helmfile Version

0.147.0
