### ISSUE TITLE
--state-values-set for arrays broken

### ISSUE THREAD

**Issue by pjotre86** [helmfile/helmfile#532]
### Operating system

Linux Mint 20.3

### Helmfile Version

0.148.1

### Helm Version

3.10.1

### Bug description

The `--state-values-set` parameter seems to have a weird (faulty) behavior when it comes to arrays.
Example:
Given following `helmfile.yaml`:
```
releases:
  - name: myapp1
    chart: my-chart
    set:
      - name: firstValue
        value: {{ index .Values.myvalues 0 }}
      - name: secondValue
        value: {{ index .Values.myvalues 1 }}
```
Then do a build providing the values using `--state-values-set`:
`helmfile --state-values-set myvalues[0]=HELLO,myvalues[1]=HELMFILE build`
Output:
```
filepath: helmfile.yaml
helmBinary: helm
releases:
  - chart: my-chart
    name: myapp1
    set:
      - name: firstValue
        value: <no value>
      - name: secondValue
        value: HELMFILE
templates: {}
renderedvalues:
  myvalues:
    - null
    - HELMFILE
```
**As you can see: `firstValue` is not set**.  
  
I found out that it works when you reverse the order of the array elements:
`helmfile --state-values-set myvalues[1]=HELMFILE,myvalues[0]=HELLO build`
produces the correct output:
```
filepath: helmfile.yaml
helmBinary: helm
releases:
  - chart: my-chart
    name: myapp1
    set:
      - name: firstValue
        value: HELLO
      - name: secondValue
        value: HELMFILE
templates: {}
renderedvalues:
  myvalues:
    - HELLO
    - HELMFILE
```
The size of the array doesn't seem to matter, you always have to go from last to first to get the correct result.
Also, it's not only a problem of the `build` command, I actually found this when doing a `sync`, so I guess it's probably happening for all commands, but didn't verify that...

### Example helmfile.yaml

```
releases:
  - name: myapp1
    chart: my-chart
    set:
      - name: firstValue
        value: {{ index .Values.myvalues 0 }}
      - name: secondValue
        value: {{ index .Values.myvalues 1 }}
```

### Error message you've seen (if any)

No error is thrown.

### Steps to reproduce

`helmfile --state-values-set myvalues[0]=HELLO,myvalues[1]=HELMFILE build`

### Working Helmfile Version

Not sure if it ever worked.
