### ISSUE TITLE
Temporary directories used for temporary values files are left over

### ISSUE THREAD

**Issue by yann-soubeyrand** [helmfile/helmfile#540]
### Operating system

Fedora 37

### Helmfile Version

0.148.1

### Helm Version

3.10.2

### Bug description

When running `helmfile template`, temporary values files are created in temporary directories named `/tmp/helmfile*`. The temporary values files are removed before the end of the execution, but the temporary directories are left over.

After digging into the code, it seems to me that the directory created here is never removed:
https://github.com/helmfile/helmfile/blob/60621ff3187a903005dbbb44c71829ddf80ce87a/pkg/state/temp.go#L37-L42

### Example helmfile.yaml
```yaml
---
releases:
  - name: "test"
    chart: .
    values:
    - values.yaml
    - secrets.yaml
```

### Error message you've seen (if any)

There is no error message.

### Steps to reproduce

Run `helmfile template`.

### Working Helmfile Version

None?
