### ISSUE TITLE
Release 0.147.0 introduced  template: stringTemplate error

### ISSUE THREAD

**Issue by aeimer** [helmfile/helmfile#550]
### Operating system

MacOS 12.6

### Helmfile Version

v0.147.0

### Helm Version

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}

### Bug description

After updating to 0.147.0 the helmfile refuses to work with:
```shell
~/Downloads/helmfile_0.147.0_darwin_amd64/helmfile --kube-context foo -e sandbox -l namespace=default diff
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:107:25: executing "stringTemplate" at <.Values.projectEnvironments>: map has no entry for key "projectEnvironments"
```

With 0.146.0 the helmfile works as expected:
```shell
~/Downloads/helmfile_0.146.0_darwin_amd64/helmfile --kube-context foo -e sandbox -l namespace=default diff
==> usual expected output
```

Tested with 0.148.1, same broken result:
```shell
~/Downloads/helmfile_0.148.1_darwin_amd64/helmfile --kube-context foo -e sandbox -l namespace=default diff
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:107:25: executing "stringTemplate" at <.Values.projectEnvironments>: map has no entry for key "projectEnvironments"
```

### Example helmfile.yaml

```yaml
environments:
  # Default is used if no --environment flag is set
  # The order of the projectEnvs matters
  default: ~
  sandbox:
    values:
      - projectEnvironments:
          - main

releases:
- name: base
  namespace: default
  <<: *localChart
  values:
    - *valueDefault
    - *valueEnv
    - projectEnvironments:
        {{- range .Values.projectEnvironments }}
        - {{ . }}
        {{- end }}
    - base_chart_values.yaml
  <<: *labels
  wait: true
```

### Error message you've seen (if any)

`in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:107:25: executing "stringTemplate" at <.Values.projectEnvironments>: map has no entry for key "projectEnvironments"`

Line 107 is `{{- range .Values.projectEnvironments }}` in the original file. See example helmfile

### Steps to reproduce

https://github.com/aeimer/helmfile-bugdemo-parseerror

### Working Helmfile Version

0.146.0
