### ISSUE TITLE
helmDefaults do not seem to override helmDefaults of sub-helmfile

### ISSUE THREAD

**Issue by sigurdblueface** [helmfile/helmfile#581]
### Operating system

alpine 3.16.2

### Helmfile Version

v0.148.1

### Helm Version

v3.10.2

### Bug description

I have a parent helmfile with timeout of 360s, and a child helmfile with 60s timeout

In the end, helmfile uses timeout of 60s instead of 360s on `helmfile sync`
Is it expected? Is there a way to override timeout of sub-helmfile?

### Example helmfile.yaml

parent helmfile:
```yaml
helmDefaults:
  wait: true
  timeout: 360

helmfiles:
  - path: sms-web/helmfile.yaml
```
sub-helmfile:
```yaml
helmDefaults:
  wait: true
  timeout: 60

releases:
  - name: sms-web
    chart: chartmuseum/sms_web
```

### Error message you've seen (if any)

```err 1: failed processing release dds: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
  /usr/local/bin/helm
ARGS:
...
  9: --timeout (9 bytes)
  10: 60s (3 bytes)
...
  ```

### Steps to reproduce

sorry, may I provide it a bit later?

### Working Helmfile Version

haven't yet tried another versions

**Comment by yxxhero** [comment]
@sigurdblueface I think it's a feature. good idea.

**Comment by mumoshu** [comment]
This is an expected behavior as of today. No helmfile.yaml fields have been implicitly inherited down to sub-helmfiles so far. That is to keep every (sub-)helmfile independently runnable so that debugging and reusing are easier.

If you need something to be inherited, there must be an explicit way to do that.

For environment(not release) values, we introduced `helmfiles[].values` which is used to pass some values to the sub-helmfile.

> There's still no easy way to inherit all the values, although I remember that there was an old feature request to add `helmfiles[].inheritValues=true` to let Helmfile inherit all the available values to sub-helmfile(s).

Similarly, it might be possible to add `helmfiles[].helmDefaults` to override the sub-helmfile's helmDefaults using the helmDefaults defined in the parent helmfile.

**Comment by yxxhero** [comment]
@mumoshu got it.

**Comment by xiaomudk** [comment]
@mumoshu @yxxhero  Do we need to discuss this issue and continue to open it?

**Comment by mumoshu** [comment]
@xiaomudk I'm still unsure if it is worth the complexity! What's your idea on this? Shall we add `helmfiles[].helmDefaults` or `helmfiles[].inherit: ["helmDefaults", "environments]`, or...?

**Comment by iAnomaly** [comment]
Indirectly related to this, I had asked about implemented `go-getter` for `bases` too such that top-level keys like `helmDefaults`, etc. could be layered from remote sources (instead of just local filesystem): https://github.com/roboll/helmfile/issues/1842#issuecomment-995206575

Obviously this is not the same thing as `helmfiles` supporting `helmDefaults` but it is a similar problem.

If @mumoshu @xiaomudk @yxxhero feel good about the added functionality to `bases` I could try a PR.

**Comment by mumoshu** [comment]
@iAnomaly Sounds good! I'd love it if you could write up a dedicated issue for that first, so that we can discuss there while reviewing your PR 👍

**Comment by yxxhero** [comment]
@iAnomaly free to post PR. assigned you.

**Comment by iAnomaly** [comment]
Okay, finally had some time to dig in and solve this. There are multiple pieces:
1. After tracing the code I was wrong: `bases` DOES already support the remote file/directory/go-getter code path. Here is a working example using @sigurdblueface 's example:

base helmfile (pretend it is located at https://github.com/sigurdblueface/helmfile):
```yaml
helmDefaults:
  wait: true
  timeout: 360
```

release(s) helmfile:
```yaml
bases:
  - git::https://github.com/sigurdblueface/helmfile.git@bases/base.yaml # public repo
  - git::ssh://git@github.com/sigurdblueface/helmfile.git@bases/base.yaml # private repo
---
helmDefaults:
  wait: true
  timeout: 60

releases:
  - name: sms-web
    chart: chartmuseum/sms_web
```
Now in this example, I have tested and `60` wins over `360` (which I would expect/desire). You might be able to move/add another `bases` at the _end_ of your releases Helmfile if you want the `360` to win in that case (act more like an override).

2. As I said above, this does not solve your issue _specifically_ for `helmfiles` but would this be an acceptable workaround for now? I personally find `bases` much more intuitive and useful than `helmfiles` so far for DRYing out and layering/importing Helmfiles

3. FINALLY, I have noticed the caching logic for remote go-getter content is too aggressive/will not check if a Git remote updates for example. I will make a separate issue for this.
