### ISSUE TITLE
Helmfile/helm misses crds from patched resources when using transformers in a release 

### ISSUE THREAD

**Issue by devdruggy** [helmfile/helmfile#582]
### Operating system

macOS Ventura 13.0.1

### Helmfile Version

helmfile version v0.144.0

### Helm Version

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### Bug description

Helmfile/helm misses crds from manifests when using any of kustomize transformers in a release. Example command:
```
helmfile --debug --file=helmfile.yml --environment=local-environment diff --validate
```

If transformers list is empty, then crds create normally. However kustomize works as expected when i run the build command manually. 
```
kustomize build /var/folders/__/.../cert-manager/cert-manager
```

I am ready to provide additional information as needed

### Example helmfile.yaml

```
---
filepath:   helmfile.yaml
helmBinary: helm

environments:
  local-environment:

helmDefaults:
  atomic: true
  wait: true
  waitForJobs: true
  cleanupOnFail: true
  createNamespace: true

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  installed: true
  namespace: cert-manager
  version: 1.9.1
  values:
  - installCRDs: true

  transformers:
  - annotations:
      werf.io/show-service-messages: true
    apiVersion: builtin
    kind: AnnotationsTransformer
    metadata:
      name: notImportantHere
    fieldSpecs:
    - create: true
      path: metadata/annotations

```

### Error message you've seen (if any)

I noticed that in the first template command there is an --include-crds option and crds becomes available with it.

```
running helm fetch jetstack/cert-manager --untar -d /var/folders/__/.../cert-manager-9176/cert-manager --version 1.9.1
...
running helm template --debug=false --output-dir=/var/folders/__/.../cert-manager-9176/cert-manager/cert-manager/helmx.1.rendered --include-crds --validate cert-manager /var/folders/__/.../cert-manager-9176/cert-manager/cert-manager -f /.../values.yaml -f /var/folders/__/... --namespace cert-manager-9176
...
generated and using kustomization.yaml:
kind: ""
apiversion: ""
resources:
- templates/webhook-config.yaml
- templates/crds.yaml
- templates/cainjector-rbac.yaml
- templates/service.yaml
- templates/startupapicheck-job.yaml
- templates/cainjector-serviceaccount.yaml
- templates/webhook-serviceaccount.yaml
- templates/cainjector-deployment.yaml
- templates/startupapicheck-rbac.yaml
- templates/webhook-service.yaml
- templates/webhook-deployment.yaml
- templates/startupapicheck-serviceaccount.yaml
- templates/rbac.yaml
- templates/webhook-rbac.yaml
- templates/webhook-mutating-webhook.yaml
- templates/webhook-validating-webhook.yaml
- templates/serviceaccount.yaml
- templates/deployment.yaml
transformers:
- transformers/transformer.0.yaml
...
**Detected 43 resources and 6 CRDs**
...
1 release(s) found in issue.yml
```

But there is no --include-crds flag in the second template command. When transformers are empty, this flag is also not set, but crds is fine

```
exec: helm diff upgrade --reset-values --allow-unreleased cert-manager /var/folders/__/.../cert-manager-9176/cert-manager/cert-manager --version 1.9.1 --namespace cert-manager-9176 --values /var/folders/__/.../cert-manager-9176-cert-manager-values-55dfd7ddf4 --debug
helm:OWYxY> Executing helm version
helm:OWYxY> Executing helm get manifest cert-manager --namespace cert-manager-9176
helm:OWYxY> Executing helm template cert-manager /var/folders/__/.../cert-manager-9176/cert-manager/cert-manager --version 1.9.1 --namespace cert-manager-9176 --values /var/folders/__/.../cert-manager-9176-cert-manager-values-55dfd7ddf4 --validate --is-upgrade
helm:OWYxY> Executing helm get hooks cert-manager --namespace cert-manager-9176
```

### Steps to reproduce

-

### Working Helmfile Version

-

**Comment by yxxhero** [comment]
@devdruggy try to use latest version.

**Comment by devdruggy** [comment]
I tried to use latest version of helmfile (version 0.149.0) and helm (version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}) but it did not help.

**Comment by yxxhero** [comment]
@devdruggy Thanks for your feedback. do you have an interest in putting a PR for this?

**Comment by devdruggy** [comment]
Yes, it would be great to fix it. May be useful to add an annotations parameter to releases (similar to labels) to add generic annotations instead of using transformers. Example:
```
releases:
  - name: my release
     chart: my chart
     labels:
       mylabel: myvalue
     annotations:
       myannotation: myvalue
```
