### ISSUE TITLE
environments values gotmpl file {{ .Environment.Name }} is empty

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#603]
### Operating system

ALL

### Helmfile Version

ALL

### Helm Version

ALL

### Bug description

```
[root@devops testhelmfile]# tree
.
├── aaaaa
├── env
│   └── test
│       └── a.yaml.gotmpl
└── helmfile.yaml

2 directories, 3 files
[root@devops testhelmfile]# cat env/test/a.yaml.gotmpl
a: aaa_{{ .Environment.Name }}
```

debug log:
```
envvals_loader: loaded env/test/*.yaml.gotmpl:map[a:aaa_]
merged environment: &{test map[a:aaa_] map[]}
```

### Example helmfile.yaml
helmfile.yaml
```
environments:
  test:
    values:
    - a.yaml.gotmpl

repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
```
a.yaml.gotmpl
```
a: aaa_{{ .Environment.Name }}
```
### Error message you've seen (if any)

null

### Steps to reproduce

null

### Working Helmfile Version

null
