### ISSUE TITLE
helmfiles key does not respect environments inside helmfiles

### ISSUE THREAD

**Issue by dolohow** [helmfile/helmfile#608]
### Operating system

Arch Linux

### Helmfile Version

0.149.0

### Helm Version

v3.10.2

### Bug description

In top level `helmfile.yaml`, I have:
```
helmfiles:
   - path: a/helmfile.yaml
   - path: b/helmfile.yaml
```

and inside `a/helmfile.yaml`, I have:
```
environments: 
  default:
    values:
    - dev.yaml
  prod:
    values:
    - prod.yaml

releases:
  - chart: .
    name: a
    namespace: "{{ .Values.namespace }}"
    createNamespace: true
    values:
      - {{ .Values.environment }}.yaml
 ```

now when I call:
```
helmfile diff/apply
```

everything works fine, however
```
helmfile diff/apply -e prod
```
causes
```
err: no releases found that matches specified selector() and environment(prod), in any helmfile
```

when I modify top level `helmfile.yaml` to have `environments` key:
```
environments:
  default:
    values:
    - namespace: dev
  prod:
    values:
    - namespace: prod
 ```

I am getting
```
in ./helmfile.yaml: in .helmfiles[0]: in bag/helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:16:26: executing "stringTemplate" at <.Values.namespace>: map has no entry for key "namespace
```

regardless whether top level `helmfile.yaml` has `namespace` or not
