### ISSUE TITLE
line x: mapping key "<<" already defined at line y

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [helmfile/helmfile#627]
### Operating system

Mint 20.2

### Helmfile Version

0.149.0

### Helm Version

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### Bug description

Greetings,

I had a previous helmfile where this worked:

```
releases:
- name: somerelease
  <<: *localChart
  <<: *default
```

Now after updating to `helmfile version 0.149.0` i get this error:

```
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line x: mapping key "<<" already defined at line y
```

I cannot understand what changed in helmfile causing it to break. Thank you.

### Example helmfile.yaml

```
bases:
  - environments/environments.yaml

helmDefaults:
  createNamespace: true
  timeout: 90000

templates:
  default: &default
    missingFileHandler: Error
    values:
      - charts/{{`{{ .Release.Name }}`}}/values/{{`{{ .Release.Name }}`}}.values.yaml
  
  localChart: &localChart
    chart: charts/{{`{{ .Release.Name }}`}}/charts


repositories:
    # repo here

releases:
- name: somerelease
  <<: *localChart
  <<: *default
```

### Error message you've seen (if any)

in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line x: mapping key "<<" already defined at line y

### Steps to reproduce

helmfile apply

### Working Helmfile Version

idk

### Relevant discussion

https://github.com/helmfile/helmfile/issues/493
