### ISSUE TITLE
empty chart when using `inherit: template`

### ISSUE THREAD

**Issue by VladStarr** [helmfile/helmfile#638]
### Operating system

macOS Ventura 13.1

### Helmfile Version

0.150.0

### Helm Version

v3.10.2

### Bug description

It seems that inherit option does not pass `chart` key from template to release spec.

Any help or clarification to `inherit` option will be much appreciated :)

### Example helmfile.yaml

```yaml
templates:
  redis: &redis
    chart: bitnami/redis
    labels:
      chart: redis
    version: {{ env "version" | default "" }}
    missingFileHandler: Debug
    kubeContext: {{ env "KUBE_CONTEXT" }}
    secrets:
      - secrets/{{`{{ .Release.Name }}`}}.yaml
    valuesTemplate:
      - ../common/values/redis.yaml.gotmpl
      - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl
```

```yaml
releases:
  - name: dev-redis-0
    namespace: redis
    inherit:
      template: redis
    version: ~11.3.0
```

### Error message you've seen (if any)

`in ./helmfile.yaml: in .helmfiles[0]: in dev/helmfile.yaml: error during helmfile.yaml.part.0 parsing: encountered empty chart while reading release "dev-redis-0" at index 3`

### Steps to reproduce

Provided in helmfile yaml above

### Working Helmfile Version

0.146.0
