### ISSUE TITLE
New yaml parser is too strict

### ISSUE THREAD

**Issue by metajiji** [helmfile/helmfile#642]
### Operating system

Fedora 37

### Helmfile Version

```text

▓▓▓ helmfile

  Version            0.150.0
  Git Commit         fc634c9
  Build Date         17 Jan 23 09:24 +07 (2 days ago)
  Commit Date        17 Jan 23 07:34 +07 (2 days ago)
  Dirty Build        no
  Go version         1.19.4
  Compiler           gc
  Platform           linux/amd64
```

### Helm Version

```text
{
  Version:"v3.10.3",
  GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704",
  GitTreeState:"clean",
  GoVersion:"go1.18.9"
}
```

### Bug description

Before version `0.150.0` yaml has been merged without errors on duplicate keys, but in `helmfile` version `0.150.0` we get an error.

Previously, data with type `map` is merged and `lists` and `strings` are overwritten.

### Example helmfile.yaml

```yaml
templates:
  default: &default_chart_conf
    namespace: {{ .Namespace }}
    missingFileHandler: Error
    values:
      - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl
  stateless-app: &stateless_app_chart_conf
    <<: *default_chart_conf
    chart: charts/stateless-app
    values:
      - values/{{`{{ .Release.Name }}`}}.yaml.gotmpl
      - imagePullSecrets:
          - name: regcred

releases:
  - name: app1
    <<: *stateless_app_chart_conf
```

### Error message you've seen (if any)

```
err: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 16: key "values" already set in map
  line 16: key "values" already set in map
```

### Steps to reproduce

https://github.com/metajiji/helmfile-0.150-bug/tree/main

### Working Helmfile Version

`0.149.0`
