### ISSUE TITLE
Key "already set in map" error with overrides declared in yaml

### ISSUE THREAD

**Issue by lucasshawn** [helmfile/helmfile#666]
### Operating system

macos 12.6

### Helmfile Version

 ▓▓▓ helmfile    Version            v0.150.0   Git Commit         "brew"   Build Date         16 Jan 23 16:34 PST (1 week ago)   Commit Date        16 Jan 23 16:34 PST (1 week ago)   Dirty Build        no   Go version         1.19.5   Compiler           gc   Platform           darwin/amd64

### Helm Version

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### Bug description

I've been bumping into this with 0.150.0 where I was not seeing this in 0.149.0.  Copying release file from issue 493:
```
---
templates:
  default_release: &default_release
    namespace: "myNamespace"

releases:
  - name: "release1"
    << : *default_release
    chart: "charts/mychart"
```

The above works when rendering a template.  However if I attempt an override in the release decl, like the following adjusted release file:

```
---
templates:
  default_release: &default_release
    namespace: "myNamespace"

releases:
  - name: "release1"
    << : *default_release
    chart: "charts/mychart"
    namespace: "overridenamespace"
```

I get the following:

```
❯ helmfile -l name=release1 template
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 13: key "namespace" already set in map
```

Expect this to be valid yaml and the keys to be merged/overwritten, effectively getting this from the release decl:

```
releases:
  - name: "release1"
    chart: "charts/mychart"
    namespace: "overridenamespace"
```

### Example helmfile.yaml
```
---
templates:
  default_release: &default_release
    namespace: "myNamespace"

releases:
  - name: "release1"
    << : *default_release
    chart: "charts/mychart"
    namespace: "overridenamespace"
```

### Error message you've seen (if any)
```
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 13: key "namespace" already set in map
```
### Steps to reproduce

See simple helmfile release decl above

### Working Helmfile Version

Team members are not seeing this with 0.149.0

### Relevant discussion

https://github.com/helmfile/helmfile/issues/493

**Comment by yxxhero** [comment]
`HELMFILE_GOCCY_GOYAML=true`

**Comment by yxxhero** [comment]
@lucasshawn

**Comment by lucasshawn** [comment]
Thank you very much for the quick response.  Tried you recommended env var, but I'm not seeing any differences.  I turned on debugging just to get a full diag:
```
❯ HELMFILE_GOCCY_GOYAML=true
❯ helmfile --debug template --skip-deps
processing file "helmfile.yaml" in directory "."
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: 

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: 

merged environment: &{default map[] map[]}
first-pass rendering starting for "helmfile.yaml.part.1": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.1":
 0: templates:
 1:   default_release: &default_release
 2:     namespace: "myNamespace"
 3:   default_labels:
 4:     labels: &default_labels
 5:       project: "myProject"
 6:       group: "myGroup"
 7: 
 8: releases:
 9:   - name: "release1"
10:     << : *default_release
11:     chart: "charts/mychart"
12:     namespace: "overridenamespace"
13:   

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.1": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.1":
 0: templates:
 1:   default_release: &default_release
 2:     namespace: "myNamespace"
 3:   default_labels:
 4:     labels: &default_labels
 5:       project: "myProject"
 6:       group: "myGroup"
 7: 
 8: releases:
 9:   - name: "release1"
10:     << : *default_release
11:     chart: "charts/mychart"
12:     namespace: "overridenamespace"
13:   

err: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 13: key "namespace" already set in map
changing working directory back to "/Users/shawnlucas/repos/siemv2/src/helmfile"
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 13: key "namespace" already set in map
```
### Helmfile.yaml
```

---
templates:
  default_release: &default_release
    namespace: "myNamespace"
  default_labels:
    labels: &default_labels
      project: "myProject"
      group: "myGroup"

releases:
  - name: "release1"
    << : *default_release
    chart: "charts/mychart"
    namespace: "overridenamespace"
  ```
