### ISSUE TITLE
jsonPatches (chartify) does not render with helm-hooks

### ISSUE THREAD

**Issue by Sea-you** [helmfile/helmfile#668]
### Operating system

Darwin

### Helmfile Version

v0.150.0

### Helm Version

v3.11.0

### Bug description

With the helm hook [here](https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/101.0.0%2Bup19.0.3/templates/rancher-monitoring/hardened.yaml) only the `Job` resource renders properly from this file.

I tested locally by removing the hook and all other resources rendered.

If I remove the `jsonPatches`, it also renders properly. Any clue what could be wrong here?

[debug.log](https://github.com/helmfile/helmfile/files/10556216/debug.log)

### Example helmfile.yaml

```
repositories:
- name: rancher
  url: https://charts.rancher.io

releases:
- name: rancher-monitoring
  chart: rancher/rancher-monitoring
  namespace: cattle-monitoring-system
  version: '100.1.3+up19.0.3'
  jsonPatches:
  - patch:
      - op: replace
        path: /metadata/namespace
        value: cattle-monitoring-system
    target:
      kind: ServiceMonitor
      name: rancher-monitoring-apiserver
      group: monitoring.coreos.com
      version: v1
```

### Error message you've seen (if any)

N/A

### Steps to reproduce

Run the helmfile attached.

### Working Helmfile Version

N/A
