### ISSUE TITLE
Misleading error message when dependency-repository is not defined

### ISSUE THREAD

**Issue by firefrei** [helmfile/helmfile#669]
### Operating system

Ubuntu 20.04.5 LTS

### Helmfile Version

0.150.0

### Helm Version

v3.8.0

### Bug description

When I try to add cert-manager's helm chart repo, I receive the following error during `helmfile deps` (same for `helmfile sync/apply`):
```bash
Adding repo jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

in ./helmfile.yaml: [failed reading adhoc dependencies: unexpected format of `helm repo list` at line 2 "" in:
NAME    	URL
jetstack	https://charts.jetstack.io
]
```

However, with other repositories I am not facing this issue. Only difference: All of them have a path in the URL, like `https://projectcalico.docs.tigera.io/charts` while cert-manager has not `https://charts.jetstack.io`.

Installed helm plugins:
```bash
NAME    	VERSION	DESCRIPTION
diff    	3.6.0  	Preview helm upgrade changes as a diff
helm-git	0.14.2 	Get non-packaged Charts directly from Git.
```

### Example helmfile.yaml
```yaml
# Fails:
repositories:
  - name: jetstack
    url: 'https://charts.jetstack.io'

# Works:
repositories:
  - name: metallb
    url: 'https://metallb.github.io/metallb'
```
### Error message you've seen (if any)
```
failed reading adhoc dependencies: unexpected format of `helm repo list`
```

### Steps to reproduce

See example

### Working Helmfile Version

unknown

**Comment by yxxhero** [comment]
@firefrei please put debug log by adding --debug flag.

**Comment by firefrei** [comment]
I figured out the issue of the error message.
I was using a chart-dependecy using a repo that did not exist.
So, the error message was misleading and does not reflect the actual issue.

helmfile:
```yaml
repositories:
  - name: jetstack
    url: 'https://charts.jetstack.io'

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    installed: true
    wait: true
    atomic: true
    values:
      - values.yaml
    dependencies:
      - chart: <internal-repo>/cert-manager-root-ca
        version: "0.0.0"
        alias: rootCa
```
`<internal-repo>` was not yet added to helm's repo list.

However, the error message is complaining about the output of "helm repo list":
```bash
processing file "helmfile.yaml" in directory "."
changing working directory to "<hidden-path>/cert-manager"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: # Configuration file examples:
 1: # https://helmfile.readthedocs.io/en/latest/#configuration
 2:
 3: repositories:
 4:   - name: jetstack
 5:     url: 'https://charts.jetstack.io'
 6:
 7: releases:
 8:   - name: cert-manager
 9:     namespace: cert-manager
10:     createNamespace: true
11:     chart: jetstack/cert-manager
12:     installed: true
13:     wait: true
14:     atomic: true
15:     values:
16:       - values.yaml
17:     dependencies:
18:       - chart: <internal-repo>/cert-manager-root-ca
19:         version: "0.0.0"
20:         alias: rootCa
21:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: # Configuration file examples:
 1: # https://helmfile.readthedocs.io/en/latest/#configuration
 2:
 3: repositories:
 4:   - name: jetstack
 5:     url: 'https://charts.jetstack.io'
 6:
 7: releases:
 8:   - name: cert-manager
 9:     namespace: cert-manager
10:     createNamespace: true
11:     chart: jetstack/cert-manager
12:     installed: true
13:     wait: true
14:     atomic: true
15:     values:
16:       - values.yaml
17:     dependencies:
18:       - chart: <internal-repo>/cert-manager-root-ca
19:         version: "0.0.0"
20:         alias: rootCa
21:

merged environment: &{default map[] map[]}
helm:uhjTj> v3.11.0+g472c573
helm:uhjTj>
Adding repo jetstack https://charts.jetstack.io
exec: helm repo add jetstack https://charts.jetstack.io --force-update
helm:gXIzW> "jetstack" has been added to your repositories
helm:gXIzW>
"jetstack" has been added to your repositories

Chartify process for jetstack/cert-manager
Successfully generated the value file at values.yaml. produced:
#
# Root CA Creation
#
rootCa:
  root_secret_name: ce-r-root-ca-secret
  common_name: ca.<hidden-domain>
  cluster_issuer_name: ce-r-cluster-issuer
  issuer_ca_name: ce-r-ca-issuer


#
# cert manager deployment
#

#version: 'vXXX'
installCRDs: true
#ingressShim:
#  defaultIssuerName: "letsencrypt-prod"
#  defaultIssuerKind: "ClusterIssuer"
#  defaultIssuerGroup: "cert-manager.io"

running helm fetch jetstack/cert-manager --untar -d /tmp/chartify1077886989/cert-manager/cert-manager
running helm repo list
Removed /tmp/helmfile300815712/cert-manager-cert-manager-values-744bff57d4
Removed /tmp/helmfile300815712
err: [failed reading adhoc dependencies: unexpected format of `helm repo list` at line 2 "" in:
NAME    	URL
jetstack	https://charts.jetstack.io
]
changing working directory back to "<hidden-path>/cert-manager"
in ./helmfile.yaml: [failed reading adhoc dependencies: unexpected format of `helm repo list` at line 2 "" in:
NAME    	URL
jetstack	https://charts.jetstack.io
]
```

When I add the dependency, either in the helmfile or manually using helm repo add, the error is gone and updating dependencies works as expected.
