### ISSUE TITLE
--state-values-set does not work properly in gotmpl value files

### ISSUE THREAD

**Issue by vladimir-avinkin** [helmfile/helmfile#700]
### Operating system

MacOS 12.1

### Helmfile Version

0.150.0

### Helm Version

v3.9.4

### Bug description

See the linked github repo's README file

### Example helmfile.yaml

See the linked github repo's README file.

### Error message you've seen (if any)

None

### Steps to reproduce

https://github.com/vladimir-avinkin/helmfile-bug-repro

### Working Helmfile Version

Haven't found one

**Comment by yxxhero** [comment]
@vladimir-avinkin quick solution:
```
environments:
  default:
    values:
      - base.yaml
      - override.yaml
# key change
--- 
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}
    values:
      - values.yaml.gotmpl
```
