### ISSUE TITLE
kubeVersion is being loaded from helmfile.yaml instead of cli

### ISSUE THREAD

**Issue by Edu-DevOps** [helmfile/helmfile#722]
### Operating system

macOS Ventura

### Helmfile Version

v0.151.0 arm64

### Helm Version

v3.11.1

### Bug description

The current helmfile [official doc](https://helmfile.readthedocs.io/en/latest/) specify this:
`helmfile.yaml`
```
# DEPRECATED: This is available only on Helm 2, which has been EOL since 2020
# Configure a Kubernetes version to  pass to 'helm template' via the --kube-version flag:
# See https://github.com/roboll/helmfile/pull/2002 for more information.
kubeVersion: v1.21
```

I've been working with an issue trying to specify the kubeVersion via CLI as the doc said but it's not working.

I've found [this](https://github.com/helmfile/helmfile/blob/f629ee1ae6540dcb1b3c9917bf3dbc81f96a07c0/pkg/state/state.go#L1205) in the code so I believe that helmfile is getting the kubeVersion from the release defined in the `helmfile.yaml` file instead of CLI as doc says.

Is this expected? Am I missing anything?

Thanks in advance.

```
### Example helmfile.yaml

environments:
  <env name>:
    missingFileHandler: Warn
    values: # These values are the ones used to render values.yaml.gotmpl
      - values.yaml

templates:
  default: &default
    chart: .
    namespace: argo-cd-system
    missingFileHandler: Warn
    version: 1.0
    kubeVersion: 1.18.0
    set:
      - name: foo
        value: bar
      - name: foo1
        value: bar1
    values: # Values to render the helm chart
      - <n values files>
    jsonPatches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: redis-ha-haproxy
        path: jsonpatches/patch.redis-ha-haproxy-deployment.yaml
      - target:
          group: apps
          version: v1
          kind: StatefulSet
          name: redis-ha-server
        path: jsonpatches/patch.redis-ha-statefulset.yaml
      - target:
          version: v1
          kind: Pod
          name: redis-ha-configmap-test
        path: jsonpatches/patch.test-redis-ha-configmap.yaml
      - target:
          version: v1
          kind: Pod
          name: redis-ha-service-test
        path: jsonpatches/patch.test-redis-ha-pod.yaml

releases:
  - name: kraken
    <<: *default
```

### Error message you've seen (if any)

I'm working with the argocd helm chart v5.8.7.

So, if I render the templates specifying the kubeVersion in the `helmfile.yaml` file, I get the expected output:
```
apiVersion: autoscaling/v2beta1
```

But if I remove the kubeVersion from the `helmfile.yaml` I get the wrong output:
```
apiVersion: autoscaling/v2 #this apiVersion is not available in my k8s version`
```

### Steps to reproduce

N/A

### Working Helmfile Version

v0.151.0
