### ISSUE TITLE
helmBinary ignored in helmfile.d/ files

### ISSUE THREAD

**Issue by iridian-ks** [helmfile/helmfile#754]
### Operating system

macOS 13

### Helmfile Version

  Version            v0.151.0   Git Commit         "brew"   Build Date         16 Feb 23 22:09 PST (4 weeks ago)   Commit Date        16 Feb 23 22:09 PST (4 weeks ago)   Dirty Build        no   Go version         1.19.6   Compiler           gc   Platform           darwin/arm64

### Helm Version

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}

### Bug description

Apologies if I am missing something simple here.

## Setup

```
$ tree
├── helmfile.d
│   ├── cert-manager.yaml
├── scripts
│   ├── helm-driver-configmap
│   └── helm-driver-secrets
```

```
$ cat scripts/helm-driver-secrets
#!/bin/sh

echo "TICK" >> ../logs.txt

export HELM_DRIVER="secret"

helm $@
```

## Expectation

The `helmBinary` config would select the executable that `helmfile` will use.

### Example helmfile.yaml

```
---

helmBinary: ../scripts/helm-driver-secrets
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager-system
    chart: jetstack/cert-manager
    version: ~1.8
```

### No args
```
$ helmfile diff --debug
...
exec: helm diff upgrade  ...
...
```

```
$ cat logs.txt
gcat: logs.txt: No such file or directory
```

### Select specific helmfile
```
$ helmfile -f helmfiles.d/cert-manager.yaml diff --debug
...
exec: helm diff upgrade  ...
...
```

```
$ cat logs.txt
gcat: logs.txt: No such file or directory
```

### Specify helm binary via CLI

```
$ helmfile --helm-binary ../scripts/helm-driver-secrets -f helmfile.d/cert-manager.yaml diff --debug
...
exec: ../scripts/helm-driver-secrets diff upgrade ...
...
```

```
$ cat logs.txt
TICK
TICK
TICK
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@iridian-ks thanks very much. good catch. I will post a quick fix.

**Comment by yxxhero** [comment]
wait. I can't reproduce your issue. could you try to test it by `helmfile template` cmd?

**Comment by yxxhero** [comment]
@iridian-ks ping

**Comment by iridian-ks** [comment]
Hi! Sorry I didn't get back to you sooner. I did a hacky workaround by using a Makefile and labels:

```
release:
    helmfile --helm-binary scripts/helm-driver-secrets --selector driver=secret ...
    helmfile --helm-binary scripts/helm-driver-configmap --selector driver=secret ...
```

```
...
releases:
  - name: metrics-server
    namespace: kube-system
    version: {{ .Values.metricsServer.version }}
    chart: metrics-server/metrics-server
    labels:
      driver: secret
    installed: {{ .Values.metricsServer.enabled }}
    values:
      - ../values/metrics-server.yaml
...
```

The CLI flag `--helm-binary` did work perfectly in this case, but for some reason was having issues in the YAML files.

Unfortunately, as you can tell, I don't have a ton of time to help fix/reproduce and my workaround (while hacky) is sufficient for now.

I really appreciate you looking at this and responding though!! 💯
