### ISSUE TITLE
`helmfile apply` fails whenever chart defines custom resource instances while defining their CRDs

### ISSUE THREAD

**Issue by zer0def** [helmfile/helmfile#763]
### Operating system

Arch Linux, but not technically relevant

### Helmfile Version

0.151.0, also happens with devel HEAD

### Helm Version

version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.20.1"}

### Bug description

Whenever a new chart defines custom resources alongside their definitions, during preparation phase of `helmfile apply`, specifically while running `helm diff`, that last command is ran with validation against the target cluster, resulting in errors like the following:

```
  Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "cassandra" namespace: "storage" from "": no matches for kind "ScyllaCluster" in version "scylla.scylladb.com/v1"
  ensure CRDs are installed first
```

Naturally, validating custom resources which are yet to have their definition applied to the target cluster doesn't make sense. While it can be argued as bad practice, even a number of high profile charts at some point in the past, while some others still do, provided CRs alongside CRDs, like Istio, Minio-Operator or Kube-Prometheus-Stack.

### Example helmfile.yaml

```
releases:
- name: cassandra-operator
  namespace: storage
  chart: "/home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator"  # https://github.com/zer0def/scylla-operator/blob/master/helm/scylla-operator/templates/cluster.scyllacluster.yaml
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args:
    - "-xec"
    - |
      until kubectl wait --for condition=established crd/scyllaclusters.scylla.scylladb.com; do sleep 1; done 2>/dev/null ||:
      sleep 30
  values:
  - fullnameOverride: "cassandra-operator"
    webhook:
      createSelfSignedCertificate: false
    scyllaClusters:
    - name: cassandra
      namespace: storage
      scyllaImage:
        tag: 5.1.5
      agentImage:
        tag: 3.0.2
      alternator:
        enabled: true
      developerMode: true
      serviceMonitor:
        create: false
      sysctls:
      - fs.aio-max-nr=2097152
      racks:
      - name: a
        members: 2
        storage:
          capacity: 1Gi
```

### Error message you've seen (if any)

```
exec: /usr/bin/helm diff upgrade --allow-unreleased cassandra-operator /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator --namespace storage --values /tmp/helmfile263147092/storage-cassandra-operator-values-6b69d777bb --detailed-exitcode --no-color --reset-values
helm:rQyTC> ********************
helm:rQyTC> 
helm:rQyTC> Release was not present in Helm.  Diff will show entire contents as new.
helm:rQyTC> 
helm:rQyTC> ********************
helm:rQyTC> 
helm:rQyTC> Error: Failed to render chart: exit status 1: walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_nodeconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml. Contents of linked file included and used
helm:rQyTC> walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaclusters.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml. Contents of linked file included and used
helm:rQyTC> walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml. Contents of linked file included and used
helm:rQyTC> Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "cassandra" namespace: "storage" from "": no matches for kind "ScyllaCluster" in version "scylla.scylladb.com/v1"
helm:rQyTC> ensure CRDs are installed first
helm:rQyTC> 
helm:rQyTC> 
helm:rQyTC> Error: plugin "diff" exited with error
helm:rQyTC> 
Comparing release=cassandra-operator, chart=/home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator
err: release "cassandra-operator" in "scylla.yaml" failed: command "/usr/bin/helm" exited with non-zero status:

PATH:
  /usr/bin/helm

ARGS:
  0: /usr/bin/helm (13 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: cassandra-operator (18 bytes)
  5: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator (76 bytes)
  6: --namespace (11 bytes)
  7: storage (7 bytes)
  8: --values (8 bytes)
  9: /tmp/helmfile263147092/storage-cassandra-operator-values-6b69d777bb (67 bytes)
  10: --detailed-exitcode (19 bytes)
  11: --no-color (10 bytes)
  12: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_nodeconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml. Contents of linked file included and used
  walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaclusters.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml. Contents of linked file included and used
  walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml. Contents of linked file included and used
  Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "cassandra" namespace: "storage" from "": no matches for kind "ScyllaCluster" in version "scylla.scylladb.com/v1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  ********************
  	Release was not present in Helm.  Diff will show entire contents as new.
  ********************
  Error: Failed to render chart: exit status 1: walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_nodeconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_nodeconfigs.yaml. Contents of linked file included and used
  walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaclusters.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1/scylla.scylladb.com_scyllaclusters.yaml. Contents of linked file included and used
  walk.go:74: found symbolic link in path: /home/zer0def/sync/projects/aquarium/charts/scylla/helm/scylla-operator/crds/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml resolves to /home/zer0def/sync/projects/aquarium/charts/scylla/pkg/api/scylla/v1alpha1/scylla.scylladb.com_scyllaoperatorconfigs.yaml. Contents of linked file included and used
  Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "cassandra" namespace: "storage" from "": no matches for kind "ScyllaCluster" in version "scylla.scylladb.com/v1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error
```

### Steps to reproduce

`helmfile -f /path/to/provided/helmfile.yaml apply`

### Working Helmfile Version

No version down to 0.132.0 exhibits working behavior.
