### ISSUE TITLE
Helm values.yaml from URL

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#780]
### Discussed in https://github.com/helmfile/helmfile/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **yellowmegaman** August  4, 2022</sup>
Greetings!

Can someone share an example of using values.yaml from url?
```
releases:
- name: haproxy
  namespace: "haproxy"
  createNamespace: true
  chart: "haproxytech/haproxy"
  version: "v1.14.0"
  atomic: true
  timeout: 300
  values:
    - https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml
```

Like it is working in helm:
```
helm install haproxy --values=https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml haproxytech/haproxy
```

Example above yelds:
```
in ./helmfile.yaml: values file matching "https://storage.googleapis.com/somebucket/haproxy-values-istio-v1.0.0.yaml" does not exist in "."
```

Thanks in bunch in advance!</div>
