### ISSUE TITLE
Migrating pre-0.150 release templates to 0.152.0

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#786]
### Discussed in https://github.com/helmfile/helmfile/discussions/779

<div type='discussions-op-text'>

<sup>Originally posted by **jjungnickel** April  4, 2023</sup>
I'm having trouble refactoring our existing releases to the latest helmfile release. I've reduced the existing helmfile definition to a minimal case:
```yaml
templates:
  default:
    missingFileHandler: Warn
    valuesTemplate:
      - fullnameOverride: '{{`{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}`}}'
    values:
       - "../apps/{{`{{ .Release.Name }}`}}.yaml.gotmpl"
    labels:
      app: "{{`{{ .Release.Name }}`}}"

releases:
  - name: my-app
    inherit:
      - template: default
```

This fails as follows:
```> HELMFILE_V1MODE=true HELMFILE_GOCCY_GOYAML=true helmfile  template --debug
processing file "helmfile.yaml.gotmpl" in directory "."
changing working directory to "<obfuscated>"
rendering starting for "helmfile.yaml.gotmpl.part.0": inherited=&{default map[] map[]}, overrode=<nil>
rendering result of "helmfile.yaml.gotmpl.part.0":
 0: templates:
 1:   default:
 2:     missingFileHandler: Warn
 3:     valuesTemplate:
 4:       - fullnameOverride: '{{ .Values | get (printf "%s.releaseName" .Release.Name) .Release.Name }}'
 5:     values:
 6:        - "../apps/{{ .Release.Name }}.yaml.gotmpl"
 7:     labels:
 8:       app: "{{ .Release.Name }}"
 9: 
10: releases:
11:   - name: my-app
12:     inherit:
13:       - template: default
14: 

merged environment: &{default map[] map[]}
changing working directory back to "<obfuscated>"
in ./helmfile.yaml.gotmpl: failed executing release templates in "helmfile.yaml.gotmpl": failed executing templates in release "helmfile.yaml.gotmpl"."my-app": failed executing template expressions in release "my-app".values[0] = "fullnameOverride: "{{ .Values | get (printf \"%s.releaseName\" .Release.Name) .Release.Name }}"
": template: stringTemplate:1: unexpected "\\" in operand
```

I'd appreciate any hints in the right direction.</div>
