### ISSUE TITLE
Support --enable-dns helm flag

### ISSUE THREAD

**Issue by wiegandf** [helmfile/helmfile#788]
### Operating system

darwin/arm64

### Helmfile Version

v0.152.0

### Helm Version

v3.11.2

### Bug description

With helm 3.11.1, the --enabe-dns flag was introduced. Background for this was https://github.com/advisories/GHSA-pwcw-6f5g-gxf8. The PR was this https://github.com/helm/helm/commit/5abcf74227bfe8e5a3dbf105fe62e7b12deb58d2. 

When adding this flag via helmDefaults.args[], helmfile template works properly and the getHostByName function works properly. 
helmfile apply will show two issues though:
1. It always shows a (wrong) diff with getHostByName not working. Is this just an issue from helm-diff? The resulting release shows no error and the k8s resource seems to be correctly deployed.
2. the resulting helm list fails because helm list doesn't have support for this flag.

I had to disable validation because helm diff also doesn't support this flag, see https://github.com/databus23/helm-diff/issues/447.

### Example helmfile.yaml

```yaml
...

helmDefaults:
  disableValidation: true
  args:
    - "--enable-dns"
  
...
```

### Error message you've seen (if any)

An (artifical) example template value to show the first issue:
```yaml
kind: Endpoints
apiVersion: v1
metadata:
  name: endpoint
subsets:
- addresses:
  - ip: {{ "google.com" | getHostByName }}
  ports:
    - name: https
      port: 443
```

Without --enable-dns working, this results in the following diff:
```yaml
  kind: Endpoints
  apiVersion: v1
  metadata:
    name: kafka-monitoring-node
    namespace: monitoring
  subsets:
  - addresses:
-   - ip: 142.251.36.206
+   - ip:
```
---
helm list (error only shows with --debug flag)
PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^release-name$ (18 bytes)
  4: --namespace (11 bytes)
  5: namespace-name (10 bytes)
  6: --uninstalling (14 bytes)
  7: --deployed (10 bytes)
  8: --failed (8 bytes)
  9: --pending (9 bytes)
  10: --debug (7 bytes)
  11: --enable-dns (12 bytes)

### Steps to reproduce

see above

### Working Helmfile Version

n/a

### Relevant discussion

https://helmfile.readthedocs.io/en/latest/proposals/towards-1.0/#remove-the-args-flag-from-the-helmfile-command
