### ISSUE TITLE
Helmfile sync not downloading remote charts dependencies (helm dep build)

### ISSUE THREAD

**Issue by efiShtain** [helmfile/helmfile#795]
### Operating system

Mac (intel)

### Helmfile Version

v0.149.0

### Helm Version

v3.8.0

### Bug description

# Description

I have a chart in a private chartmuseum with the following Chart.yaml file

```yaml
apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetess
name: environment
version: 1.0.0
dependencies:
    - name: mysql5.7
      alias: mysql
      version: 1.4.0
      condition: mysql.enabled
    - name: mysql
      alias: mysql8
      version: 9.4.8
      repository: '@bitnami'
      condition: mysql8.enabled
```

since version 1.4.0 is really old, I store the chart in the charts directory (there is no repository or file key in it's definition), it is also aliased as mysql5.7

mysql8 is an updated version, so I use ```helm dep up``` to download it when I want to install the chart

# The Problem
Running ```helmfile sync``` with the following helmfile does not install the mysql8 depdenency

```yaml
releases:
- name: environment
  chart: chartmuseum/environment
  namespace: namespace
```

_If I download the chart from chartmusem manually, and change the helmfile to reference the local chart, it does download the extra dependency_

# Expected behaviour
running ```helmfile sync``` should recursively download dependencies 

### Example helmfile.yaml

releases:
- name: environment
  chart: chartmuseum/environment
  namespace: namespace

### Error message you've seen (if any)

 An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies

### Steps to reproduce

described in description

### Working Helmfile Version

?
