### ISSUE TITLE
`helmfile list --output json` outputs invalid json when hook is present with showlogs

### ISSUE THREAD

**Issue by yelhouti** [helmfile/helmfile#798]
### Operating system

fedora 37

### Helmfile Version

helmfile version 0.152.0

### Helm Version

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### Bug description

`helmfile list --output json` outputs
When hooks has `showLogs`
> hook[prepare] logs | 
<JSON_HERE>

### Example helmfile.yaml

```
- chart: bitnami/keycloak
  name: keycloak
  version: 10.1.5
  wait: true
  hooks:
    - events: [ "prepare" ]
      showlogs: false
      command: "./preview.sh"
```

preview.sh:
```
#!/bin/sh
```

### Error message you've seen (if any)

error happens when parsing

### Steps to reproduce

explained above

### Working Helmfile Version

none
