### ISSUE TITLE
Unexpected rendering issue for v1 mode

### ISSUE THREAD

**Issue by gakesson** [helmfile/helmfile#807]
### Operating system

Ubuntu 20.04.4 LTS

### Helmfile Version

0.152.0

### Helm Version

3.11.2

### Bug description

I've started to look into our helmfile v1 mode and bumped into an issue.

In the attached **helmfile.yaml.gotmpl** the $configDir variable is added as a value, and within same yaml document the environments (attached **envs.yaml**) section is loaded, which uses the configDir previously added .Values. However, in v1 mode this fails with:

`in ./helmfile.yaml.gotmpl: error during helmfile.yaml.gotmpl.part.0 parsing: template: stringTemplate:9:6: executing "stringTemplate" at <tpl (readFile $envFile) .>: error calling tpl: template: stringTemplate:4:18: executing "stringTemplate" at <.Values.configDir>: map has no entry for key "configDir`

Without v1 mode it works fine, i.e. configDir in .Values is instantly exposed to the envs.yaml rendering, even if adding of configDir to .Values is done within same yaml document as the envs.yaml rendering.

Using attached files this can be reproduced by:

`export HELMFILE_V1MODE=true && helmfile -e prod template`

It is working with:

`export HELMFILE_V1MODE=false && helmfile -e prod template`

### Example helmfile.yaml

helmfile.yaml.gotmpl :
```
{{ $configDir := default (env "CONFIG_DIR") | default "config" }}
values:
- configDir: {{ $configDir }}
{{ tpl (readFile (printf "%s/envs.yaml" $configDir)) . }}
---
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
releases:
- name: service-a
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: {{ .Values | get "some-random-key" "" }}
```

envs.yaml :

```
environments:
  prod:
    values:
      - {{ .Values.configDir }}/envs/prod/values.yaml
```
config/envs/prod/values.yaml :

`some-random-key: with-some-random-value`

### Error message you've seen (if any)

`in ./helmfile.yaml.gotmpl: error during helmfile.yaml.gotmpl.part.0 parsing: template: stringTemplate:9:6: executing "stringTemplate" at <tpl (readFile $envFile) .>: error calling tpl: template: stringTemplate:4:18: executing "stringTemplate" at <.Values.configDir>: map has no entry for key "configDir`

### Steps to reproduce

See bug description

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@mumoshu

**Comment by mumoshu** [comment]
Hey @gakesson and @yxxhero! Thank you so much for your support as always ❤️ 
I just reviewed this, and I think this is supposed to fail in helmfile v1 because it depends on the double-rendering feature we will disable in v1.

**gakesson's (original)**
```
{{ $configDir := default (env "CONFIG_DIR") | default "config" }}
values:
- configDir: {{ $configDir }}
{{ tpl (readFile (printf "%s/envs.yaml" $configDir)) . }}
```

is almost equivalent to

**gakesson's (how it's treated)**
```
{{ $configDir := default (env "CONFIG_DIR") | default "config" }}
values:
- configDir: {{ $configDir }}
environments:
  prod:
    values:
      - {{ .Values.configDir }}/envs/prod/values.yaml
```

This is a template that must be rendered before decoding the YAML data. At the render time `values` are not present because it isn't decoded as YAML yet.

I think @yxxhero got this and rewrote @gakesson's example so that the values and environments parts are separated with `---`. This removes the dependency on double-rendering and, therefore, should work.

Hey @yxxhero, did you example work? (I presume so- just confirming!

I can suggest further enhancing yxxhero's awesome example to keep configDir definition DRY.

**yxxhero's**

```
{{ $configDir := default (env "CONFIG_DIR") | default "config" }}
values:
- configDir: {{ $configDir }}
---
{{ $configDir := default (env "CONFIG_DIR") | default "config" }}
{{ tpl (readFile (printf "%s/envs.yaml" $configDir)) . }}
```

**My suggestion (in case you want to keep configDir definition DRY**

```
values:
- configDir: {{ default (env "CONFIG_DIR") | default "config" }}
---
{{ tpl (readFile (printf "%s/envs.yaml" .Values.configDir)) . }}
```

Note also that you should be able to apply my suggestion before migrating to v1!

Does my explanation makes sense, @gakesson? I'd appreciate any feedback/comment/etc from you! Thanks ❤️

**Comment by yxxhero** [comment]
So we should give some tips when running helmfile？ WDYT？ @mumoshu

**Comment by yxxhero** [comment]
my example works fine. you got me. @mumoshu

**Comment by mumoshu** [comment]
@yxxhero Thanks for your confirmation! Yeah if you are to add a warning message that let the user know that this is an instance of double-rendering and needs an additional `---` before upgrading to v1, that would be awesome!

**Comment by gakesson** [comment]
Hello @mumoshu and @yxxhero ,

Thanks for input!
Maybe I misunderstood but I'm not able to get @yxxhero example to work.
If I run the helmfile attached in this issue it fails with:

```
export HELMFILE_V1MODE=true && helmfile -e prod template
err: no releases found that matches specified selector() and environment(prod), in any helmfile
```

The specified environment **prod** is required to be defined in the first yaml document, which happens in the tpl/readFile command so that tpl/readFile can't be deferred?

**Comment by yxxhero** [comment]
@gakesson yes. you are right. I will see this issue.

**Comment by mumoshu** [comment]
The `no releases found that matches specified selector() and environment(prod), in any helmfile` error typically happen when the whole helmfile config (the result of rendering and merging all the helmfile parts separated by `---`) misses the `prod` environment even though you specified `-e prod`.

So... I'm unsure why that happens in this case 🤔 Does it fail on both  v0 and v1 modes? If so, the environment existence check might be happening too early (bug)?

**Comment by gakesson** [comment]
@mumoshu yes, both v0 and v1 expects that the environment is defined in the very first yaml document. This has been the case as far as I can remember (~1 year).
Relaxing this constraint, pushing validation later if possible, would certainly address the issue observed here. Then we can simply do as @yxxhero proposes. 

Thoughts?

**Comment by gakesson** [comment]
Just to give a helmfile to reproduce the "eager" `no releases found that matches specified selector() and environment(prod), in any helmfile` error:

```
{{ $configDir := "config" }}
values:
- configDir: {{ $configDir }}
---
environments:
  prod:
    values:
      - some-random-key: with-some-random-value
---
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
---
releases:
- name: service-a
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: {{ .Values | get "some-random-key" "" }}
        bar: {{ .Values.configDir }}

```
