### ISSUE TITLE
helmfile not support if else 

### ISSUE THREAD

**Issue by willzhang** [helmfile/helmfile#819]
### Operating system

ubuntu 22.04

### Helmfile Version

v0.151.0

### Helm Version

v3.11.0

### Bug description

helmfile not support if else in helmfile.yaml

### Example helmfile.yaml

```
environments:
  default:
    values:
      - serviceType-not-patch:  NodePort
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: nginx
    namespace: nginx
    createNamespace: true
    chart: bitnami/nginx
    values:
    {{ if .Values.serviceType }}
      - service:
          type: {{ .Values.serviceType }}
    {{ end }}
```

### Error message you've seen (if any)

if not supply serviceType  helmfile will give error, but i hope it not give error if user not supply serviceType  

```
root@node35:~# helmfile apply
in ./helmfile.yaml: error during helmfile.yaml.part.1 parsing: template: stringTemplate:10:17: executing "stringTemplate" at <.Values.serviceType>: map has no entry for key "serviceType"
```

### Steps to reproduce

create helmfile.yaml then run helmfile apply

### Working Helmfile Version

v0.151.0

**Comment by yxxhero** [comment]
@willzhang I don't understand the meaning of the title.  but you can use the `get` func.https://helmfile.readthedocs.io/en/latest/templating_funcs/#get

**Comment by willzhang** [comment]
get function resolved my problems, thanks.
```
environments:
  default:
    values:
      - serviceType:  NodePort
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: nginx
    namespace: nginx
    createNamespace: true
    chart: bitnami/nginx
    values:
    {{ if .Values | get "serviceType1" "" }}
      - service:
          type: {{ .Values | get "serviceType1" "" }}
    {{ end }}
```
