### ISSUE TITLE
go-getter URL does not work for ad-hoc dependencies

### ISSUE THREAD

**Issue by sjdrc** [helmfile/helmfile#821]
### Operating system

Ubuntu 22.04 LTS

### Helmfile Version

0.152.0

### Helm Version

3

### Bug description

I added an ad-hoc dependency to a chart from a git repo, but it is not detecting the go-getter URL and instead is trying to install it from a repository.

This works if I separate the ad-hoc dependency into a separate chart:
```
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 45.17.0
    disableValidationOnInstall: true
    needs:
      - monitoring/kube-prometheus-stack-crds

  - name: kube-prometheus-stack-crds
    namespace: monitoring
    chart: git::https://github.com/prometheus-community/helm-charts.git@charts/kube-prometheus-stack/crds?ref=kube-prometheus-stack-45.17.0
    jsonPatches:
      - target:
          group: monitoring.coreos.com
          kind: CustomResourceDefinition
          name: .*monitoring\.coreos\.com
        patch:
          - op: add
            path: /spec/labels
            value: app.kubernetes.io/managed-by=Helm
          - op: add
            path: /spec/annotations
            value:
              - meta.helm.sh/release-name={{`{{ .Release.Name }}`}}
              - meta.helm.sh/release-namespace={{`{{ .Release.Namespace }}`}}
```

### Example helmfile.yaml

```
helmDefaults:
  wait: false
  cleanupOnFail: true
  createNamespace: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 45.17.0
    disableValidationOnInstall: true
    dependencies:
      - chart: "git::https://github.com/prometheus-operator/prometheus-operator.git@example/prometheus-operator-crd?ref=v{{`{{ .Release.Version }}`}}"
```

### Error message you've seen (if any)

```
in clusters/blackhole/helmfile.yaml: [failed reading adhoc dependencies: no helm list entry found for repository "git::https:". please `helm repo add` it!]
```

### Steps to reproduce

helmfile --apply --skip-diff-on-install

### Working Helmfile Version

N/A
