### ISSUE TITLE
Go getter urls only work for 'git' prefix

### ISSUE THREAD

**Issue by woodcockjosh** [helmfile/helmfile#831]
### Operating system

Mac OS 12.4

### Helmfile Version

v0.153.1

### Helm Version

v3.11.3

### Bug description

According to the docs we should be able to use go-getter urls. It's not clear that only `git` urls are supported because perhaps underlying go-getter is not used? 
https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files

### Example helmfile.yaml

```yaml
releases:
  - chart: charts/hello
    name: hello
    version: 0.1.0
    values:
      - values/hello.values.yaml.gotmpl
  - chart: charts/message
    name: message
    version: 0.1.0
    values:
      - values/message.values.yaml.gotmpl
---
environments:
  default:
    values:
      - data/exclaim.values.yaml
      - data/first.values.yaml
      - data/last.values.yaml
      - git::https://github.com/woodcockjosh/s3-values@/examples/data/message.values.yaml?ref=main
      - git::https://github.com/woodcockjosh/s3-values@/examples/data/values.yaml?ref=main
      # Should work but doesn't
#      - s3::https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - s3::helm-s3-values-example.s3.amazonaws.com/values.yaml
      # Doesn't work
#      - https://john:doe@helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - http:://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - http:://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - s3:://helm-s3-values-example/values.yaml
      # Could work if s3-values plugin was incorporated into helmfile
#      - s3://helm-s3-values-example/values.yaml
```

### Error message you've seen (if any)

```text
in ./helmfile.yaml: failed to read helmfile.yaml: environment values file matching "s3::https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml" does not exist in "."
```

### Steps to reproduce

https://github.com/woodcockjosh/s3-values/blob/main/examples/helmfile.yaml

### Working Helmfile Version

N/A

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/792
