### ISSUE TITLE
Duplicate list-values in v1mode with sub-helmfiles. 

### ISSUE THREAD

**Issue by Anubiso** [helmfile/helmfile#835]
### Operating system

MacOs 13.2.1

### Helmfile Version

0.153.1

### Helm Version

3.11.3

### Bug description

When using HELMFILE_V1MODE=true we get duplicated list-values in "some" cases, which is not the case without the v1Mode. 

![image](https://user-images.githubusercontent.com/7769367/234931518-ae9f1c48-3057-4230-9dd7-2dba8621bae7.png)
![image](https://user-images.githubusercontent.com/7769367/234932743-3024e4c1-c088-4a78-af3c-f7a2f8562a7b.png)

### Example helmfile.yaml

```
############# 000-environments.yaml.gotmpl ###############

environments:
  default:
    values:
      - "./dev.values.yaml"
  dev:
    values:
      - "./dev.values.yaml"
---

helmDefaults:
  kubeContext: {{ .Values.kubeContext }}
  verify: false
  wait: true
  timeout: 1800
  tls: false

############# 000-repositories.yaml.gotmpl ###############

repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator/

############# dev.values.yaml ##########################

kubeContext: my-kubecontext
myExample:
  myContainers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]

############# my_helmfile.yaml.gotmpl ###################

bases:
  - 000-environments.yaml.gotmpl

---

helmfiles:
  - path: my_subhelmfile.yaml.gotmpl
    selectorsInherited: true
    values:
    {{- with .Values.myExample }}
    - specificValues:
        {{ toYaml . | nindent 8 }}
    {{- end }}

############# my_subhelmfile.yaml.gotmpl ################

bases:
  - 000-environments.yaml.gotmpl
  - 000-repositories.yaml
---

releases:
  - name: my-helmfile-test
    namespace: my-namespace
    labels:
      release: "{{`{{ .Release.Name }}`}}"
      namespace: "{{`{{ .Release.Namespace }}`}}"
    chart: incubator/raw
    version: 0.1.0
    values:
      - "./my-values.yaml.gotmpl"


############# my-values.yaml.gotmpl ####################

resources:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: test
    spec:
      {{- with .Values.specificValues.myContainers }}
      containers:
          {{ toYaml . | nindent 8 }}
      {{- end }}

```

[small_example.zip](https://github.com/helmfile/helmfile/files/11346182/small_example.zip)

### Error message you've seen (if any)

`helmfile -i -f ./small_example/my_helmfile.yaml.gotmpl -e dev apply` produces correct result
`HELMFILE_V1MODE=true helmfile -i -f ./small_example/my_helmfile.yaml.gotmpl -e dev apply` produces 2 containers

With helmfile_v1mode we get 2 containers instead of 1.

### Steps to reproduce

see example

### Working Helmfile Version

-
