### ISSUE TITLE
Strategic merge with envelope charts does not work

### ISSUE THREAD

**Issue by markussiebert** [helmfile/helmfile#851]
### Operating system

linux / mac

### Helmfile Version

0.151.0

### Helm Version

not that relevant

### Bug description

Trying to apply kustomizations (strategicMergePatch) to my generated helm chart fails. I am trying to manipulate the gitlab chart, that itself is an envelope chart for several other charts.

```
├── gitlab
│   ├── certmanager
│   ├── certmanager-issuer
│   ├── registry
│   ├── gitlab
│       ├── webservice
│       ├── shell
│       ├── pages
│       ├── gitaly
│       ├── ...
```

when I use kustomizations on this chart like below, I think something goes wrong and each charts overwrites the created patched_resources.yaml file created by the chart befor.

### Example helmfile.yaml

```yaml
- name: gitlab
  <<: *releaseGitLab
  version: {{ .Values.versions.chart }}
  values: 
    - gitlab.yaml.gotmpl
  set:
  - name: global.gitlabVersion
    value: {{ .Values.versions.gitlab }}
  strategicMergePatches:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: gitlab-gitaly
      namespace: gitlab-{{ .Values.app.environment }}-{{ .Values.app.identifier }}
    spec:
      jobLabel: promJobLabel
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: gitlab-praefect
      namespace: gitlab-{{ .Values.app.environment }}-{{ .Values.app.identifier }}
    spec:
      jobLabel: promJobLabel
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: gitlab-webservice
      namespace: gitlab-{{ .Values.app.environment }}-{{ .Values.app.identifier }}
    spec:
      jobLabel: promJobLabel
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: gitlab-gitlab-pages
      namespace: gitlab-{{ .Values.app.environment }}-{{ .Values.app.identifier }}
    spec:
      jobLabel: promJobLabel
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: gitlab-gitlab-shell
      namespace: gitlab-{{ .Values.app.environment }}-{{ .Values.app.identifier }}
    spec:
      jobLabel: promJobLabel
```

### Error message you've seen (if any)

No error message - so helmfile values and kustomization is successfull (kind of)
The resulting apply/diff fails because dependencies of resources are not met (many resources are not "in" the apply).

But those lines are an indicator for what may be happening here:

```
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
wrote ../tmp/_helmfile-477acc42-gitlab/gitlab/templates/patched_resources.yaml
```
so I think, the same path is used for the kustomization of every subchart? So at the end there is only the content of the last chart applied?

### Steps to reproduce

Try to apply a strategicMerge to nested charts (A Helm Chart containing several other helm charts)

### Working Helmfile Version

none
