### ISSUE TITLE
Values set with --set flag are ignored when used in conjunction with jsonPatches

### ISSUE THREAD

**Issue by AntonioAlfrz** [helmfile/helmfile#853]
### Operating system

Fedora 37

### Helmfile Version

0.153.1

### Helm Version

v3.11.3

### Bug description

When jsonPatches are used in a helmfile, values overwritten with --set flag are ignored.
Let's take this helmfile.yaml as an example:
```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
```
By default the replica count is 1:
```
$ helmfile template | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify3659108862/foo
  replicas: 1
```
Let's say we'd like to increase the replicas:
```
$ helmfile template --set replicaCount=3 | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify3653282249/foo
  replicas: 3
```
So far so good. Let's now assume that we want to change the deployment strategy with jsonPatches. Must be noted that there are much simpler ways of doing it, this is just for the sake of reproducing the behaviour:
```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
  jsonPatches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: foo-nginx
      patch:
      - path: "/spec/strategy/type"
        op: replace
        value: Recreate
```
Now values set with --set flag are ignored:
```
$ helmfile template --set replicaCount=3 | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify2208595413/foo
  replicas: 1
```

### Example helmfile.yaml

```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
  jsonPatches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: foo-nginx
      patch:
      - path: "/spec/strategy/type"
        op: replace
        value: Recreate
```

### Error message you've seen (if any)

None

### Steps to reproduce

helmfile template --set replicaCount=3 --debug

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@AntonioAlfrz do you have an interest to fix the issue?

**Comment by AntonioAlfrz** [comment]
Once I improve my golang skills, I can give it a try.
In the meanwhile, to overcome this, we have used state values:
```yaml
releases:
- name: foo
  chart: oci://registry-1.docker.io/bitnamicharts/nginx
  version: 14.1.0
  jsonPatches:
    - target:
        group: apps
        version: v1
        kind: Deployment
        name: foo-nginx
      patch:
      - path: "/spec/strategy/type"
        op: replace
        value: Recreate
  values:
  - replicaCount: {{ .Values.replicaCount }}
```
```
$ helmfile template --state-values-set replicaCount=3 | grep replicas
Pulling registry-1.docker.io/bitnamicharts/nginx:14.1.0
Templating release=foo, chart=/tmp/chartify1290229187/foo
  replicas: 3
```
