### ISSUE TITLE
splited helmfile.yaml with '---'  cause helmfile does not work

### ISSUE THREAD

**Issue by joelee2012** [helmfile/helmfile#862]
### Operating system

ubuntu 20.04

### Helmfile Version

0.153.1

### Helm Version

v3.11.3

### Bug description

To fix `Warning: environments and releases cannot be defined within the same YAML part. Use --- to extract the environments into a dedicated part`, i try to split helmfile.yaml with '---', but seems it does not work if define `environment` after other block，
following is working helmfile.yaml
```yaml
environments:
  dev:
    kubeContext: dev
  prod:
    kubeContext: prod
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - chart: bitnami/nginx
    name: my-nginx
```

### Example helmfile.yaml

```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - chart: bitnami/nginx
    name: my-nginx

# remove '---' everything is fine
---
environments:
  dev:
    kubeContext: dev
  prod:
    kubeContext: prod
```

### Error message you've seen (if any)

err: no releases found that matches specified selector() and environment(prod), in any helmfile

### Steps to reproduce

helmfile template -e dev

### Working Helmfile Version

none
