### ISSUE TITLE
Can not use a lock file per environment with different chart versions

### ISSUE THREAD

**Issue by olivierboudet** [helmfile/helmfile#870]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.154

### Helm Version

3.11.3

### Bug description

Lock files per environment can not be used with different chart versions but I think it is necessary to rollout a new chart version progressively.
I am encountering this error : `in ./helmfile.yaml: [no resolved dependency found for "mongodb", running "helmfile deps" may resolve the issue]
`

For example, I am trying to do these steps.
 
```
$ cat helmfile.yaml
lockFilePath: env/{{ .Environment.Name}}/helmfile.{{ .Environment.Name}}.lock

environments:
  dev:
  staging:

repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
---
releases:
  - name: mongodb
    namespace: default
    chart: bitnami/mongodb
    version: 13.10.2
    values:
      - env/{{ .Environment.Name }}/mongodb.values.yaml
```
I generate the lock file pour each environment and deploy the version 13.10.2: 
```
$ helmfile --environment dev deps 
$ helmfile --environment dev apply
$ helmfile --environment staging deps 
$ helmfile --environment staging apply
```

Then, I want to deploy the version 13.10.3 in dev but NOT in staging (I want to wait some days before) :
```
$ sed -i 's/13.10.2/13.10.3/g' helmfile.yaml
$ helmfile --environment dev deps 
$ helmfile --environment dev apply
```
At this time I can not do any change in staging environment because chart version differs in helmfile.yaml and the lock file : 
```
$ helmfile --environment staging template                                         git:(master|) 
in ./helmfile.yaml: [no resolved dependency found for "mongodb", running "helmfile deps" may resolve the issue]
```

See this repo to reproduce the error : https://github.com/olivierboudet/helmfile-issue-lockfile

I think the version should always be read from the lock file if it exists and should not fails.

### Example helmfile.yaml

```
lockFilePath: env/{{ .Environment.Name}}/helmfile.{{ .Environment.Name}}.lock

environments:
  dev:
  staging:

repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
---
releases:
  - name: mongodb
    namespace: default
    chart: bitnami/mongodb
    version: 13.10.2
    values:
      - env/{{ .Environment.Name }}/mongodb.values.yaml
```

### Error message you've seen (if any)

 [no resolved dependency found for "mongodb", running "helmfile deps" may resolve the issue]

### Steps to reproduce

https://github.com/olivierboudet/helmfile-issue-lockfile

### Working Helmfile Version

N/A
