### ISSUE TITLE
CRDs not installed for charts which normally install their own CRDs

### ISSUE THREAD

**Issue by btxbtx** [helmfile/helmfile#884]
### Operating system

macOS 13.4 22F66 arm64

### Helmfile Version

helmfile version v0.154.0

### Helm Version

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

### Bug description

Take any chart that installs its own CRDs, such as cloudnative-pg.  We can install this chart using helm via:

```
helm install postgres cnpg/cloudnative-pg --version 0.18.0
```

The chart will install its CRDs without issue.

If you create a simple helmfile to install the same chart, without modifying any values, no CRDs will be installed

I have seen related bugs in the past, which suggest using things such as hooks, etc.  Rather than workarounds, I would prefer  to add a release, sync my helmfile, and have the underlying chart installation behave just as it would if I were running `helm install`.

### Example helmfile.yaml

```
repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
    
 releases:
  - name: postgres
    namespace: default
    chart: cnpg/cloudnative-pg
    version: 0.18.0
```

### Error message you've seen (if any)

No error messages, the CRDs just arent installed.

### Steps to reproduce

Using the example helmfile, run `helmfile sync` and notice the lack of CRDs installed.

### Working Helmfile Version

n/a
