### ISSUE TITLE
Set file on windows

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#892]
### Discussed in https://github.com/helmfile/helmfile/discussions/889

<div type='discussions-op-text'>

<sup>Originally posted by **henkaa** June  8, 2023</sup>
Me and my colleague are trying to get helmfile working for our helm charts, but we both run into trouble when using files in folders in the set file section.
We are both running helm and helmfile on a Windows 10 system (have tried both cmd and Powershell with same result) and both helm and helmfile is installed and maintained via scoop. helmfile is latest version.

Example from the helmfile.yaml
```
releases:
  - name: timespan-rest
    namespace: cda2-test
    installed: true
    createNamespace: true
    chart: cda2/timespan-rest
    values:
      - image:
          tag: "develop"
    set:
      - name: applicationyaml
        file: local/timespan-application.yml
```

When I run lint on it I get this output
---
  ARGS:
    0: helm (4 bytes)
    1: lint (4 bytes)
    2: C:\Users\henand2\AppData\Local\Temp\helmfile3968896767\cda2-test\timespan-rest\cda2\timespan-rest\latest\timespan-rest (118 bytes)
    3: --namespace (11 bytes)
    4: cda2-test (9 bytes)
    5: --values (8 bytes)
    6: C:\Users\henand2\AppData\Local\Temp\helmfile2343919300\cda2-test-timespan-rest-values-574f6f4f6d (96 bytes)
    7: --set-file (10 bytes)
    8: applicationyaml=local\timespan-application.yml (46 bytes)

  ERROR:
    exit status 1

  EXIT STATUS
    1

  STDERR:
    Error: failed parsing --set-file data: open localtimespan-application.yml: The system cannot find the file specified.

  COMBINED OUTPUT:
    Error: failed parsing --set-file data: open localtimespan-application.yml: The system cannot find the file specified.

---

There seems to be a "transformation" of slashes made, and on windows, one backslash is not enough. We have tried using following variants, all with the same outcome:
local/timespan-application.yml
local\\/timespan-application.yml
local\\timespan-application.yml
local\\\\timespan-application.yml

Are we doing something wrong or have we run into a bug here?</div>

**Comment by xiaomudk** [comment]
see: https://github.com/helm/helm/issues/9537. 
I'll try to be compatible

**Comment by yxxhero** [comment]
@xiaomudk cool. maybe we can reference https://github.com/GoogleContainerTools/skaffold/pull/5648, WDYT?

**Comment by xiaomudk** [comment]
@yxxhero  I have fixed it, and the test passed on the window.

helmfile.yaml:
```
releases:
  - name: prometheus-adapter
    namespace: cda2-test
    installed: true
    createNamespace: true
    chart: public/prometheus-adapter
    values:
      - image:
          tag: "develop"
    set:
      - name: applicationyaml
        file: local/timespan-application.yml
```

```
helmfile_windows_amd64.exe -f .\helmfile.yaml template --debug


exec: helm template prometheus-adapter public/prometheus-adapter --namespace cda2-test --values C:\Users\xiaomudk\AppData\Local\Temp\helmfile1939855288\cda2-test-prometheus-adapter-values-78b7695785 --set-file applicationyaml=local\\timespan-application.yml --debug
```
