### ISSUE TITLE
Using strategicMergePatches leads to set values being ignored

### ISSUE THREAD

**Issue by vbode** [helmfile/helmfile#895]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.154.0

### Helm Version

3.11.2

### Bug description

When using the provided helmfile, I see that the ingress resource is missing when templating. When removing the 'strategicMergePatches' the ingress resource is templated again.

This issue does not occur in helmfile 0.152.0.

### Example helmfile.yaml
```
repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
environments:
  local:
    values:
helmDefaults:
  timeout: 300
  wait: true
---
releases:
- name: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  version: 6.0.6
  strategicMergePatches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kubernetes-dashboard
    spec:
      template:
        metadata:
          labels:
            app: kubernetes-dashboard
  kubeContext: minikube
  namespace: solutions
  createNamespace: false
  atomic: true
  values:
    - rbac:
        create: true
        clusterReadOnlyRole: true
        clusterRoleMetrics: true
        clusterReadOnlyRoleAdditionalRules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]
  set:
    - name: podLabels.app
      value: kubernetes-dashboard
    - name: extraArgs[0]
      value: --enable-skip-login
    - name: extraArgs[1]
      value: --enable-insecure-login
    - name: protocolHttp
      value: true
    - name: service.externalPort
      value: 80
    - name: ingress.enabled
      value: true
    - name: ingress.className
      value: solutions-ingress-controller-ingress-class
    - name: ingress.hosts[0]
      value: kubernetes-dashboard.kubernetes.loc
    - name: serviceAccount.create
      value: true
    - name: serviceAccount.name
      value: kubernetes-dashboard
```
### Error message you've seen (if any)

No Errros

### Steps to reproduce

-

### Working Helmfile Version

0.152.0
