### ISSUE TITLE
Helmfile fetch fail to reuse cache from oci repositories

### ISSUE THREAD

**Issue by zephyros-dev** [helmfile/helmfile#910]
### Operating system

Debian GNU/Linux 11 (bullseye)

### Helmfile Version

0.154.0

### Helm Version

v3.12.1

### Bug description

When I use `helmfile fetch` with oci charts, it will fail to pull the second time due to existing files from the last pull. This doesn't happen with normal helm charts since they seems to have a check for existing files and stop fetching from there.

### Example helmfile.yaml
```
repositories:
  - name: docker
    url: registry-1.docker.io
    oci: true
releases:
  - name: docker/bitnamicharts/matomo
    chart: docker/bitnamicharts/matomo
    version: "1.1.2"
```

### Error message you've seen (if any)
```
ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://registry-1.docker.io/bitnamicharts/matomo (47 bytes)
  3: --version (9 bytes)
  4: 1.1.2 (5 bytes)
  5: --destination (13 bytes)
  6: charts/docker/bitnamicharts/matomo/bitnamicharts/matomo/1.1.2 (61 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Pulled: registry-1.docker.io/bitnamicharts/matomo:1.1.2
  Digest: sha256:4f06cbfcb9a6ddc3b7c36d9ade4e95004b93f6b669232f6115c08ed1298072e9
  Error: failed to untar: a file or directory with the name charts/docker/bitnamicharts/matomo/bitnamicharts/matomo/1.1.2/matomo already exists

COMBINED OUTPUT:
  Pulled: registry-1.docker.io/bitnamicharts/matomo:1.1.2
  Digest: sha256:4f06cbfcb9a6ddc3b7c36d9ade4e95004b93f6b669232f6115c08ed1298072e9
  Error: failed to untar: a file or directory with the name charts/docker/bitnamicharts/matomo/bitnamicharts/matomo/1.1.2/matomo already exists]
```
### Steps to reproduce
1. Make the above `helmfile.yaml`
2. Run `helmfile fetch`
3. Run `helmfile fetch` again

### Working Helmfile Version

0.154.0
