### ISSUE TITLE
Key already set in map

### ISSUE THREAD

**Issue by iasikou** [helmfile/helmfile#917]
### Operating system

macOS Ventura 13.4

### Helmfile Version

v0.155.0

### Helm Version

v3.12.1

### Bug description

Same issue as https://github.com/helmfile/helmfile/issues/394 

This is seen again in versions `v0.155.0` and `v0.154.0` of Helmfile, not sure when this stopped working but it is certainly working on version `v0.147.0`.

They key in the release section should overwrite the key of the template section.

### Example helmfile.yaml

```yaml
repositories:
  - name: ecr
    url: <aws_account_id>.dkr.ecr.<region>.amazonaws.com
    oci: true
environments:
  dev:
    missingFileHandler: Warn
templates:
  defaultValues: &defaultValues
    chart: ecr/charts/{{`{{ .Release.Name }}`}}
    wait: true
    timeout: 1800
    atomic: true
releases:
  - name: not-valid-name-for-chart-path
    version: 0.0.1
    !!merge <<: *defaultValues
    chart: ecr/charts/valid
```

### Error message you've seen (if any)

key "chart" already set in map

### Steps to reproduce

Override a template key in the release section.

### Working Helmfile Version

v0.147.0

### Relevant discussion

https://github.com/helmfile/helmfile/issues/394
