### ISSUE TITLE
--output-dir-template is broken for OCI registries

### ISSUE THREAD

**Issue by SeWieland** [helmfile/helmfile#928]
### Operating system

Windows 10

### Helmfile Version

0.155.0

### Helm Version

v3.12.1

### Bug description

When using a simple fetch command to pull an OCI chart into a custom directory via helmfile, the `--output-dir-template` is not working.

Using: `helmfile -l name=my-release fetch --output-dir "../charts/" --output-dir-template "{{ .OutputDir }}"`

I would expect that the chart is pulled into `../charts/custom-chart`. Instead, the chart is pulled into something like

`../charts/default/my-release/custom-chart/^1.0.0/custom-chart` which looks like the default structure.

I need to access parts of the chart in a prepare hook. The deeply nested structure makes a this tedious task..

**This issue only applies to charts pulled via OCI registries**. Classical chart repos work as expected.

### Example helmfile.yaml

```yaml
repositories:
  - name: ocirepo
    url: registry.example.com
    oic: true

releases:
  - name: my-release
    namespace: default
    chart: ocirepo/custom-chart
    version: "^1.0.0"
```

### Error message you've seen (if any)

no errors.

### Steps to reproduce

`helmfile -l name=my-release fetch --output-dir "../charts/" --output-dir-template "{{ .OutputDir }}"`

### Working Helmfile Version

not sure if this worked at all at some point
