### ISSUE TITLE
OCI chart cannot contain digest

### ISSUE THREAD

**Issue by uhthomas** [helmfile/helmfile#939]
### Operating system

N/Ah

### Helmfile Version

v0.150.0

### Helm Version

N/A

### Bug description

It doesn't seem possible to specify a digest for OCI charts.

### Example helmfile.yaml

```yaml
repositories:
 - name: actions-runner-controller-charts
   url: ghcr.io/actions/actions-runner-controller-charts
   oci: true
- name: gha-runner-scale-set-controller
  namespace: gha-runner-scale-set-controller
  chart: actions-runner-controller-charts/gha-runner-scale-set-controller
  version: 0.4.0@sha256:e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09
```

### Error message you've seen (if any)

```sh
❯ helmfile template -e production/pdx-c
Pulling ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.4.0@sha256:e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09
in ./helmfile.yaml: [release "gha-runner-scale-set-controller": command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: pull (4 bytes)
  2: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller:0.4.0@sha256 (99 bytes)
  3: --version (9 bytes)
  4: e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09 (64 bytes)
  5: --destination (13 bytes)
  6: /var/folders/ws/lyfqx2sn72v223fhz5kb77m40000gp/T/helmfile1124613467/github/gha-runner-scale-set-controller-production/gha-runner-scale-set-controller/0.4.0@sha256:e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09 (227 bytes)
  7: --untar (7 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: improper constraint: e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09

COMBINED OUTPUT:
  Error: improper constraint: e3fc797b2c0603245ea971ece556862810646df6a046a735dd0db6aeae074b09]
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

### Relevant discussion

N/A
