### ISSUE TITLE
No releases found that matches specified selector and environment

### ISSUE THREAD

**Issue by teksuo** [helmfile/helmfile#950]
### Operating system

Fedora 37 Workstation

### Helmfile Version

0.155.1

### Helm Version

3.12.2

### Bug description

After upgrading from 0.148.1 to 0.155.1 I found out that some things stopped working. One of those that I was not yet able to resolve is this error message when using template/sync/apply commands:

`err: no releases found that matches specified selector() and environment(<cloud_provider>/<cluster_name>), in any helmfile`

We are using sub-helmfiles and separate repositories.gotmpl and environments.yaml files. I also tried to use .gotmpl for the environments file (although we are not using templating there) but no luck.

I looked for issues and PRs but did not see anything similar to this.

After checking some other releases, I see this is working fine for both 0.153.1 and 0.154.0.

Thanks in advance 

### Example helmfile.yaml
```
bases:
 - ./bases/environments.yaml
 - ./bases/repositories.yaml.gotmpl
---

helmfiles:
  - path: ./sub-helmfiles/*.yaml.gotmpl
    values:
      - ./environments/{{ requiredEnv "CLOUD_PROVIDER" }}/{{ requiredEnv "CLUSTER_NAME" }}/*.yaml
```
### Error message you've seen (if any)

err: no releases found that matches specified selector() and environment(<cloud_provider>/<cluster_name>), in any helmfile

### Steps to reproduce

helmfile template -e <env_name>

### Working Helmfile Version

0.154.0

**Comment by yxxhero** [comment]
https://github.com/roboll/helmfile/pull/294 @mumoshu

**Comment by yxxhero** [comment]
@teksuo could you post an example?

**Comment by gldkru** [comment]
> @teksuo could you post an example?

For example:
**helmfile.yaml**
```yaml
environments:
  dev:
    values:
    - environments/dev/values.yaml
  staging:
    values:
    - environments/staging/values.yaml
  prod:
    values:
    - environments/prod/values.yaml

helmfiles:
  - releases/**/helmfile.yaml
```

**environments/dev/values.yaml**
```yaml
global:
  domain: dev.example.com
```

**releases/app1/helmfile.yaml**
```yaml
releases:
- name: app1
  namespace: default
  chart: ./charts/app1
  version: 1.0.0
  values:
  - values.yaml.gotmpl
```

**releases/app1/values.yaml.gotmpl**
```yaml
service:
  domain: "app1.{{ .Environment.Values.global.domain }}"
```

`helmfile list -e dev` or `helmfile -e dev apply`

error:

> err: no releases found that matches specified selector() and environment(dev), in any helmfile
