### ISSUE TITLE
publish v0.155.2 release?

### ISSUE THREAD

**Issue by yurrriq** [helmfile/helmfile#969]
### Operating system

Ubuntu 22.04.2 LTS

### Helmfile Version

v0.155.1 (or v0.155.0)

### Helm Version

v3.12.2

### Bug description

Without any changes, my setup works with v0.155.0 and fails with v0.155.1

```bash
helmfile -e example -l name=example build
```

### Example helmfile.yaml

**include/environments.yaml:**
```yaml
environments:
  example:
    kubeContext: ...
    values:
      - foo: bar
        baz: quux
      - ./environments/default.yaml
      - ./environments/cluster-specific.yaml
```

**helmfile.yaml.gotmpl:**
```yaml
bases:
  - ./include/environments.yaml
---
helmfiles:
  - path: git::https://...@helmfile.d/?ref={{ .Values.exampleRef }}
    values:
      - {{ toYaml .Values | nindent 8 }}
```

### Error message you've seen (if any)

> err: no releases found that matches specified selector(name=example) and environment(example), in any helmfile

### Steps to reproduce

private

### Working Helmfile Version

v0.154.0
