### ISSUE TITLE
No releases found that matches specified selector and environment - v0.156.0

### ISSUE THREAD

**Issue by adecchi-2inno** [helmfile/helmfile#977]
### Operating system

Mac

### Helmfile Version

0.156.0

### Helm Version

v3.12.3

### Bug description

When I execute:

`helmfile -e dev -l layer=infra,release-name=argocd --no-color --log-level debug diff`

I get:

`err: no releases found that matches specified selector(layer=infra,release-name=argocd) and environment(dev), in any helmfile`

### Example helmfile.yaml

I have 2 helmfile.

**The main helmfile:**

```
environments:
    dev:
        missingFileHandler: Error 
        kubeContext: test
helmDefaults:
  atomic: true
  cleanupOnFail: false

helmfiles:
  - path: helmfiles/argo/cd/helmfile.yaml

templates:
  argocd-apps: &argocd-apps
  chart: helm-charts/argocd-apps

releases:
  - name: argo-rollouts
    <<: *argocd-apps
    namespace: argo-rollouts
    disableValidation: true

```

**The subhelmfile(helmfiles/argo/cd/helmfile.yaml):**

```
releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 5.21.0
    missingFileHandler: Error
    atomic: true
    verify: false
    wait: true
    waitForJobs: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "infra"
    values:
      - "{{ .Environment.Name }}/values.yaml"
```

### Error message you've seen (if any)

err: no releases found that matches specified selector(layer=infra,release-name=argocd) and environment(dev), in any helmfile

### Steps to reproduce

n/a

### Working Helmfile Version

v3.12.3

**Comment by adecchi-2inno** [comment]
Looks like i have to add the environment defined in the main **helmfile.yaml** to the **sub-helmfile.yaml** file ?  Is a way to skip this declaration again and the **sub-helmfile.yaml** inherits the variables and the environment from the main **helmfile.yaml**

**Comment by yxxhero** [comment]
```
helmfiles:
- # Path to the helmfile state file being processed BEFORE releases in this state file
  path: path/to/subhelmfile.yaml
  # Label selector used for filtering releases in the nested state.
  # For example, `name=prometheus` in this context is equivalent to processing the nested state like
  #   helmfile -f path/to/subhelmfile.yaml -l name=prometheus sync
  selectors:
  - name=prometheus
  # Override state values
  values:
  # Values files merged into the nested state's values
  - additional.values.yaml
  # One important aspect of using values here is that they first need to be defined in the values section
  # of the origin helmfile, so in this example key1 needs to be in the values or environments.NAME.values of path/to/subhelmfile.yaml
  # Inline state values merged into the nested state's values
  - key1: val1
```

you can try to use:
```
  # Override state values
  values:
```

**Comment by adecchi-2inno** [comment]
@yxxhero In my main **helmfile.yaml** are defined the environments, my idea is that any **sub-helmfile.yaml** inherit these environments. I do not want to pass any additional values to **sub-helmfile.yaml** or is mandatory to create **additional.values.yaml** file with the environment definition that are also included in my **helmfile.yaml**
Regarding the document in the last release it is possible, in the way that I did, but it does not work.

**Comment by yxxhero** [comment]
@adecchi-2inno sub-helmfile is designed to run on its own. you can try to see: https://helmfile.readthedocs.io/en/latest/writing-helmfile/#re-using-environment-state-in-sub-helmfiles

**Comment by yxxhero** [comment]
@mumoshu WDYT?

**Comment by adecchi-2inno** [comment]
@yxxhero 
Thank you for your response. I tried that option but the error persists.

**The sub-helmfile(helmfiles/argo/cd/helmfile.yaml):**

```
releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 5.21.0
    missingFileHandler: Error
    atomic: true
    verify: false
    wait: true
    waitForJobs: true
    labels:
      release-name: argocd
      layer: "infra"
    values:
      - "{{ .Environment.Name }}/values.yaml"
```

**The main helmfile.yaml**


```
bases:
  - environments.yaml
  - templates.yaml

helmDefaults:
  atomic: true
  cleanupOnFail: false

releases:
  - name: argo-rollouts
    inherit:
      - template: argocd-apps
    namespace: argo-rollouts
    disableValidation: true
    #missingFileHandler: Warn
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "infra"
    set:
      - name: source.helm.file
        file: "helmfiles/argo/rollouts/{{ .Environment.Name }}/values.yaml"
      - name: source.repoURL
        value: "https://argoproj.github.io/argo-helm"
      - name: source.targetRevision
        value: 2.9.3
      - name: source.chart
        value: "argo-rollouts"
      - name: destination.namespace
        value: "argo-rollouts"
    needs:
      - argocd/argocd
 
helmfiles:
  - path: helmfiles/argo/cd/helmfile.yaml
    selectorsInherited: true
    values:
      - {{ toYaml .Values }}
```


But continue not finding the release.


`0 release(s) matching layer=infra,release-name=argocd found in helmfile.yaml`
