### ISSUE TITLE
[homebrew] helmfile 0.156.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [helmfile/helmfile#978]
### Operating system

macos

### Helmfile Version

0.156.0

### Helm Version

3.12.3

### Bug description

while trying to upgrade to the latest release, I ran into the following test failure while regression test the build

```
  ==> /opt/homebrew/Cellar/helmfile/0.156.0/bin/helmfile -f helmfile.yaml repos 2>&1
  in ./helmfile.yaml: no top-level config keys are found in helmfile.yaml
```

### Example helmfile.yaml

This helmfile.yaml was working in 0.155.1 release
```yaml
    repositories:
    - name: stable
      url: https://charts.helm.sh/stable

    releases:
    - name: vault                            # name of this release
      namespace: vault                       # target namespace
      createNamespace: true                  # helm 3.2+ automatically create release namespace (default true)
      labels:                                # Arbitrary key value pairs for filtering releases
        foo: bar
      chart: stable/vault                    # the chart being installed to create this release, referenced by `repository/chart` syntax
      version: ~1.24.1                       # the semver of the chart. range constraint is supported
```

### Error message you've seen (if any)

see above

### Steps to reproduce

- `wget https://raw.githubusercontent.com/Homebrew/homebrew-core/7f2118f13802d4bcdd572503d31003713fb4abdb/Formula/h/helmfile.rb -O helmfile.rb` 
- `HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source -d -v helmfile.rb` 
- `brew test helmfile`

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5904108823/job/16015685004?pr=139878

relates to Homebrew/homebrew-core#139878

### Working Helmfile Version

0.155.1
