### ISSUE TITLE
Failed read Template from external yaml file

### ISSUE THREAD

**Issue by adecchi-2inno** [helmfile/helmfile#979]
### Operating system

Mac

### Helmfile Version

0.156.0

### Helm Version

v3.12.3

### Bug description

Failed to read template from external yaml file.

### Example helmfile.yaml

helmfile.yaml

```
bases:
  - environments.yaml
  - templates.yaml

helmDefaults:
  atomic: true
  cleanupOnFail: false

releases:
  - name: argo-rollouts
    <<: *argocd-apps
    namespace: argo-rollouts
    disableValidation: true
    labels:
      release-name: "{{ `{{ .Release.Name }}` }}"
      layer: "infra"
```

templates.yaml

```
templates:
  argocd-apps: &argocd-apps
    chart: helm-charts/argocd-apps
    version: 0.0.1
```

### Error message you've seen (if any)

I get the following error:

`err: failed to read helmfile.yaml: reading document at index 1: yaml: unknown anchor 'argocd-apps' referenced`

### Steps to reproduce

n/a

### Working Helmfile Version

0.156.0

### Relevant discussion

n/a
