### ISSUE TITLE
[Feature] Verify that charts are pulled from trusted sources - verify with gpg signed helm charts.

### ISSUE THREAD

**Issue by yxxhero** [helmfile/helmfile#983]
### Discussed in https://github.com/helmfile/helmfile/discussions/980

<div type='discussions-op-text'>

<sup>Originally posted by **dominikkaminski** August 20, 2023</sup>
Hey helmfile community and maintainers,

at first, thanks for this great open-source project - it helps us a lot!

For a project focused on security and verifiable software supply chains, we are looking for way to verify that helm charts are published from the vendor/community we trust. For example, we sign our to OCI registry published helm charts with the native `helm sign` method.

During native installation, we set `helm --verify --keyring <trusted keyring file>` arguments, so only trusted artifacts get installed.

We miss the same possibilities for the helmfile `repositories`. In my opinion, there should be a way to verify (`oci: true`) packages during pull and thus I miss a `verify` and `keyring` argument:
```
repositories:
  - name: "dont-trust-verify"
    oci: true
    url: "my.registry.local"
    verify: true
    keyring: "~/.gnupg/pubring.gpg"
```

**TL;DR;**
Before installing releases into a cluster, helm charts should be verifiable against gpg public key.

Thanks for taking this idea into consideration! :pray: </div>
