### ISSUE TITLE
helmfile sync ignores needs when needed chart is not installed

### ISSUE THREAD

**Issue by fetidbell** [helmfile/helmfile#987]
### Operating system

macOS Ventura 13.4.1

### Helmfile Version

v0.156.0

### Helm Version

v3.12.3

### Bug description

If you specify `needs` in release and needed release has `installed: false` property, `helmfile sync` will install release anyway, without needed release.
For example, if you have `chart-a` which has `chart-b` in `needs` and `chart-b` has `installed: false`, then `helmfile sync` will install `chart-a` without `chart-b`

### Example helmfile.yaml

```yaml
namespace: default

releases:
  - name: chart-a
    chart: ./chart-a
    installed: true
    needs:
      - chart-b

  - name: chart-b
    chart: ./chart-b
    installed: false
```

### Error message you've seen (if any)

No error massage

### Steps to reproduce

https://github.com/fetidbell/helmfile-sync-needs-issue

### Working Helmfile Version
_no info_

### Relevant discussion
_no info_
