### ISSUE TITLE
Unmarshal errors: field not found in type state.helmStateAlias

### ISSUE THREAD

**Issue by bencat-sixense** [helmfile/helmfile#991]
### Operating system

Ubuntu 22.04 - Manjaro 23.0

### Helmfile Version

v0.155.1 (0.156.0 still not available in Arch)

### Helm Version

v3.12.0

### Bug description

When I apply my Helmfile configuration, everything is fine, my values are filled correctly, my deployment work as expected and my cluster is updated, but the last output return an error:

> in environments/staging/values.yaml: failed to read values.yaml: reading document at index 1: yaml: unmarshal errors:
line 3: field global not found in type state.helmStateAlias
line 7: field poc-service-01 not found in type state.helmStateAlias
line 15: field poc-service-02 not found in type state.helmStateAlias
Error: Process completed with exit code 1.

I cannot find anything about helmStateAlias, and I don't understand what in my configuration can lead to this. 

A link to a repository containing my configuration to reproduce: https://github.com/bencatlab/helmfile-state-issue

Here is a Github Actions workflow that reproduce my issue: https://github.com/bencatlab/helmfile-state-issue/actions/runs/5977358315/job/16217170875

Any help will be very appreciate ! 
Thank you :)

### Example helmfile.yaml
```

bases:
  - ../../common/environments.yaml

templates:
  defaultRelease:
    chart: ../../charts/{{`{{ .Release.Name }}`}}
    namespace: '{{`{{ .Environment.Name }}`}}'
    values:
      - ../../charts/{{`{{ .Release.Name }}`}}/values.yaml
      - ../../common/environment-values.gotmpl

releases:
  - name: poc-service-01
    inherit:
      - template: defaultRelease
  - name: poc-service-02
    inherit:
      - template: defaultRelease
```

### Error message you've seen (if any)

> in environments/staging/values.yaml: failed to read values.yaml: reading document at index 1: yaml: unmarshal errors:
line 3: field global not found in type state.helmStateAlias
line 7: field poc-service-01 not found in type state.helmStateAlias
line 15: field poc-service-02 not found in type state.helmStateAlias
Error: Process completed with exit code 1.

### Steps to reproduce

https://github.com/bencatlab/helmfile-state-issue

### Working Helmfile Version

v0.155.1
